### ISSUE TITLE
missing Hash.h

### ISSUE THREAD

**Issue by tripzero** [Links2004/arduinoWebSockets#1]
Trying to compile the WebsocketServer example I get: fatal error: Hash.h: No such file or directory

**Comment by Links2004** [comment]
are you using the ESP8266 arduino?
the Hash library is included there.
https://github.com/esp8266/Arduino/tree/esp8266-sdk-1.0/hardware/esp8266com/esp8266/libraries/Hash

**Comment by tripzero** [comment]
I'm using the arduino sparkfun thing package.  Looks like they are missing Hash.  Thanks!

**Comment by dmarkey** [comment]
So hash.h isnt included in ordinary arduino. so do you support ordinary arduino?

**Comment by Links2004** [comment]
the support is planed.
currently ist not supported see: #19

**Comment by dmarkey** [comment]
My version of the Client works for AVR, There are some crappy changes so probably not ready for a PR  https://github.com/dmarkey/arduinoWebSockets

**Comment by Links2004** [comment]
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/WebSocketClientAVR/WebSocketClientAVR.ino
