### ISSUE TITLE
implement WStype_BAD_REQUEST in WebSocketServer

### ISSUE THREAD

**Issue by starlino** [Links2004/arduinoWebSockets#10]
It would be nice to implement a WStype_BAD_REQUEST for non-websocket connections and allow user to send a different response rather than the hard-coded one ( HTTP/1.1 400 Bad Request ) . This also can be used to handle simple non-websocket requests.
_cbEvent(client->num, WStype_BAD_REQUEST, (uint8_t *) client->cUrl.c_str(), client->cUrl.length());
 If after calling the event   connection is still open , or some variable is set , then fall -back to same hard-coded message as it is now at the end of  WebSocketsServer.cpp file. I could fork this , but I think it would be a nice feature to the base code :)

**Comment by Links2004** [comment]
a WStype_BAD_REQUEST notification is possible, but access to the socket connection is currently not possible from outside of the library (in callback function). 
for this a new callback function is needed that also has the socket connection as parameter (pointer). 

but i dont see the real use case, for websites i recommend using the ESP8266WebServer:
https://github.com/esp8266/Arduino/tree/esp8266/hardware/esp8266com/esp8266/libraries/ESP8266WebServer 

@igrr is currently working on FS integration then its really easy to get static html and js from the internal file system, and then loading the dynamic variables whit the web socket. 

the WebServer also has the functions to parse the POST and GET parameters.
do you really plan to implement this functions again? or miss I good use case for this?

**Comment by starlino** [comment]
How about we do this - we put the last lines in handleHeader that send Bad Request in a separate function let's say handleOtherHeader . This way I can inherit your class and implement my own handleOtherHeader without having to rewrite the entire handleHeader function.
I want to be able to serve a simple HTML and web socket from same port. I don't want to use another library since it will consume resources and needs to listen to another port.

**Comment by Links2004** [comment]
yes this is a good solution, if you extent the class you get access to the socket.
will do the changes for that.

**Comment by starlino** [comment]
I can confirm this is working (See code below). We still need one modification in
WebSocketServer.h , change all members from "private:"  to  "protected:" , to allow descendant class to call clientDisconnect() and other functions currently "private" .  So on line 84  change _private_ to _protected_, normal end users should not be affected by this. Thanks !
```c
class icWebSocketsServer : public WebSocketsServer{
  public:
  icWebSocketsServer(uint16_t port) : WebSocketsServer(port){};
  protected:
  void handleNonWebsocketConnection(WSclient_t * client) {
    client->tcp.write("HTTP/1.1 200 OK\r\n"
            "Content-Type: text/plain\r\n"
            "Content-Length: 4\r\n"
            "Connection: close\r\n"
            "\r\n"
            "Hey!"); 
    clientDisconnect(client);
  }  
    
};

icWebSocketsServer webSocket = icWebSocketsServer(80);
```
