### ISSUE TITLE
WebSockets.cpp:308:87: error: 'bind' is not a member of 'std'

### ISSUE THREAD

**Issue by mok-liee** [Links2004/arduinoWebSockets#101]
Hello :)

what can i do with this issue?

`C:\Users\user\Documents\Arduino\libraries\arduinoWebSockets-2.0.3\src\WebSockets.cpp: In member function 'bool WebSockets::handleWebsocketWaitFor(WSclient_t*, size_t)':`

`C:\Users\user\Documents\Arduino\libraries\arduinoWebSockets-2.0.3\src\WebSockets.cpp:308:87: error: 'bind' is not a member of 'std'`

```
 readCb(client, &client->cWsHeader[client->cWsRXsize], (size - client->cWsRXsize), std::bind([](WebSockets * server, size_t size, WSclient_t * client, bool ok) {

                                                                                   ^
```

`C:\Users\user\Documents\Arduino\libraries\arduinoWebSockets-2.0.3\src\WebSockets.cpp:319:25: error: 'std::placeholders' has not been declared`

```
 }, this, size, std::placeholders::_1, std::placeholders::_2));

                     ^
```

`C:\Users\user\Documents\Arduino\libraries\arduinoWebSockets-2.0.3\src\WebSockets.cpp:319:48: error: 'std::placeholders' has not been declared`

```
 }, this, size, std::placeholders::_1, std::placeholders::_2));

                                            ^
```

`C:\Users\user\Documents\Arduino\libraries\arduinoWebSockets-2.0.3\src\WebSockets.cpp: In member function 'void WebSockets::handleWebsocketCb(WSclient_t*)':`

`C:\Users\user\Documents\Arduino\libraries\arduinoWebSockets-2.0.3\src\WebSockets.cpp:403:53: error: 'bind' is not a member of 'std'`

```
     readCb(client, payload, header->payloadLen, std::bind(&WebSockets::handleWebsocketPayloadCb, this, std::placeholders::_1, std::placeholders::_2, payload));

                                                 ^
```

`C:\Users\user\Documents\Arduino\libraries\arduinoWebSockets-2.0.3\src\WebSockets.cpp:403:113: error: 'std::placeholders' has not been declared`

```
     readCb(client, payload, header->payloadLen, std::bind(&WebSockets::handleWebsocketPayloadCb, this, std::placeholders::_1, std::placeholders::_2, payload));

                                                                                                             ^
```

`C:\Users\user\Documents\Arduino\libraries\arduinoWebSockets-2.0.3\src\WebSockets.cpp:403:136: error: 'std::placeholders' has not been declared`

```
     readCb(client, payload, header->payloadLen, std::bind(&WebSockets::handleWebsocketPayloadCb, this, std::placeholders::_1, std::placeholders::_2, payload));

                                                                                                                                    ^
```

`

Sorry, i tried to format it better, but i can't :(

**Comment by Links2004** [comment]
do you try to compile for AVR? if yes you need the version 1.4. (https://github.com/Links2004/arduinoWebSockets/releases/tag/1.4)
the g++ in arduino for AVR is unfortunately missing the standard c++ libs.
