### ISSUE TITLE
Connection between 2 ESP8266

### ISSUE THREAD

**Issue by morgan-wild** [Links2004/arduinoWebSockets#102]
Hi Markus,

I'm trying to use a ws server on a ESP (AP) and a ws client on another one (STA). If I try your samples, I have theses messages in my serial output :

[WSc] Disconnected!
[WSc] Disconnected!
[WSc] Disconnected!
[WSc] Disconnected!
...

I'm trying to connect to the ip 192.168.4.1 which is the default gateway for ESPs in the AP mode, and the port 8080. Note the Wifi is always OK.

[ESP WS CLIENT STA] -------------X----------->[ESP WS SERVER AP] : FAILED

The server seems ok, if I replace the client by a computer or a smartphone with Chrome it works :

[HTML5 WS CLIENT] --------------------------->[ESP WS SERVER AP] : OK

To check the client again, I tried that :

[ESP WS CLIENT] ------>[WIFI ROUTER]---X-->[SOCKET.IO WS SERVER] : FAILED

And surprising :

[ESP WS CLIENT] ------>[WIFI ROUTER]------>[WEBSOCKETD WS SERVER] : OK ^^

I'm sure it's a little thing somewhere, but I need help :)

Any Idea? Best regards :)

**Comment by Links2004** [comment]
Please enable the debug output and post the results here.

1. Set debug port in IDE Menu
2. enable debug for Websockets (https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L30)

**Comment by morgan-wild** [comment]
Thank you for your fast answer :)

So :


[SETUP] BOOT WAIT 4...
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 0 (11)
[SETUP] BOOT WAIT 3...
reconnect
f 0, scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 2
cnt 

connected with Lightning remote, channel 1
dhcp client start...
[SETUP] BOOT WAIT 2...
ip:192.168.4.3,mask:255.255.255.0,gw:192.168.4.1
[SETUP] BOOT WAIT 1...
[WS-Client] connect ws...
[WS-Client] connection to 192.168.4.1:8080 Faild
[WS-Client] client disconnected.
[WSc] Disconnected!
[WS-Client] connect ws...
[WS-Client] connection to 192.168.4.1:8080 Faild
[WS-Client] client disconnected.
[WSc] Disconnected!
[WS-Client] connect ws...
[WS-Client] connection to 192.168.4.1:8080 Faild
[WS-Client] client disconnected.
[WSc] Disconnected!
[WS-Client] connect ws...
[WS-Client] connection to 192.168.4.1:8080 Faild
[WS-Client] client disconnected.
[WSc] Disconnected!
[WS-Client] connect ws...
[WS-Client] connection to 192.168.4.1:8080 Faild
[WS-Client] client disconnected.
[WSc] Disconnected!
[WS-Client] connect ws...

The sketch is the example. I've just changed the SSID / PASS and that :
    webSocket.begin("192.168.4.1", 8080);
    //webSocket.setAuthorization("user", "Password"); // HTTP Basic Authorization

Maybe an authorization is needed? 

Meanwhile, a Smartphone is correctly connected to the ws server (192.168.4.1:8080).

Note : Yes it's true, it was a desperate test ^^

**Comment by Links2004** [comment]
from the log I can say the error is at TCP level.
the tcp socket never gets opened.
but why is a good question. 
does the log at the server side shows any think?
you also can try to enable the WiFi / network debug in the IDE menu.

the authorization is way later in the code and only needed when enabled on the server side too.

can you try to establish a TCP connection with ```WiFiClient``` and ```WiFiServer```?
may this give us some hints too.

**Comment by morgan-wild** [comment]
Hi Markus!

To be sure the server is ok at TCP level, I tried to connect from a laptop with the telnet command. The connection is etablished. I can see the '400 Bad request' message if I type something. At this moment, the serial output of the server writes '[0] Disconnected'. No problem here.

If I try the connection from an ESP, the server didn't write something in the serial output :s

I tried the example sketch named ESP8266Wifi/WifiClient (using the data.sparkfun server), it works perfectly on my 2 ESPs. WifiWebServer works too.

It's very strange. I use the latest IDE (1.6.9), the latest Board package (2.3.0) for Arduino and the latest version of arduinoWebSocket (2.0.2).

**Comment by Links2004** [comment]
I think its problem at TCP level, that only is visible when 2 ESP directly connects.
try to set Core + WiFi debug this will show use more detail of the TCP part.
![image](https://cloud.githubusercontent.com/assets/974709/16526443/9e3909d2-3fb1-11e6-8c52-3018666b1cf6.png)

**Comment by pieman64** [comment]
@morgan-wild did you ever manage to get the two ESP's to communicate via websockets?

**Comment by morgan-wild** [comment]
Hi! No I finally used UDP, I'm still interesting by websockets if you have
some news.

Best regards.

**Comment by pieman64** [comment]
@morgan-wild I'm afraid I am further behind than you.
You mentioned you were able to get a Smartphone to connect to via websockets to the ESP.
I have a Smartphone app that has websockets functionality but I'm struggling with the required sketch for the ESP.

My router is 192.168.10.90 and a normal connection for the ESP is on 192.168.10.207.
I have tried 192.168.4.1 etc but no joy.
Could you indicate which sketch I should be using for Smartphone to ESP and what IP addresses I should be using in the sketch?

**Comment by morgan-wild** [comment]
Hi!

The IP address 192.168.4.1 is the default address of an ESP when it is an
AP (access point).
If you want to use it as STA with your router, you have two options : let
the DHCP of your router define the IP of your ESP or define a static IP in
the sketch. Your phone must use theses address to connect, not 192.168.4.1.

Does your ESP is connected to your router? Your smartphone too? You can use
'Advanced IP Scanner' to find the IP of your ESP if you are using DHCP.
Else, you can add this code in your sketch to define a static one :

IPAddress ip(192, 168, 10, XX);           //The IP you want to use, eg
192.168.10.77 cause your router.
IPAddress gateway(192, 168, 10, 90); //The IP of your router
IPAddress subnet(255, 255, 255, 0);   //Set subnet mask to match your
network
WiFi.config(ip, gateway, subnet);

With this code, your phone must connect 192.168.10.77 using your router.

Sorry for my bad english :)

2016-12-13 15:26 GMT+01:00 theCHARioT <notifications@github.com>:

**Comment by pieman64** [comment]
@morgan-wild I don't have any problems with the IP per se. It is the actual sketch that I am struggling with. For the ESP is it a websocket client or server that I need for the Smartphone to connect to? Do you have a link to a suitable sketch?

**Comment by Links2004** [comment]
you need the Server code on the ESP.
the browser on the Smartphone will be the client.

**Comment by pieman64** [comment]
@Links2004 and @morgan-wild I am slowly making some progress.

**My smartphone can now access the websocket server on the ESP!!!** 
I am using the following sketch: https://github.com/Links2004/arduinoWebSockets/blob/master/examples/WebSocketServer/WebSocketServer.ino.
I can also access the websocket server on the ESP via a web browser from a PC on the same LAN.
However both the Smartphone and web browser are showing immediate disconnects with the following debug information in Serial Monitor:
```
WS:ac
:ref 1
WS:av
:ref 2
:ur 2
[WS-Server][0] new client from 192.168.10.251
:rn 17
[WS-Server][0][handleHeader] RX: Sent from Smartphone
:c0 1, 17
[WS-Server][0][handleHeader] Header read fin.
[WS-Server][0][handleHeader]  - cURL: 
[WS-Server][0][handleHeader]  - cIsUpgrade: 0
[WS-Server][0][handleHeader]  - cIsWebsocket: 0
[WS-Server][0][handleHeader]  - cKey: 
[WS-Server][0][handleHeader]  - cProtocol: 
[WS-Server][0][handleHeader]  - cExtensions: 
[WS-Server][0][handleHeader]  - cVersion: 0
[WS-Server][0][handleHeader]  - base64Authorization: 
[WS-Server][0][handleHeader]  - cHttpHeadersValid: 1
[WS-Server][0][handleHeader]  - cMandatoryHeadersCount: 0
[WS-Server][0][handleHeader] no Websocket connection close.
:wr
:sent 186
:ww
:ur 1
:close
WS:dis
:del
[WS-Server][0] client disconnected.
[0] Disconnected!
```
Any ideas why the websocket is disconnecting?

Also @Links2004 in your sketch you have the following line:

`WiFiMulti.addAP("SSID", "passpasspass");`

I was expecting for the Smartphone to see an ESP AP named SSID but nothing is coming up and the websocket connection (disconnection) is made without the AP. What is the purpose of the addAP function and can you confirm it's not actually needed for websockets to work?

**Comment by Links2004** [comment]
```WiFiMulti.addAP``` is for connection to a WiFi,
to open a AP with the ESP you need other code.

the WebSocketServer.ino example not deliver any html pages, for a all in one demo you can use:
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/WebSocketServer_LEDcontrol/WebSocketServer_LEDcontrol.ino
simple remove all ```WiFiMulti``` stuff and use 
```cpp
    WiFi.softAP("ssid", "password");
    IPAddress myIP = WiFi.softAPIP();
    Serial.print("AP IP address: ");
```

**Comment by pieman64** [comment]
@Links2004 I looked at your "LED" sketch the other day but I didn't think it was what I needed.
Started looking at it again before your last post and I now have a browser turn a single LED 'up and down'.
Haven't needed to do any "multi" changes yet and all I did was set IP and port 8080 (as ultimately that is what I have in the Smartphone code). I'll see if I can make the mods to the Smartphone app to make it work like html file.

**Comment by pieman64** [comment]
![led control](https://cloud.githubusercontent.com/assets/8315296/21366490/b1ba70ee-c702-11e6-8dfd-2ba5c7a994b6.png)
OK with WiFi.softAP() I can now control the LED's from the Smartphone browser on 192.168.4.1 (screenshot above) **and** a laptop web browser connected via the main LAN router.
@Links2004 in the Smartphone app I have the following code:

```
	var socket = Ti.Network.Socket.createTCP({
		host : hostName,
		port : 8080,
		connected : function(e) {
			Ti.API.info('Socket opened!');
			Ti.Stream.pump(e.socket, readCallback, 1024, true);
			Ti.Stream.write(socket, Ti.createBuffer({
				value : 'Sent from Smartphone\n\r\n'
			}), writeCallback);
		},
	});
	socket.connect();
```
I can see this being sent to the ESP in Serial Monitor but it fails to connect as indicated in my earlier post. Do you have any idea what's wrong with the code above that is preventing the Smartphone from connecting to the ESP via the websocket?

**Comment by pieman64** [comment]
A few more hacks and I think the Smartphone app can now connect to the ESP via the websocket.
```
WS:ac
:ref 1
WS:av
:ref 2
:ur 2
[WS-Server][4] new client from 192.168.10.251
:urch 132, 132
:urch 132, 132
:urch 132, 132
:rn 7
:c0 1, 7
[WS-Server][4][handleHeader] RX: #FFFFFF
:rn 8
:c0 1, 8
[WS-Server][4][handleHeader] RX: #000000
:urch 132, 132
:urch 132, 132
:urch 132, 132
```
I'm not getting the full connection status details that @Links2004 gets from a browser connection but Serial Monitor (above) certainly seems to indicate a connection has been made. At the moment the Smartphone app just has an ON and an OFF button and I am trying to use the same notation as the "LED" sketch with #FFFFFF being sent for ON and #000000 sent for OFF.

@Links2004 do you know how I make use of the HandleHeader entries?

**Comment by Links2004** [comment]
you use a function called ```Ti.Network.Socket.createTCP``` will it create a websocket connection or a TCP connection?
the messages are encoded in the web socket protocol (RFC6455).

the sending at binary level can be seen here:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.cpp#L82

note sure which language you code in, it looks a lot like javascript, if yes you have a really good change that you have native websocket support.
if it something else check for a websocket lib, on Mobile platform you have a good change to find a good one.

```js
var connection = new WebSocket('ws://' + location.hostname + ':81/', ['arduino']);
connection.onopen = function() {
	connection.send('Connect ' + new Date());
};
connection.onerror = function(error) {
	console.log('WebSocket Error ', error);
};
connection.onmessage = function(e) {
	console.log('Server: ', e.data);
};

function sendRGB() {
	var r = parseInt(document.getElementById('r').value).toString(16);
	var g = parseInt(document.getElementById('g').value).toString(16);
	var b = parseInt(document.getElementById('b').value).toString(16);
	if (r.length < 2) {
		r = '0' + r;
	}
	if (g.length < 2) {
		g = '0' + g;
	}
	if (b.length < 2) {
		b = '0' + b;
	}
	var rgb = '#' + r + g + b;
	console.log('RGB: ' + rgb);
	connection.send(rgb);
}
```

**Comment by pieman64** [comment]
Thanks @Links2004  I will study your last post and see if I can move forward.

For reference the details for `Ti.Network.Socket.createTCP` are at http://docs.appcelerator.com/platform/latest/#!/api/Titanium.Network.Socket.TCP

It looks like the function just creates a TCP socket rather than a websocket but the following GitHub looks like it adds Websockets functionality to Titanium

https://github.com/omorandi/tiws

**Comment by pieman64** [comment]
Seasons greetings @Links2004 
I have a Titanium websocket up and running now (SDK 5.5.1 from a few months ago rather than the current 6.0.1).
My java skills are worse than my C++ skills but the following is the syntax required in the app on my Smartphone:
```
var test = 'raw',  //  can be raw, socket.io or nowjs
uri = 'ws://192.168.10.207:8080';
if ('raw' === test) { // example using a plain websockets
    var socket = require('net.iamyellow.tiws').createWS();
	socket.addEventListener('open', function () {
		Ti.API.debug('websocket opened');
	});
	socket.addEventListener('close', function (ev) {
		Ti.API.info(ev);
	});
	socket.addEventListener('error', function (ev) {
		Ti.API.error(ev);
	});
	socket.addEventListener('message', function (ev) {
		Ti.API.log(ev);
	});	
	socket.open(uri);
}
```
Could you please indicate how I would change this for your ESP library especially the following line of your code in your last post:

`var connection = new WebSocket('ws://' + location.hostname + ':81/', ['arduino']);`

**Comment by pieman64** [comment]
Smartphone is now controlling the ESP and the syntax for the websocket connection is.

```
var hostName = '192.168.10.207';
uri = 'ws://' + hostName + ':8080';
var WSsocket = require('net.iamyellow.tiws').createWS();
	WSsocket.addEventListener('open', function () {
		Ti.API.debug('websocket opened');
		WSsocket.send('Connected ' + new Date());
		clientStatusArea.value=('Connected ' + new Date());
	});
	WSsocket.addEventListener('close', function (ev) {
		Ti.API.info(ev);
		clientStatusArea.value=('Connection was closed ' + new Date());
	});
	WSsocket.addEventListener('error', function (ev) {
		Ti.API.error(ev);
		clientStatusArea.value=('Websockets error ' + new Date());
	});
	WSsocket.addEventListener('message', function (ev) {
		Ti.API.log(ev);
	});	
	WSsocket.open(uri, ['arduino']); 
```

**Comment by Links2004** [comment]
feel free to reopen when there still is an Issue.

**Comment by izanette** [comment]
Hi, 

Has the original issue have ever been solved? I'm trying to connect two ESPs using the ESP's AP network (192.168.4.1) using websockets without success.
It works fine if my client connects to my own router, but when I try use the network created by the ESP, it fails. This is the log with the debug enabled and the Debug Level set to "SSL+TLS_MEM+HTTP_CLIENT+HTTP_SERVER+CORE+WIFI...":

```
[SETUP] BOOT WAIT 4...
wifi evt: 2
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 1
cnt 

connected with ESPap, channel 4
dhcp client start...
wifi evt: 0
ip:192.168.4.2,mask:255.255.255.0,gw:192.168.4.1
wifi evt: 3
wifi evt: 7
wifi evt: 7
wifi evt: 7
[SETUP] BOOT WAIT 3...
[SETUP] BOOT WAIT 2...
[SETUP] BOOT WAIT 1...
sta config unchangedscandone
[WS-Client] connect ws...
[hostByName] Host: 192.168.4.1 is a IP!
:ref 1
:abort
:ur 1
:del
[WS-Client] connection to 192.168.4.1:81 Faild
[WS-Client] client disconnected.
[WSc] Disconnected!
wifi evt: 7
wifi evt: 7
[WS-Client] connect ws...
[hostByName] Host: 192.168.4.1 is a IP!
:ref 1
:abort
:ur 1
:del
[WS-Client] connection to 192.168.4.1:81 Faild
[WS-Client] client disconnected.
[WSc] Disconnected!
[WS-Client] connect ws...
[hostByName] Host: 192.168.4.1 is a IP!
:ref 1
wifi evt: 7
:abort
:ur 1
:del
[WS-Client] connection to 192.168.4.1:81 Faild
[WS-Client] client disconnected.
[WSc] Disconnected!
[WS-Client] connect ws...
[hostByName] Host: 192.168.4.1 is a IP!
:ref 1
:abort
:ur 1
:del
[WS-Client] connection to 192.168.4.1:81 Faild
[WS-Client] client disconnected.
[WSc] Disconnected!
[WS-Client] connect ws...
[hostByName] Host: 192.168.4.1 is a IP!
:ref 1
wifi evt: 7
:abort
:ur 1
:del
[WS-Client] connection to 192.168.4.1:81 Faild
[WS-Client] client disconnected.
[WSc] Disconnected!
```

The server doesn't show much:

```
[SETUP] BOOT WAIT 4...
[SETUP] BOOT WAIT 3...
wifi evt: 7
add 1
aid 1
station: 5c:cf:7f:53:90:30 join, AID = 1
wifi evt: 5
[SETUP] BOOT WAIT 2...
wifi evt: 7
wifi evt: 7
[SETUP] BOOT WAIT 1...
[AP] softap config unchanged
AP IP address: 192.168.4.1
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
station: 5c:cf:7f:53:90:30 leave, AID = 1
rm 1
wifi evt: 6
add 1
aid 1
station: 5c:cf:7f:53:90:30 join, AID = 1
wifi evt: 5
wifi evt: 7
wifi evt: 7
```

Thanks!

**Comment by izanette** [comment]
Found that a fix for this issue. If I set the client to connect in station mode (WIFI_STA), it works fine.

Hope it helps others with the same issue.

**Comment by Links2004** [comment]
ok, now the problem makes sense.

as long the AP mode on the client is active it has most likely the local IP 192.168.4.1.
then the traffic never goes out to the Server.

**Comment by leoncoolmoon** [comment]
This seems answered my question. I will try it tonight. Also I think it would be great help if the example can include the demo of connect two nodeMCU with websocket.

**Comment by NathanCanovas** [comment]
Hello, I just want to say thank you for this library, because it is really well written, very understandable and works very well. AMAZING ! And thank you again.   :)
