### ISSUE TITLE
SSL error,failed to grow plain buffer

### ISSUE THREAD

**Issue by jatayu86** [Links2004/arduinoWebSockets#103]
Hi,
I am getting the below error when trying to connect to wss enabled server.Below are the logs after debug is enabled.Could you please help me as to why we get this error. The esp resets after some time.

[WS-Client] connect wss...
please start sntp first !
[WS-Client] connected to predix-eyweb.run.aws-usw02-pr.ice.predix.io:443.
[WS-Client][sendHeader] sending header...
failed to grow plain buffer
[WS-Client][sendHeader] sending header... Done (21764us).
[WS][0][sendFrame] not in WSC_CONNECTED state!?

**Comment by Links2004** [comment]
the error most likely comes from the SSL lib, try to enable debug for SSL in the Arduino menu and try again, then we will see more.

**Comment by jatayu86** [comment]
i enabled core+ssl and found below logs.Kindly advise.
[WS-Client] connect wss...
:ref 1
please start sntp first !
State:	sending Client Hello (1)
:wr
:sent 52
:ww
:rn 1460
:rd 5, 1460, 0
:rdi 1460, 5
:rd 74, 1460, 5
:rdi 1455, 74
State:	receiving Server Hello (2)
:rd 5, 1460, 79
:rdi 1381, 5
:rd 1376, 1460,:rch 1460, 1460
 84
::rch 2920, 1176
rdi 1376, 1376
:c 1376, 14:rch 4096, 1460
:rch 5556, 118
60, 4096
:rd 4205, 4214, 0
:rdi 1460, 1460
:c 1460, 1460, 4214
:rdi 1176, 1176
:c 1176, 1176, 2754
:rdi 1460, 1460
:c 1460, 1460, 1578
:rdi 118, 109
State:	receiving Certificate (11)
:rd 5, 118, 109
:rdi 9, 5
:rd 4, 118, 114
:rdi 4, 4
:c0 4, 118
State:	receiving Server Hello Done (14)
State:	sending Client Key Exchange (16)
:wr
:sent 267
:ww
:wr
:sent 6
:ww
State:	sending Finished (16)
:wr
:sent 69
:rn 75
:ww
:rd 5, 75, 0
:rdi 75, 5
:rd 1, 75, 5
:rdi 70, 1
:rd 5, 75, 6
:rdi 69, 5
:rd 64, 75, 11
:rdi 64, 64
:c0 64, 75
State:	receiving Finished (16)
[WS-Client] connected to predix-eyweb.run.aws-usw02-pr.ice.predix.io:443.
[WS-Client][sendHeader] sending header...
failed to grow plain buffer
[WS-Client][sendHeader] sending header... Done (21766us).
[WS][0][sendFrame] not in WSC_CONNECTED state!?

**Comment by jatayu86** [comment]
and the below log after enabling core+ssl+tls

[WS-Client] connect wss...
:ref 1
ssl/tls1.c:549 malloc 6864, left 27144
please start sntp first !
State:	sending Client Hello (1)
:wr
:sent 52
:ww
:rn 1460
:rd 5, 1460, 0
:rdi 1460, 5
:rd 74, 1460, 5
:rdi 1455, 74
State:	receiving Server Hello (2)
:rd 5, 1460, 79
:rdi 1381, 5
:rd 1376, 1460, 84
:rdi:rch 1460, 1460
 1376, 1:rch 2920, 1176
376
:c 1376, 1460, 4:rch 4096, 1460
:rch 5556, 118
096
:rd 4205, 4214, 0
:rdi 1460, 1460
:c 1460, 1460, 4214
:rdi 1176, 1176
:c 1176, 1176, 2754
:rdi 1460, 1460
:c 1460, 1460, 1578
:rdi 118, 109
State:	receiving Certificate (11)
crypto/bigint.c:1072 realloc 1032, left 22720
crypto/bigint.c:1072 realloc 1032, left 19160
crypto/bigint.c:1072 realloc 1028, left 15312
crypto/bigint.c:1072 realloc 2056, left 13152
crypto/bigint.c:1072 realloc 1032, left 9672
:rd 5, 118, 109
:rdi 9, 5
:rd 4, 118, 114
:rdi 4, 4
:c0 4, 118
State:	receiving Server Hello Done (14)
crypto/bigint.c:1072 realloc 1024, left 6080
State:	sending Client Key Exchange (16)
:wr
:sent 267
:ww
:wr
:sent 6
:ww
State:	sending Finished (16)
:wr
:sent 69
:rn 75
:ww
:rd 5, 75, 0
:rdi 75, 5
:rd 1, 75, 5
:rdi 70, 1
:rd 5, 75, 6
:rdi 69, 5
:rd 64, 75, 11
:rdi 64, 64
:c0 64, 75
State:	receiving Finished (16)
[WS-Client] connected to predix-eyweb.run.aws-usw02-pr.ice.predix.io:443.
[WS-Client][sendHeader] sending header...
ssl/tls1.c:1422 malloc 17408 failed, left 32824
ssl/tls1.c:1422 malloc 17408, left 32824
failed to grow plain buffer
[WS-Client][sendHeader] sending header... Done (22227us).
[WS][0][sendFrame] not in WSC_CONNECTED state!?

**Comment by Links2004** [comment]
you run out of heap (ram), the code try to alloc 17408 in one peace 
but the ram has no 17408 Byte in a row free (memory fragmentation).

you can try two thinks:

- call the websocket loop early as possible, may the there is the needed space.
- optimize you heap (ram) usage to use more static buffers to reduce the memory fragmentation.

**Comment by jatayu86** [comment]
I am unable to find any more optimization,can you please check if there is any more than can be done.. :(
#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>
#include <WebSocketsClient.h>
#include <Hash.h>
ESP8266WiFiMulti WiFiMulti;
WebSocketsClient webSocket;
#define USE_SERIAL Serial

void webSocketEvent(WStype_t type, uint8_t * payload, size_t lenght) {
    switch(type) {
        case WStype_DISCONNECTED:
            USE_SERIAL.printf("[WSc] Disconnected!\n");
            break;
        case WStype_CONNECTED:
            {
                USE_SERIAL.printf("[WSc] Connected to url: %s\n",  payload);
            }
            break;
        case WStype_BIN:
            USE_SERIAL.printf("[WSc] get binary lenght: %u\n", lenght);
            hexdump(payload, lenght);
            break;
    }

}

void setup() {
    // USE_SERIAL.begin(921600);
    USE_SERIAL.begin(115200);
    USE_SERIAL.setDebugOutput(true);
      for(uint8_t t = 4; t > 0; t--) {
          USE_SERIAL.printf("[SETUP] BOOT WAIT %d...\n", t);
          USE_SERIAL.flush();
          delay(1000);
      }
    WiFiMulti.addAP("xxx", "xxx");
    while(WiFiMulti.run() != WL_CONNECTED) {
        delay(100);
    }
    webSocket.beginSSL("predix-eyweb.run.aws-usw02-pr.ice.predix.io",443,"/");
    webSocket.onEvent(webSocketEvent);
}

void loop() {
  String device="P101";
String json= "{\"device\":\""+device+"\"}";
    USE_SERIAL.println(json);
    webSocket.loop();
    delay(100);
  }

**Comment by Links2004** [comment]
currently I not see a way to improve the memory usage.
can you test it with a other server? may the SSL certificate is to bug (common problem when using SSL on ESP).
