### ISSUE TITLE
unstable websocket connection when use the software serial 

### ISSUE THREAD

**Issue by mkeyno** [Links2004/arduinoWebSockets#105]
Hi @Links2004 Markus , I have no problem with websocket unless try read the software serial data and pass it over the websocket link . its kinda some buffer full and overflow, because after couple of try the connection is sever
following is the loop function 
```cpp
#include <SoftwareSerial.h>
#define RxD 15  
#define TxD 13 
SoftwareSerial SIM(RxD, TxD, false, 256);
WebSocketsServer webSocket = WebSocketsServer(81);
ESP8266WebServer server(80);
void webSocketEvent(uint8_t num, WStype_t type, uint8_t * payload, size_t lenght) {
 client_num=num;
 switch(type) {
        case WStype_DISCONNECTED:
                                 Serial.printf("[WS:%u Disconnected!]\n", num); 
                 ACCESS=false;
        break;
        case WStype_CONNECTED:   { 
                       IPAddress ip = webSocket.remoteIP(num);
                   ACCESS=true;
                  Serial.print("[WS:]Clinet "); Serial.print(num); Serial.print(" CONNECTED with IP: ");Serial.println(ip);
                  
                 } 
        break;
        case WStype_TEXT:    // this for  webSocket request          
                String text = String((char *) &payload[0]);
                Serial.print("[WS:"); Serial.print(num);Serial.print("]");Serial.println(text);
                
               SIM.print(text+"\r\n");
        break;
        
        
      }

}

String read_sim(void)
{
   String sim_buf="";
  while (SIM.available() > 0) 
                           { 
                           char c = (char)SIM.read();
                            sim_buf+=c;
                           Serial.print(c);
                           }
 return sim_buf;
}

void loop() 
{
 server.handleClient();  
 webSocket.loop(); 
if(SIM.available() > 0) webSocket.sendTXT(client_num,read_sim().c_str()); 
}
```

**Comment by Links2004** [comment]
you overload the TCP layer of the ESP (too many sendText calls, possible for every byte you get from serial).
I personal have add a buffer for the serial data when I do WS to Serial.

example with advanced buffer handling:
https://github.com/Links2004/arduinoWebSockets/issues/61#issuecomment-198231422

**Comment by mkeyno** [comment]
can you be more specific Markus , how come reading serial overload websocket layer ?it is due to softserial library or hardware serial? when I increase softserial buffer from 256 to 1024 it became more stable , but still have problem when I read big data from serial ,  you said I must encapsulate serial reading from TCP layer? what would your solution when need read softserial data and pass it to websocket link

**Comment by mkeyno** [comment]
I recheck your last solution  about Serial to WS  bridge, you make time constraint and websocket header reservation for given buffer length, am I right? 
I might add I reading from SIM module so I should send commend and wait for respond

**Comment by Links2004** [comment]
the reading  itself in your code is not the problem, but if you call for every byte ```sendTXT``` you will send a full tcp packet + websocket header for one byte, this can easily overload the TCP layer.

yes, the buffer will be send when full or when for 50ms no new data is coming in.

Debugging:
1. Set debug port in IDE Menu
2. enable debug for Websockets (https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L30)

**Comment by mkeyno** [comment]
thanks Markus
