### ISSUE TITLE
mqtt server auth

### ISSUE THREAD

**Issue by kiralikbeyin** [Links2004/arduinoWebSockets#106]
Is it possible to send messages to mqtt server (mosca) with authentication method?

**Comment by Links2004** [comment]
this is a websocket lib not mqtt.

**Comment by kiralikbeyin** [comment]
but mqtt broker accepts ws connection..

**Comment by Links2004** [comment]
ok I not know the mosca server itself,
http basic authentication is integrated, costume authentication methods are possible too,
which exact method is used for authentication in mosca?

**Comment by kiralikbeyin** [comment]
I am sending a post from html page to node server,

```
var authenticate = function(client, username, password, callback) {
    try {
        fs.readFile(__dirname + '/public/users.json', 'utf8', function(err, data) {

            var datam = JSON.parse(data);
            //   console.log(datam);
            bir = jsonQuery('[username=' + username + ']', {
                    data: datam
                }).value
                //   console.log(bir);
  })
              authorized = (username == bir["username"] && password.toString() == bir["password"]);
            if (authorized) client.user = bir["kull"];
            callback(null, authorized);

    } catch (e) {
     }

}

```

I am not happy with knolleary/pubsubclient mqtt lib because it is not stable need update.

I think your lib can be a mqtt client lib with a few changes?

**Comment by Links2004** [comment]
the function not show how the authentication is done at WS / HTTP level, so its hard to say.

**Comment by kiralikbeyin** [comment]
Sorry, here javascript in html;
```

client = mqtt.connect('ws://172.20.10.7:3000', {
                         username: logid,
                        password: logpass,
                      //  clientId: something,
                        keepalive: 0
                    });
```

with the help of Browserify --> https://www.npmjs.com/package/mqtt

```
<html>
<head>
  <title>test Ws mqtt.js</title>
</head>
<body>
<script src="./browserMqtt.js"></script>
<script>
      var client = mqtt.connect(); // you add a ws:// url here
      client.subscribe("mqtt/demo");
 
      client.on("message", function(topic, payload) {
        alert([topic, payload].join(": "));
        client.end();
      });
 
      client.publish("mqtt/demo", "hello world!");
    </script> 
</body>
</html>
```

**Comment by kiralikbeyin** [comment]
ok i found a good esp mqtt lib based on https://github.com/tuanpmt/esp_mqtt (this guy is awesome)

https://github.com/i-n-g-o/esp-mqtt-arduino/issues/8

i was having a lot of trouble with https://github.com/knolleary/pubsubclient
