### ISSUE TITLE
Websocket client

### ISSUE THREAD

**Issue by au190** [Links2004/arduinoWebSockets#107]
Hi !

I want to connect with ESP to one websocket server. But I can not.
With javascript it is working perfectly.

How can I use begin function if I have anotaion ? this is the link "ws://xhome.hu/examples/websocket/echoAnnotation"

	wsC.begin("xhome.hu", 80, "/examples/websocket/echoAnnotation");//
	wsC.onEvent(webSocketCEvent);

My ESP program is working perfectly with this link : echo.websocket.org

	wsC.begin("echo.websocket.org", 80);//

Can you help me ?

Thx Br Robi.

**Comment by Links2004** [comment]
Please enable debug and post the output here.

1. Set debug port in IDE Menu
2. enable debug for Websockets (https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L30)

**Comment by au190** [comment]
Thx for quiq replay !

You can find the log: the good ones a bad ones.

0 [SETUP] Booting 3...
0 [SETUP] Booting 2...
0 [SETUP] Booting 1...
0 getFS: Total:52961 Used:502
Flash real id:   001440E0
Flash real size: 1048576

Flash ide  size: 524288
Flash ide speed: 40000000
Flash ide mode:  DIO


0 wifi: [Roby][rkallos1976]
f r0, scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 196
cnt 

connected with Roby, channel 1
ip:192.168.1.191,mask:255.255.255.0,gw:192.168.1.1
[WiFi-event] event: 0
[WiFi-event] event: 3
0 
0 wifi: connRes: [3]
0 Wifi connected ip: 192.168.1.191
[WS-Server] Server Started.
[WS-Client] asyncConnect...
[WS-Client] connected to xhome.hu:80.
[WS-Client][sendHeader] sending header...
[WS-Client][sendHeader] sending header... Done (3431us).
[WS-Client][handleHeader] RX: HTTP/1.1 101 Switching Protocols
[WS-Client][handleHeader] RX: Server: Apache-Coyote/1.1
[WS-Client][handleHeader] RX: Upgrade: websocket
[WS-Client][handleHeader] RX: Connection: upgrade
[WS-Client][handleHeader] RX: Sec-WebSocket-Accept: 1YFNPIG698+ZANdGT4eCW8UF1Bg=
[WS-Client][handleHeader] RX: Date: Sun, 10 Jul 2016 08:11:44 GMT
[WS-Client][handleHeader] Header read fin.
[WS-Client][handleHeader] Client settings:
[WS-Client][handleHeader]  - cURL: /examples/websocket/echoAnnotation
[WS-Client][handleHeader]  - cKey: lZJLwg+0WcmjZXbaUXM3+w==
[WS-Client][handleHeader] Server header:
[WS-Client][handleHeader]  - cCode: 101
[WS-Client][handleHeader]  - cIsUpgrade: 0
[WS-Client][handleHeader]  - cIsWebsocket: 1
[WS-Client][handleHeader]  - cAccept: 1YFNPIG698+ZANdGT4eCW8UF1Bg=
[WS-Client][handleHeader]  - cProtocol: arduino
[WS-Client][handleHeader]  - cExtensions: 
[WS-Client][handleHeader]  - cVersion: 0
[WS-Client][handleHeader] no Websocket connection close.
[WS-Client] client disconnected.
[WS-Server][0] Disconnect client
[WS-Client] asyncConnect...
[WS-Client] connection to xhome.hu:80 Faild
pm open,type:2 0




0 [SETUP] Booting 3...
0 [SETUP] Booting 2...
0 [SETUP] Booting 1...
0 getFS: Total:52961 Used:502
Flash real id:   001440E0
Flash real size: 1048576

Flash ide  size: 524288
Flash ide speed: 40000000
Flash ide mode:  DIO


0 wifi: [Roby][rkallos1976]
f r0, scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 196
cnt 

connected with Roby, channel 1
ip:192.168.1.191,mask:255.255.255.0,gw:192.168.1.1
[WiFi-event] event: 0
[WiFi-event] event: 3
0 
0 wifi: connRes: [3]
0 Wifi connected ip: 192.168.1.191
[WS-Server] Server Started.
[WS-Client] asyncConnect...
[WS-Client] connected to echo.websocket.org:80.
[WS-Client][sendHeader] sending header...
[WS-Client][sendHeader] sending header... Done (3643us).
[WS-Server][0] new client from 192.168.1.4
[WS-Server][0][handleHeader] RX: GET / HTTP/1.1
[WS-Server][0][handleHeader] RX: Host: 192.168.1.191:81
[WS-Server][0][handleHeader] RX: Connection: Upgrade
[WS-Server][0][handleHeader] RX: Pragma: no-cache
[WS-Server][0][handleHeader] RX: Cache-Control: no-cache
[WS-Server][0][handleHeader] RX: Upgrade: websocket
[WS-Server][0][handleHeader] RX: Origin: http://hu-rkallos-w7
[WS-Server][0][handleHeader] RX: Sec-WebSocket-Version: 13
[WS-Server][0][handleHeader] RX: User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
[WS-Server][0][handleHeader] RX: Accept-Encoding: gzip, deflate, sdch
[WS-Server][0][handleHeader] RX: Accept-Language: hu-HU,hu;q=0.8,en-US;q=0.6,en;q=0.4
[WS-Server][0][handleHeader] RX: Sec-WebSocket-Key: z8RA0882WOkjPUGizgw/Lg==
[WS-Server][0][handleHeader] RX: Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
[WS-Server][0][handleHeader] Header read fin.
[WS-Server][0][handleHeader]  - cURL: /
[WS-Server][0][handleHeader]  - cIsUpgrade: 1
[WS-Server][0][handleHeader]  - cIsWebsocket: 1
[WS-Server][0][handleHeader]  - cKey: z8RA0882WOkjPUGizgw/Lg==
[WS-Server][0][handleHeader]  - cProtocol: 
[WS-Server][0][handleHeader]  - cExtensions: permessage-deflate; client_max_window_bits
[WS-Server][0][handleHeader]  - cVersion: 13
[WS-Server][0][handleHeader]  - base64Authorization: 
[WS-Server][0][handleHeader] Websocket connection incoming.
[WS-Server][0][handleHeader]  - sKey: PCGMTBkjUkfYPNP+eq0DC+lE9ts=
[WS][0][headerDone] Header Handling Done (1073697944us).
[WS][0][handleWebsocketWaitFor] size: 2 cWsRXsize: 0
[WS][0][sendFrame] ------- send massage frame -------
[WS][0][sendFrame] fin: 1 opCode: 9 mask: 0 length: 0 headerToPayload: 0
[WS][0][sendFrame] sending Frame Done (20us).
[0] Connected from 192.168.1.4 url: /
[WS][0][sendFrame] ------- send massage frame -------
[WS][0][sendFrame] fin: 1 opCode: 1 mask: 0 length: 9 headerToPayload: 0
[WS][0][sendFrame] text: Connected
[WS][0][sendFrame] pack to one TCP package...
[WS][0][sendFrame] sending Frame Done (4us).
[WS-Client][handleHeader] RX: HTTP/1.1 101 Web Socket Protocol Handshake
[WS-Client][handleHeader] RX: Connection: Upgrade
[WS-Client][handleHeader] RX: Date: Sun, 10 Jul 2016 08:22:56 GMT
[WS-Client][handleHeader] RX: Sec-WebSocket-Accept: F1Ccsv1yuGwXtfuiWJMZWz1d3uQ=
[WS-Client][handleHeader] RX: Server: Kaazing Gateway
[WS-Client][handleHeader] RX: Upgrade: websocket
[WS-Client][handleHeader] Header read fin.
[WS-Client][handleHeader] Client settings:
[WS-Client][handleHeader]  - cURL: /
[WS-Client][handleHeader]  - cKey: wiLeQn4DzPtET/dra9Fldw==
[WS-Client][handleHeader] Server header:
[WS-Client][handleHeader]  - cCode: 101
[WS-Client][handleHeader]  - cIsUpgrade: 1
[WS-Client][handleHeader]  - cIsWebsocket: 1
[WS-Client][handleHeader]  - cAccept: F1Ccsv1yuGwXtfuiWJMZWz1d3uQ=
[WS-Client][handleHeader]  - cProtocol: arduino
[WS-Client][handleHeader]  - cExtensions: 
[WS-Client][handleHeader]  - cVersion: 0
[WS-Client][handleHeader] Websocket connection init done.
[WS][0][headerDone] Header Handling Done (0us).
[WS][0][handleWebsocketWaitFor] size: 2 cWsRXsize: 0
32 Rcv1: Connected to url: /
[WS][0][sendFrame] ------- send massage frame -------
[WS][0][sendFrame] fin: 1 opCode: 1 mask: 1 length: 9 headerToPayload: 0
[WS][0][sendFrame] text: Connected
[WS][0][sendFrame] pack to one TCP package...
[WS][0][sendFrame] sending Frame Done (1029us).
[WS][0][handleWebsocketWaitFor][readCb] size: 2 ok: 1
[WS][0][handleWebsocket] ------- read massage frame -------
[WS][0][handleWebsocket] fin: 1 rsv1: 0 rsv2: 0 rsv3 0  opCode: 10
[WS][0][handleWebsocket] mask: 1 payloadLen: 0
[WS][0][handleWebsocketWaitFor] size: 6 cWsRXsize: 2
[WS][0][handleWebsocketWaitFor][readCb] size: 6 ok: 1
[WS][0][handleWebsocket] ------- read massage frame -------
[WS][0][handleWebsocket] fin: 1 rsv1: 0 rsv2: 0 rsv3 0  opCode: 10
[WS][0][handleWebsocket] mask: 1 payloadLen: 0
[WS][0][handleWebsocket] get pong  (<null>)
[WS][0][handleWebsocketWaitFor] size: 2 cWsRXsize: 0
[WS][0][handleWebsocketWaitFor][readCb] size: 2 ok: 1
[WS][0][handleWebsocket] ------- read massage frame -------
[WS][0][handleWebsocket] fin: 1 rsv1: 0 rsv2: 0 rsv3 0  opCode: 1
[WS][0][handleWebsocket] mask: 0 payloadLen: 9
[WS][0][handleWebsocket] text: Connected
32 Rcv1: Connected
[WS][0][handleWebsocketWaitFor] size: 2 cWsRXsize: 0
pm open,type:2 0
[WS][0][sendFrame] ------- send massage frame -------
[WS][0][sendFrame] fin: 1 opCode: 1 mask: 1 length: 70 headerToPayload: 0
[WS][0][sendFrame] text: {"f":"10","h":"+String(xhour)+","m":"String(xmin)","s":"String(xsec)"}
[WS][0][sendFrame] pack to one TCP package...
[WS][0][sendFrame] sending Frame Done (1422us).
[WS][0][handleWebsocketWaitFor][readCb] size: 2 ok: 1
[WS][0][handleWebsocket] ------- read massage frame -------
[WS][0][handleWebsocket] fin: 1 rsv1: 0 rsv2: 0 rsv3 0  opCode: 1
[WS][0][handleWebsocket] mask: 0 payloadLen: 70
[WS][0][handleWebsocket] text: {"f":"10","h":"+String(xhour)+","m":"String(xmin)","s":"String(xsec)"}
42 Rcv1: {"f":"10","h":"+String(xhour)+","m":"String(xmin)","s":"String(xsec)"}
[WS][0][handleWebsocketWaitFor] size: 2 cWsRXsize: 0
[WS][0][sendFrame] ------- send massage frame -------

**Comment by Links2004** [comment]
do you have the latest git version?
looks like something which is "fixed" last month.
(the not working server sends "Connection: upgrade" but RFC says "Connection: Upgrade")

**Comment by au190** [comment]
I have this veriosn:

name=WebSockets
version=2.0.2
author=Markus Sattler
maintainer=Markus Sattler 
sentence=WebSockets for Arduino (Server + Client)
paragraph=use 2.x.x for ESP and 1.3 for AVR
category=Communication
url=https://github.com/Links2004/arduinoWebSockets
architectures=*

**Comment by Links2004** [comment]
2.0.3 is the latest release https://github.com/Links2004/arduinoWebSockets/releases
but the git itself is 18 commits newer ;)
use the green download button here:
https://github.com/Links2004/arduinoWebSockets/
and you will get the latest.

**Comment by au190** [comment]
Thx you ! With new version is working!!!
:)
