### ISSUE TITLE
How can change the websocket server IP?

### ISSUE THREAD

**Issue by williamesp2015** [Links2004/arduinoWebSockets#108]
Hi everyone, is it possible to make change in the ESP8266 IP when using different chips?

**Comment by Links2004** [comment]
sure, check the WiFi API.
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/ESP8266WiFiAP.h#L40
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/ESP8266WiFiSTA.h#L42
