### ISSUE TITLE
How to test WebSocketClient.ino using our webserver

### ISSUE THREAD

**Issue by williamesp2015** [Links2004/arduinoWebSockets#109]
Hi, I compiled and tested the WebSocketClient.ino but output on serial port says [WSc] Disconnected!. Do you have a test HTML page and little help to use it in our website to test it. Thank you

**Comment by Links2004** [comment]
the Client needs a websocket server, no html file will help there ;)
example server in nodejs:
https://github.com/Links2004/arduinoWebSockets/tree/master/tests/webSocketServer

may the debug output helps to:

1. Set debug port in IDE Menu
2. enable debug for Websockets (https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L30)

**Comment by williamesp2015** [comment]
@Links2004 
Thank you for your help. Unfortunately after upload the websocket directory contain json file and rename websocket server.html to index.html and upload to url, ESP after connect to the url says handshake failed.

**Comment by hutch120** [comment]
Bit of info...

When I used the example the websocket library failed on the call to request.accept with "Error: Specified protocol was not requested by the client."

The reason seems to be the requestedProtocols array is empty.

I adapted the example as follows to get a connection, not sure as to the effect on security or other functions at this time, but at least it does get a connection and seems to be passing basic messages.

Change:

    var connection = request.accept('arduino', request.origin);

to

    var connection = request.accept('', request.origin);

**Comment by Links2004** [comment]
yes the protocols need to match,
on Arduino side the protocol can be set at the begin call for the client:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.h#L43
or on the class contractor for the Server: 
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsServer.h#L47
default is Arduino.

**Comment by hutch120** [comment]
Hmm, I did try as follows: 

Client Code:

```
webSocket.begin("mywebserverurl", 3000, "/", "arduino");
```

Server Code:

```
var connection = request.accept('ardunio', request.origin)
```

But the request object still didn't appear to contain 'ardunio', and still didn't work... I'm out of time now, but I will try again tomorrow, maybe I spelt ardunio wrong on one of them...

**Comment by lucasmaziero** [comment]
Hello,
It is possible to use ESP as a server and client, at the same time?
server - serving a local app.
client - connected to a remote server.

**Comment by Links2004** [comment]
@lucasmaziero  sure, the only Limitation is the RAM, you can start as many servers and clients as you like.  https://github.com/Links2004/arduinoWebSockets/issues/112#issuecomment-233375705
