### ISSUE TITLE
Enabling async mode without modifying WebSockets.h

### ISSUE THREAD

**Issue by anisimovsergey** [Links2004/arduinoWebSockets#110]
I think it would be really nice to be able to enable async mode without modifying the library. 
Otherwise it diminishes the whole  point of platform.io automatic library update.

**Comment by Links2004** [comment]
its only possible, when platform.io allows to set defineds in a conf menu or file.
a switch during run time in the Arduino code not possible.

**Comment by anisimovsergey** [comment]
Thanks for the reply. 

I though it might be possible to do something like 
#define WEBSOCKETS_NETWORK_TYPE (0) in my code before I include WebSocketsServer.h so that in WebSockets.h it doesn't override it WEBSOCKETS_NETWORK_TYPE it's already defined in the consumer's code. Maybe I'm wrong and it's not possible.

**Comment by Links2004** [comment]
no it is not possible like this.
since the cpp of the lib and the ino file are compiled in different steps. 
the cpp not know anythink about the define in the ino files

**Comment by anisimovsergey** [comment]
Yes you probably right, but I did some experiment and it seems like I can pass a variable using 
-D name=definition
like this (in my platformio.ini see -D TEST=1) (I'm using platformio not Arduino) 
[env:espduino]
platform = espressif
framework = arduino
board = espduino
build_flags = -Isrc -lstdc++ -lsupc++ -Wall **-D TEST=1**
lib_install = 28,64,306,549

In the code
#if (TEST == (1))
...
#endif

**Comment by Links2004** [comment]
if you can add compiler options in platformio.ini it is possible.
simple add a 
```
#if !defined(WEBSOCKETS_NETWORK_TYPE) 
#endif
```
around the  Network type selection and define WEBSOCKETS_NETWORK_TYPE via commandline and its done.

**Comment by anisimovsergey** [comment]
Ok, can I crate a pull request then? 

Because the code which should be modified is in WebSocketsServer.h
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h

**Comment by Links2004** [comment]
sure, simple add the code around https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L55-L61
will integrate it.

**Comment by anisimovsergey** [comment]
Done 
https://github.com/Links2004/arduinoWebSockets/pull/111/commits

**Comment by anisimovsergey** [comment]
Thanks for merging! I'm closing the issue.

**Comment by jendakol** [comment]
@Links2004 I know this issue is very old, but it's still very relevant. Can you please change your README to mention this possibility instead of need to change the `WebSockets.h`?
