### ISSUE TITLE
Websocket server and client running with condition

### ISSUE THREAD

**Issue by lkeehon** [Links2004/arduinoWebSockets#112]
Is it possible to configure as web socket server when there is no connection to cloud (e.g. no internet connection). Under normal condition e.g. with internet connection, it will be configured as client to the cloud server? Many thanks in advance for your kind advice.

**Comment by Links2004** [comment]
yes sure, you can run the WS Server and Client at the same ESP at the same time.
if you like you can start ans stop them based on the connection state or you leave them running in parallel.

**Comment by lkeehon** [comment]
Hi Marcus, thanks for your prompt reply and published such a useful library for web socket. Currently working on it and seems to work fine. Will publish the result if I can run parallel.

**Comment by lkeehon** [comment]
Hi Marcus, yes web socket client and server can work concurrently without any issue. Thanks again for the good library.

**Comment by Links2004** [comment]
you are welcome.
