### ISSUE TITLE
How to convert "payload" to a real String

### ISSUE THREAD

**Issue by yuwenyangfeng** [Links2004/arduinoWebSockets#113]
`case WStype_TEXT:
		USE_SERIAL.printf("[WSc] get text: %s\n", payload);`
before from WebSocketClient.ino
I try to find keywords from 'payload', however, can't use strstr(payload, "keywords");
could you give me some good idea, please.

**Comment by kiralikbeyin** [comment]
String really = (char * )payload;

**Comment by yuwenyangfeng** [comment]
`USE_SERIAL.printf("[WSc] get text: %s\n", payload);
		String really = (char * )payload;
		USE_SERIAL.print(really);
		USE_SERIAL.printf("\n");`
that is what I need. thank you.
