### ISSUE TITLE
websockets disconnects after trying to receive large string

### ISSUE THREAD

**Issue by kristsm** [Links2004/arduinoWebSockets#114]
Hi!
I have a project where I have to display an image file on a small LCD, which is received from time to time from another wifi device. 
I am using Adafruit GFX library for generating image to LCD (with  drawBitmap function). By default the function takes the image coordinates from PROGMEM array, but there is also possibility to take the image coordinates from another source (which I am using now). The string looks like this: "X: 0x77, 0xFB, 0xDB, 0xDB, 0x17, 0xFD, 0xF9, 0xFF, 0xFF, ..... etc."
I have a small LCD screen connected to ESP-12E, the websockets server service is working fine in case some small amount text strings are transmitted to ESP, they can be easily drawn to the LCD screen as soon as they are received to ESP.  
But the problem comes when I want to receive approx 3000 characters long string.

As soon as I push the button on remote pc to send the string through websockets, ESP hangs up and reboots. The code for receiving this specific string looks like this:

``` cpp
 case WStype_TEXT:
        {
            String text = String((char *) &payload[0]);
if(text.startsWith("X:")){

            String X=(text.substring(text.indexOf("X:")+2,text.length()));
            uint8_t X_data[X.length()];
            X.getBytes(X_data,X.length());
            display.drawBitmap(30, 0, X_data, 64, 64, WHITE);
            display.display();
            delay(2000);
            display.clearDisplay();

           }
}
```

As I said already, the code works ok with smaller amount strings, but it hangs up after about 100x (maybe more) character strings are sent. If this is the case of hardware limits of ESP and there is no straight cure for the problem,  I could somehow split the string into pieces and then send them one by one?

Thank you for your time in advance!

**Comment by Links2004** [comment]
at the first look the question is there a reason to not use binary mode of websocket?
3000 Byte normally is no problem for the websocket or the ESP.

do you get a stack dump or wtd reset?
what kind of display is it? when connected by I2C its may block to long since I2C is emulated by Software on the ESP.

**Comment by kristsm** [comment]
Hi! The same length array  loaded from PROGMEM Works great , so this is not the problem with the OLED or its Interface.
Sorry to say, but I am quiet too far from experienced programmer skills :( Can you please provide me of any hints on how to use the websockets bin file functionality and where to save that file in the memory? I could not find any example on web on how the binary function of the websockets Works.

Thanks!

**Comment by Links2004** [comment]
on the ESP side, the lib will handle all the storing stuff for you ;)
```cpp
 case WStype_BIN:
        {
            if(length == [insert correct size here]) {
                display.drawBitmap(30, 0, payload, 64, 64, WHITE);
                display.display();
                delay(2000);
                display.clearDisplay();
            }
}
```

the browser part is more or less the same as for text:
```js
socket.binaryType = 'arraybuffer';
 var buffer = new Uint8Array(size);
// or  var buffer = new Uint8Array([1,2,34,55,66,255,128,135,148]); // with data
  socket.send(buffer); 
```

**Comment by Links2004** [comment]
feel free to reopen when this still is a Issue.
may retest with the latest git version.
