### ISSUE TITLE
WebSockets and Sleep

### ISSUE THREAD

**Issue by atton16** [Links2004/arduinoWebSockets#117]
Hi,

I am wondering how well can this library handle the sleep (especially on ESP8266) when you run it as WebSocket client for both modem sleep and light sleep.

Thanks

**Comment by Links2004** [comment]
light sleep - will disable CPU + WIFI --> will result in auto reconnect wenn Wifi is up again.
modem sleep - will work fin and will be automatically enabled be the SDK when ever possible.

**Comment by atton16** [comment]
My esp8266 stop receiving ws message after a few hours of idle. With in the first hour of every boot the device can receive message normally.

So I suspect the auto-sleep functionality of esp8266 which automatically turns the device down to modem sleep as soon as it detects idle in CPU (or WiFi ?).

My understanding is, WS protocol would always exchange Ping/Pong messages which effectively render the device to be not able to sleep (???).

However, to make sure that my device wont go to modem sleep, I set the auto-sleep setting to NONE_SLEEP_T. Yet the result is the same, my esp8266 just stop receiving any message after a few hours. (Im using NodeMCU 1.0 -- ESP-12E).

Do you have any suggestions?

**Comment by Links2004** [comment]
have seen a similar behavior with a old WiFi AP i had used for testing, the TCP where still open but no traffic where passed truth it.
think the old AP not handle the DTIM very well (DTIM is used for modem sleep),
or simple drop the inactive client some how, have never go in to the deep there.
after switching the AP the problem where gone.

ping/pong is implemented, but in need to be triggert from the server side.
there is no timer running on the ESP side that triggers a periodical ping.

the WS protocol not force the use of ping/pong, and I have not seen any server that has it enabled by default out there.
but when you enable it should prevent the problem.

**Comment by atton16** [comment]
I read it on the ESP8266 data-sheet that both modem sleep and light sleep can be wake up by DTIM packet. I checked my router the DTIM interval is set to "3". However, this confuses me as even if I set the ESP to _NOT SLEEP_, after a few hours the same problem arises.

P.S. Thank you so much for helping me figure out the problem.
