### ISSUE TITLE
How to make Asynchronous Websocket?

### ISSUE THREAD

**Issue by williamesp2015** [Links2004/arduinoWebSockets#119]
Current version wait until client or server reply and it is the reason for slowness. Please help to have an asynchronous version of Websocket Server or Client to have fastest binary communication (i.e. 512 bytes).
Thank you

**Comment by Links2004** [comment]
you only need to enable async mode.
https://github.com/Links2004/arduinoWebSockets#esp-async-tcp
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L59

**Comment by williamesp2015** [comment]
Thank you. Do you have an example or does not change the program. I guess it is necessary to change loop(). In this case server can send message continuously without necessary to wait for client reply.

**Comment by Links2004** [comment]
in async mode loop is not needed all is "event" based in the background.
the loop is empty function in async mode.

https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsServer.h#L56
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.h#L55

**Comment by sundeep110** [comment]
Hi, 
I have a node server running websocket and esp websocket client.
Problem is client does not connect to server in asynchronous mode, however it works in synchronous mode. I want to go asynchronous as i have to handle few pin states in the loop and this activity gets interrupted (get delayed in websocket.loop() in synchronous mode) trying to connect, even if there is not internet connection.
I am wondering if this is fine. Also let me know if there is any other way of handling this problem
Following is the asynchronous client code snippet:

# include <ESP8266WiFi.h>
# include <Arduino.h>
# include <WebSocketsClient.h>
# include "Timer.h"
#define WEBSOCKETS_NETWORK_TYPE NETWORK_ESP8266_ASYNC

Timer t;
WebSocketsClient webSocket;
char* ssid = "userid";
char* password = "password";


void webSocketEvent(WStype_t type, uint8_t* payload, size_t lenght)
{
  String strPayload = (char*)payload;
  switch (type)
  {
    case WStype_DISCONNECTED:
      break;
    case WStype_CONNECTED:
      {
        break;
      }
    case WStype_TEXT:
      break;
    case WStype_BIN:
      break;

  }
}


void setup()
{
  Serial.begin(115200);
  WiFi.begin(ssid, password);

  //WiFi.disconnect();
  while (WiFi.status() != WL_CONNECTED)
  {
    delay(100);
  }

  webSocket.begin("ws://echo.websocket.org", 3050);
  webSocket.onEvent(webSocketEvent);
}


void loop()
{
   //websocket.loop(); Not required when in async mode
}

Thanks.

**Comment by Links2004** [comment]
doing the ```#define WEBSOCKETS_NETWORK_TYPE``` in the ino file will not work.
you need to Change the header file, or set command line arguments for the compiler (not supported by the arduino IDE)

**Comment by ksundeep** [comment]
Thanks Markus, that worked!

**Comment by KevinNelSL** [comment]
is there a way to use async on esp32, there is no define for ESP32_ASYNC
