### ISSUE TITLE
Disconnect problem in socket.io

### ISSUE THREAD

**Issue by STASIUK** [Links2004/arduinoWebSockets#121]
If you turn off socket.io server, again on and connect to he, you get idle client

**Comment by mhanuel26** [comment]
Hello.

Not sure  which server you are connecting, I am having a problem with connection too, for me it's not clear if it has to be with socket.io, the server is api.samsungsami.io,
I am working with WINC1500, I adapted a little bit the library, and I have test server is working using chrome websocket tool. The problem I have is when connecting as client using SSL, I have been able to test my client is ok by connecting non secure websocket to websocket.org test tool.
I already load certificates and I have been able to connect to same server using HTTP/REST.

Here is a console debug output

[WS-Client] connect wss...
[WS-Client] connected to api.samsungsami.io:443.
[WS-Client][sendHeader] sending header...
[WS-Client][sendHeader] sending header... Done 
[WS-Client][handleHeader] RX: HTTP/1.0 408 Request Time-out
[WS-Client][handleHeader] RX: Cache-Control: no-cache
[WS-Client][handleHeader] RX: Connection: close
[WS-Client][handleHeader] RX: Content-Type: text/html
[WS-Client][handleHeader] Header read fin.
[WS-Client][handleHeader] Client settings:
[WS-Client][handleHeader]  - cURL: /v1.1/websocket?ack=true
[WS-Client][handleHeader]  - cKey: FpCeHW5figKt81nP+epNCA==
[WS-Client][handleHeader] Server header:
[WS-Client][handleHeader]  - cCode: 408
[WS-Client][handleHeader]  - cIsUpgrade: 0
[WS-Client][handleHeader]  - cIsWebsocket: 1
[WS-Client][handleHeader]  - cAccept: 
[WS-Client][handleHeader]  - cProtocol: arduino
[WS-Client][handleHeader]  - cExtensions: 
[WS-Client][handleHeader]  - cVersion: 0
[WS-Client][handleHeader]  - cSessionId: 
[WS-Client][handleHeader] no Websocket connection close.
[WS-Client] client disconnected.


I have some .pcap captures if someone is willing to give me any hint.

I would like to know if someone can try to do a simple test to connect to that server, here is how I am doing it

webSockClient.beginSSL("api.samsungsami.io", 443, "/v1.1/websocket?ack=true");
webSockClient.onEvent(webSocketSamiEvent);

I cannot pass the connection stage.

Any comments will be appreciated.

Best,

**Comment by Links2004** [comment]
@mhanuel26 
in your case the server sends:
```
HTTP/1.0 408 Request Time-out
Cache-Control: no-cache
Connection: close
Content-Type: text/html
```
looks like the request is not handled correct on the server side.

may the server require some additional header or cookie.
you also can try to change the protocol header (4th parameter),
some server dont like the header at all, it can be disabled with:
```
webSockClient.beginSSL("api.samsungsami.io", 443, "/v1.1/websocket?ack=true", "");
```

**Comment by mhanuel26** [comment]
Hile @Links2004,

Thank you for your replay,

I change and try again with your suggestion but still same result,

If you were to debug this issue, where will you start ? capturing encrypted traffic seems not very useful.

Please let me know your thoughts,

**Comment by mhanuel26** [comment]
I use chrome development tools to see the decoded actual header needed, after playing a little bit I make it work.

Thank you,

**Comment by Links2004** [comment]
feel free to reopen when this still is a Issue.
may retest with the latest git version.

**Comment by jcmojj** [comment]
How do I get those debug messages at serial? I didn't have any debug option at arduino ide and it is version 1.8.1.
