### ISSUE TITLE
Help with setting up push event with server

### ISSUE THREAD

**Issue by drifterz28** [Links2004/arduinoWebSockets#125]
I am working with an ESP8266 and in the project I would like to have a timed event to trigger and send information every 2 seconds to every connected client?

Thanks for any help on this.

**Comment by Links2004** [comment]
simple example:

```cpp
const long interval = 2000;
unsigned long previousMillis = 0; 

void loop() {
  unsigned long currentMillis = millis();
  if (currentMillis - previousMillis >= interval) {
    previousMillis = currentMillis;
    broadcastTXT("2sec event");
  }
}
```

**Comment by drifterz28** [comment]
Thanks. that is the same solution I came up with shortly after I posted this. I was reading the source and thought "why shouldn't this work"
