### ISSUE TITLE
The command "arduino --install-library "WebSockets"" failed and exited with 255

### ISSUE THREAD

**Issue by krzychb** [Links2004/arduinoWebSockets#127]
Hi @Links2004,

Since July 10th, 2016 I am using using Travis CI that includes installation of WebSockets library:
```
  - arduino --install-library "WebSockets"
```
I got the following error today:
![image](https://cloud.githubusercontent.com/assets/12953787/18889590/e5c776b2-84fd-11e6-8611-9777d5bd9995.png)

Similar builds on the same repository completed without any issues including the last one 15 days ago:
![image](https://cloud.githubusercontent.com/assets/12953787/18889566/c47a04e8-84fd-11e6-95ad-9c9bad3b9a44.png)

The repository where I have this issue is https://github.com/krzychb/EspScopeA0
I restarted Travis CI build three times and it failed each time in the sample place.

Do you know what the issue may be?

Krzysztof

**Comment by Links2004** [comment]
all the archives are auto generated by github, if I download them i can unpack then without error.
can you provide the download link that makes the problems?

**Comment by krzychb** [comment]
Now I also think the issue is not with the archive. 
After contacting Travis CI support I decided to make additional tests and documented them under https://github.com/arduino/Arduino/issues/5424
Thanks for checking this one and sorry for false alarm.
