### ISSUE TITLE
Client automatic reconnect?

### ISSUE THREAD

**Issue by gabrieluly** [Links2004/arduinoWebSockets#128]
Hi there, my client is working, if the server is not available it will keep trying to connect until succeeds, but if it has connection and eventually loses it won't reconnect, it seems like the websocket.loop() won't try to connect anymore. How can I implement this? Thanks

**Comment by Links2004** [comment]
as long the TCP stack not say that the connection has close, no retry will happen.

code that try to get the state from IP stack:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.cpp#L336
but unforgettably the IP stack is not able to detect the correct state until it tries to send some data.
  
some very easy way to get it to do this is sending some ping or keep alive messages over the web socket.
if the sending is failed the TCP stack will close the connection and the auto reconnect is triggert.

If your application server sends for example all 10 sec a message and you not get a message for 30 sec you can call  ```disconnect()``` to force a reconnect too.

with this two Technics combined you can get the connection much more fail save.

**Comment by gabrieluly** [comment]
Gotcha, worked like a charm, thank you very much!
