### ISSUE TITLE
Make ping

### ISSUE THREAD

**Issue by pauloeduardosp** [Links2004/arduinoWebSockets#130]
Dear,

How can I do a websocket ping? I didn't find any documentation about
Tks

**Comment by Links2004** [comment]
no public API for it yet.

all code is there.
there is only a public function needed that calls:
```
sendFrame(client, WSop_ping);
```

incoming ping request is handled here (pong will be send):
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.cpp#L433

**Comment by pauloeduardosp** [comment]
tks for your answare,
I tried put this in code
sendFrame(client, WSop_ping);
but i receive a compilation error

**Comment by Links2004** [comment]
the library need to be adapted.
currently there is no function that can be called in the ino file.

**Comment by pauloeduardosp** [comment]
tks for your atention.
i'm not familiarized with biblioteca customization. 
I'll try to do in other way,

tks

**Comment by Links2004** [comment]
I can do the change on weekend.

**Comment by Links2004** [comment]
version 2.0.5 can send pings now

**Comment by pauloeduardosp** [comment]
Tks, could you put an example how to use it?

**Comment by Links2004** [comment]
call
```cpp
webSocket.sendPing();
```
to send a ping from Client to Server.
optional you can give a payload, but this is not required.
