### ISSUE TITLE
Custom Websocket-Header

### ISSUE THREAD

**Issue by mafe** [Links2004/arduinoWebSockets#131]
I am using this library as a client, in order to connect to a ashx-WebSocketHandler in asp.net, but it is not possible to connect to it with the default protocol header that is in the library.

With the following header it works:

```
    "GET /WSHandler.ashx HTTP/1.1\r\n"
    "Host: " + _host + ":" + _port + "\r\n"
    "Connection: Upgrade\r\n"
    "Pragma: no-cache\r\n"
    "Cache-Control: no-cache\r\n"
    "Upgrade: websocket\r\n"
    "Origin: ws://websocketorigin\r\n"
    "Sec-WebSocket-Version: 13\r\n"
    "Sec-WebSocket-Key: " + client->cKey + "\r\n";
    "Sec-WebSocket-Protocol: chat\r\n"
    "\r\n";
```

Is or will it be possible, to configure it from the main sketch in future?

**Comment by Links2004** [comment]
most likely the ```protocol``` is not set correct.

you can try:
```cpp
   webSocket.begin("192.168.0.123", 81, "/WSHandler.ashx", "");
```
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.h#L43
