### ISSUE TITLE
Add support for continuation frames (by allowing no FIN bit on frames)

### ISSUE THREAD

**Issue by nerochiaro** [Links2004/arduinoWebSockets#134]
At the moment I can't find any way to send a frame with the FIN bit not set. If I want to send a large amount of data this is necessary to be able to use continuation frames.

The only way to do this at the moment is to inherit directly from WebSocket, but there is a lot of important things that I would have to copy from WebSocketServer if I wanted to do that, and it's not very efficient.

I think that this would be easily solved if WebSocketServer had public inheritance form WebSocket, instead of private. Is there any reason why WebSocketServer is using private inheritance, or can this be changed ?

**Comment by nerochiaro** [comment]
Note that by replacing private with public inheritance in WebSocketServer.h, adding support for continuation frames becomes relatively easy, as you can see here: https://gist.github.com/nerochiaro/6d5ad350ad6c094c21b6cd02c48c67e3

**Comment by Links2004** [comment]
all functions that are not needed for common use cases are ```protected``` to keep the interface simple.
they can simple be accessed by extending the class. 
one simple option is to add a ```bool fin = true```as parameter to all the ```broadcast*``` and ```send*``` functions.

**Comment by nerochiaro** [comment]
>  they can simple be accessed by extending the class. 

Yes, but right now, this does not seem possible.
If you try to compile with the current version of the library [the code here](https://gist.github.com/nerochiaro/6d5ad350ad6c094c21b6cd02c48c67e3) . 

The compilation will fail because the class WebSocketServer is declared 
`WebSocketServer : private WebSocket` 

This means we can not access protected members of the base class from our derived classes (for example we can not access `_clients`).

> all functions that are not needed for common use cases are protected to keep the interface simple.

I agree on keeping the members protected. But the inheritance should be public, so that derived classes can access the protected members.

**Comment by Links2004** [comment]
will changing to:
```class WebSocketsServer: protected WebSockets```
not does the trick?
no access from outside the class, and access to all when you extend it.

**Comment by nerochiaro** [comment]
Yes, that will work

**Comment by Links2004** [comment]
Done with #137
