### ISSUE TITLE
Implemente API to control the reconnecting behavior 

### ISSUE THREAD

**Issue by romuye123** [Links2004/arduinoWebSockets#135]
If my nodejs websockets server is shut down for some or any other reason. My ESP websockets client shows **[WSc] Disconnected** every 1 millisecond. This delays my other functions written in main loop() function.

Whats wrong i would be doing ?

**Comment by Links2004** [comment]
if there is no connection the code tries to connect on ever loop call.
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.cpp#L137

for your use case its may helpful to add an API to control the reconnecting manually.

**Comment by Links2004** [comment]
implementation of `setReconnectInterval` 522a67bc1b4ec0e56cb7e86d4d0bd780ccfa3dff
