### ISSUE TITLE
Reciving Error Multiple Times

### ISSUE THREAD

**Issue by pipoblak** [Links2004/arduinoWebSockets#139]
Hi, i'm reciving this error multiple times, and i dont know how solve this:

dev 1143

 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v09f0c112
~ld
ü

My code: https://gist.github.com/pipoblak/2d63e052ff74612b7429a45ef0eeab22
Using = NODEMCU 1.0

**Comment by Links2004** [comment]
you have some loop (while or for) which take to much time.
first step for debug this is finding the function which is called befor this happens.

simple add a ```Serial.println('<function name>');``` to all your functions.
when we know in which one we get stuckt. 
add some more prints in that functions to find the loop which brakes it.
and then add a ```delay(0);``` to it and it will work.
may there are more than one loop which makes problems,
have seen much animation code which sure take some time.

**Comment by pipoblak** [comment]
Thanks, i will try and post a reply =P

**Comment by pipoblak** [comment]
I tryed with delay(0) but the error persist :( 
I will make more trys, and post a result.

**Comment by pipoblak** [comment]
No Sucess :( 
Can you give me a help?

Actual code : https://gist.github.com/pipoblak/7f02b275c6d11d1c232ca438fd8dd60a#file-websocketwithleds

Last 10 lines from Serial Monitor with DebugOutput:
chg_B2:0
chg_B1:-40
chg_B2:0
chg_B1:-40
chg_B2:0
chg_B1:-40
chg_B2:0
dev 1143

 ets Jan  8 2013,rst cause:4, boot mode:(1,7)

wdt reset

**Comment by Links2004** [comment]
I not see anything like ```Serial.println('<function name>');``` in the code.
do you know which is the last function of your code that is called before the wdt reset?
the ```chg``` and ```dev``` output is from the ESP Wifi part.

**Comment by Links2004** [comment]
may something like this:
https://gist.github.com/Links2004/9119a19638037bef03e13e33f06b0a5e

**Comment by pipoblak** [comment]
![image](https://cloud.githubusercontent.com/assets/18637121/20437731/3c2d76a2-ad9c-11e6-88fb-6b18353deb1d.png)
I recive this error with that

**Comment by pipoblak** [comment]
I change the code because its causing overflow memory, and put into functions who can spend more time, i will post the result soon .

actual code: https://gist.github.com/pipoblak/290e5c3dc191b71a59386eb9a7b10ac3

**Comment by pipoblak** [comment]
![image](https://cloud.githubusercontent.com/assets/18637121/20438439/d386a1ac-ad9e-11e6-99e1-1524c34749b4.png)
Recived that now.

**Comment by Links2004** [comment]
looks like the problem is some how inside ```simpleRainbow``` or a function that is called from there.
may the Adafruit_NeoPixel lib needs to much time to write all pixel data out, or disables interrupts to long.
which the WiFi stack really hates.
may give the WS281X I2S DMA driver a go, there is no need for bit banging then, currently not finding the link to it but last time I used it worked well together with WiFi.

**Comment by pipoblak** [comment]
Thx, i will try =D
