### ISSUE TITLE
Pass a class member function to onEvent?

### ISSUE THREAD

**Issue by marvinroger** [Links2004/arduinoWebSockets#14]
My skills are kind of limited in C++. A code being better than a thousand words:

**MyClass.h**

```cpp
#ifndef MyClass_h
#define MyClass_h

#include <WebSocketsServer.h>
#include <Hash.h>

class MyClass {
  public:
    MyClass();
    ~MyClass();
  private:
    WebSocketsServer* wss;
    int needToAccessThisValue;
    void onWsEvent(uint8_t num, WStype_t type, uint8_t * payload, size_t length);
};

#endif
```

**MyClass.cpp**

```cpp
#include "MyClass.h"

MyClass::MyClass()  {
  this->wss = new WebSocketsServer(81);
  this->wss->onEvent(/* this->onWsEvent */);
  this->needToAccessThisValue = 123;
}

MyClass::~MyClass() {
  delete this->wss;
}

void MyClass::onWsEvent(uint8_t num, WStype_t type, uint8_t * payload, size_t length) {
  Serial.println(this->needToAccessThisValue);
}
```

How can I pass `onWsEvent` to the `onEvent` method? I can't make onWsEvent static because I need to access properties from this function (static would not allow a `this`).

Thanks!

**Comment by Links2004** [comment]
there is no easy way right now.
the best concept may is to extend the WebSocketsClient class and then override the callback handling.
will do some changes in the code for this on the weekend.

**Comment by marvinroger** [comment]
Great, thanks a lot! This will allow to use the lib in a much more modulable way.
BTW, the WebSocket object in Javascript doesn't have a leading `s`. I know this is would a breaking change to rename the class, but I wanted to tell you.

**Comment by Links2004** [comment]
some like this shut do the jop now (not tested)
```cpp
class MyClass: private WebSocketsServer {
  public:
    MyClass();
  private:
    int needToAccessThisValue;
    void runCbEvent(uint8_t num, WStype_t type, uint8_t * payload, size_t length);
};
```

```cpp
MyClass::MyClass() : WebSocketsServer(81) {
  this->needToAccessThisValue = 123;
}

void MyClass::runCbEvent(uint8_t num, WStype_t type, uint8_t * payload, size_t length) {
  Serial.println(this->needToAccessThisValue);
}
```

**Comment by marvinroger** [comment]
If you change

```c++
typedef void (*WebSocketServerEvent)(uint8_t num, WStype_t type, uint8_t * payload, size_t length);
```

by

```c++
typedef std::function<void(uint8_t num, WStype_t type, uint8_t * payload, size_t length)> WebSocketServerEvent;
```

This should do the trick no? Then we could simply:

```c++
this->wss->onEvent(std::bind(&MyClass::onWsEvent, this));
```

**Comment by Links2004** [comment]
habe changed it, thanks for the note.

**Comment by ccostel** [comment]
Hey @Links2004. Yet again I am using your awesome library. Great thanks for it! 

Quick question. Do you plan to allow the passing of a member function or is it still to be used with the way you mentioned?

Thanks!

**Comment by Links2004** [comment]
@ccostel `std::bind` is possible or the ESP, the std lib of the arduino AVR has no support for `std::bind`.
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.h#L35

**Comment by ccostel** [comment]
I think I am a bit confused. 
When I try to use the `std::bind` I get: 

> error: no matching function for call to 'WebSocketsServer::onEvent(std::_Bind_helper<false, void (WebSocket::*)(unsigned char, WStype_t, unsigned ch
> ar*, unsigned int), WebSocket* const>::type)'

WebSocket.h

```
class WebSocket {
public:
  WebSocketsServer* wss;
  WebSocket();
  void onWsEvent(uint8_t num, WStype_t type, uint8_t * payload, size_t length);
};

```

WebSocket.cpp
```
WebSocket::WebSocket()
{
  this->wss = new WebSocketsServer(81);
  this->wss->onEvent(std::bind(&WebSocket::onWsEvent, this));
}
```

I am sure I am not understanding something.  Any hint would be much appreciated :)

**Comment by Links2004** [comment]
PlatformIO is fine.
which version of the lib do you use?

may this helps:

```cpp
using namespace std::placeholders;

WebSocket::WebSocket()
{
  this->wss = new WebSocketsServer(81);
  this->wss->onEvent(std::bind(&WebSocket::onWsEvent, this, _1, _2, _3, _4);
}
```

**Comment by ccostel** [comment]
@Links2004 Your suggestion has worked. Thank you very much for the fast reply. 

I was using the latest version of your library and the following Espressif 1.3.0 

Huge thanks again :)
