### ISSUE TITLE
Client Time out

### ISSUE THREAD

**Issue by pauloeduardosp** [Links2004/arduinoWebSockets#141]
Dear,

how can't i decrease a client timeout?

**Comment by Links2004** [comment]
which timeout do you mean?

connect timeout and write timeout are set here:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L45

**Comment by pauloeduardosp** [comment]
When the server is down to cliente take almost 5 seconts to take a timeout, so the loop take freeze this 5 seconds. 

Like this, I put a millis()/1000 to see how much time take on websocket

102	[WSc] Disconnected!
 [HTTP_C] Entrou na funcao http_config()
109	[WSc] Disconnected!
115	[WSc] Disconnected!
 [HTTP_C] Entrou na funcao http_config()
122	[WSc] Disconnected!
128	[WSc] Disconnected!

**Comment by pauloeduardosp** [comment]
I tried to change this but didn't changed the time
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L45

**Comment by Links2004** [comment]
can you enable debug for Websockets may we get a hint.
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L30

**Comment by Links2004** [comment]
feel free to reopen when this still is a Issue.
may retest with the latest git version.
