### ISSUE TITLE
Echo

### ISSUE THREAD

**Issue by swilsonnc** [Links2004/arduinoWebSockets#144]
Does this Library have Echo capabilities?  If so could you post some example code.  Or some example code for simple ping pong to keepalive client/server connection.

Thanks

**Comment by Links2004** [comment]
echo is easy done by adding
```cpp
webSocket.sendTXT(payload);
```
to the event callback.

for ping there are two ways.
1. the server sends the ping and the client (ESP) answers, for this there is no code extra code needed on the ESP, the lib will automatically response with the correct pong to the server.

2. sending ping with client. add ```webSocket.sendPing();``` to the loop with some millis check to send a ping all 10 sec for example. If the server not answers (ACK) the package the client will automatically disconnect.

**Comment by swilsonnc** [comment]
Is this what you mean?
`case WStype_TEXT:
      if (payload[0] == '#') {
        Serial.printf("[%u] get Text: %s\n", num, payload);
        webSocket.sendTXT(payload);
        yield();
      }`
If I do that it won't compile.  Any idea?

**Comment by swilsonnc** [comment]
Ok. Got the echo part figured out and it works fine.  Used:

`webSocket.sendTXT(num, payload, lenght);`

Now just gotta figure the ping out.

**Comment by Links2004** [comment]
ok your on the server side with the ESP, the code I posted where for the ESP in Client mode.
for ping you can use a millis construct like with ```BlinkWithoutDelay```
and instand of LED blinking you call
```
uint8_t x;
for(x= 0; x < WEBSOCKETS_SERVER_CLIENT_MAX; x++) {
    webSocket.sendPing(x);
}
```

**Comment by swilsonnc** [comment]
OK thank you.  After thinking about it I am not sure that is even my problem.  I don't think the ESP is losing connection with the server at all.  I think the browser that I am using is actually stopping with its updates.  My setup includes th bme280 and esp and sends temp, humidity, pressure, and dew point to the browser every 10 seconds using this command: webSocket.sendTXT(socketNumber, "wpMeter,Arduino," + temp_str + "," + humid_str + "," + dew_str + "," + pres_str + ",1");

You can open console log in the browser and see everything working just fine.  I have a tablet that will do nothing else but sit there with the browser open parked on that page with the sensors on it.  After a while chrome on the tablet stops updating and the sensors freeze.  As soon as I hit refresh on the browser it is back to normal.  Just trying to figure out how to not have to hit refresh so the sensors are right when I look at it.   So, just trying to figure out what is happening and how to fix it.  I may experiment with a laptop the same way a bit later.

I basially built this so I could look at those sensors from anywhere on y phone which works great every time.  I then decided to use a tablet like a weather station so it shows the sensors all the time on the page and that is what needs refreshing at times.

**Comment by Links2004** [comment]
on simple fix on the browser side is to implement a auto reconnect of the websocket when you not get any data for 30sec.
is the tablet going to disable the screen / going to standby? may this disconnects the ws.

**Comment by swilsonnc** [comment]
I think I know what is going on.  I can open the html file in the browser on my laptop and watch console.log in the browser and all is well.  can see the esp sending the data to the page.  If I open the same page with my phone while watching console.log on the laptop and the laptop stops receiving data from the esp.  The phone steals the data.  The laptop never starts back even if phone browser is closed.  I have tried reconnecting-websocket script but it isn't working right ot I misunderstand how it works.

It is my understanding that i should be able to look at the same page with multiple browsers or devices and receive data on all at the same time.  Any thoughts?

**Comment by Links2004** [comment]
yes you can send the data all clients at the same time.
your code includes:
```cpp
webSocket.sendTXT(socketNumber, "wpMeter,Arduino," + temp_str + "," + humid_str + "," + dew_str + "," + pres_str + ",1");
```

```webSocket.sendTXT``` is to send a message to a specific client (socketNumber);
you can use
 ```cpp
webSocket.broadcastTXT("wpMeter,Arduino," + temp_str + "," + humid_str + "," + dew_str + "," + pres_str + ",1");
```
to send it to all.
```broadcastTXT``` is a simple loop over all connected clients.
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsServer.cpp#L205-L211

**Comment by swilsonnc** [comment]
AHHH.  Let me try that.  Thanks.

**Comment by swilsonnc** [comment]
That is working just fine now.  Only thing to figure out now is to update the browser with the values on connection and not have to wait until the esp sends the values after the 10 seconds is up.  websocket.broadcastTXT is on a 10 second timer so the browser doesn't get the values until the 10 sec timer of the esp is up and it sends the data.  I could probably do a if client.something something.  Will have to see.  Thanks

**Comment by Links2004** [comment]
use
 ```cpp
webSocket.sendTXT(num, "wpMeter,Arduino," + temp_str + "," + humid_str + "," + dew_str + "," + pres_str + ",1");
```
in the ```WStype_CONNECTED``` case will do the trick.

**Comment by swilsonnc** [comment]
I just changed it so the timer is 1 second.  The ESP and the BME280 hndle it just fine and the page is pretty much live.  Thanks for all the help and pointing out websocket.broadcastTXT.
