### ISSUE TITLE
TLS 1.2

### ISSUE THREAD

**Issue by au190** [Links2004/arduinoWebSockets#145]
Hi !

Is it planed to implement TLS 1.2 in the near future ?
As I know this wss working only with TLS 1.1, is it true ?

Thx

**Comment by Links2004** [comment]
for SSL / TLS support the ESP libs are use (https://github.com/igrr/axtls-8266)
as soon as its supported there its automatically works for the wss too.
looks like some work on TLS 1.2 is ongoing for axtls.

**Comment by Maxtoq** [comment]
Hi,

I need to use TLS 1.2 with the Websocket Client code on ESP 8266. 
How can I integrate axTLS in the code ?

Thx

**Comment by Links2004** [comment]
as soon it is integrated in to the Arduino for ESP8266, it will work out of the box.
@igrr sure can give you the info about the status.
https://github.com/esp8266/Arduino
