### ISSUE TITLE
Nonstandard headers from achex.ca make the client disconnect

### ISSUE THREAD

**Issue by ondrejhenek** [Links2004/arduinoWebSockets#146]
Hi!

We've been using this great library for quite some together with a service called achex.ca, but some time ago our stuff stopped working. While debugging I found out that it's because this library expects all headers to have a space after semicolon, see WebsocketsClient.cpp:490 where the +2 trims semicolon and space. Unfortunately achex.ca doesn't use a space in Sec-WebSocket-Accept therefore it trims the first letter of token and there is a mismatch...

            String headerName = headerLine->substring(0, headerLine->indexOf(':'));
            String headerValue = headerLine->substring(headerLine->indexOf(':') + 2);

So I've updated the library to strip the semicolon and then trim the value, see below. It works great, but another issue came up. They don't send sessionId headers so the client disconnects anyway. I just hardcoded some random stuff there and it works, but it's pretty ugly.

            String headerName = headerLine->substring(0, headerLine->indexOf(':'));
            String headerValue = headerLine->substring(headerLine->indexOf(':') + 1);
            client->cSessionId = "XYZ123";
            headerValue.trim();

I've also sent a message linking here to the guys from achex.ca since some users might have the same issue with their service. So who is breaking the standards here? Is it required to have semicolon followed by space in headers? And is it required to send the sessionID?

**Comment by Links2004** [comment]
the websocket lib is implemented like the RFC6455 describes it.

the session headers are described here:
https://tools.ietf.org/html/rfc6455#section-11.3.1

the first generation of websocket dont have this headers but they are obsolete and not compatible with RFC6455.
they only exists as draft and never make it to a RFC.
https://tools.ietf.org/html/draft-hixie-thewebsocketprotocol-75

regarding the HTTP header
the RFC6455 points to the HTTP RFC2616 https://tools.ietf.org/html/rfc2616
currently I have no time to read it, but i habe never seen a real webserver that not have a space after the ":". 
some creepy embedded implementations yes, but I would not use them as reference for ok or not. 

can you provide a Header that is send from the server or a URL that i can check it?

**Comment by ondrejhenek** [comment]
Hi!

So here is the headers sent and received:

```
GET / HTTP/1.1
Host: achex.ca:4010
Connection: Upgrade
Upgrade: websocket
Origin: file://
User-Agent: arduino-WebSocket-Client
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: JpLcU5ROpzIAY8vlMCXv4w==
Sec-WebSocket-Protocol: arduino
Host: achex.ca:4010
Origin: file://
User-Agent: arduino-WebSocket-Client
```
```
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Version: 13
Sec-WebSocket-Accept:WgW8mWGx1s4FQoQXTwCiokKF9j8=
```

The response `Sec-WebSocket-Accept:WgW8mWGx1s4FQoQXTwCiokKF9j8=` is missing a space after semicolon, therefore the first letter gets trimmed and the security check fails. My proposal in the post above is to get rid of the semicolon only and then trim the result if it has space or not. (Let's forget about the session thing. I can't replicate it anymore anyway so it's not an issue.)

But author of this free websocket service, Alex, responded that it will be probably an easy fix. So if you want to make sure, that also _creepy embedded implementations_ will work, look at my proposal. Otherwise I'll wait for Alex to answer and fix it on his server side.

**Comment by Links2004** [comment]
will keep it open as remainder to read the RFC2616.

**Comment by Links2004** [comment]
had final some time to read the RFC2616,
both is allowed with space and without space after the ":"
