### ISSUE TITLE
'struct WSclient_t' has no member named 'SessionId'

### ISSUE THREAD

**Issue by c1nemA1** [Links2004/arduinoWebSockets#148]
`C:\Users\***\Documents\Arduino\libraries\ArduinoWebSockets\src\WebSocketsClient.cpp: In member function 'virtual void WebSocketsClient::clientDisconnect(WSclient_t*)':`

`C:\Users\***\Documents\Arduino\libraries\ArduinoWebSockets\src\WebSocketsClient.cpp:334:13: error: 'struct WSclient_t' has no member named 'SessionId'`

I could easily fix it by changing Line 334 from `client->SessionId = "";` to client->**c**SessionId = "";.
The "c" was missing. just a typo I guess.

**Comment by c1nemA1** [comment]
Oh darn. Just saw that odelot already provided the needed Pull request for this.

Update WebSocketsClient.cpp
#147 opened 8 hours ago by odelot

#147

**Comment by Links2004** [comment]
yes it where a typo, lessen learned never commit in half sleep ;)
