### ISSUE TITLE
Closed connection not noticed by WebSocketClient

### ISSUE THREAD

**Issue by nodemand** [Links2004/arduinoWebSockets#15]
Hi!

Thank you for coding such a great websocket library! It works like a charm! 
However, I am running into the following issue...
I have an ESP8266 websocket client running your code and it connects to a php ratchet websocket server (latest version: 0.3.3). The ESP2866 waits for commands from other websocket clients to do something. This works perfectly, however, after a while (more than 20-30 minutes) the connection closes (most likely initiated by the client). This shows up in the ratchet log BUT the websocket client still says _client.tcp.connected() == true. I checked whether it was ratchet falsely claiming the connection was closed, but after running "netstat -natp" on the websocket server it became clear that indeed there is no active connection anymore between the ratchet server and the ESP8266 client while _client.tcp.connected() in the loop function still returns true :-(...

I checked online and found this on https://www.arduino.cc/en/Reference/WiFiClientConnected: 

"Note that a client is considered connected if the connection has been closed but there is still unread data."

So maybe there is still unread data in the connection somehow? Or perhaps a bug in the ESP's tcp stack? 

Thanx!

Jeroen

**Comment by Links2004** [comment]
the Note from the Arduino page is not valide for the ESP IP stack.
The ESP has a similar API the the normal WiFi class from Arduino to make it easier to use but its internally complete different.

when the client is connected then ```handleClientData``` is called:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.cpp#L89

if the data available it handle it based of the state:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.cpp#L238-L249

can you please enable debug for the web sockets:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L40
(select a valid Serial port for your setup)

if the Web Sockets code will do the disconnect you will get a message: 
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.cpp#L43

is the socket active used or do you have no data flow during the 20min?
if you not get a message for disconnection, 
 - its most likely a communication / tcp stack problem 
 - may a trace with Wireshark helps to see what is going on.
do the PHP script has a maximum run time?

I have here connections over many days with the library to a nodejs websocket server.

**Comment by nodemand** [comment]
hi links2004,
sorry for my late reply. i somehow missed the notification about your reply. thank you for answering!
in my case there is no data flow. i'm building an IoT product [The LovePod](http://lovepod.nl) that just sits and waits until someone sends a command to it. so i expect the connection to be kept open. after posting the issue i implemented heartbeat code that sends a one character heartbeat every 5 seconds and the websockets server replies. if no reply is received i reconnect. this solved the problem in my unique case.

the php script runs and keeps running. no problem there.

i have no experience using WireShark, but i'll give it a try.

thanx again!

jeroen
