### ISSUE TITLE
RAM is wasted on const strings

### ISSUE THREAD

**Issue by everslick** [Links2004/arduinoWebSockets#152]
is there a specific reason why constant strings are not wrapped in F() or PSTR() macros? At a first glance I would guess, that at least 400 bytes of RAM are wasted this way. Is there a good reason NOT to wrap them?

**Comment by Links2004** [comment]
the only reason is performance, and the macro where not really stable at the time where I write it.

Note for others: 
```DEBUG_WEBSOCKETS``` stuff will not end in the bin unless the debug define is set.

**Comment by Links2004** [comment]
if you need the space in ram, you are welcome to add a define in the config to move them to flash.
something like.


```cpp
// moves all Header strings to Flash
#define WEBSOCKETS_SAVE_RAM

#ifndef WEBSOCKETS_SAVE_RAM
#define WEBSOCKETS_STRING(var)   var
#else 
#define WEBSOCKETS_STRING(var)   F(var)
#endif
```

**Comment by everslick** [comment]
ok, will make a PR later, when i get to it. thx, for the clarification.

**Comment by MoegerleStephan** [comment]
Great idea! 
I'm not 100% familiar with #define WEBSOCKETS_STRING (var) F(var). 
If I want two use the content of the address in flash.. How can I address the specific memory location in flash? 
E.g. if I want to Serial.print the content of WEBSOCKETS_STRING. How do I have to do this?

**Comment by Links2004** [comment]
the ESP core will handle all memory access thinks, no need to deal with addresses.
https://github.com/esp8266/Arduino/blob/master/doc/reference.md#progmem
https://github.com/esp8266/Arduino/blob/master/cores/esp8266/Print.cpp#L89-L99
```cpp
Serial.print(WEBSOCKETS_STRING("YOUR STRING"));
```
of
```cpp
Serial.print(F("YOUR STRING"));
```

**Comment by MoegerleStephan** [comment]
Ahh nice! :+1: Thanks for that!
