### ISSUE TITLE
is delay(0) really needed?

### ISSUE THREAD

**Issue by everslick** [Links2004/arduinoWebSockets#153]
i removed all occurrences of delay(0) in the server and in the base class and everything is running fine. I believe they are not needed, but introduce latencies that might be problematic in other parts of the firmware.

**Comment by Links2004** [comment]
for less load its not needed since every end of ```void loop()``` run, the same internal Handling is done with the ``` delay(0)``` call.
if you push the websockets to the max it get very instabile without the delay(0).
