### ISSUE TITLE
Error on compiling ATmega branch '  _fingerprint' not declared

### ISSUE THREAD

**Issue by petrusz1** [Links2004/arduinoWebSockets#154]
The ATmega branch is not compiling:

Arduino: 1.6.13 (Linux)

/path-to-sketchbook/libraries/arduinoWebSockets-ATmega/src/WebSocketsClient.cpp: In member function 'void WebSocketsClient::begin(const char*, uint16_t, const char*)':
/path-to-sketchbook/libraries/arduinoWebSockets-ATmega/src/WebSocketsClient.cpp:43:5: error: '_fingerprint' was not declared in this scope
     _fingerprint = "";

     ^
exit status 1

**Comment by Links2004** [comment]
https://github.com/Links2004/arduinoWebSockets/commit/7c5113fe2dbe86fceec21b2846652d26de866234
will fix it
