### ISSUE TITLE
on disconnect event WebSocketClient tries to reconnect before ca

### ISSUE THREAD

**Issue by c-mysec** [Links2004/arduinoWebSockets#157]
WebScoketClient.loop checks disconnection, calls webSocketEvent, and immediatly tries to reconnect.
How can I disable this behavior?
I call webSocketClient.disconnect on disconnect event and I want this call to prevent WebSocketClient to try to reconnect.
Alternatively reconnection should be done on next call to loop for example, not on the same loop iteration that detects disconnection.

That is because I have an http call before each websocket connection when I use DH key-exchange and also do ws load balancing.

Any idea how to achieve this behavior?

thanks

**Comment by Links2004** [comment]
destroy the class WebSocketsClient is the easiest way right now.

```cpp
WebSocketsClient * webSocket;

void connect() {
    webSocket = new WebSocketsClient();
    webSocket->begin("192.168.0.123", 81);
    webSocket->onEvent(webSocketEvent);
}

void disconnect() {
    webSocket->disconnect();
    delete webSocket;
    webSocket = null;
}

void loop() {
    if(webSocket) webSocket.loop();
}
```

with this you have full control.

**Comment by c-mysec** [comment]
i did not understand. Callback is called within webSocket->loop().

void WebSocketsClient::loop(void) {
    if(!clientIsConnected(&_client)) {   // ---> detects disconnection and rises disconnection event
       ////// immediatly tries to reconnect ---> i do not want this....I want that WebSocketsClient::loop is aborted on the event of a disconnetion.
    }
    .......
}

I think deleting webSocket will not prevent reconnection attemp and will lead to undefined behavior in the rest of the loop method.

if(webSocket) webSocket->loop(); will stop auto-reconnection on the next cycle.
But will not prevent reconnection on the same cycle because of the above "if".

**Comment by Links2004** [comment]
ok, now I get it.
the best way then is ti extend the WebSocketsClient class,
then you can write your one loop to handle the reconnection attempt in any way you like too.

```cpp
class customWebSocketsClient: public WebSocketsClient {
    public:
       void loop(void) {
              if(!WebSocketsClient::clientIsConnected(&_client)) {
                 // if you want to reconnect call
                 WebSocketsClient::loop();
                 // if not skip it until you want to reconnect.
              }
       }
}

customWebSocketsClient * webSocket;

// rest of the code is like for WebSocketsClient
```

**Comment by Links2004** [comment]
https://github.com/Links2004/arduinoWebSockets/issues/135

**Comment by c-mysec** [comment]
For now I am verifying if websock is disconnected before calling "WebSocketsClient::loop();" as you said.
But it would be greate if the API has some kind of control over the reconnection attempt.
I think the common use case for this functionality is when the websocket endpoint uses an authentication mechanism which requires new token on every connection before upgrade.

**Comment by Links2004** [comment]
API for control is on the todo list (#135).

**Comment by Links2004** [comment]
implementation of `setReconnectInterval` 522a67bc1b4ec0e56cb7e86d4d0bd780ccfa3dff

**Comment by denden4444** [comment]
Hi @c-mysec 

Did you ever get the above working ?
I just want to connect once . send one message and disconnect.

Look forward to your reply

Den

**Comment by c-mysec** [comment]
As a wrote above, it worked by just verifing the connection before call the loop() method.
As for your problem, you can set a large ReconnectInterval.
But I can't see the point of using WebSockets to send just one message.
