### ISSUE TITLE
about #define USE_SERIAL Serial1

### ISSUE THREAD

**Issue by yuwenyangfeng** [Links2004/arduinoWebSockets#16]
dear friend,
first,when I use your client from example, I don't know yours "Serial1" is from which library? how can read serial data.
secondly, I used nodemcu0.9 module, take ch340g connected mcu's rx(D9),tx(D10), received lots of messy code.
may you help me. thanks.

**Comment by Links2004** [comment]
over the define you can select if you want to user ```Serial``` or ```Serial1``` for serial output.
in you case you need;
```cpp
#define USE_SERIAL Serial
```
more about serial on ESP https://github.com/esp8266/Arduino/blob/master/doc/reference.md#serial

the nodemcu boards has for some reason a other pin naming then the rest of all ESP modules see here:
https://github.com/esp8266/Arduino/blob/master/doc/boards.md#nodemcu-0-9

D9 and D10 will map to GPIO1 + GPIO3 thy are connected to ```Serial```

**Comment by yuwenyangfeng** [comment]
Thanks for your response,immediately.
I have no time to try,from now on.
However still thanks for your help.

发自宇文杨峰

**Comment by yuwenyangfeng** [comment]
Thanks for your response,immediately.
I have no time to try,from now on.
However still thanks for your help.
