### ISSUE TITLE
esp8266 says disconnected but nodejs says connected

### ISSUE THREAD

**Issue by chjno** [Links2004/arduinoWebSockets#160]
I'm having trouble with the WebSocketClientSocketIO.ino example. Here's my code:

esp8266
```
#include <Arduino.h>

#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>

#include <WebSocketsClient.h>

#include <Hash.h>

ESP8266WiFiMulti WiFiMulti;
WebSocketsClient webSocket;


#define USE_SERIAL Serial

#define MESSAGE_INTERVAL 30000
#define HEARTBEAT_INTERVAL 25000

uint64_t messageTimestamp = 0;
uint64_t heartbeatTimestamp = 0;
bool isConnected = false;

void webSocketEvent(WStype_t type, uint8_t * payload, size_t lenght) {


    switch(type) {
        case WStype_DISCONNECTED:
            USE_SERIAL.printf("[WSc] Disconnected!\n");
            isConnected = false;
            break;
        case WStype_CONNECTED:
            {
                USE_SERIAL.printf("[WSc] Connected to url: %s\n",  payload);
                isConnected = true;

          // send message to server when Connected
                // socket.io upgrade confirmation message (required)
        webSocket.sendTXT("5");
            }
            break;
        case WStype_TEXT:
            USE_SERIAL.printf("[WSc] get text: %s\n", payload);

      // send message to server
      // webSocket.sendTXT("message here");
            break;
        case WStype_BIN:
            USE_SERIAL.printf("[WSc] get binary lenght: %u\n", lenght);
            hexdump(payload, lenght);

            // send data to server
            // webSocket.sendBIN(payload, lenght);
            break;
    }

}

void setup() {
    // USE_SERIAL.begin(921600);
    USE_SERIAL.begin(115200);

    //Serial.setDebugOutput(true);
    USE_SERIAL.setDebugOutput(true);

    USE_SERIAL.println();
    USE_SERIAL.println();
    USE_SERIAL.println();

      for(uint8_t t = 4; t > 0; t--) {
          USE_SERIAL.printf("[SETUP] BOOT WAIT %d...\n", t);
          USE_SERIAL.flush();
          delay(1000);
      }

    WiFiMulti.addAP("itpsandbox", "NYU+s0a!+P?");

    //WiFi.disconnect();
    while(WiFiMulti.run() != WL_CONNECTED) {
        delay(100);
    }

    webSocket.beginSocketIO("128.122.6.241", 3000);
    //webSocket.setAuthorization("user", "Password"); // HTTP Basic Authorization
    webSocket.onEvent(webSocketEvent);

}

void loop() {
    webSocket.loop();

    if(isConnected) {

        uint64_t now = millis();

        if(now - messageTimestamp > MESSAGE_INTERVAL) {
            messageTimestamp = now;
            // example socket.io message with type "messageType" and JSON payload
            webSocket.sendTXT("42[\"messageType\",{\"greeting\":\"hello\"}]");
        }
        if((now - heartbeatTimestamp) > HEARTBEAT_INTERVAL) {
            heartbeatTimestamp = now;
            // socket.io heartbeat message
            webSocket.sendTXT("2");
        }
    }
}
```

node.js
```
var express = require('express');
var app = express();
var server = require('http').Server(app);
var port = 3000;
var io = require('socket.io')(server);
var request = require('request');

function listen(){
  var host = server.address().address;
  var port = server.address().port;
  console.log('Example app listening at http://' + host + ':' + port);
}

var io = require('socket.io')(server);

io.on('connection', function (socket){

  console.log('connected ' + socket.id);

  socket.on('disconnect', function(){
    console.log('disconnected: ' + socket.id);
  });
});

server.listen(port, function() {
  console.log('Express server running on *:' + port);
});

```

serial monitor output
```
connected with itpsandbox, channel 11
dhcp client start...
chg_B1:-40
ip:172.22.6.89,mask:255.255.255.0,gw:172.22.6.1
[WSc] Disconnected!
[WSc] Disconnected!
[WSc] Disconnected!
```

node.js output
```
Express server running on *:3000
connected ZDYf7pXW24BwWQtUAAAA
connected MzlipxRUPwIJ29y0AAAB
connected VV2oGOz_Or2nQufBAAAC
connected Y_cjPv2cgGEgadn0AAAD
```

Any help would be greatly appreciated.

**Comment by Links2004** [comment]
Please enable the debug output and post the results here.
1. Set debug port in IDE Menu
2. enable debug for Websockets (https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L30)

**Comment by nguyenhunga5** [comment]
Hi Links2004,

I have same problem. This is log:

[WS-Client] asyncConnect...
[WS-Client] connected to xxx.xxx.xxx.xxx:3000.
[WS-Client][sendHeader] sending header...
[WS-Client][sendHeader] handshake GET /socket.io/?EIO=3&transport=websocket&sid=z3FT7cOWC8T5zHA-AAAD; Path=/; HttpOnly HTTP/1.1
Host: xxx.xxx.xxx.xxx:3000
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: TO/+hfBThYeLHH2CG0zXOg==
Sec-WebSocket-Protocol: arduino
Origin: file://
User-Agent: arduino-WebSocket-Client

[WS-Client][sendHeader] sending header... Done (27415us).
[WS-Server][0] Disconnect client

**Comment by kptdobe** [comment]
Hi @Links2004, I have the same issue here.

I have approximatively the same code than above.

My ESP8266 logs:

`Connected to WIFI
Socket started
[WS-Client] connect ws...
[WS-Client] connected to 192.168.1.100:9000.
[WS-Client][sendHeader] sending header...
[WS-Client][sendHeader] sending header... Done (24329us).
[WS-Client][handleHeader] RX: HTTP/1.1 200 OK
[WS-Client][handleHeader] RX: Content-Type: application/octet-stream
[WS-Client][handleHeader] RX: Content-Length: 101
[WS-Client][handleHeader] RX: Access-Control-Allow-Credentials: true
[WS-Client][handleHeader] RX: Access-Control-Allow-Origin: file://
[WS-Client][handleHeader] RX: Set-Cookie: io=0sWUVobNwxdjk5dbAAAB; Path=/; HttpOnly
[WS-Client][handleHeader] RX: Date: Tue, 07 Feb 2017 16:09:56 GMT
[WS-Client][handleHeader] RX: Connection: keep-alive
[WS-Client][handleHeader] Header read fin.
[WS-Client][handleHeader] Client settings:
[WS-Client][handleHeader]  - cURL: /socket.io/?EIO=3
[WS-Client][handleHeader]  - cKey: vvIlmgo9KxCfAvc8ErVQyg==
[WS-Client][handleHeader] Server header:
[WS-Client][handleHeader]  - cCode: 200
[WS-Client][handleHeader]  - cIsUpgrade: 0
[WS-Client][handleHeader]  - cIsWebsocket: 1
[WS-Client][handleHeader]  - cAccept: 
[WS-Client][handleHeader]  - cProtocol: arduino
[WS-Client][handleHeader]  - cExtensions: 
[WS-Client][handleHeader]  - cVersion: 0
[WS-Client][handleHeader]  - cSessionId: 0sWUVobNwxdjk5dbAAAB; Path=/; HttpOnly
[WS-Client][sendHeader] sending header...
[WS-Client][sendHeader] sending header... Done (8656us).
[WS-Client][handleHeader] RX: 
[WS-Client] connection lost.
[WS-Client] client disconnected.
[WSc] Received socket event! <null>
[WSc] Disconnected!
[WS-Client] connect ws...`

NodeJS + Socket.io logs:
`
socket.io:server initializing namespace / +0ms
  socket.io:server creating http server and binding to 9000 +2ms
  socket.io:server creating engine.io instance with opts {"path":"/socket.io"} +4ms
  socket.io:server attaching client serving req handler +1ms
  engine intercepting request for path "/socket.io/" +36s
  engine handling "GET" http request "/socket.io/?EIO=3&transport=polling" +1ms
  engine handshaking client "a-y_3-ViU2nY6EReAAAA" +2ms
  engine:socket sending packet "open" ({"sid":"a-y_3-ViU2nY6EReAAAA","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}) +2ms
  engine:polling setting request +0ms
  engine:socket flushing buffer to transport +1ms
  engine:polling writing "	�0{"sid":"a-y_3-ViU2nY6EReAAAA","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}" +1ms
  engine:socket executing batch send callback +9ms
  socket.io:server incoming connection with id a-y_3-ViU2nY6EReAAAA +0ms
  socket.io:client connecting to namespace / +0ms
  socket.io:namespace adding socket to nsp / +1ms
  socket.io:socket socket connected - writing packet +2ms
  socket.io:socket joining room a-y_3-ViU2nY6EReAAAA +0ms
  socket.io:client writing packet {"type":0,"nsp":"/"} +1ms
  socket.io-parser encoding packet {"type":0,"nsp":"/"} +0ms
  socket.io-parser encoded {"type":0,"nsp":"/"} as 0 +1ms
  engine:socket sending packet "message" (0) +1ms
Connected a-y_3-ViU2nY6EReAAAA
  socket.io:client writing packet {"type":2,"data":["welcome",{"text":"hello a-y_3-ViU2nY6EReAAAA"}],"nsp":"/"} +2ms
  socket.io-parser encoding packet {"type":2,"data":["welcome",{"text":"hello a-y_3-ViU2nY6EReAAAA"}],"nsp":"/"} +2ms
  socket.io-parser encoded {"type":2,"data":["welcome",{"text":"hello a-y_3-ViU2nY6EReAAAA"}],"nsp":"/"} as 2["welcome",{"text":"hello a-y_3-ViU2nY6EReAAAA"}] +0ms
  engine:socket sending packet "message" (2["welcome",{"text":"hello a-y_3-ViU2nY6EReAAAA"}]) +1ms
  socket.io:socket joined room a-y_3-ViU2nY6EReAAAA +0ms
  engine:polling closing +1m
  engine:polling transport not writable - buffering orderly close +1ms
  socket.io:client client close with reason ping timeout +0ms
  socket.io:socket closing socket - reason ping timeout +0ms
`

Thanks for support.

**Comment by Links2004** [comment]
@kptdobe what version do you, from the logs it looks like a older one.
can you try using the latest git version?

**Comment by kptdobe** [comment]
arff, genau! 
Just tested with the git version and works fine! 

Thanks a lot.

For the record:
- I was using 2.0.5 which is the version provided by the Arduino library manager... Now that I updated the library manually, Arduino library manager says 2.0.6. I assume the latest version is not released yet., works for me with:
- Works for me with:
   - https://github.com/Links2004/arduinoWebSockets (latest code)
   - almost similar code than in the orginal comment (node server and ESP code)
   - Socket.io is socket.io-1.7.2 on the node instance

**Comment by Links2004** [comment]
looks like it is time for a release ;)
