### ISSUE TITLE
ESP32 support

### ISSUE THREAD

**Issue by williamesp2015** [Links2004/arduinoWebSockets#161]
When we can use Websocket with ESP32?

Thank you

**Comment by Links2004** [comment]
have not tried it yet, currently only have a ESP31.
but there is a good change that it work already in async mode.
if I remember correct ESPAsyncTCP supports ESP32.

**Comment by n0f8r** [comment]
@Links2004  please excuse my ignorance/and/or/dumb questions, C is not my "native" language.

Looking at the ifdef's in WebSockets.h - if you want to enable NETWORK_ESP8266_ASYNC that requires that ESP8266WiFi.h or ESP31BWiFi.h be available when compiling - and they're not part of the Arduino core for ESP32....

So can you explain more on how to use WebSocket with ESP32??

**Comment by Links2004** [comment]
looks like it named ```WiFi.h``` for ESP32, then a other ifdef is needed ```#ifdef ESP32```
https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/src/WiFi.h

**Comment by n0f8r** [comment]
So something like this in WebSockets.h - and put a #define ESP32 1 as first line in my sketch?
Also am I seeing double, or are lines 75-79 and lines 91-95 in current WebSockets.h copyand paste duplicates?

#if defined(ESP8266) || defined(ESP31B) || defined(ESP32)
//#define WEBSOCKETS_NETWORK_TYPE NETWORK_ESP8266
**#define WEBSOCKETS_NETWORK_TYPE NETWORK_ESP8266_ASYNC**
#else
#define WEBSOCKETS_NETWORK_TYPE NETWORK_W5100
#endif
#endif

#if (WEBSOCKETS_NETWORK_TYPE == NETWORK_ESP8266_ASYNC)

// Note:
//   No SSL/WSS support for client in Async mode
//   TLS lib need a sync interface!

#if !defined(ESP8266) && !defined(ESP31B) && **!defined(ESP32)**
#error "network type ESP8266 ASYNC only possible on the ESP mcu!"
#endif

#ifdef ESP8266
#include <ESP8266WiFi.h>
**#elif defined(ESP32)**
**#include <Wifi.h>**
#else
#include <ESP31BWiFi.h>
#endif
#include <ESPAsyncTCP.h>
#include <ESPAsyncTCPbuffer.h>
#define WEBSOCKETS_NETWORK_CLASS AsyncTCPbuffer
#define WEBSOCKETS_NETWORK_SERVER_CLASS AsyncServer

#elif (WEBSOCKETS_NETWORK_TYPE == NETWORK_ESP8266)

#if !defined(ESP8266) && !defined(ESP31B) **&& !defined(ESP32)**
#error "network type ESP8266 only possible on the ESP mcu!"
#endif

**Comment by Links2004** [comment]
yes, like this.

lines 75-79 are for ASYNC
lines 91-95 are for SYNC
the Wifi is the same for them ;)

note: you not need to define ```ESP32``` the IDE will do this based on which board you select.

**Comment by dericpr** [comment]
I'm trying to use your lib with an ESP32 and I'm stuck in some dependency hell.   My current issue is with adding the ESPAsyncTCP library. 

I'm seeing a lot of errors like the following.

`ESPAsyncTCP-master/src/ESPAsyncTCP.cpp:113:36: error: macro "ip_route" requires 2 arguments, but only 1 given netif* interface = ip_route(&addr);`

It seems like these macros have changes in the esp32 SDK

'hardware/espressif/esp32/tools/sdk/include/lwip/lwip/ip.h:#define ip_route(src, dest)'

Any thoughts?

**Comment by zenmanenergy** [comment]
I've started playing around with this today. The majority of the errors (as of today) with the arduinoWebSockets on esp32 are issues with SSL. After commenting out many lines I have been able to get it to compile, although so far I am unable to connect to the server. At the moment I'm trying to get some debugging information to display.

**Comment by zenmanenergy** [comment]
I have made a little progress, but I can't seem to get my browser to connect to the socket server. If anyone would like to help debug this, I would be grateful!

I've added a bunch of #if defined(ESP32) to the code. It's compiling now and outputting some debug info, but still not connecting. Here's the fork:
https://github.com/zenmanenergy/arduinoWebSockets

**Comment by bbx10** [comment]
I have a version working on ESP32. Not much testing so far but simple cases work. 

https://github.com/bbx10/Hash_tng

https://github.com/bbx10/arduinoWebSockets/tree/esp32

Be sure to use the esp32 branch. The Hash_tng library is required.

**Comment by wurst44** [comment]
@bbx10 it's working!!!!! after commenting out this line:

//#if (WEBSOCKETS_NETWORK_TYPE == NETWORK_ESP8266)
//    while(_server->hasClient()) {
//#endif

hasClient() seems undefined in ESP32 WifiServer.cpp/h

**Comment by bbx10** [comment]
I am glad to hear it is working! hasClient was added recently. Try git pull.

```
432bcf5 Add WiFiServer hasClient and WiFiTelnetToSerial example (#394)
```

**Comment by arlaor** [comment]
@bbx10  
It's great news!

**Comment by copercini** [comment]
Async TCP for ESP32 is here: https://github.com/me-no-dev/AsyncTCP

**Comment by mixtool** [comment]
Hello!

Totally new to github so sorry for my noob question: how do I use this https://github.com/me-no-dev/AsyncTCP in arduino IDE?

**Comment by ajw685** [comment]
THIS IS AWESOME. THANK YOU SO MUCH!
