### ISSUE TITLE
Cannot work with pointer declaration

### ISSUE THREAD

**Issue by MoegerleStephan** [Links2004/arduinoWebSockets#162]
Hello there,

I'm using the ESP-12 (SDK 2.3.0) and having strange problems with the following way of initialization:

`WebSocketsClient * meshClient;`

> meshClient = new WebSocketsClient();
>   
> meshClient -> begin("192.168.1.1", 80, "/ws", "arduino");
> meshClient->onEvent(meshClientEvent);

Output was:

> [WSc] get text: <null>
> [WSc] Disconnected!

If I use following way of declaration everything works fine:

`WebSocketsClient meshClient;`

```
meshClient.begin("192.168.1.1", 80, "/ws", "arduino");
meshClient.onEvent(meshClientEvent);
```

Because of the easy way of deleting the client object I really want to use the pointer initialization..

Now the strange thing. If I use the pointer declaration and init the client directly at the start (setup()), everything seems to work fine. 
If I init the websocket client on another tab in Arduino (before or behind the webserver), the client doesn't work in my specific project anymore. 

The debug response was following:

> [WS-Client] asyncConnect...
> [WS-Client] connected to 192.168.1.1:80.
> [WS-Client][sendHeader] sending header...
> [WS-Client][sendHeader] handshake GET /ws&transport=polling HTTP/1.1
> Host: 192.168.1.1:80
> Connection: keep-alive
> Origin: file://
> User-Agent: arduino-WebSocket-Client
> 
> [WS-Client][sendHeader] sending header... Done (15036us).
> [WS-Client][handleHeader] RX: HTTP/1.1 302 Found
> [WS-Client][handleHeader] RX: Content-Length: 0
> [WS-Client][handleHeader] RX: Connection: close
> [WS-Client][handleHeader] RX: Location: http://redirect-to-page/
> [WS-Client][handleHeader] RX: Accept-Ranges: none
> [WS-Client][handleHeader] Header read fin.
> [WS-Client][handleHeader] Client settings:
> [WS-Client][handleHeader]  - cURL: /ws
> [WS-Client][handleHeader]  - cKey: 5io3clEUBLTLHdpZugXt1w==
> [WS-Client][handleHeader] Server header:
> [WS-Client][handleHeader]  - cCode: 302
> [WS-Client][handleHeader]  - cIsUpgrade: 0
> [WS-Client][handleHeader]  - cIsWebsocket: 0
> [WS-Client][handleHeader]  - cAccept: 
> [WS-Client][handleHeader]  - cProtocol: 
> [WS-Client][handleHeader]  - cExtensions: 
> [WS-Client][handleHeader]  - cVersion: 0
> [WS-Client][handleHeader]  - cSessionId: 
> [WS-Client][handleHeader] no Websocket connection close.
> [WS-Client] client disconnected.
> [WSc] get text: <null>
> [WSc] Disconnected!
> 
> [WS-Server][0] Disconnect client

On the server side there's a redirection to http://redirect-to-page/ implemented, that triggers if the page wasn't found.

In comparision to the log of a working connection, following header lines are missing/different:

> [WS-Client][sendHeader] handshake GET /ws HTTP/1.1
> Connection: Upgrade
> Upgrade: websocket
> Sec-WebSocket-Version: 13
> Sec-WebSocket-Key: Auo5ULosePloWjJAOL1c8w==
> Sec-WebSocket-Protocol: arduino

What does the extension '&transport=polling ' in the broken header means ?
> [WS-Client][sendHeader] handshake GET /ws&transport=polling HTTP/1.1 

Thanks in advance and best regards,
Stephan

**Comment by Links2004** [comment]
can you check if you have used ```begin``` and not ```beginSocketIO``` ?
the ```&transport=polling``` is needed for socket.io to get the needed cookies.

**Comment by MoegerleStephan** [comment]
Ok thanks! 
I've found the problem.. you forgot to initialize the flag "isSocketIO".
Please add following init in "WebSocketsClient.cpp" line 79:
`    _client.isSocketIO = false;`

Thanks and best regards,
Stephan
