### ISSUE TITLE
WebSocketClient on ESP can't connect : ERR -8

### ISSUE THREAD

**Issue by Maxtoq** [Links2004/arduinoWebSockets#165]
Hi,

I'm trying to create a Websocket between my computer (index.js server) and an ESP8266 D1 Mini (WebSocketClient.ino). 
Here's what I changed in the codes : 
In WebSocketClient.ino : 
`#define USE_SERIAL Serial1`
to 
`#define USE_SERIAL Serial`

`WiFiMulti.addAP("SSID", "passpasspass");`
to
`WiFiMulti.addAP("Internet", "Acc3ssGr@nted");` (my Wifi)

put my IP address
`webSocket.begin("172.23.6.58", 81);`

In index.js : 
`var connection = request.accept('arduino', request.origin);`
to
`var connection = request.accept('', request.origin);`

Here's what I get in the Arduino monitor : 

> scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 137
cnt 
connected with Internet, channel 11
dhcp client start...
ip:172.23.6.64,mask:255.255.248.0,gw:172.23.0.1
[SETUP] BOOT WAIT 3...
[SETUP] BOOT WAIT 2...
[SETUP] BOOT WAIT 1...
pm open,type:2 0
[WSc] Disconnected!
[WSc] Disconnected!
[WSc] Disconnected!
[WSc] Disconnected!
[WSc] Disconnected!
[WSc] Disconnected!
[WSc] Disconnected!
[WSc] Disconnected!
[WSc] Disconnected!
[WSc] Disconnected!
[WSc] Disconnected!
[WSc] Disconnected!
[WSc] Disconnected!
[WSc] Disconnected!
[WSc] Disconnected!
...

The ESP can't connect to the server (I tested it with "Simple Websocket Client" on Chrome and it worked). I don't have any request in node.js. 
Do I have to change/add anything in the code(s) ?
Maybe in : 
`var connection = request.accept('', request.origin);` 
??? 

Thx for your help

Edit : The WebSocketClient.ino is working on my ESP with the link "echo.websocket.org":
`webSocket.begin("echo.websocket.org", 80);`
But still not on my server, so I assume the issue is in the arguments of : 
`webSocket.begin("172.23.6.58", 81);`
Please help

**Comment by Links2004** [comment]
ypu can try.
```cpp
webSocket.begin("echo.websocket.org", 80, "/", "");
```
if this not help please enable the debug output and post the results here.
1. Set debug port in IDE Menu
2. enable debug for Websockets (https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L30)

**Comment by Maxtoq** [comment]
With the debugger I have : 

> [SETUP] BOOT WAIT 4...
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 182
cnt 
connected with Internet, channel 11
dhcp client start...
wifi evt: 0
[SETUP] BOOT WAIT 3...
[SETUP] BOOT WAIT 2...
ip:172.23.6.64,mask:255.255.248.0,gw:172.23.0.1
wifi evt: 3
[SETUP] BOOT WAIT 1...
[WIFI][APlistAdd] add SSID: Internet
[hostByName] Host: 172.23.6.58 is a IP!
pm open,type:2 0
:err -8
[WSc] Disconnected!
[hostByName] Host: 172.23.6.58 is a IP!
:err -8
[WSc] Disconnected!
[hostByName] Host: 172.23.6.58 is a IP!
:err -8
[WSc] Disconnected!
[hostByName] Host: 172.23.6.58 is a IP!
:err -8
...

So what is "err -8" ?

Thx for helping !

**Comment by Links2004** [comment]
looks like a network problem.

```cpp
#define ERR_ABRT       -8    /* Connection aborted.      */
```
https://github.com/esp8266/Arduino/blob/4897e0006b5b0123a2fa31f67b14a3fff65ce561/tools/sdk/lwip/include/lwip/err.h#L63

**Comment by Maxtoq** [comment]
Ok thanks ! I'm going to check this. 
Still if anyone have any idea how to solve this problem, it'll be helpfull !

Thx for helping

**Comment by Maxtoq** [comment]
Also, I think it might be a problem with the Wifi connection. So if anyone knows the meaning of : 

> wifi evt: 3

in the debug output, it could help me !

**Comment by Links2004** [comment]
github can search in code ;)
https://github.com/esp8266/Arduino/blob/4897e0006b5b0123a2fa31f67b14a3fff65ce561/libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp#L205
https://github.com/esp8266/Arduino/blob/4897e0006b5b0123a2fa31f67b14a3fff65ce561/tools/sdk/include/user_interface.h#L230

3 = STATION_NO_AP_FOUND

**Comment by Maxtoq** [comment]
Ok Thanks ! (also for the tip ;) )

After testing at home  (instead of work), turned out it is the Wifi network which is causing a problem. It must be too complicated for the ESP to connect to a websocket with this wifi. So the problem is solved, but I can't connect :'( 

Thx for helping !
