### ISSUE TITLE
Ignore invalid certificate

### ISSUE THREAD

**Issue by markusschweitzer** [Links2004/arduinoWebSockets#166]
Hi, 
do you know if its possible to temporarly ignore an invalid certificate when starting a wss connection with beginSSL(..)?

Best regards,
Markus

**Comment by Links2004** [comment]
the cert check is is here:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.cpp#L619
you can add a flag to jump over the code.

**Comment by markusschweitzer** [comment]
Thanks
