### ISSUE TITLE
Cannot connect to wss

### ISSUE THREAD

**Issue by chessweb01** [Links2004/arduinoWebSockets#172]
I tried to change a working ws connection between NodeMCU and my server to wss. This is what I get:

[WS-Client] connection to kreidestaub.de:8080 Faild
[WS-Client] client disconnected.
[WSc] Disconnected!
[WS-Client] connect wss...
[WS-Client] connection to kreidestaub.de:8080 Faild
[WS-Client] client disconnected.
[WSc] Disconnected!
[WS-Client] connect wss...
[WS-Client] connection to kreidestaub.de:8080 Faild
[WS-Client] client disconnected.
[WSc] Disconnected!
[WS-Client] connect wss...
[WS-Client] connection to kreidestaub.de:8080 Faild
[WS-Client] client disconnected.
[WSc] Disconnected!
[WS-Client] connect wss...
[WS-Client] connection to kreidestaub.de:8080 Faild
[WS-Client] client disconnected.
[WSc] Disconnected!
[WS-Client] connect wss...
ssl->need_bytes=20527 violates spec
[WS-Client] connection to kreidestaub.de:8080 Faild
[WS-Client] client disconnected.
[WSc] Disconnected!
[WS-Client] connect wss...

The problem is not with the server or the certificate, as browser wss connections work just fine.

**Comment by Links2004** [comment]
are you sure the port is correct?
```
nc: connect to kreidestaub.de port 8080 (tcp) failed: Connection refused
```
you can enable debug for WS and or SSL, by this we sure get a hint what is going wrong.

for debug to work you need to enable the debug options of the ESP to,
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md#usage
simple set the Serial port you want to user and activate debug here:
https://github.com/Links2004/arduinoWebSockets/blob/7810d0d0b3cf07012bd6c67735713bbcd0af6485/src/WebSockets.h#L35

**Comment by chessweb01** [comment]
No, server and port are OK because it works with my NodeMCU client and ws as well as with a browser client and ws/wss. Only NodeMCU and wss is not working. When you tried to contact the server with netcat it just wasn't running.

Does the error message "ssl->need_bytes=20527 violates spec" (see above) provide any clues? It can't be the size of the key and cert files, both are about 1K in size.

**Comment by Links2004** [comment]
the debug stuff are only defines, if you can set compiler options / defines you can enable it.
I do the same in eclipse ;) 
```
-DDEBUG_ESP_PORT=Serial -DDEBUG_ESP_SSL
```
some docu from the time when I have implemented it for the Arduino IDE.
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md

you are sure your server can handle ssl?
currently your server not speak any SSL dialect. 
```
# ./testssl.sh https://kreidestaub.de:8080
 Start 2017-02-23 22:55:15    -->> 5.35.243.61:8080 (kreidestaub.de) <<--

 rDNS (5.35.243.61):     mail.kreidestaub.de.

 5.35.243.61:8080 doesn't seem to be a TLS/SSL enabled server
 Note that the results might look ok but they are nonsense. Proceed ? 

 Testing protocols (via sockets except TLS 1.2, SPDY+HTTP2) 

 SSLv2               not offered (OK)
 SSLv3               not offered (OK)
 TLS 1               not offered
 TLS 1.1             not offered
 TLS 1.2             not offered
```

**Comment by chessweb01** [comment]
I fixed it. You were right, it was the server after all.
