### ISSUE TITLE
[Question] Passing query Params in host disrupts connection

### ISSUE THREAD

**Issue by quantumlicht** [Links2004/arduinoWebSockets#174]
Hello, when I try to pass in query params,
such as `myhost.com?clientId=mobile` It seems to disrupt the connection. Is that expected? As soon as I remove the query params, the connection happens without problems.

What's the correct way of passing query params?

**Comment by quantumlicht** [comment]
I think I got my answer by stumbling on https://github.com/Links2004/arduinoWebSockets/issues/131 by chance

I should do the following `webSocket.begin(WS_HOST, PORT, '/?clientId=mobile');` right?

I think it would be a nice addition to document the main method's signature in the README. I can contribute if you need help

**Comment by Links2004** [comment]
yes, you are right.
Pull request are always welcome.

**Comment by quantumlicht** [comment]
There you go: https://github.com/Links2004/arduinoWebSockets/pull/175
