### ISSUE TITLE
Using wired connection via ENC28J60

### ISSUE THREAD

**Issue by alxferraz** [Links2004/arduinoWebSockets#177]
I'm trying to implement a wired ethernet connection using nodemcu and ENC28J60.
I tried the example WebSocketClientAVR.ino with no success then I noticed i could change the connection method by

`#define WEBSOCKETS_NETWORK_TYPE NETWORK_ENC28J60`

but it runs into a compilation error

```
In file included from /Users/andreferraz/Dropbox/projetos/Arduino/libraries/WebSockets/src/WebSocketsClient.h:28:0,
                 from /var/folders/3n/7q9hvh8x79x5c1vtwj1w4b5h0000gn/T/arduino_modified_sketch_303209/WebSocketClientAVR.ino:14:
/Users/andreferraz/Dropbox/projetos/Arduino/libraries/WebSockets/src/WebSockets.h:224:17: error: 'function' in namespace 'std' does not name a type
         typedef std::function<void(WSclient_t * client, bool ok)> WSreadWaitCb;

                 ^
In file included from /Users/andreferraz/Dropbox/projetos/Arduino/libraries/WebSockets/src/WebSocketsClient.h:28:0,
                 from /var/folders/3n/7q9hvh8x79x5c1vtwj1w4b5h0000gn/T/arduino_modified_sketch_303209/WebSocketClientAVR.ino:14:
/Users/andreferraz/Dropbox/projetos/Arduino/libraries/WebSockets/src/WebSockets.h:246:66: error: 'WSreadWaitCb' has not been declared
         bool readCb(WSclient_t * client, uint8_t *out, size_t n, WSreadWaitCb cb);

                                                                  ^
In file included from /var/folders/3n/7q9hvh8x79x5c1vtwj1w4b5h0000gn/T/arduino_modified_sketch_303209/WebSocketClientAVR.ino:14:0:
/Users/andreferraz/Dropbox/projetos/Arduino/libraries/WebSockets/src/WebSocketsClient.h:35:17: error: 'function' in namespace 'std' does not name a type
         typedef std::function<void (WStype_t type, uint8_t * payload, size_t length)> WebSocketClientEvent;

                 ^
In file included from /var/folders/3n/7q9hvh8x79x5c1vtwj1w4b5h0000gn/T/arduino_modified_sketch_303209/WebSocketClientAVR.ino:14:0:
/Users/andreferraz/Dropbox/projetos/Arduino/libraries/WebSockets/src/WebSocketsClient.h:60:22: error: 'WebSocketClientEvent' has not been declared
         void onEvent(WebSocketClientEvent cbEvent);

                      ^
/Users/andreferraz/Dropbox/projetos/Arduino/libraries/WebSockets/src/WebSocketsClient.h:88:9: error: 'WebSocketClientEvent' does not name a type
         WebSocketClientEvent _cbEvent;

         ^
/Users/andreferraz/Dropbox/projetos/Arduino/libraries/WebSockets/src/WebSocketsClient.h: In member function 'virtual void WebSocketsClient::runCbEvent(WStype_t, uint8_t*, size_t)':
/Users/andreferraz/Dropbox/projetos/Arduino/libraries/WebSockets/src/WebSocketsClient.h:116:16: error: '_cbEvent' was not declared in this scope
             if(_cbEvent) {

                ^
/var/folders/3n/7q9hvh8x79x5c1vtwj1w4b5h0000gn/T/arduino_modified_sketch_303209/WebSocketClientAVR.ino: In function 'void webSocketEvent(WStype_t, uint8_t*, size_t)':
/var/folders/3n/7q9hvh8x79x5c1vtwj1w4b5h0000gn/T/arduino_modified_sketch_303209/WebSocketClientAVR.ino:32:11: warning: enumeration value 'WStype_ERROR' not handled in switch [-Wswitch]
     switch(type) {
           ^
/var/folders/3n/7q9hvh8x79x5c1vtwj1w4b5h0000gn/T/arduino_modified_sketch_303209/WebSocketClientAVR.ino: In function 'void setup()':
WebSocketClientAVR:88: error: invalid conversion from 'void (*)(WStype_t, uint8_t*, size_t) {aka void (*)(WStype_t, unsigned char*, unsigned int)}' to 'int' [-fpermissive]
     webSocket.onEvent(webSocketEvent);
                                     ^
In file included from /var/folders/3n/7q9hvh8x79x5c1vtwj1w4b5h0000gn/T/arduino_modified_sketch_303209/WebSocketClientAVR.ino:14:0:
/Users/andreferraz/Dropbox/projetos/Arduino/libraries/WebSockets/src/WebSocketsClient.h:60:14: error:   initializing argument 1 of 'void WebSocketsClient::onEvent(int)' [-fpermissive]
         void onEvent(WebSocketClientEvent cbEvent);
```

Does anybody know what could be done?

**Comment by Links2004** [comment]
the AVR example will not work in the ESP ;)
you need the normal example 
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/WebSocketClient/WebSocketClient.ino
and the version 2.x.x of the library.

and yes changing the define of `WEBSOCKETS_NETWORK_TYPE` is the way to go for switching the Network interface.
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L78

last time I test ESP with ENC28J60 it worked, but there are many changes since then.

**Comment by alxferraz** [comment]
Hey @Links2004 thanks for your reply!

i just tried the socketIO example with some changes:

`/*
 * WebSocketClientSocketIO.ino
 *
 *  Created on: 06.06.2016
 *
 */

#define WEBSOCKETS_NETWORK_TYPE NETWORK_ENC28J60

#include <Arduino.h>

#include <WebSocketsClient.h>

#include <Hash.h>

#include <UIPEthernet.h>


#define USE_SERIAL Serial

#define MESSAGE_INTERVAL 30000
#define HEARTBEAT_INTERVAL 25000

uint64_t messageTimestamp = 0;
uint64_t heartbeatTimestamp = 0;
bool isConnected = false;

WebSocketsClient webSocket;

// Enter a MAC address for your controller below.
// Newer Ethernet shields have a MAC address printed on a sticker on the shield
byte mac[] = { 0x5E, 0xA9, 0xBE, 0xE7, 0xFE, 0xED };

// Set the static IP address to use if the DHCP fails to assign
IPAddress ip(192, 168, 1, 177);

void webSocketEvent(WStype_t type, uint8_t * payload, size_t lenght) {


    switch(type) {
        case WStype_DISCONNECTED:
            USE_SERIAL.printf("[WSc] Disconnected!\n");
            isConnected = false;
            break;
        case WStype_CONNECTED:
            {
                USE_SERIAL.printf("[WSc] Connected to url: %s\n",  payload);
                isConnected = true;

			    // send message to server when Connected
                // socket.io upgrade confirmation message (required)
				webSocket.sendTXT("5");
            }
            break;
        case WStype_TEXT:
            USE_SERIAL.printf("[WSc] get text: %s\n", payload);

			// send message to server
			// webSocket.sendTXT("message here");
            break;
        case WStype_BIN:
            USE_SERIAL.printf("[WSc] get binary lenght: %u\n", lenght);
            hexdump(payload, lenght);

            // send data to server
            // webSocket.sendBIN(payload, lenght);
            break;
    }

}

void setup() {
    // USE_SERIAL.begin(921600);
    USE_SERIAL.begin(115200);

    //Serial.setDebugOutput(true);
    USE_SERIAL.setDebugOutput(true);

    USE_SERIAL.println();
    USE_SERIAL.println();
    USE_SERIAL.println();

      for(uint8_t t = 4; t > 0; t--) {
          USE_SERIAL.printf("[SETUP] BOOT WAIT %d...\n", t);
          USE_SERIAL.flush();
          delay(1000);
      }


      if (Ethernet.begin(mac) == 0) {
      Serial.println("Failed to configure Ethernet using DHCP");
      // no point in carrying on, so do nothing forevermore:
      // try to congifure using IP address instead of DHCP:
      Ethernet.begin(mac, ip);
    }else{
      Serial.print("localIP: ");
      Serial.println(Ethernet.localIP());
      Serial.print("subnetMask: ");
      Serial.println(Ethernet.subnetMask());
      Serial.print("gatewayIP: ");
      Serial.println(Ethernet.gatewayIP());
      Serial.print("dnsServerIP: ");
      Serial.println(Ethernet.dnsServerIP());
      
      }

    
    webSocket.beginSocketIO("app.iportao.com", 80);
    //webSocket.setAuthorization("user", "Password"); // HTTP Basic Authorization
    webSocket.onEvent(webSocketEvent);

}

void loop() {
    webSocket.loop();

    if(isConnected) {

        uint64_t now = millis();

        if(now - messageTimestamp > MESSAGE_INTERVAL) {
            messageTimestamp = now;
            // example socket.io message with type "messageType" and JSON payload
            webSocket.sendTXT("42[\"messageType\",{\"greeting\":\"hello\"}]");
        }
        if((now - heartbeatTimestamp) > HEARTBEAT_INTERVAL) {
            heartbeatTimestamp = now;
            // socket.io heartbeat message
            webSocket.sendTXT("2");
        }
    }
}`

I run into the same compilation error.
`invalid conversion from 'void (*)(WStype_t, uint8_t*, size_t) {aka void (*)(WStype_t, unsigned char*, unsigned int)}' to 'int' [-fpermissive]`
Any Ideias?

**Comment by Links2004** [comment]
add 
```cpp
#include <functional>
```
in the WebSockets.h will fix it.

**Comment by alxferraz** [comment]
@Links2004 Thank You very much! It worked like a charm. I'll try to implement a way to fallback on wifi in case ethernet fails on startup.

**Comment by Links2004** [comment]
ok fail over is harder one, since the decision currently is done on compilation time.
I think, best way to do it is to write a wrapper class with the same interface then all arduino Network classes, and then create a new define for it.

more or less:
```cpp
#define NETWORK_ENC28J60_FAILOVER_ESP8266        (100)

.....

#define WEBSOCKETS_NETWORK_TYPE NETWORK_ENC28J60_FAILOVER_ESP8266

.....

#elif (WEBSOCKETS_NETWORK_TYPE == NETWORK_ENC28J60_FAILOVER_ESP8266)

#include <yourFailOverNetworkClass.h>
#define WEBSOCKETS_NETWORK_CLASS FailOverClient
#define WEBSOCKETS_NETWORK_SERVER_CLASS FailOverServer
#else

```

the class itself then needs to redirect the ```write```, `read`, `connect`, ... to ENC28J60 or ESP WiFi.

**Comment by g-arais** [comment]
Hi, I'm trying to connect the nodeMCU to the ENc but I'm not getting it to work. It does not connect. 
Can you show me the connections you made between the modules? 
I'm using this: https://github.com/UIPEthernet/UIPEthernet/blob/master/hardware/NodeMCU_enc28j60_wiring.PNG
Thanks

**Comment by alxferraz** [comment]
That wiring is the one i used. Have you changed the library and set the connection method to enc28j60?

**Comment by g-arais** [comment]
Thanks. It's working. It was my mistake.

**Comment by Loucotolo** [comment]
Hi, I'm trying to use the websocketServer example with a esp8266 and an enc28j60, but I'm not able to connect to it, the code I have and the following:

/*
   WebSocketServer.ino
*/
#define WEBSOCKETS_NETWORK_TYPE NETWORK_ENC28J60

#include <Arduino.h>

#include <WebSocketsServer.h>
#include <Hash.h>
#include <UIPEthernet.h>


// Enter a MAC address for your controller below.
// Newer Ethernet shields have a MAC address printed on a sticker on the shield
byte mac[] = { 0x5E, 0xA9, 0xBE, 0xE7, 0xFE, 0xED };

// Set the static IP address to use if the DHCP fails to assign
IPAddress ip(192, 168, 1, 177);

WebSocketsServer webSocket = WebSocketsServer(81);

#define USE_SERIAL Serial1

void webSocketEvent(uint8_t num, WStype_t type, uint8_t * payload, size_t length) {

  switch (type) {
    case WStype_DISCONNECTED:
      USE_SERIAL.printf("[%u] Disconnected!\n", num);
      break;
    case WStype_CONNECTED:
      {
      //  IPAddress ip = webSocket.remoteIP(num);
      //  USE_SERIAL.printf("[%u] Connected from %d.%d.%d.%d url: %s\n", num, ip[0], ip[1], ip[2], ip[3], payload);

        // send message to client
        webSocket.sendTXT(num, "Connected");
      }
      break;
    case WStype_TEXT:
      USE_SERIAL.printf("[%u] get Text: %s\n", num, payload);

      // send message to client
      // webSocket.sendTXT(num, "message here");

      // send data to all connected clients
      // webSocket.broadcastTXT("message here");
      break;
    case WStype_BIN:
      USE_SERIAL.printf("[%u] get binary length: %u\n", num, length);
      hexdump(payload, length);

      // send message to client
      // webSocket.sendBIN(num, payload, length);
      break;
  }

}

void setup() {
  // USE_SERIAL.begin(921600);
  USE_SERIAL.begin(115200);

  //Serial.setDebugOutput(true);
  USE_SERIAL.setDebugOutput(true);

  USE_SERIAL.println();
  USE_SERIAL.println();
  USE_SERIAL.println();

  for (uint8_t t = 4; t > 0; t--) {
    USE_SERIAL.printf("[SETUP] BOOT WAIT %d...\n", t);
    USE_SERIAL.flush();
    delay(1000);
  }
  
  if (Ethernet.begin(mac) == 0) {
    Serial.println("Failed to configure Ethernet using DHCP");
    // no point in carrying on, so do nothing forevermore:
    // try to congifure using IP address instead of DHCP:
    Ethernet.begin(mac, ip);
  } else {
    Serial.print("localIP: ");
    Serial.println(Ethernet.localIP());
    Serial.print("subnetMask: ");
    Serial.println(Ethernet.subnetMask());
    Serial.print("gatewayIP: ");
    Serial.println(Ethernet.gatewayIP());
    Serial.print("dnsServerIP: ");
    Serial.println(Ethernet.dnsServerIP());

  }

  webSocket.begin();
  webSocket.onEvent(webSocketEvent);
}

void loop() {
  webSocket.loop();
}

OUTPUT COMPORT:

[SETUP] BOOT WAIT 4...
[SETUP] BOOT WAIT 3...
[SETUP] BOOT WAIT 2...
[SETUP] BOOT WAIT 1...

localIP: 192.168.0.185
subnetMask: 255.255.255.0
gatewayIP: 192.168.0.1
dnsServerIP: 62.28.116.41

And I'm trying to call me at:
192.168.0.185:81
