### ISSUE TITLE
Finding connected IP address

### ISSUE THREAD

**Issue by DarklyLabs** [Links2004/arduinoWebSockets#179]
We are running arduinoWebSockets on an ESP8266 12F to allow our machine to communicate via WiFi.
Once our device is connected to the network, is it possible to determine the IP address it has been assigned via arduinoWebsockets?

We are looking for a simpler way than getting into the router backend or using another piece of software to scan the IP addresses on the network and then sift through them.

Any ideas welcomed.

**Comment by Links2004** [comment]
UPnP and/or mDNS can handle this.

a mDNS example can be found here:
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/WebSocketServer_LEDcontrol/WebSocketServer_LEDcontrol.ino#L109

**Comment by DarklyLabs** [comment]
Thank you. 
Can you recommend and developer who can help us implement this feature?

**Comment by Links2004** [comment]
mDNS is part of the ESP8266 libraries 
https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266mDNS
same goes for UPnP / SSDP
https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266SSDP

Windows supports native UPnP / SSDP  
for MAC you are better with mDNS since its native supported.
Linux can handle both well.

**Comment by DarklyLabs** [comment]
Hi Markus,
Thank you for the quick response.
My lack of programming knowledge is very evident here, so apologies for the following questions.
How do you see the process of finding the connected IP address happening?
Is it a command that would be sent to the websocket server and a response received?

**Comment by Links2004** [comment]
websockets will not help to find your device.

when you use mDNS you only need to type the configured name in the browser thats it.
```
mDNS.begin("esp8266");
```
will result in http://esp8266/ thats it.

UPnP work a little different,
you will get a New Icon in the Windows Network view, when you click it the browser will open.

Notes: 
mDNS is also known under zeroconf or bonjour.
you can install Apple bonjour on Windows.
the Arduino IDE uses mDNS to finde the ESP when you use OTA.

after you have a Website served by the ESP you can use websockets to exchange data with the ESP.

**Comment by DarklyLabs** [comment]
Thank you.
Makes sense now.

**Comment by DarklyLabs** [comment]
So we can potentially assign a unique name to each of our devices by using the MAC address. That way multiple devices on the same network can be identified and controlled uniquely.

**Comment by Links2004** [comment]
correct.
