### ISSUE TITLE
Example with both server and client with ESP8266

### ISSUE THREAD

**Issue by nicoverduin** [Links2004/arduinoWebSockets#18]
I am trying to create on 2 nodeMCU's a socket connection.
On one I install the server example on the other the client example.
How do I send a message from my client to the server. The IP's are correct and I added in the loop a simple sendTXT but all I get is messages that the buffer is overflowing. Is there an example containing my question? If I use the browser and change it to the server IP the browser test works great,

**Comment by Links2004** [comment]
sending in every loop is too much for the ESP.
the Network stack can not handle so much data.

```cpp
#include <Arduino.h>

#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>

#include <WebSocketsClient.h>

#include <Hash.h>

ESP8266WiFiMulti WiFiMulti;
WebSocketsClient webSocket;

#define USE_SERIAL Serial

void webSocketEvent(WStype_t type, uint8_t * payload, size_t lenght) {

    switch(type) {
        case WStype_DISCONNECTED:
            USE_SERIAL.printf("[WSc] Disconnected!\n");
            break;
        case WStype_CONNECTED:
            {
                USE_SERIAL.printf("[WSc] Connected to url: %s\n",  payload);
            }
            break;
        case WStype_TEXT:
            USE_SERIAL.printf("[WSc] get text: %s\n", payload);
            break;
        case WStype_BIN:
            USE_SERIAL.printf("[WSc] get binary lenght: %u\n", lenght);
            hexdump(payload, lenght);
            break;
    }
}

void setup() {
    USE_SERIAL.begin(115200);
    USE_SERIAL.setDebugOutput(true);

    USE_SERIAL.println();

     for(uint8_t t = 4; t > 0; t--) {
          USE_SERIAL.printf("[SETUP] BOOT WAIT %d...\n", t);
          USE_SERIAL.flush();
          delay(1000);
      }

    WiFiMulti.addAP("SSID", "passpasspass");

    while(WiFiMulti.run() != WL_CONNECTED) {
        delay(100);
    }

    webSocket.begin("192.168.0.123", 81);
    webSocket.onEvent(webSocketEvent);
}

void loop() {
    static unsigned long last = 0;
    webSocket.loop();
    if(abs(millis() - last) > 1000) {
        webSocket.sendTXT(String(millis()));
        last = millis();
    }
}
```
shut work fine (sends message every second).

**Comment by nicoverduin** [comment]
I do not know what I am doing wrong. My server code is this:
[code]
/*
 * WebSocketServer.ino
 *
 *  Created on: 22.05.2015
 *
 */

#include <Arduino.h>

#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>
#include <WebSocketsServer.h>
#include <Hash.h>

ESP8266WiFiMulti WiFiMulti;

WebSocketsServer webSocket = WebSocketsServer(81);

#define USE_SERIAL Serial

void webSocketEvent(uint8_t num, WStype_t type, uint8_t * payload, size_t length) {

    switch(type) {
        case WStype_DISCONNECTED:
            USE_SERIAL.printf("[%u] Disconnected!\n", num);
            break;
        case WStype_CONNECTED:
            {
                IPAddress ip = webSocket.remoteIP(num);
                USE_SERIAL.printf("[%u] Connected from %d.%d.%d.%d url: %s\n", num, ip[0], ip[1], ip[2], ip[3], payload);
            }
            break;
        case WStype_TEXT:
            USE_SERIAL.printf("[%u] get Text: %s\n", num, payload);

            // echo data back to browser
            webSocket.sendTXT(num, payload, length);
            // send data to all connected clients
            webSocket.broadcastTXT(payload, length);
            break;
        case WStype_BIN:
            USE_SERIAL.printf("[%u] get binary length: %u\n", num, length);
            hexdump(payload, length);
            // echo data back to browser
            webSocket.sendBIN(num, payload, length);
            break;
        case WStype_ERROR:
        	break;

        default:
        	break;
    }

}

void setup() {
    // USE_SERIAL.begin(921600);
    USE_SERIAL.begin(115200);

    Serial.setDebugOutput(true);
    USE_SERIAL.setDebugOutput(true);

    USE_SERIAL.println();
    USE_SERIAL.println();
    USE_SERIAL.println();

    for(uint8_t t = 4; t > 0; t--) {
        USE_SERIAL.printf("[SETUP] BOOT WAIT %d...\n", t);
        USE_SERIAL.flush();
        delay(1000);
    }

    WiFiMulti.addAP(SSID, PASSWORD);

    while(WiFiMulti.run() != WL_CONNECTED) {
        delay(100);
    }

    webSocket.begin();
    webSocket.onEvent(webSocketEvent);
    USE_SERIAL.printf("Server Started\n");
}

void loop() {
    webSocket.loop();
}
[/code]

And the server connects fine see:
[code]
[SETUP] BOOT WAIT 4...
scandone
[SETUP] BOOT WAIT 3...
add 0
aid 6
pm open phy_2,type:2 0 0
cnt 

connected with Verelec, channel 2
dhcp client start...
ip:10.0.0.63,mask:255.255.255.0,gw:10.0.0.1
[SETUP] BOOT WAIT 2...
[SETUP] BOOT WAIT 1...
Server Started
[/code]

The client:
[code]
/*
 * WebSocketClient.ino
 *
 *  Created on: 24.05.2015
 *
 */

#include <Arduino.h>

#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>
#include <WebSocketsClient.h>
#include <Hash.h>

ESP8266WiFiMulti WiFiMulti;
WebSocketsClient webSocket;

#define USE_SERIAL Serial

void webSocketEvent(WStype_t type, uint8_t * payload, size_t lenght) {


    switch(type) {
        case WStype_DISCONNECTED:
            USE_SERIAL.printf("[WSc] Disconnected!\n");
            break;
        case WStype_CONNECTED:
            {
                USE_SERIAL.printf("[WSc] Connected to url: %s\n",  payload);
            }
            break;
        case WStype_TEXT:
           USE_SERIAL.printf("[WSc] get text: %s\n", payload);

            // send data to back to Server
            webSocket.sendTXT(payload, lenght);
            break;
        case WStype_BIN:
            USE_SERIAL.printf("[WSc] get binary lenght: %u\n", lenght);
            hexdump(payload, lenght);

            // echo data back to Server
            webSocket.sendBIN(payload, lenght);
            break;

        case WStype_ERROR:
        	USE_SERIAL.printf("We received an error \n");
        	break;

        default:
        	break;
    }

}


void setup() {
    // USE_SERIAL.begin(921600);
    USE_SERIAL.begin(115200);

    Serial.setDebugOutput(true);
    USE_SERIAL.setDebugOutput(true);

    USE_SERIAL.println();
    USE_SERIAL.println();
    USE_SERIAL.println();

      for(uint8_t t = 4; t > 0; t--) {
          USE_SERIAL.printf("[SETUP] BOOT WAIT %d...\n", t);
          USE_SERIAL.flush();
          delay(1000);
      }

    WiFiMulti.addAP("Verelec", "z569n300");

    //WiFi.disconnect();
    while(WiFiMulti.run() != WL_CONNECTED) {
        delay(100);
    }
    webSocket.begin("10.0.0.63", 81);
    webSocket.onEvent(webSocketEvent);
    USE_SERIAL.println("Client started\n");


}



void loop() {
    static unsigned long last = 0;
    webSocket.loop();
    if(abs(millis() - last) > 1000) {
        webSocket.sendTXT(String(millis()));
        last = millis();
        USE_SERIAL.println("Send millis text");
    }


}
[/code]

And that connects fine as well:

But no response. Am I doing something wrong here?

**Comment by Links2004** [comment]
I miss the "[%u] Connected from %d.%d.%d.%d url: %s\n" serial output on the server side.
it looks like the client never connects to the server.

can you please enable the websocket debug here:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L40
and then post the serial output from server and client.

**Comment by nicoverduin** [comment]
Servers
```
[SETUP] BOOT WAIT 4...
scandone
[SETUP] BOOT WAIT 3...
add 0
aid 7
pm open phy_2,type:2 0 0
cnt 

connected with Verelec, channel 2
dhcp client start...
[SETUP] BOOT WAIT 2...
ip:10.0.0.63,mask:255.255.255.0,gw:10.0.0.1
[SETUP] BOOT WAIT 1...
Server Started

[SETUP] BOOT WAIT 4...
scandone
[SETUP] BOOT WAIT 3...
add 0
aid 6
pm open phy_2,type:2 0 0
cnt 

connected with Verelec, channel 2
dhcp client start...
[SETUP] BOOT WAIT 2...
[SETUP] BOOT WAIT 1...
rm 0
pm close 7 0 0/3090512
f 0, scandone
f -240, scandone
reconnect
f 0, scandone
add 0
aid 6
pm open phy_2,type:2 0 0
cnt 

connected with Verelec, channel 2
dhcp client start...
ip:10.0.0.61,mask:255.255.255.0,gw:10.0.0.1
Client started
```
This is al I am getting

**Comment by nicoverduin** [comment]
reloaded the original files an now I am getting:
```
[WS-client]connection to 10.0.0.63:81 faild
```

**Comment by Links2004** [comment]
k have you enabled the "communication between devices" function in you wifi router?
the problem is clearly that the to ESP can not communicate with each other.

**Comment by nicoverduin** [comment]
Markus thansk for the suggestion... It was the router. Works like a charm now :)
