### ISSUE TITLE
Problems with Serial and arduinoWebSockets

### ISSUE THREAD

**Issue by caballero03** [Links2004/arduinoWebSockets#180]
We are attempting to use arduinoWebSockets in a serial-to-browser bridge. Basically a simple over-the-air serial terminal and control console. Everything serial works well until we use Websockets to send. When we use sendTXT(...) the hardware serial port misses incoming characters randomly due to some kind of interrupt suppression or some other interference. 

Do you know what could be causing this? Do you know of a work around? Is this type of thing even possible?

TIA

**Comment by Links2004** [comment]
yes its possible, with out seeing the code I can only guess the problem.
but most likely you try to send byte by byte over the web-socked, this generate overhead.
you need to buffer the Incoming data and send it in "blocks",
the TCP layer of is not designed to handle many small requests, windows for example sends a TCP ack only when a bigger amount of data is received or after 200ms what is a big pain when you send small or on byte at the time. 
The ESP blocks until it gets the ACK. 
the lost you see is most likely the RX buffer which is overflowing, during the wait for the ACK.

some code with intelligent buffering can be found her:
https://github.com/Links2004/arduinoWebSockets/issues/61#issuecomment-198231422

and you can use the async TCP lib for the ESP to improve the Performance more.
https://github.com/Links2004/arduinoWebSockets#esp-async-tcp

**Comment by caballero03** [comment]
Thank you for your fast response. I am sure this will help us out. I cannot explain how that page escaped all of my searching. :-|
