### ISSUE TITLE
webSocket.begin - how to set for localhost

### ISSUE THREAD

**Issue by jcmojj** [Links2004/arduinoWebSockets#181]
Hello Links,

I really liked your lib and I am trying to use it in my project. I started using the webSocketClient example. First I did a Java webSocket server that can perfectly communicate with the website. The example works and both server and browser can talk with each other. 
Than I run your example and I can't make it work and I keep receiving Disconnected. 
I received this from the Serial Monitor:

> connected with Familia Trunci 2.4G, channel 6
> dhcp client start...
> ip:192.168.0.100,mask:255.255.255.0,gw:192.168.0.1
> [SETUP] BOOT WAIT 3...
> [SETUP] BOOT WAIT 2...
> [SETUP] BOOT WAIT 1...
> pm open,type:2 0
> [WSc] Disconnected!
> [WSc] Disconnected!

I created the webserver at localhost:8080 and it address is http://localhost:8080/websockets/example. Example is the ServerEndPoint name and WebSocket is the name of the server.
I think the problem is that I can`t properly configure the begin method (**void WebSocketsClient::beginSocketIO(String host, uint16_t port, String url, String protocol)**). I don't know what exactly should I set as the parameters (host, port, url and protocol) since I didn't find any example using localhost.  My doubts are:
_1) should I use http:// or ws://  or nothing like that at the host
2) should I use localhost or my ip (ex. 192.168.0.102)
3) should I use the port at the host or not (ex. localhost:8080 or just localhost)
4) should I use the full host name at host or just localhost
5) what should I use at url ("/"or "/websockets"or "/websockets/example"_

If you could give just a simple example it would help a lot. I acess the websocket from the browser by the address: **http://localhost:8080/websocket/**
Probably it is not necessary, but I will put the Java Server File and the HTML file just to make it clear for you.

**Java WebServer**
```
package websocket;

import java.io.IOException;
import javax.annotation.Resource;
import javax.ejb.Stateless;
import javax.enterprise.concurrent.ManagedExecutorService;
import javax.enterprise.context.ApplicationScoped;
import javax.websocket.CloseReason;
import javax.websocket.OnClose;
import javax.websocket.OnMessage;
import javax.websocket.OnOpen;
import javax.websocket.Session;
import javax.websocket.server.ServerEndpoint;
import org.jboss.logging.Logger;

@ApplicationScoped
@ServerEndpoint("/example")
@Stateless
public class WSEndpoint {
	Logger log = Logger.getLogger(this.getClass());
	@Resource
	ManagedExecutorService mes;

	@OnMessage
	public String receiveMessage(String message, Session session) {
		log.info("Received : " + message + ", session:" + session.getId());
		return "Response from the server";
	}

	@OnOpen
	public void open(Session session) {
		log.info("Open session:" + session.getId());
		final Session s = session;
		mes.execute(new Runnable() {
			@Override
			public void run() {
				try {
					for (int i = 0; i < 3; i++) {
						Thread.sleep(10000);
						s.getBasicRemote().sendText("Message from server");
					}
				} catch (InterruptedException | IOException e) {
					e.printStackTrace();
				}
			}
		});
	}

	@OnClose
	public void close(Session session, CloseReason c) {
		log.info("Closing:" + session.getId());
	}
}
```

**HTML Code**
```
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>WebSocket Client</title>
 <script type="text/javascript">
	 var ws = new WebSocket("ws://localhost:8080/websocket/example");
	 ws.onopen = function()
	 {
		alert("Web Socket ws is connected!!");
	 };
	 ws.onmessage = function (evt)
	 {
		var msg = evt.data;
		alert("Message ws received:" +  msg);
	 };
	 ws.onclose = function()
	 {
		alert("Connection ws is closed...");
	 };
	 function sendMessage() 
	 {
		ws.send("Message to server ws from client");
	 }

  </script>
</head>
<body>
<a href="javascript:sendMessage()">Send message ws</a>
</body>
</html>
```

I also didn't understand why  I receive that debug code:  **pm open,type:2 0**
I think one simple example of the method will clear it up.
Thank you

**Comment by Links2004** [comment]
localhost will not work since it always point to 127.0.0.1 (your local machine where your code is running).
you need to use the IP of your network interface, make sure your server is bind to 0.0.0.0 or the network interface and not to localhost.

beginSocketIO is for a Socket.IO connection since your Javascript code shows a plain web socket you need to use ```begin```.

in your cases:
```cpp
webSocket.begin("<your IP here>", 8080, "/websocket/example");
```
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/WebSocketClient/WebSocketClient.ino#L79
