### ISSUE TITLE
403 permission denied when the field "Origin: file://" is included in header 

### ISSUE THREAD

**Issue by chessweb01** [Links2004/arduinoWebSockets#182]
When the field "Origin: file://" is included in the header (see WebSocketsClient.cpp:469), my WebSocket server responds with 403 permission denied. Removing the origin field from the header fixes the issue.

**Comment by Links2004** [comment]
the Origin is designed to detect from which side the websocket is coming.
most server Implementation require it, best way will be to allow to configure it.
