### ISSUE TITLE
Get completion event/status for Async TCP mode on the ESP

### ISSUE THREAD

**Issue by starlino** [Links2004/arduinoWebSockets#186]
When using Async TCP mode on the ESP, is there any way to check when the call to .sendBIN() for example is complete (since it returns right away).
I am getting this error in browser: 
WebSocket connection to 'ws://192.168.4.1/' failed: A server must not mask any frames that it sends to the client.
I am guessing this is due to calling  .sendBIN() too fast (before the previous one completed). If I increase the interval between calls I no longer get the error.
Shouldn't the library itself do some sanity checks as well to avoid any overwriting of the headers ... 
Thanks,
-sergiu

**Comment by Links2004** [comment]
normally the TCP stack will take care of this,
how big are the messages in each `sendBin` call?
I can think of two thinks that can help.
1. use the `headerToPayload` feature to ensure the header is in the same TCP packet then the data.
2. dont send more then one TCP packet big data (~1400) at one `sendBin` call.

may you need to combine both.

for `headerToPayload` you need to reserve `WEBSOCKETS_MAX_HEADER_SIZE` (14) byte at the beginning of your data ptr and set the parameter on the call to true.
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsServer.h#L77

if you can provide a debug log I may get a better clue what is going on.
for debug to work you need to enable the debug options of the ESP to,
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md#usage
simple set the Serial port you want to user.

**Comment by starlino** [comment]
Hey Markus, thanks for the ideas. I am actually already using headerToPayload with ping-pong scheme, where one buffer is being filled while the other is being transmitted.
But you still didn't answer my main question:
I have uncommented in WebSockets.h
#define WEBSOCKETS_NETWORK_TYPE NETWORK_ESP8266_ASYNC

**Now my calls to WebSocketServer.sendBIN() return right away (in about 400us or so ...), how do I know when the server finished sending the packet ?**

**Comment by starlino** [comment]
Below is the debug , log the error in browser is:
 **WebSocket connection to 'ws://192.168.4.1/' failed: Invalid frame header**

----------------------------------------------------
[WS-Server] Server Started.
add 1
aid 1
station: 34:23:87:1c:9b:47 join, AID = 1
[WS-Server][0] new client from 192.168.4.2
[WS-Server][0][handleHeader] RX: GET / HTTP/1.1
[WS-Server][0][handleHeader] RX: Host: 192.168.4.1
[WS-Server][0][handleHeader] RX: Connection: Upgrade
[WS-Server][0][handleHeader] RX: Pragma: no-cache
[WS-Server][0][handleHeader] RX: Cache-Control: no-cache
[WS-Server][0][handleHeader] RX: Upgrade: websocket
[WS-Server][0][handleHeader] RX: Origin: http://projects
[WS-Server][0][handleHeader] RX: Sec-WebSocket-Version: 13
[WS-Server][0][handleHeader] RX: User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
[WS-Server][0][handleHeader] RX: Accept-Encoding: gzip, deflate, sdch
[WS-Server][0][handleHeader] RX: Accept-Language: en-US,en;q=0.8
[WS-Server][0][handleHeader] RX: Sec-WebSocket-Key: 1H6MXUHliCy+vDwK6FUy0Q==
[WS-Server][0][handleHeader] RX: Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
[WS-Server][0][handleHeader] Header read fin.
[WS-Server][0][handleHeader]  - cURL: /
[WS-Server][0][handleHeader]  - cIsUpgrade: 1
[WS-Server][0][handleHeader]  - cIsWebsocket: 1
[WS-Server][0][handleHeader]  - cKey: 1H6MXUHliCy+vDwK6FUy0Q==
[WS-Server][0][handleHeader]  - cProtocol: 
[WS-Server][0][handleHeader]  - cExtensions: permessage-deflate; client_max_window_bits
[WS-Server][0][handleHeader]  - cVersion: 13
[WS-Server][0][handleHeader]  - base64Authorization: 
[WS-Server][0][handleHeader]  - cHttpHeadersValid: 1
[WS-Server][0][handleHeader]  - cMandatoryHeadersCount: 0
[WS-Server][0][handleHeader] Websocket connection incoming.
[WS-Server][0][handleHeader]  - sKey: up/bGiJ7TiL/0neL8vzqiMQBORs=
[WS][0][headerDone] Header Handling Done (1074792753us).
[WS][0][sendFrame] ------- send massage frame -------
[WS][0][sendFrame] fin: 1 opCode: 9 mask: 0 length: 0 headerToPayload: 0
[WS][0][sendFrame] sending Frame Done (4184us).
client_num[0] Connected from 192.168.4.2 url: /
[WS][0][handleWebsocketWaitFor] size: 2 cWsRXsize: 0
[readCb] n: 2 t: 67857
[WS][0][handleWebsocketWaitFor][readCb] size: 2 ok: 1
[WS][0][handleWebsocket] ------- read massage frame -------
[WS][0][handleWebsocket] fin: 1 rsv1: 0 rsv2: 0 rsv3 0  opCode: 1
[WS][0][handleWebsocket] mask: 1 payloadLen: 11
[WS][0][handleWebsocketWaitFor] size: 6 cWsRXsize: 2
[readCb] n: 4 t: 67870
[WS][0][handleWebsocketWaitFor][readCb] size: 6 ok: 1
[WS][0][handleWebsocket] ------- read massage frame -------
[WS][0][handleWebsocket] fin: 1 rsv1: 0 rsv2: 0 rsv3 0  opCode: 1
[WS][0][handleWebsocket] mask: 1 payloadLen: 11
[readCb] n: 11 t: 67881
[WS][0][handleWebsocket] text: batch:5:250
client_num[0] get Text: batch:5:250
batch_start batch_ticker_ms:5 batch_size:250 sample_bytes:31
who_am_i:113 113
[WS][0][handleWebsocketWaitFor] size: 2 cWsRXsize: 0
[readCb] n: 2 t: 67891
[WS][0][handleWebsocketWaitFor][readCb] size: 2 ok: 1
[WS][0][handleWebsocket] ------- read massage frame -------
[WS][0][handleWebsocket] fin: 1 rsv1: 0 rsv2: 0 rsv3 0  opCode: 10
[WS][0][handleWebsocket] mask: 1 payloadLen: 0
[WS][0][handleWebsocketWaitFor] size: 6 cWsRXsize: 2
[readCb] n: 4 t: 67905
[WS][0][handleWebsocketWaitFor][readCb] size: 6 ok: 1
[WS][0][handleWebsocket] ------- read massage frame -------
[WS][0][handleWebsocket] fin: 1 rsv1: 0 rsv2: 0 rsv3 0  opCode: 10
[WS][0][handleWebsocket] mask: 1 payloadLen: 0
[WS][0][handleWebsocket] get pong  (<null>)
[WS][0][sendFrame] ------- send massage frame -------
[WS][0][sendFrame] fin: 1 opCode: 2 mask: 0 length: 7750 headerToPayload: 0
[WS][0][sendFrame] sending Frame Done (215109us).
dt_us:215292 d0:67893911 r:0 dl:7750
[WS][0][sendFrame] ------- send massage frame -------
[WS][0][sendFrame] fin: 1 opCode: 2 mask: 0 length: 7750 headerToPayload: 0
[WS][0][sendFrame] sending Frame Done (214355us).
dt_us:214535 d0:69143508 r:0 dl:7750
[WS][0][sendFrame] ------- send massage frame -------
[WS][0][sendFrame] fin: 1 opCode: 2 mask: 0 length: 7750 headerToPayload: 0
[WS][0][sendFrame] sending Frame Done (212589us).
dt_us:212768 d0:70393111 r:0 dl:7750
[WS][0][handleWebsocketWaitFor] size: 2 cWsRXsize: 0
[readCb] n: 2 t: 71851
[WS][0][handleWebsocketWaitFor][readCb] size: 2 ok: 1
[WS][0][handleWebsocket] ------- read massage frame -------
[WS][0][handleWebsocket] fin: 1 rsv1: 0 rsv2: 0 rsv3 0  opCode: 8
[WS][0][handleWebsocket] mask: 1 payloadLen: 26
[WS][0][handleWebsocketWaitFor] size: 6 cWsRXsize: 2
[readCb] n: 4 t: 71864
[WS][0][handleWebsocketWaitFor][readCb] size: 6 ok: 1
[WS][0][handleWebsocket] ------- read massage frame -------
[WS][0][handleWebsocket] fin: 1 rsv1: 0 rsv2: 0 rsv3 0  opCode: 8
[WS][0][handleWebsocket] mask: 1 payloadLen: 26
[readCb] n: 26 t: 71875
[WS][0][handleWebsocket] get ask for close. Code: 1002 (WebSocket Protocol Error)
[WS][0][handleWebsocket] clientDisconnect code: 1000
[WS][0][sendFrame] not Connected!?
[WS-Server][0] client disconnected.
client_num[0] Disconnected!
chg_A2:-40

**Comment by Links2004** [comment]
currently there is no way, the data is handed over to the TCP stack
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.cpp#L236

the only part that know if all data is send is the TCP stack, the websocked lib itself has no need to keep track of this.
I can image two thinks that can go wrong.
1. to less heap to store all messages
2. race condition in the Async TCP or lwip stack buffer do to the async nature of the calls.

the return value you get from the sendBin function will tell you if the TCP layer has accepted the full messages.
have you checked the return value? may the TCP stack buffer gets an overflow with all this data.

in the log I see `sending Frame Done (215109us).` 
this looks like the all to well known lasy ACKing of windows (windows has an tcp ack delay of 200ms in many cases).
the TCP stack only frees the data internally when the data is ACKed.

may enable debug for the Async TCP too.
https://github.com/me-no-dev/ESPAsyncTCP/blob/master/src/ESPAsyncTCPbuffer.h#L28

the first TCP buffer is here:
https://github.com/me-no-dev/ESPAsyncTCP/blob/master/src/ESPAsyncTCPbuffer.cpp#L103

the last is in the ESP lwip stack not easy to debug there.

**Comment by starlino** [comment]
Markus thanks. I am closing this issue. Because I am abandoning the idea of ASYNC, since there's no way to know when data was completed sending. It seems current ASYNC approach is very fragile and if data is sent too fast, I get either WDT errors or frame errors on clients (maybe due to overwrriting buffers inside the TCP stack?). I will open however another issue also related to sending big chunks of data fast but in SYNC mode.
