### ISSUE TITLE
Make multiple calls to client->tcp->write() for partial transfers

### ISSUE THREAD

**Issue by starlino** [Links2004/arduinoWebSockets#187]
I ran into this problem by sending binary packets with an interval of 250ms.
Anything larger than  ~2900bytes would fail. My client is windows and has probably the dreaded  200ms ACK delay, hence my rate of  250ms.

I looked into WebSockets.cpp code and in particular the one that uses headerToPayload (since  I am using this feature to merge header and payload in same buffer):

I made a small modification that now allows me to send larger buffers (>2900bytes) with a frequency of  250ms (with Windows client):

~around line  250 in WebSockets.cpp 

```
       //if(client->tcp->write(&payloadPtr[(WEBSOCKETS_MAX_HEADER_SIZE - headerSize)], (length + headerSize)) != (length + headerSize)) {
	if(client_tcp_write_multi(client,&payloadPtr[(WEBSOCKETS_MAX_HEADER_SIZE - headerSize)], (length + headerSize)) != (length + headerSize)) {
            ret = false;
        }
```

Note that I replaced **client->tcp->write()** with a function **client_tcp_write_multi** that basically makes multiple calls to  **client->tcp->write()**  if the later only returns a partial result. In  current code  v2.0.6  it is  required for the payload to be sent in a single **client->tcp->write()**  - was it assumed that tcp->write() will handle this multi-write internally and why it's not doing so in my case and from where comes the ~2900 limit ?:

```
size_t client_tcp_write_multi(WSclient_t * client, uint8_t * data, int32_t data_len){
	int32_t total_bytes_written = 0;
	int32_t bytes_written;
	do{
		bytes_written = client->tcp->write(&data[0], data_len);
		data_len -= bytes_written;
		data += bytes_written;
		total_bytes_written += bytes_written;
		Serial.printf("tcp_bytes_written:%d\n",bytes_written);
	}while(bytes_written > 0 && data_len > 0 );	
		
	return total_bytes_written;
}
```
 

I hope you can review this and implement as a permanent feature in your code (or at least in those critical calls likely to be called by people who need speed in sending).

You can see from output of my code that indeed it is possible to make multiple calls to 
 **client->tcp->write()** and rescue **sendFrame()** from failing.

```
seq:22 dt_us:205401 ms:121371 ms_delta:251 r:1 dl:6500
tcp_bytes_written:2920
tcp_bytes_written:2920
tcp_bytes_written:664
seq:23 dt_us:205191 ms:121622 ms_delta:251 r:1 dl:6500
tcp_bytes_written:2920
tcp_bytes_written:2920
tcp_bytes_written:664
```
and snippet from my code:

```
void loop() {
  uint32_t ms_delta =  millis() - ms_last;
  if(batch_run && current_client_num>=0 && ms_delta >  interval_ms){
      ms_last = millis();
      memcpy(data , &sequence, 1);      
      memcpy(data + 1, &ms_last, 4);
      uint32_t t0 = micros();
      bool result = ws.sendBIN(current_client_num,buf,data_len ,1 /*headerToPayload*/);
      DBG_SERIAL.printf("seq:%u dt_us:%u ms:%u ms_delta:%u r:%u dl:%u\n",sequence, micros()-t0 ,  ms_last, ms_delta ,result,data_len);
      sequence++;
  }      
  ws.loop();

}

```

Interesting phenomena: Without the patch code above , even if **sendFrame()** would return  0, I would still get some data on client side, but with every other call to .sendBin() skipped , so not all packets make it to the client.

**Comment by Links2004** [comment]
we may can fix it like this, but I think its a better Idea to fix it in the Arduino for ESP8266 since the Problem will effect all Application not only the Websockets lib.
the assumed that tcp->write() will handle this multi-write internal is correct it need to do, and up to 2920 it does it.

the write call ends up here:
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/include/ClientContext.h#L286
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/include/ClientContext.h#L322
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/include/ClientContext.h#L336

at first look I think 
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/include/ClientContext.h#L354

need to be:

```cpp
            if (err == ERR_OK) {
                _datasource->release_buffer(buf, next_chunk);
                _written += next_chunk;
                did_write = true;
            }
```

the internal TCP buffer in lwip has a size of max 2920 (TCP_SND_BUF)

may add some debug output to `_write_some` and `_write_some_from_cb` will allow us to track this down.

Note:
the 200ms from windows can be workaround ed when you send a small answer at the moment when you get first message in the browser.
when you send data back from windows to the ESP windows will send the ACK immediately ;)

**Comment by starlino** [comment]
Markus,  I think giving user control is always a good practice.
Personally for my application  I think it's kind of convenient that tcp->write() does chunked transfers .... It frees up part of the buffer that can be reused and gives application a chance to do some work - this is very useful in SYNC transfers, otherwise the application could spend  a long time in tcp->write() , holding the buffer busy, and without a chance for the rest of the app to do anything. I know we have ASYNC now, but it is not very stable in ESP8266. I think it was never the intention of tcp->write()  to do a full transfer at once, otherwise it would return just **true/false*. Currently it returns bytes transferred which is logical and resuming from where it left with another call to tcp->write()  seems to work well. 

I think the safest way to implement it is to replace tcp->write() with a  
#ifn defined
#define   TCP_WRITE(client)   client->tcp->write() 
#endif 
and let users redefine it if needed .... 

Another advantage of having our own  client_tcp_write_multi() is that we can trigger an event, and give user progress updates of the TCP transfer, for example to display a progress bar, etc ... 



Can 2920 (TCP_SND_BUF) be changed at run time or at compile time ?

**Comment by Links2004** [comment]
TCP_SND_BUF is part of the lwip stack, there is no way to change it on runtime.

if you send enough data Windows will send ACKs before the 200ms.

the goal is to keep the API as simple as possible, normally the user expects the send the data at once when `sendBin` is called.
if you need a process bar simple use smaller amounts with multible `sendBin` calls,
and update the bar in between. 
is a much easier to understand approche then overriding the tcp write via the class in my opinion.

using a DEFINE is not possible with the Arduino IDE, for any IDE that can modify the compiler parameters sure. 

`tcp->write()` itself can not send more then 1490 byte in one TCP Paket the 2920 will always end up in two TCP packets.
based on the network setup this amount that can change, but in one TCP packet can not be more then 1490 byte.

not really get the reason why `client->tcp->write()` 2920 byte --> 2 TCP packets is ok, but 8500 --> 6 TCP packets is not good in your opinion.

sure I will fix it, sending only partially data is very bad.
but adding a API the see the calls of each write is unnecessary complexity, from my point of view.

**Comment by Links2004** [comment]
including timeout and error handling i currently end up with:
https://github.com/Links2004/arduinoWebSockets/commit/adb52b11e9123c8fab10683ca044f290f72cd1e5
if you like you can try it, until next weckend I have no access to a ESP8266 too try it.

**Comment by starlino** [comment]
> if you send enough data Windows will send ACKs before the 200ms.
agreed, that is what I am doing now, however it seems like currently the sendBIN does not work reliably for packets larger than  2920.

> if you need a process bar simple use smaller amounts with multible sendBin calls, and update the bar in between.

this is in contradiction with what you said earlier .... I need to send bigger chunks of data so I don't have the 200ms Windows delay.

All I am asking is that you put a  'virtual'  in front of your    WebSockets::write(.. ) function, you don't even have to announce it as a feature , people (like me) who need to hook into it will be happy you did.

**Comment by Links2004** [comment]
ok, now I get it.
will add `virtual` to the write.

**Comment by Links2004** [comment]
`write_big_data` branch is now part of master
