### ISSUE TITLE
Problem with remote websocket client connection

### ISSUE THREAD

**Issue by markowanga** [Links2004/arduinoWebSockets#189]
Hi,
I want to connect my esp8266 with remote server (Heroku, application written in node.js). I can't begin a connection. I tried put many differences hosts (for example with ws:// begin) but I still can't connect. When I try connect with localhost (the host is my local IP address) it is working with no problems. The my remote host name is: websocketmarkowanga.herokuapp.com

**Comment by quantumlicht** [comment]
The page does not exist. Make sure your heroku app is correctly deployed. Test it first with a client. Personally I use the `Simple WebSocket Client` chrome extension.

**Comment by gnkarn** [comment]
Did you finally made it to work?
I have the same problem , I'm using nodejs on heroku, it works fine with a JavaScript ws client on the browser , but with the ESP , the connection  was not possible .

So it has to be something with the socketio client configuration on the ESP client , but it is being very difficult to debug so far ..

Any recommendations appreciated ..

**Comment by markowanga** [comment]
Yes, it works.
In my case I set the port on 80 in WebSocketsClient and it strats work.

**Comment by Links2004** [comment]
https://github.com/Links2004/arduinoWebSockets/issues/204
