### ISSUE TITLE
Arduino Original Wifi Shield Using Wifi Library

### ISSUE THREAD

**Issue by code4funcies** [Links2004/arduinoWebSockets#19]
Hi.
Thank you for implementing this solution.
How hard will it be to implement this arduinoWebsockets using the Original Arduino WifiShield and the wifiLibrary? What are the neccesary steps?
https://www.arduino.cc/en/Main/ArduinoWiFiShield
https://www.arduino.cc/en/Reference/WiFi

Thank you

**Comment by Links2004** [comment]
add the needed includes here:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L30-L38

use the right class here:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L78-L86

same for the server
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsServer.h#L30-L38
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsServer.h#L87-L95
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsServer.cpp#L30


the biggest part is to add a sha1 implementation for the AVR
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.cpp#L334

hope this helps

**Comment by code4funcies** [comment]
Thank you for your Reply.
I will try to make those changes and let you know how it goes.

**Comment by Links2004** [comment]
I add basic support for W5100
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/WebSocketClientAVR/WebSocketClientAVR.ino
