### ISSUE TITLE
Can not compile for ESP8266 using latest version

### ISSUE THREAD

**Issue by Fireflaker** [Links2004/arduinoWebSockets#191]
This is what it says.

C:\Users\win7\Documents\Arduino\libraries\WebSockets\src\WebSocketsClient.cpp: In member function 'void WebSocketsClient::begin(const char*, uint16_t, const char*, const char*)':

C:\Users\win7\Documents\Arduino\libraries\WebSockets\src\WebSocketsClient.cpp:69:16: error: 'RANDOM_REG32' was not declared in this scope

     randomSeed(RANDOM_REG32);

                ^

exit status 1

**Comment by Fireflaker** [comment]
**This is my simplest sketch**

#include <WebSockets.h>
#include <WebSocketsClient.h>
#include <WebSocketsServer.h>


void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}


**And here is the result:**

C:\Users\win7\Documents\Arduino\libraries\WebSockets\src\WebSocketsClient.cpp: In member function 'void WebSocketsClient::begin(const char*, uint16_t, const char*, const char*)':

C:\Users\win7\Documents\Arduino\libraries\WebSockets\src\WebSocketsClient.cpp:69:16: error: 'RANDOM_REG32' was not declared in this scope

     randomSeed(RANDOM_REG32);

                ^

exit status 1


Unable to compile

**Comment by jjssoftware** [comment]
The RANDOM_REG symbol is defined here: 

https://github.com/esp8266/Arduino/blob/4897e0006b5b0123a2fa31f67b14a3fff65ce561/cores/esp8266/esp8266_peri.h#L843

..so it looks like either you don't have the esp8266 arduino core correctly installed or you have some sort of local path problem

**Comment by jjssoftware** [comment]
..or perhaps you just need to include this:

`#include <Arduino.h>`

**Comment by Fireflaker** [comment]
Thank you very much!!!!

**Comment by Fireflaker** [comment]
Problem solved by re-installing the ESP8266 thing and using ATMEL-ICE compiler
