### ISSUE TITLE
Send and receive data other than string and multiple data on websockets

### ISSUE THREAD

**Issue by sibangjack** [Links2004/arduinoWebSockets#192]
Is it possible to send data other than string over websockets?
For example I can send data like
```
String data = "hello world";
webSocket.sendTXT(data);
```
But it gives me error messages when trying to send data like int, float, etc.
For example
```
int num = 12;
webSocket.sendTXT(num);
```
Is it also possible to send or receive an array or struct that contains multiple data over websockets?
I'm trying to send temperature and humidity data from DHT11 sensor to websockets server. Is there any documentation or can you give me advice on how to achieve that and my websockets server can recognize which data is temperature and which data is humidity?

**Comment by sibangjack** [comment]
Thank you very much man. That was really helpful 👍 👍 
But now I have a little problem. I want my node can send temperature or humidity data based on server's request. My code is like this
```
void webSocketEvent(WStype_t type, uint8_t * payload, size_t length) {
    switch (type) {
       case WStype_DISCONNECTED:
          Serial.printf("Disconnected!\n");
          break;
       case WStype_CONNECTED:
          webSocket.sendTXT("DHT11");
          break;
       case WStype_TEXT:
          if(payload == "requesttemp"){
             String temperature = dht.readTemperature();
             webSocket.sendTXT(temperature);
          }
          else{
             String humidity = dht.readHumidity();
             webSocket.sendTXT(humidity);
          }
          break;
   }
}
```
So, for example if server says "requesttemp" my node will send temperature data, other than that my node will send humidity data.

But when I use that code, I got red line under `case WStype_TEXT:` at
`if(payload == "requesttemp")
`

And error messages

> exit status 1
> comparison between distinct pointer types 'uint8_t* {aka unsigned char*}' and 'const char*' lacks a cast [-fpermissive]

Can you help me how is the correct one to do that? Sorry for my bad English btw.

**Comment by Links2004** [comment]
``payload`` is not a string (its ```uint8_t *```) you can not use it like this, but you can create a string out of it.

```cpp
String payload_str = String((char*) payload);

if(payload_str == "requesttemp")
```

**Comment by sibangjack** [comment]
@Links2004 Ok man thanks again, it works now 👍

**Comment by vilasrao** [comment]
nice explanation!

**Comment by Jose456654** [comment]
void webSocketEvent(WStype_t type, uint8_t * payload, size_t length) {
    switch (type) {
       case WStype_DISCONNECTED:
          Serial.printf("Disconnected!\n");
          break;
       case WStype_CONNECTED:
          webSocket.sendTXT("DHT11");
          break;
       case WStype_TEXT:
          if(payload == "requesttemp"){
             String temperature = dht.readTemperature();
             webSocket.sendTXT(temperature);
          }
          else{
             String humidity = dht.readHumidity();
             webSocket.sendTXT(humidity);
          }
          break;
   }
}

This code that was above, is similar to mine I have one when using:

webSocket.sendTXT(moisture);

How do I capture that "humidity" value on the client side so that it is displayed in the html page.

**Comment by piyush9999** [comment]
Hello @Links2004 @sibangjack @Jose456654 @nerochiaro @sovcik I want to use websocket Library with the Tinygsm, I am connecting to the websocket server using Tinygsm lib and GSM module, Now as per websocket my server is able to send message in actual bytes, but while sending message from the device the message need to be encoded and some fragmented. 
So for this I want to use the websocket.sendTXT method which will send the message in the required format. 
Is anyone tried this,
