### ISSUE TITLE
DEBUG outputs are not getting printed at Serial console

### ISSUE THREAD

**Issue by debojitk** [Links2004/arduinoWebSockets#193]
Hi,
I am using a websockets library on esp8266 using espArduino. The code runs fine, but inside the library no Serial.println works. The library has got its own marcos as debug switch, but after enabling the switch no serail output comes in the console. Later I replaced all macro with direct Serial call, but it also does not work. But the Serial works in all my ino and classes that access the library.

Here is the macro part
```
//#define DEBUG_WEBSOCKETS(...) os_printf( __VA_ARGS__ )
//#define DEBUG_WEBSOCKETS(...) Serial.printf(__VA_ARGS__)

#ifndef DEBUG_WEBSOCKETS
#define DEBUG_WEBSOCKETS(...)
#define NODEBUG_WEBSOCKETS
```
The second commented line at the top added by me.
Uncommenting none of them don't work though.

What can be the problem?

Thanks,
Debojit

**Comment by Links2004** [comment]
where do you add the ```#define``` ?
in the ```ino ```or do have you changed the ```WebSockets.h```

```os_printf``` will only work when you enable debug on the ESP.
