### ISSUE TITLE
How to accept multiple client connections

### ISSUE THREAD

**Issue by kietcroco** [Links2004/arduinoWebSockets#194]
làm thế nào để chấp nhận nhiều kết nối client cùng lúc.

xin lỗi tiếng anh của tôi không được tốt.

cảm ơn !!

> **by goole translate**
> Sorry my english is not good
> How to accept multiple client connections at the same time
> thanks all!

["https://github.com/Links2004/arduinoWebSockets/blob/master/examples/WebSocketServer/WebSocketServer.ino"](https://github.com/Links2004/arduinoWebSockets/blob/master/examples/WebSocketServer/WebSocketServer.ino)

**Comment by Links2004** [comment]
its done automatically, the ESP can handle up to 5 Clients.
the clients can be identified by ```num```.

**Comment by kietcroco** [comment]
có thể cho tôi 1 ví dụ về 2 client kết nối vào được không,
tôi muốn gửi nội dung khác nhau cho từng client.

cảm ơn bạn!

> **By google translate**
> Can you give me an example of two connected clients,
> I want to send different content to each client.
> 
> thank you!

**Comment by Links2004** [comment]
on every `webSocketEvent` call you get the variable `num` by the variable you can identify from which client the message / event is coming.

to send a message to a specific client you use the first variable of the send function.
```cpp
// send message to client 1 ( the first one that has connected )
webSocket.sendTXT(1, "Hello client 1");

// send message to client 2
webSocket.sendTXT(2, "Hello client 2");

// send message to client 3
webSocket.sendTXT(3, "Hello client 3");
```

**Comment by kietcroco** [comment]
thanks you!
