### ISSUE TITLE
why does a broadcastTXT let hang my esp8266?

### ISSUE THREAD

**Issue by Primus007** [Links2004/arduinoWebSockets#196]
Thank you for this great websockets library. 

I use an esp-01 to control an small led strip.

my goal:
when a connected user makes changes on the esp website then the website of all other connected users should be updated immediately.

this is my try:
`    case WStype_TEXT:                     // if new text data is received
      Serial.printf("[%u] get Text: %s\n", num, payload);

     /* Brightness */
     if (payload[0] == '+') {            // we get brightness back
         String payloadString=(const char *)payload;
         String text = String((char *) &payload[1]);
         helligkeit = text.toInt();
         FastLED.setBrightness(helligkeit);
         Serial.println("brightness: "+text);
         webSocket.broadcastTXT('+'+String(helligkeit));
      }

     /* Speed */
     if (payload[0] == '-') {            // we get speed back
         String payloadString=(const char *)payload;
         String text = String((char *) &payload[1]);
         animation_speed = text.toInt();
         Serial.println("speed: "+ animation_speed);
         webSocket.broadcastTXT('-'+String(animation_speed));
      }
     `

both are slider in the html page.
if i tap the slider all works fine but if i drag the slider then my esp8266 hangs a lot and nothing is possible. 

Please can you help me to solve this problem?

many thanks.

**Comment by Links2004** [comment]
you are most likely creating a endless feedback loop since you use ```broadcastTXT```.
Client 1 send update event --> ESP gets it --> ESP send update to all clients including Client 1 --> Client 1 process Update and create a new events (since the user still touches the slider) --> ESP gets it --> .....

you can try some think like this:
```cpp
for(uint8_t i = 0; i < WEBSOCKETS_SERVER_CLIENT_MAX; i++) {
 if(i != num) {
  webSocket.sendText(i, payload);
 }
}
```

**Comment by Primus007** [comment]
Thanks for your answer.

the problem are not to many clients. there are only two.
have you another suggestion for me?

**Comment by Links2004** [comment]
to trigger loop you only need the one client.
the code above will send the update to all clients expect the one where the info ( event ) where coming from, as result there is no loop any more.

one other common problem it the TCP 200ms ACK delay of windows, which gets easy in the way of fast updating, but at first you need the stop the loop.
If you run in the ACK delay, the best option is to use the async variant DEFINE from the lib.
