### ISSUE TITLE
Delay in connection code makes esp8266 stutter

### ISSUE THREAD

**Issue by schlaegerz** [Links2004/arduinoWebSockets#198]
I have a long running action I want my esp8266 to be doing, and when it tries to connect to the server after being disconnected there is a delay that makes my entire thing stutter

```
 if(_client.tcp->connect(_host.c_str(), _port)) {
            connectedCb();
        } else {
            connectFailedCb();
            delay(10); //some little delay to not flood the server
        }

```
This only seems to be a problem in some cases for me when there is a more immediate failed response, such as when the server is returning instantly with a rejecting (When I'm testing a local IP address and kill my server).

**Comment by Links2004** [comment]
to the 10ms delay comes the syn timeout of the TCP connect call (since your server is down) which is much more then the delay, itself.
may using the Async variant is an option for you.

https://github.com/Links2004/arduinoWebSockets#esp-async-tcp
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L81

changing the connect reconnect handling is on my todo list, but currently there is no "release" date for it.

may the infos here, helps you.
https://github.com/Links2004/arduinoWebSockets/issues/135
https://github.com/Links2004/arduinoWebSockets/issues/157

**Comment by schlaegerz** [comment]
Ok thanks! I'll take a look at it.

It looks like SSL doesn't work for the async version is that right?

**Comment by schlaegerz** [comment]
Thanks for the help I was able to fix it by overriding both the WebSocketsClient and the WifiClient

For anyone else who comes across this problem here is my code:
`
extern "C"
{
#include "lwip/ip.h"
#include "lwip/tcp.h"
}

void NoWaitWebSocketsClient::loop(void) {

    if (!_client.tcp || 
        !_client.tcp->connected() || 
        waitingForConnect)
    {
        if (_client.tcp && !waitingForConnect)
        {
            clientDisconnect(&_client);
        }

        if (lastDisconnectTime + 5000 > millis())
        {
            // Wait for tcp to be connected, then call the callback
            if (_client.tcp)
            {
                if ((bool)(*_client.tcp) && _client.status == WSC_NOT_CONNECTED)
                {
                    waitingForConnect = false;
                    connectedCb();
                }
            }
        }
        else
        {
#if (WEBSOCKETS_NETWORK_TYPE == NETWORK_ESP8266)
            if (_client.isSSL) {
                DEBUG_WEBSOCKETS("[WS-Client] connect wss...\n");
                if (_client.ssl) {
                    delete _client.ssl;
                    _client.ssl = NULL;
                    _client.tcp = NULL;
                }
                _client.ssl = new WiFiClientSecure();
                _client.tcp = _client.ssl;
            }
            else {
                DEBUG_WEBSOCKETS("[WS-Client] connect ws...\n");
                if (_client.tcp) {
                    delete _client.tcp;
                    _client.tcp = NULL;
                }
                _client.tcp = new WiFiClient();
            }
#else
            _client.tcp = new WEBSOCKETS_NETWORK_CLASS();
#endif

            if (!_client.tcp) {
                DEBUG_WEBSOCKETS("[WS-Client] creating Network class failed!");
                return;
            }

            waitingForConnect = true;
            _client.tcp->connect(_host.c_str(), _port);
            lastDisconnectTime = millis();
        }
    }
    else {
        //Serial.println("CONNECTED");
        waitingForConnect = false;

        handleClientData();
    }
}


int NoWaitWifiClient::connect(IPAddress ip, uint16_t port)
{
    ip_addr_t addr;
    addr.addr = ip;

    if (_client)
        stop();

    // if the default interface is down, tcp_connect exits early without
    // ever calling tcp_err
    // http://lists.gnu.org/archive/html/lwip-devel/2010-05/msg00001.html
    netif* interface = ip_route(&addr);
    if (!interface) {
        DEBUGV("no route to host\r\n");
        return 0;
    }

    tcp_pcb* pcb = tcp_new();
    if (!pcb)
        return 0;

    if (_localPort > 0) {
        pcb->local_port = _localPort++;
    }

    tcp_arg(pcb, this);
    tcp_err(pcb, &WiFiClient::_s_err);
    tcp_connect(pcb, &addr, port, reinterpret_cast<tcp_connected_fn>(&WiFiClient::_s_connected));

    //esp_yield(); This is what made the connection wait
    if (_client)
        return 1;

    //  if tcp_error was called, pcb has already been destroyed.
    // tcp_abort(pcb);
    return 0;
}`

**Comment by Links2004** [comment]
implementation of `setReconnectInterval` 522a67bc1b4ec0e56cb7e86d4d0bd780ccfa3dff
