### ISSUE TITLE
Watch Dog Timer keeps firing

### ISSUE THREAD

**Issue by RussMathis** [Links2004/arduinoWebSockets#2]
Have been trying to create a simple server/client communications scheme with arduinoWebSockets but the WDT keeps firing on the server and client? The basic difference is that I'm trying to use access point mode without the multi.

While testing WebSocketsServer and WebSocketsClient on the ESP in Access mode I ran across an issue that is still unresolved. More than likely something wrong on my part but if someone has an idea please let me know!

The issue is that the WDT keeps firing...

The server code: ****************************

#include
#include
#include
#include "WebSockets.h"
#include "WebSocketsServer.h"

#define ssid "racemaster"
#define pass "00112233445566778899aabbcc"

WebSocketsServer webSocket = WebSocketsServer(81);

void webSocketEvent(uint8_t num, WStype_t type, uint8_t * payload, size_t lenght) {

switch (type) {
case WStype_DISCONNECTED:
Serial.printf("[%u] Disconnected!\n", num);
break;
case WStype_CONNECTED:
{
IPAddress ip = webSocket.remoteIP(num);
Serial.printf("[%u] Connected from %d.%d.%d.%d url: %s\n", num, ip[0], ip[1], ip[2], ip[3], payload);
}
break;
case WStype_TEXT:
Serial.printf("[%u] get Text: %s\n", num, payload);

// echo data back to browser
webSocket.sendTXT(num, payload, lenght);

// send data to all connected clients
webSocket.broadcastTXT(payload, lenght);
break;
case WStype_BIN:
Serial.printf("[%u] get binary lenght: %u\n", num, lenght);
hexdump(payload, lenght);

// echo data back to browser
webSocket.sendBIN(num, payload, lenght);
break;
}

}
IPAddress netServerIp = { 192, 168, 10, 1 };
IPAddress netSubNetIp = { 255, 255, 255, 0 };
void setup() {
Serial.begin(115200);

WiFi.disconnect();
WiFi.mode(WIFI_AP);
WiFi.softAPConfig(netServerIp, netServerIp, netSubNetIp);

WiFi.softAP(ssid, pass);

webSocket.begin();
webSocket.onEvent(webSocketEvent);
}

void loop() {
webSocket.loop();
delay(5);
}

The client code:****************************

#include
#include
#include <WebSockets/src/WebSocketsClient.h>
#include

#define ssid "racemaster"
#define pass "00112233445566778899aabbcc"

WebSocketsClient webSocket;

void webSocketEvent(WStype_t type, uint8_t * payload, size_t lenght) {
switch (type) {
case WStype_DISCONNECTED:
Serial.printf("[WSc] Disconnected!\n");
break;
case WStype_CONNECTED:
{
Serial.printf("[WSc] Connected to url: %s\n", payload);
}
break;
case WStype_TEXT:
Serial.printf("[WSc] get text: %s\n", lenght);

// send data to back to Server
webSocket.sendTXT(payload, lenght);
break;
case WStype_BIN:
Serial.printf("[WSc] get binary lenght: %u\n", lenght);
hexdump(payload, lenght);

// echo data back to Server
webSocket.sendBIN(payload, lenght);
break;
}
}

void setup() {
Serial.begin(115200);

WiFi.disconnect();
WiFi.mode(WIFI_STA);
WiFi.begin(ssid, pass);

while (WiFi.status() != WL_CONNECTED){
//Wait for client to connect
Serial.print(".");
delay(500);
}

Serial.println();
Serial.print("Connected:");
Serial.println(WiFi.localIP());

webSocket.begin("192.168.10.1", 81);
webSocket.onEvent(webSocketEvent);
}

unsigned long lastSentMsg = millis();
void loop() {
webSocket.loop();

//Send a message to the server every 5 seconds
if ((millis() - lastSentMsg) > 5000){
webSocket.sendTXT("testing",7);
lastSentMsg = millis();
}
delay(5);
}

**Comment by Links2004** [comment]
please test: 
```cpp
if(WiFi.status()== WL_CONNECTED)  {
     webSocket.loop();
}
```

and 
```cpp
if(WiFi.status()== WL_CONNECTED)  {
     webSocket.loop();

//Send a message to the server every 5 seconds
if ((millis() - lastSentMsg) > 5000){
   webSocket.sendTXT("testing",7);
   lastSentMsg = millis();
}
}
```

trying network stuff without connection is may bad.
when i have some free time  i test you complete example
