### ISSUE TITLE
How to detect the received message name? In order to implement an on.message callback?

### ISSUE THREAD

**Issue by gnkarn** [Links2004/arduinoWebSockets#201]
As there is not a way to implement individual message callbacks, I understand everything needs to be done on the same callback, right?
In that case how we detect the messag name ?  From the socket object ?

im looking for a functionality like : socket.on(eventName, callback)

**Comment by Links2004** [comment]
```cpp
 socket.on(eventName, callback)
```
looks like socketio to me, the low level handling of the socketio protocol is implemented.
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/WebSocketClientSocketIO/WebSocketClientSocketIO.ino

all messages will be decoded in json and end up in the `WStype_TEXT`
its up to the developer to distributed them to other functions if needed.

**Comment by gnkarn** [comment]
ok, thanks for your answer ,
as im connecting two clients to one nodeJS on Heroku server,  the web browser client is working fine , but on the ESP i only receive disconnected messages, there may be some problem with my configuration on ESP.

as im working on visual studio 2015, by following your instructions i enabled this line on the websocket.h  

#define DEBUG_WEBSOCKETS(...) os_printf( __VA_ARGS__ ) // !!! enabled only for debuging

#ifndef DEBUG_WEBSOCKETS
#define DEBUG_WEBSOCKETS(...)
#define NODEBUG_WEBSOCKETS
#endif

but im not receiving any messages , other than my own .

is there other changes i should do on the code ?
tis

**Comment by Links2004** [comment]
you need to enable debug for the Arduino.
add the `DEBUG_ESP_PORT` define with value `Serial` to your compiler
https://github.com/esp8266/Arduino/blob/master/boards.txt#L193

other way is to add:
```cpp
Serial.setDebugOutput(true);
```
in your ```setup``` function

**Comment by gnkarn** [comment]
this works perfect , thank you for your help .

i receive the sockets now, but the JSON parser is not giving the intended output , most jure i have something wrong , as the server is adding a 42 (?) , and the callback function name to the payload, so i will need to take that part out before parsing ...

for example  the time event  payload looks like
42["time","{\"msgName\":\"time\",\"type\":3,\"message\":\"17:58:24 GMT+0000 (UTC)\"}"]

so its is not in JSON format yet ..
