### ISSUE TITLE
Pong response contains a mask

### ISSUE THREAD

**Issue by anisimovsergey** [Links2004/arduinoWebSockets#208]
Pong response to my ping requests contains a mask and overall it looks like this "8a 80 00 00 00 00". I'm not entirely sure if sending a mask without data is a valid case.

**Comment by Links2004** [comment]
from the RFC:

> In the WebSocket Protocol, data is transmitted using a sequence of
   frames.  To avoid confusing network intermediaries (such as
   intercepting proxies) and for security reasons that are further
   discussed in Section 10.3, a client MUST mask all frames that it
   sends to the server (see Section 5.3 for further details).  (Note
   that masking is done whether or not the WebSocket Protocol is running
   over TLS.)  The server MUST close the connection upon receiving a
   frame that is not masked.

hopes that answer the question.

**Comment by anisimovsergey** [comment]
Thank you @Links2004 for your prompt response. 
It does seem like it's a problem is the client I'm trying to use. It closes connection upon receiving a pong with a mask. What is strange though, that this is a quite popular WebSocktets client library ~3000 stars on github and claims to be conformant with the Autobahn test suite. Anyhow, I'm closing this one.

**Comment by anisimovsergey** [comment]
Finally I got some time to go through the RFC and that what it is saying in section Section 5.3 
```
A server MUST NOT mask any frames that it sends to
   the client.  A client MUST close a connection if it detects a masked
   frame. 
```
PONG should not be masked since it is sent from a server to a client.

**Comment by Links2004** [comment]
missed your response, will look in to this.
may need some restructuring to handle this cases.

**Comment by Gl0ntz** [comment]
Connection being dropped by the client running on an Android Device with Reason="A frame from the server is masked". Is there a solution to this?

**Comment by sanketplus** [comment]
any plans to fix this?  @Links2004 

One approach I have in mind is to introduce a `isServer` field in `WSClient_t` and use it in `sendFrame` on line [#L197](https://github.com/Links2004/arduinoWebSockets/blob/a3079f564541c49c3973869990be3c40761c5e8b/src/WebSockets.cpp#L197) to check if it is server, and skip.

If you think this is a good way to approach, happy to open a PR :)

**Comment by Links2004** [comment]
sounds good, a PR is welcome.
I hink with the `isServer` change it we can remove the `mask` parameter all together form the function.
since `sendFrame` is a internal function it will not change the external API.
