### ISSUE TITLE
Question :  How to detect data type from Javascript web socket ?

### ISSUE THREAD

**Issue by gnkarn** [Links2004/arduinoWebSockets#209]
on the other side , either a nodejs, server or a JS client , how to detect if the message is binary type or text  as soon as the message is received ,
i understand that the info is part of the header Wsopcode , and is clear on your library , but how to detect the same condition on the other end of the line ?
appreciate your insight .. gus

**Comment by Links2004** [comment]
nodejs has a message type.
```js
connection.on('message', function(message) {
    if (message.type === 'utf8') {

    }  else if (message.type === 'binary') {

    }
}
```
more here:
https://www.npmjs.com/package/websocket#server-example


on the Browser I never tried "mixed" mode.
but something like this may work:

```js
connection.onmessage = function (message) {
    if (message.data instanceof ArrayBuffer) {
        // binary
    } else {
        // UTF-8
    }
};
```

**Comment by gnkarn** [comment]
this works very good on the web client , here is how my code looks:
`ws.onmessage = function(evt) {
    //if (typeof evt.data === 'string') { // utf8 o string
    //create a JSON object
    var tipo = evt.data instanceof ArrayBuffer;
    if (tipo) {
      // if binary
      //*console.log('binario');
      var buffer = new ArrayBuffer;
       buffer = (evt.data);
       var bufferView = new Uint8Array(buffer); // enable access to the buffer array
      //var bufferArray = Array.from(buffer); // convert to normal array
      //*console.log(bufferView);
      for (var y = 0; y < ledMatrixHeight; y++) {
        for (var x = 0; x < ledMatrixWidth; x++) {
          var index = (x + (y * ledMatrixWidth)); // index represents pixels adress, index*3 is begining of each RGB value on the flat bin arrray
          // converts to a normal array
          matrixReceived[index] = [bufferView[3*index+0],bufferView[3*index + 1],bufferView[3*index + 2]];
          //matrixReceived[index+1] = bufferView[index + 1];
          //matrixReceived[index+2] = bufferView[index + 2];

          //matrixReceived = evt.data
          //alert('binary received')
          //readyToSend = OK; //* enable for  debugging , receiving a frame enables the next
        }
      }

    } else {
      // if text UTF-8
      //*console.log('text');
      var JsonObject = safelyParseJson(evt.data);
      var msgName = JsonObject.msgName;
      var msgContent = JsonObject.message;
      switch (msgName) {
        case "msgArray1": // antes msgArray2
          //var columna = JsonObject.columna ;
          var footer2 = select('#footer2');
          footer2.html('FRarray= ' + floor(frameRate()));
          //console.log('recibido array:', evt.length);
          matrixReceived = msgContent;
          //readyToSend = OK; // enable for  debugging , receiving a frame enables the next
          break;
        case "recibido":
          readyToSend = OK;
          break;
`

thank you
