### ISSUE TITLE
How to build a websocket project by SDK instead of arduino?

### ISSUE THREAD

**Issue by EdVince** [Links2004/arduinoWebSockets#211]
I want to make a project to connect esp8266 with a html website to transmit a huge of data in at a fixed time interval. I plan to use the websocket to do it. But I could not found any doucument about the use of she websocket by SDK, I only find here. I want to konw how to build a websocket project by SDK?

**Comment by Links2004** [comment]
the SDK has no websocket implementation by itself.
this library need the Arduino abstraction layer to work.

if you use the Arduino framework you still can use all SDK functions, 
the easiest way to get a websocket client or server is to use this lib with the Arduino framework on top of the SDK.

**Comment by EdVince** [comment]
I am trying to do it. Arduino is to slow and weak. Any way thanks.
