### ISSUE TITLE
webSocketClient.sendTXT throws Exception 3: LoadStoreError

### ISSUE THREAD

**Issue by ThePaceMaker** [Links2004/arduinoWebSockets#212]
Hi Links2004

I have the strangest exception being thrown and I'm at a loss.  

When I **don't** have the serial cable plugged in to the NodeMCU 12e, everything works as it should. 

The problem **only** occurs when I have the cable plugged in and trying to monitor the debug information through the serial monitor. I get an exception thrown as soon as I it hits webSocketClient.sendTXT(buffer); method and then exists with -  ets Jan  8 2013,rst cause:2, boot mode:(3,6)

![image](https://user-images.githubusercontent.com/8189997/28268842-b488331c-6af7-11e7-9bd6-7c783ad775b5.png)

Im running the firmware on  1.5.4.1-final that I built off of [https://nodemcu-build.com/](https://nodemcu-build.com/)

Arduino 1.8.3 running the stable board manager package from [http://arduino.esp8266.com/versions/2.3.0/package_esp8266com_index.json](http://arduino.esp8266.com/versions/2.3.0/package_esp8266com_index.json)

I wondering if you have come into a scenario like this before? 

Thank you in advance

**Comment by Links2004** [comment]
from the function names and the call stack its looks like out of free memory to me.
how big is you buffer and how many RAM is free before your sendFrame call?

**Comment by ThePaceMaker** [comment]
I think you might be right. I found this article [https://github.com/esp8266/Arduino/issues/2557](https://github.com/esp8266/Arduino/issues/2557) which explains whats happening. Im probably running out of stack space. 

Im running some tests now.  Just weird how it only happens when the cable is plugged in.

Just as a disclaimer, I new to c++ so just trying to get my head around this behemoth of a language :-)
