### ISSUE TITLE
Websocket "sendBIN" is only limited  to uint8 array how to send float array?

### ISSUE THREAD

**Issue by williamesp2015** [Links2004/arduinoWebSockets#213]
Websocket is able to send text and binary but when sending binary for fast transmission is limited to unsigned integer (uint8_t). Is there any way to send float or int32?

**Comment by Links2004** [comment]
the sendBin takes a pointer you can move the ptr to any address you like in memory.
if you want to send a ```int``` for example:

```cpp
int i = 1234;
uint8_t * buf = (uint8_t *) &i;
size_t buf_len = sizeof(i); // 4 byte
```

the sendBIN takes a start pointer and a length, what data is represented in this memory space makes no difference for the send function.
you can send 1KB of date if you like.

**Comment by williamesp2015** [comment]
Problem starts when array of float sending out and on the other side needs to retrieve from uint8_t array. If be possible to configure binary data as int, float,etc not uint8_t then the receiver can create array by the same binary type.

**Comment by Links2004** [comment]
on the other side its works the same ;) 
cast the pointer and you are done,
the websocket Protokoll itself sends BIN data byte by byte, there are not data types in it.
if you need the BIN data in a format cast it, this is normal C/C++ programming.
with a TCP socket you will run in the exact same problem.

```cpp
void webSocketEvent(WStype_t type, uint8_t * payload, size_t length) {
    if(type == WStype_BIN) {
       USE_SERIAL.printf("[WSc] get binary length: %u\n", length);
       hexdump(payload, length);

       float * farray = (float *) payload;
       int elements = (length/sizeof(float));
       for( int i = 0; i < elements; i++ ) {
            float val = farray[i];
            USE_SERIAL.print(val);
            USE_SERIAL.println();
        }             
    }
}
```

**Comment by williamesp2015** [comment]
Thank you for  example on the ESP websocket client. I have problem with javascript to receive float32 bits using unsigned bytes binary array and convert it to float again on my HTML page using Javascript.

var buffer = new Uint8Array(message.data);
var dataview = new Float32Array(10);

**Comment by Links2004** [comment]
check out:
https://github.com/feross/buffer
it makes this very easy, works the same as in nodejs with buffer.

**Comment by royseberg** [comment]
Dear Links2004:
I'm trying to send an integer from a Wemos D1(ESP8266) as server using your library, to an Android client using OkHttpClient library, as you suggested, using sendBIN(num , buf , buf_len) as follows:

int i = 1234;
uint8_t * buf = (uint8_t *) &i;
size_t buf_len = sizeof(i);
sendBIN(num , buf , buf_len); // num is set to 0, which I believe is client # 0, n'est pas?

but what I get at the Android end, instead of 1234   I get        d2040000

The Android listener appears to be this:

    public void onMessage(WebSocket webSocket, ByteString bytes) {
        output("Received bytes : " + bytes.hex());
    }

and the result on the TextView output as I said is d2040000 instead of 1234 as sent

Can you clarify the confusion? (Thanks)

**Comment by Links2004** [comment]
@royseberg you habe a little vs big endian problem.

1234 in
UINT32 - Mid-Little Endian (CDAB) is 00 00 04 D2 (HEX)
UINT32 - Mid-Big Endian (BADC) is D2 04 00 00 (HEX)

you need to convert the data on one side if your two connected devices have not the same endian.
