### ISSUE TITLE
DEBUG_WEBSOCKETS not working when declared in *.ino (it worked in version 2.0.6)

### ISSUE THREAD

**Issue by mgbckr** [Links2004/arduinoWebSockets#214]
Hi,

since updating from version 2.0.6 to 2.0.7, declaring
```
#define DEBUG_WEBSOCKETS
#define DEBUG_WEBSOCKETS(...) Serial.printf( __VA_ARGS__ )
```
at the beginning of an `*.ino` sketch does not work anymore. How would I go about enabling debugging in 2.0.7 (besides editing the `WebSockets.h`)? 

Thanks in advance!

**Comment by Links2004** [comment]
declaring in ```*.ino``` file normally will never worked this is simple not how cpp works ;)
there is no need to edit if you at the latest git version.
simple enable the debug port in the Arduino IDE.

https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.rst#usage

**Comment by mgbckr** [comment]
Thanks for the info! I was using the board "NodeMCU 1.0 (ESP-13E Module)" which did not have that setting. I switched to the "Generic ESP8266 Module" as in the link you posted and changed the "Reset Method" from "ck"to "nodemcu" and now it works. It will give some debug from the WiFi as well which is not as nice as before, but this is fine for me.

For educational purposes: do you have an idea why using preprocessor statements works for 2.0.6 and not for 2.0.7?

**Comment by Links2004** [comment]
from a c++ / gcc stand point it can never has worked.
may the Arduino IDE has done some crazy stuff, that now is not done any more.
have you updated the IDE in between?

from 2.0.6 to 2.0.7 is no change on the debugging itself.
only:
```cpp
#ifdef DEBUG_ESP_PORT
#define DEBUG_WEBSOCKETS(...) DEBUG_ESP_PORT.printf( __VA_ARGS__ )
#else
//#define DEBUG_WEBSOCKETS(...) os_printf( __VA_ARGS__ )
#endif
```
has been added, which has no effect until you configure the Debug Port in the IDE.


if you use a real IDE you can add 
```
-DDEBUG_ESP_PORT=Serial
```
as compiler parameters.

not sure if its possible to define function macros via command parameters but if yes, something like this will activate debug only for websockets.
```
-DDEBUG_WEBSOCKETS(...)=Serial.printf(__VA_ARGS__)
```

if its not possible I can add a other define to as Alternative to `DEBUG_ESP_PORT`.
but you need to find a way to add compiler options.

**Comment by mgbckr** [comment]
Thanks for the detailed answer! 

I was fearing that it would be some Arduino IDE magic since I found no obvious reasons for the observed behavior in the diff, too :smirk: 

Well that's how it is then: either modifying `WebSockets.h` or using a "real" IDE :smile:
