### ISSUE TITLE
Possibility of connecting two ESP modules as a websocket client and server without connecting to the router using WiFiMulti.addAP

### ISSUE THREAD

**Issue by williamesp2015** [Links2004/arduinoWebSockets#217]
To connect an ESP32 as a websocket server to another ESP module (websocket client) we must connect to a router using SSID and password (WiFiMulti.addAP). Without internet can connect two modules?

**Comment by Links2004** [comment]
no, you can open an AP with one ESP and connect with the other, all that is needed is a network connection in between them.
having a router or the internet in between them is not needed.

**Comment by williamesp2015** [comment]
Does not connect without correct router SSID and Password.

**Comment by Links2004** [comment]
one ESP opens the AP:
```cpp
WiFi.softAP("ESPap",  "thereisnospoon");

IPAddress myIP = WiFi.softAPIP();
Serial.print("AP IP address: ");
Serial.println(myIP);
```
the other side connects.

```cpp
WiFiMulti.addAP("ESPap", "thereisnospoon");
```
use the ip shown as AP IP address in you WS client
