### ISSUE TITLE
Connecting to wss:// url

### ISSUE THREAD

**Issue by pburgio** [Links2004/arduinoWebSockets#218]
Hello I am trying to connect to a ws server whose url is not https://SOMETHNG, but rather wss://SOMETING

I tried to pass beginSSL("wss://SOMETING" to the API call, but he library doesn't seem to  connect. In the lib readme.md file it is specified

"wss / SSL
supported for:
wss client on the ESP8266"

so I'm certainly doing  something stupid?  Could you please support me?
Paolo

**Comment by Links2004** [comment]
`beginSSL` already indicates thats it is wss (https websocket)
you need:
```cpp
 webSocket.beginSSL("SOMETING", 443);
```
