### ISSUE TITLE
Desactivate debug print

### ISSUE THREAD

**Issue by AhmedX6** [Links2004/arduinoWebSockets#222]
Hello

Is there an easy wway to deactivate the debug print as it's very large and I can't really debug with it...

Thank you =)

**Comment by Links2004** [comment]
its is off by default, you get it off the same way you enabled it.
most likely via the IDE Debug port setting.

or commend this line:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L38

**Comment by Links2004** [comment]
in the latest git version you can set the `NODEBUG_WEBSOCKETS` define via compiler option to disable it too.
