### ISSUE TITLE
Ticker interrupt function causing random crashes.

### ISSUE THREAD

**Issue by Xhantorz** [Links2004/arduinoWebSockets#224]
My problem is pretty straight forward, I have 2 ESP-wrooms, one of them is the websocket server and the other is the client. When running Ticker interruption function at a frequency of 100ms on the esp with the server, the web socket server will randomly crash, WDT reset.  It's also running in WIFI_AP_STA mode. I'm running async mode on both. When I remove the ticker interruption, it works flawlessly. 
`Soft WDT reset

ctx: cont
sp: 3fff2fa0 end: 3fff3290 offset: 01b0

>>>stack>>>
3fff3150:  3fffa124 000005b3 3fffa934 401004d8
3fff3160:  3fffa124 000005b3 3fffa86c 3fffa934
3fff3170:  3fffa124 000005b3 3fffa934 4020920e
3fff3180:  3fff31c0 00000002 00000002 402092e6
3fff3190:  00000000 00000000 00000001 3fff2255
3fff31a0:  00000000 3fffdad0 3fff225c 00000002
3fff31b0:  00000000 00000000 00000000 402068d0
3fff31c0:  00000089 00000000 00000000 00000000
3fff31d0:  00000000 3fffdad0 3fff225c 00000030
3fff31e0:  00000000 3fff0f24 00000000 00000009
3fff31f0:  00000001 3fff17b4 3fff39b8 3ffe9858
3fff3200:  4021722a 3ffe8360 3fff39a0 00000000
3fff3210:  00000000 3fff0f24 3fff0eec 40205ebc
3fff3220:  00000001 00000000 00000000 00000000
3fff3230:  3ffe8f5c 5c01a8c0 3fff3210 3fff225c
3fff3240:  3fff0eec 3fff1308 00000001 4020da50
3fff3250:  3fffdad0 3fff2184 3fff133c 3fff225c
3fff3260:  3fffdad0 00000000 3fff2255 4020e025
3fff3270:  3fffdad0 00000000 3fff2255 4020232c
3fff3280:  feefeffe feefeffe 3fff2270 4020341c
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(1,6)

 ets Jan  8 2013,rst cause:4, boot mode:(1,6)

wdt reset
`

Decode:

Decoding 10 results
0x401004d8: malloc at ?? line ?
0x4020920e: AsyncTCPbuffer::_sendBuffer() at ?? line ?
0x402092e6: AsyncTCPbuffer::write(unsigned char const*, unsigned int) at ?? line ?
0x402068d0: WebSockets::sendFrame(WSclient_t*, WSopcode_t, unsigned char*, unsigned int, bool, bool, bool) at ?? line ?
0x4021722a: wifi_get_opmode at ?? line ?
0x40205ebc: WebSocketsServer::sendPing(unsigned char, unsigned char*, unsigned int) at ?? line ?
0x4020da50: WSHandler() at ?? line ?
0x4020e025: loop at ?? line ?
0x4020232c: loop_wrapper() at core_esp8266_main.cpp line ?
0x4020341c: cont_norm at cont.o line ?

**Comment by Links2004** [comment]
what do you do in the Interrupt?
from the first look i see 3 reasons:
1. you have to less free memory
2. may have a corrupted memory
3. you memory is highly fragmented

**Comment by Xhantorz** [comment]
In the function itself I just increment a variable.
void InteruptCallback(void){
  Interupt.InteruptCount ++;
}

I may have issues with memory, trying to slowly diagnose my issues.
