### ISSUE TITLE
opening websocketserver example gets 2 ino files

### ISSUE THREAD

**Issue by holla2040** [Links2004/arduinoWebSockets#225]
these 2 files are copied in a directory when saved
WebSocketServer.ino
WebSocketServerHttpHeaderValidation.ino

compiling the WebSocketServer example now fails with multiple references to several items.

using arduino 1.8.2
ubuntu 16.04 x64

**Comment by Links2004** [comment]
can you try latest git?
I think i fixed this there with cc3ce02c670563d039a769dd72703a0976887862

**Comment by holla2040** [comment]
OK, if install websockets with 1.8.2's library manager, I get version 2.0.6, which when I open the websocketserver example, I get 2 ino files.

So I remove that by deleting libraries/WebSockets

git clone https://github.com/Links2004/arduinoWebSockets.git in the libraries directory
mv arduinoWebSockets/ WebSockets

holla@hendrix[544]: pwd
/home/holla/Arduino/libraries
holla@hendrix[545]: ls WebSockets/examples/WebSocketServer
WebSocketServer.ino

which is correct

open the WebSocketServer example and it compiles.

So I guess the library manager is downloading an older version? I don't know how arduino's library manager works with versioning and github's version. 

Hope this helps.

**Comment by Links2004** [comment]
The library manager gets the latest release version (2.0.6), 
2.0.7 is not released yet, but it will be soon to get this fix out.

The library manager looks at the releases:
https://github.com/Links2004/arduinoWebSockets/releases

**Comment by Links2004** [comment]
2.0.7 is now released

**Comment by holla2040** [comment]
Thanks! 2.0.7 installed over here. websocketserver example compiles without issue.
