### ISSUE TITLE
two way comunication?

### ISSUE THREAD

**Issue by Azuzula** [Links2004/arduinoWebSockets#227]
Hello,
Im sorry for my english and stupid question.
My knowledge of javascript and web languages generally is poor, I can slightly modify code for my needs. Thats all.

I have Wemos D1 mini for my home automation and modified your code for websocket server led control. I can get data from javascript sliders and buttons to the wemos and use them for operate lights and dim led strips, it works after two days try and error.

Anyway I realy don't know how to push data (temp, lights state etc.) into web page without reload. 
Next step is if I open same web page from wemos at the two computers and move slider on one of them, then same slider move at the second computer. Is this possible? And if so, how?

Thank you for your help and time.

**Comment by Links2004** [comment]
yes you can push data over the websocket that is the main reason it where developed.
syncing multible clients is possible with pushing the LED status too.

on the ESP side you can call
`webSocket.broadcastTXT("temp:10");`
or
`webSocket.broadcastTXT("led:#ff00ff");`
any time you like, to send the info to any connected client.

then you need to Interpreter this on the Javascript side.

may something like this:
```js
        connection.onmessage = function(e) {
            // here you will get the messages you send with broadcastTXT
            console.log('Server: ', e.data);
            res = e.data.split(":");
            var val = res[1];
            switch(res[0]) {
                 case 'led':
                       // do something with val
                       break;
                 case 'temp':
                       // do something with val
                       break;
            }
        };
```

for more complex task you may consider using JSON.

**Comment by Azuzula** [comment]
I understand to it now. It is working like a charm :)
Here is short [video on youtube](https://youtu.be/dfMj15qposs) how its work.
Thank you.

**Comment by Links2004** [comment]
nice
