### ISSUE TITLE
Error compiling "WebSocketServer.ino"  example for esp8266 Wemos D1 Mini

### ISSUE THREAD

**Issue by dmurias** [Links2004/arduinoWebSockets#228]
Help! I get the error message below.
What I'm doing wrong?
Tks.
```
**********************************************************************************************************
In file included from C:\Users\Diego\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src/ESP8266WiFi.h:39:0,

                 from D:\Documentos\Arduino\libraries\WebSockets\src\WebSockets.h:118,

                 from D:\Documentos\Arduino\libraries\WebSockets\src\WebSockets.cpp:25:

C:\Users\Diego\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src/WiFiClient.h: In instantiation of 'size_t WiFiClient::write(T&, size_t) [with T = unsigned char*; size_t = unsigned int]':

D:\Documentos\Arduino\libraries\WebSockets\src\WebSockets.cpp:627:34:   required from here

C:\Users\Diego\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src/WiFiClient.h:123:36: error: request for member 'available' in 'source', which is of non-class type 'unsigned char*'

     size_t left = source.available();

                                    ^

C:\Users\Diego\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src/WiFiClient.h:127:5: error: request for member 'read' in 'source', which is of non-class type 'unsigned char*'

     source.read(buffer.get(), will_send);

     ^

exit status 1
Error compilando para la tarjeta WeMos D1 R2 & mini.

```

**Comment by Links2004** [comment]
hard to say, 
can you post your code?

**Comment by PeterZ99** [comment]
Same problem here with compiling from Demo from WebSocketServer_LEDcontrol.ino on IDE 1.8.3 and 1.6.4

Arduino: 1.8.3 (Windows 7), Board:"NodeMCU 1.0 (ESP-12E Module), 80 MHz, 115200, 4M (3M SPIFFS)"

In file included from C:\Users\hp\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src/ESP8266WiFi.h:39:0,

                 from C:\Users\hp\Documents\Arduino\libraries\WebSockets\src\WebSockets.h:118,

                 from C:\Users\hp\Documents\Arduino\libraries\WebSockets\src\WebSockets.cpp:25:

C:\Users\hp\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src/WiFiClient.h: In instantiation of 'size_t WiFiClient::write(T&, size_t) [with T = unsigned char*; size_t = unsigned int]':

C:\Users\hp\Documents\Arduino\libraries\WebSockets\src\WebSockets.cpp:627:34:   required from here

C:\Users\hp\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src/WiFiClient.h:123:36: error: request for member 'available' in 'source', which is of non-class type 'unsigned char*'

     size_t left = source.available();

                                    ^

C:\Users\hp\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src/WiFiClient.h:127:5: error: request for member 'read' in 'source', which is of non-class type 'unsigned char*'

     source.read(buffer.get(), will_send);

     ^

exit status 1
Fout bij het compileren van board NodeMCU 1.0 (ESP-12E Module)

**Comment by Links2004** [comment]
strange have a 1.8.1 IDE here and the examples compile fine.

travis tries to compile every example too, without no fail.
https://travis-ci.org/Links2004/arduinoWebSockets

may its windows specific, or only happens with esp8266 v2.3.0 (I am at the lastest git right now)

**Comment by PeterZ99** [comment]
I just installed on new Windows7 pro hp laptop (32Bits) with the last Arduino IDE for be sure there is not a problem on my pc(also W7 Pro but have IDE 1.6.10)), after then i go to library to download WebSocket and try to compile the example WebSocketServer_LEDcontrol.ino and no changes make.. but the error i get is still the same. 

I realy dont know why i get the error now..

**Comment by dmurias** [comment]
I used the code of "WebSocketServer_Ledcontrol. ino" unchanged, (except for sssid & password)
I downloaded the level of the WebSockets Library from 2.0.8 to 1.3.0 (AVR) and the problem has been solved. Compile correctly without errors
Can that be the problem?
Thanks to all

**Comment by Links2004** [comment]
ok looks like I need to setup one of my old PCs with windows to test this.

can you try to use the esp8266 2.4.0-rc1 
https://github.com/esp8266/Arduino/releases/tag/2.4.0-rc1

**Comment by dmurias** [comment]
Ok.

**Comment by PeterZ99** [comment]
I test it with the old Library 1.3.0 and works like as before.. thanks **dmurias**.. 

Thanks

IDE 1.6.10 and WebSocket 1.3.0 is working with esp8266 v2.3.0

**Comment by Links2004** [comment]
have a solution for newest version, 
looks like the windows compiler makes a mistake at Template handling.

**Comment by dmurias** [comment]
My Arduino.ide (1.8.3) tells me that "Arduino-2.4.0-RC1.zip" is not a valid library.....

**Comment by Links2004** [comment]
version 2.0.9 is released, 

Arduino-2.4.0-RC1.zip is not a library, its the ESP8266 core.

https://github.com/Links2004/arduinoWebSockets/releases/tag/2.0.9
will fixe it, not sure how fast the Arduino IDE gets the update but sure soon.

**Comment by PeterZ99** [comment]
Just updated to 2.0.9. and works on my W7 Pro 32b with IDE 1.6.10 and esp8266.

Thanks for this nice work again.

Regards,
Peter

**Comment by dmurias** [comment]
Hi Markus!
WebSockedClient and WebSocketsServer examples compiling without error whith  version https://github.com/Links2004/arduinoWebSockets/releases/tag/2.0.9
tks
Diego

**Comment by Links2004** [comment]
good to hear.
may I can configure travis to do the compile testing with windows and linux.
