### ISSUE TITLE
Allow to use IP address in WebSocketsClient::begin

### ISSUE THREAD

**Issue by me21** [Links2004/arduinoWebSockets#230]
Currently it accepts only host name or IP address in string form. For completeness, it would be nice to accept IP address in binary form (IPaddress type).

**Comment by tonton81** [comment]
These work, hope they help:

webSocketClient.begin(IPAddress(192,168,2,28).toString().c_str(),81);
webSocketClient.begin(IPAddress(192,168,2,28).toString(),81);

Tony

**Comment by tonton81** [comment]
Current Library methods:
void begin(const char *host, uint16_t port, const char * url = "/", const char * protocol = "arduino");
void begin(String host, uint16_t port, String url = "/", String protocol = "arduino");

Suggest a single line addition to the H file, no other changes, just below the above methods:

void begin(IPAddress host, uint16_t port, const char * url = "/", const char * protocol = "arduino"); { return begin(host.toString().c_str(), port, url, protocol; }

**Comment by tonton81** [comment]
That will give you the ability to do this:

IPAddress myServer = { 192,168,2,122 };
webSocket.begin(myServer, 81);

OR:

webSocket.begin(IPAddress(192,168,2,122),81);

Tony
