### ISSUE TITLE
Function: No such file or directory

### ISSUE THREAD

**Issue by DeltaBro** [Links2004/arduinoWebSockets#232]
In WebSockets.h an error is thrown for #include <functional> because functional doesn't exist.

**Comment by Links2004** [comment]
which board and what version of the websockets lib are you using?

**Comment by ingrocha** [comment]
I'm having the same problem:

```
Arduino:1.8.3 (Windows 8), Tarjeta:"Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from C:\Program Files (x86)\Arduino\libraries\arduinoWebSockets\src/WebSocketsClient.h:28:0,

                 from G:\Usuario\Documents\Arduino\websocket_V2\websocket_V2.ino:8:

C:\Program Files (x86)\Arduino\libraries\arduinoWebSockets\src/WebSockets.h:35:22: fatal error: functional: No such file or directory

 #include <functional>

                      ^

compilation terminated.

exit status 1
Error compilando para la tarjeta Arduino/Genuino Mega or Mega 2560.

Este reporte podría tener más información con
"Mostrar salida detallada durante la compilación"
opción habilitada en Archivo -> Preferencias.

```

**Comment by toMyLord** [comment]
WebSockets.h:35:22: fatal error: functional: No such file or directory
 #include <functional>
                      ^
compilation terminated.

Tarjeta : Seeeduino V4(Atmega328P)

Where can I find it?

**Comment by toMyLord** [comment]
```
WebSockets.h:35:22: fatal error: functional: No such file or directory
 #include <functional>
                      ^
compilation terminated.
```
tarjeta:Seeeduino V4(Atmega328P)
emmm，Could you tell me where can i find <functional>.

**Comment by toMyLord** [comment]
Maybe I need the old version（1.3）

**Comment by Links2004** [comment]
yes for AVR you need the ATmega branch 
https://github.com/Links2004/arduinoWebSockets/tree/ATmega

latest release is 1.4
https://github.com/Links2004/arduinoWebSockets/releases/tag/1.4
