### ISSUE TITLE
Please suggest how i can connect websocket client with token in header to server (ESP8266)

### ISSUE THREAD

**Issue by aatronics** [Links2004/arduinoWebSockets#233]
In my ESP8266 application, i would like to connect web socket server, but while connecting i need to send token (already generated JSON token) in header. When i tried to connect without token it will diffuse connection. Please suggest me any solution so I can connect my esp8266 with websocket server (How i can add token in header of websocket client)

Please suggest any example program.

Hardware : ESP8266 
Programming : using arduino IDE

Thanking you

**Comment by Links2004** [comment]
```setExtraHeaders``` will help you.
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.h#L84
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.cpp#L513

you can add anything you like to the header with it.

**Comment by mrdsn3** [comment]
I have same problem  can anyone help me? how to connect web socket server, while connecting I need to send token (already generated JSON token) in header.

**Comment by ahmadmuazam0** [comment]
> `setExtraHeaders` will help you. https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.h#L84 https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.cpp#L513
> 
> you can add anything you like to the header with it.

It still can't connect to the websocket. Handshake is not happening.

**Comment by ahmadmuazam0** [comment]
`websocket.begin(host,80,URL);'
No I need to send a token in header to connect with it. Can anyone tell how to do that ?
