### ISSUE TITLE
Disconnects without realising it

### ISSUE THREAD

**Issue by jLynx** [Links2004/arduinoWebSockets#237]
So first off my code sends a string of text to the server, the server then sends a response back. It does this for everything sent to it. The server is running with Node.js.

What is happening is that that after a random amount of time. Could be 2 minutes or 2 hours (from my days of testing) is that the Node MCU client disconnects from the server without the server or client releasing. The reason I say this is because when I check the Node.js server logs, it has not received any data from the client and then checking back with the console logs from the Node MCU client it has not received any response. So I am taking this has that it has disconnected from the server without either realising. 
(Please note I have done some other testing where I send another lot of "sendTXT" data once this supposed "disconnect" has happened and it still doesn't receive it. 

So for the moment as a temporary fix I am just having the Node MCU restart and then it connects up fine and this whole process above will repeat at a random interval.

Here is the log so you can see what has happened.

```
===== ConnectedCar =====
Connecting.................................................................................................
[INFO] Connected!
[WSc] get text: {"vol":"12.50","lat":"****590","lon":"****859","speed":"0.00","datetime":"09/13/2017 22:10:53","satellites":"8","altitude":"84.50"}
[WSc] get text: Welcome
[WSc] get text: CONNECTED FROM NODEMCU!!!

[INFO] Send function started
[DEBUG] Part 1
[INFO] sprintf time taken: 15614
[DEBUG] Part 2
[DEBUG] Part 3
[WSc] get text: {"vol":"12.50","lat":"****616","lon":"****828","speed":"0.00","datetime":"09/13/2017 22:11:12","satellites":"8","altitude":"81.20"}
[WSc] get text: Updated Data

[INFO] Send function started
[DEBUG] Part 1
[INFO] sprintf time taken: 17649
[DEBUG] Part 2
[DEBUG] Part 3
[WSc] get text: {"vol":"12.50","lat":"****620","lon":"****828","speed":"0.00","datetime":"09/13/2017 22:11:22","satellites":"8","altitude":"80.90"}
[WSc] get text: Updated Data

[INFO] Send function started
[DEBUG] Part 1
[INFO] sprintf time taken: 14606
[DEBUG] Part 2
[DEBUG] Part 3
[WSc] get text: {"vol":"12.50","lat":"****628","lon":"****828","speed":"0.00","datetime":"09/13/2017 22:11:32","satellites":"8","altitude":"79.20"}
[WSc] get text: Updated Data

[INFO] Send function started
[DEBUG] Part 1
[INFO] sprintf time taken: 15648
[DEBUG] Part 2
[DEBUG] Part 3
[WSc] get text: {"vol":"12.50","lat":"****620","lon":"****828","speed":"0.00","datetime":"09/13/2017 22:11:42","satellites":"8","altitude":"80.80"}
[WSc] get text: Updated Data

[INFO] Send function started
[DEBUG] Part 1
[INFO] sprintf time taken: 17684
[DEBUG] Part 2
[DEBUG] Part 3
[WSc] get text: {"vol":"12.50","lat":"****620","lon":"****813","speed":"0.00","datetime":"09/13/2017 22:11:52","satellites":"8","altitude":"81.10"}
[WSc] get text: Updated Data

[INFO] Send function started
[DEBUG] Part 1
[INFO] sprintf time taken: 15624
[DEBUG] Part 2
[DEBUG] Part 3
[WSc] get text: {"vol":"12.50","lat":"****609","lon":"****828","speed":"0.00","datetime":"09/13/2017 22:12:02","satellites":"7","altitude":"83.10"}
[WSc] get text: Updated Data

[INFO] Send function started
[DEBUG] Part 1
[INFO] sprintf time taken: 15584
[DEBUG] Part 2
[DEBUG] Part 3
[ERROR] Possibly disconnected - (I added a check to see if it got a response from the server before it sent its next lot of text, since it didn't, It restarts as a hacky way to reconnect)
[INFO] Restarting to fix..this is a temp fix

```

Here is the code that I am running for this:
https://gist.github.com/jLynx/13ac25e650ff1bd2f577757b239b6408

I am running the latest GitHub code for arduinoWebSockets.
Running on a Node MCU ESP8266
The GPS lib I am using is TinyGPS

**Comment by Links2004** [comment]
the disconnect can only be detected if you send data to the other side.
for a short message you can use "ping".

as soon a Disconnect is detected the lib will reconnect automatically on a 
```webSocket.loop();```
call.

the Interval of reconnect tries is configured with:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.h#L86

the ```send``` functions have a return value that indicates if the frame is send ( for the async version it only indicates that the data is put in the TX buffer) 

Note:
the need to send to detect a disconnect is a limitation of the the TCP stack.

**Comment by jLynx** [comment]
Thanks for the reply. Do you have any idea why it would be disconnecting?

**Comment by Links2004** [comment]
there are multible reasons why this can happens

- other side close the connection (without sending a close opcode)
- WiFi is unstable  
- WiFi has gone to sleep (where more of a Problem in older SDK versions dont have seen it in the newer on's)

you can give:

```cpp
WiFi.setSleepMode(WIFI_NONE_SLEEP);
```
a try

for checking the WiFi events you can use:

```cpp
void WiFiEvent(WiFiEvent_t event) {
	Serial.printf("[WiFi-event] event: %d\n", event);
}

void setup() {
	WiFi.onEvent(WiFiEvent);
}
```


Note:
    for forcing a reconnect you can use ```disconnect()```

**Comment by jLynx** [comment]
Alright So I have changed the code up a bit, you can see the updated parts here: https://gist.github.com/jLynx/1503d8ab61a54ff8400856e12e825b4f

Here is the console log from the latest version

```
[INFO] Send function started
[INFO] sprintf time taken: 16629
[INFO] Data sent to server fine!
[WSc] get text: {"vol":"0.00","lat":"****670","lon":"****783","speed":"0.00","datetime":"09/16/2017 00:02:05","satellites":"8","altitude":"66.90"}
[WSc] get text: Updated Data

[INFO] Send function started
[INFO] sprintf time taken: 15590
[INFO] Data sent to server fine!
[WSc] get text: {"vol":"0.00","lat":"****670","lon":"****783","speed":"0.00","datetime":"09/16/2017 00:02:15","satellites":"8","altitude":"67.00"}
[WSc] get text: Updated Data

[INFO] Send function started
[INFO] sprintf time taken: 14588
[ERROR] Data not sent to server.. :( ==============================================================
[WSc] ====Disconnected!====
[INFO] Server disconnected. Should attempt a reconnect in 1 second
[WSc] ====Disconnected!====
[INFO] Server disconnected. Should attempt a reconnect in 1 second
[WSc] ====Disconnected!====
[INFO] Server disconnected. Should attempt a reconnect in 1 second
[WSc] ====Disconnected!====
[INFO] Server disconnected. Should attempt a reconnect in 1 second
[WSc] ====Disconnected!====
[INFO] Server disconnected. Should attempt a reconnect in 1 second

```

As you can see once the data did not send to the server, I forced it to disconnect so it can reconnect but it won't reconnect. it did that disconnect message about another 80 times before I stopped the test.
When I pressed the reset button on the NodeMCU it rebooted and connected right away the first time. So my question is, why does this not reconnect?

For reference, this is the current code for the Node.js server: https://gist.github.com/jLynx/27ec5190afadb2d976f4c17f705d42e7

**Comment by CyanoFresh** [comment]
Same issue. No responses after ~50 minutes of connection. Tried with php (ratchet php lib), nodejs.

**Comment by jLynx** [comment]
Any update?

**Comment by jLynx** [comment]
@Links2004  bump

**Comment by CyanoFresh** [comment]
I've noticed that it doesn't depend on library. I've tried others but have same problem. Maybe it's tcp/ws protocol/router related. Switching to MQTT solves the problem

**Comment by jLynx** [comment]
Funny you should say that, I actually just switched to MQTT last night. I would love to switch back, but until this this is fixed, I can't

**Comment by Links2004** [comment]
is the connection idle for 40min or is there a ping or data running?
the ESP WiFi goes to sleep is there is a long time no data send or received.
this has proven to kill the connection.

if a more power consumption is not a problem you can try:
```cpp
WiFi.setSleepMode(NONE_SLEEP_T);
```

or use the ```ws.sendPing()``` command to send data periodically.

**Comment by jLynx** [comment]
I'm making a request every 30 seconds. I have made made sure the esp isn't going to sleep. I also tried on both a 32 and 8266 with the same issue.
Do you think I need to send a ping even though I'm sending every 30 sec?

**Comment by CyanoFresh** [comment]
Same, sending data every 1 minute

**Comment by Links2004** [comment]
every 1 minute shut be fine.

does the ws reconnect after the disconnect or is it dead for ever?
at least the next sending must detect in the TCP layer of the ESP (lwip) that the connection is dead,
which ends up in a reconnect.

**Comment by jLynx** [comment]
It's dead forever. My work around is restarting the esp when I manually detect that it failed

**Comment by jLynx** [comment]
Also I tried to force reconnect, but that didn't work, hence why I restart the esp

**Comment by CyanoFresh** [comment]
Just dead. I don't have experience with packet dumping to check if packet is sent

**Comment by Links2004** [comment]
wow, then the lwip Network stack has a problem.

the connection state of lwip is checked in the loop:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.cpp#L126

which ends up here:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.cpp#L394

if the function / lwip stack reports that the connection is dead then the reconnect happens here:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.cpp#L159

only possible problem on library level that i can think of is a overflow problem here:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.cpp#L128

but this is more near ~49.7 days

**Comment by jLynx** [comment]
If you want I could privately send you my exact code so you can see the issue in action?

**Comment by Links2004** [comment]
have multibel ESPs running here with the lib, but have never seen this.
but they mostly running on a older esp arduino core (with a older lwip).

can you try to reproduce the Issue with a plain TCP socket?
a simple ping pong code is good for testing this.
then we know where we need to search, if this is happening with plain TCP we can open a bug in esp8266/arduino

**Comment by jLynx** [comment]
@Links2004 do you have some example code that I could use for this?

**Comment by Links2004** [comment]
not teste but for the ESP more or less:

```cpp
/*
    This sketch sends a message to a TCP server
*/

#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>

ESP8266WiFiMulti WiFiMulti;

  // Use WiFiClient class to create TCP connections
  WiFiClient client;

void setup() {
  Serial.begin(115200);
  delay(10);

  // We start by connecting to a WiFi network
  WiFi.mode(WIFI_STA);
  WiFiMulti.addAP("SSID", "passpasspass");

  Serial.println();
  Serial.println();
  Serial.print("Wait for WiFi... ");

  while (WiFiMulti.run() != WL_CONNECTED) {
    Serial.print(".");
    delay(500);
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());

  delay(500);

const uint16_t port = 2222;
  const char * host = "192.168.1.1"; // ip or dns

  Serial.print("connecting to ");
  Serial.println(host);

while(1) {
  if (!client.connect(host, port)) {
    Serial.println("connection failed");
    Serial.println("wait 5 sec...");
    delay(5000);
  } else {
break;
}

}


void loop() {
  
if(!client.connected()) {
  Serial.println("lwip has reported disconnect");
} else {
  Serial.println("Send data...");
  // This will send the request to the server
  client.println("Send this data to server");
  //read back one line from server
 Serial.println("Read data...");
  String line = client.readStringUntil('\r');
  Serial.println(line);

  delay(1000);
}
}
```

on the server side you can use:

```
ncat -l 2222  --keep-open --exec "/bin/cat"
```
this is for linux.
what you need on the server side is a echo server.

If we are correct the ESP will stop printing lines at some point.
