### ISSUE TITLE
Connect client to local server

### ISSUE THREAD

**Issue by msieverding** [Links2004/arduinoWebSockets#239]
Is there any way to connect a client to a local server?
Just connect to 127.0.0.1 does not work on my ESP8266.

**Comment by Links2004** [comment]
127.0.0.1 is the localhost address, most likely you need a other address.

is the "local server" on the ESP?
if its on your local Network you need you local IP most likely something like 192.168.xxx.yyy.

**Comment by msieverding** [comment]
Yes, with "local server" I was talking about a WebSocketServer on the same ESP8266.
Connecting to a WebSocketClient on another ESP8266 with the correct IP address is no problem.

**Comment by Links2004** [comment]
ok, I dont think the TCP stack on the ESP supports this.
can you describe the use cases for this?

you can register a "dummy" client and server as network interface and link them together.
this is something I have on the long term todo for some blackbox testing on travis.

**Comment by msieverding** [comment]
I have a server/client architecture for an engineering application. Every client controlls an engine with commands from the server. The server is also an ESP and has also one engine. So the idea was to use the same client code on the server instead of a different non-remote client solution. Would make some things easier :)
(The communication overhead is known and would be no problem for me ;) )

**Comment by Links2004** [comment]
may the easiest way will be simply calling the callback manually.
something like:

```cpp
void webSocketEvent_client(WStype_t type, uint8_t * payload, size_t length) {
.....
}

void broadcastTXT(char * payload){
    webSocketEvent_client(WStype_TEXT, (uint8_t *)payload, strlen(payload));
    server.broadcastTXT(payload);
}

void sendTXT(uint8_t num, char * payload){
    if(num == WEBSOCKETS_SERVER_CLIENT_MAX) {
        webSocketEvent_client(WStype_TEXT, (uint8_t *)payload, strlen(payload));
    } else {
        server.sendTXT(num, payload);
    }
}
```

this way the overhead will be near to nothing ;)

**Comment by msieverding** [comment]
Yes, sure. But than it's not a WebSocketClient anymore :)

But when the TCP stack doesn't support connections to itself, it's not possible..

**Comment by Links2004** [comment]
loopback is disabled in lwip:
https://github.com/esp8266/Arduino/blob/4897e0006b5b0123a2fa31f67b14a3fff65ce561/tools/sdk/lwip/include/lwipopts.h#L1206
http://www.nongnu.org/lwip/2_0_x/group__lwip__opts__loop.html

but from reading the docu its possible that a "loopback" is possible when you use the WiFi IP.

**Comment by msieverding** [comment]
Thanks. I tried with the IP address from the interface without success.
Also changing the switches 'LWIP_NETIF_LOOPBACK' and 'LWIP_HAVE_LOOPIF' to 1 before compiling it doesn't help.

I implemented another solution this week.
Thanks for your help. I think we can close this issue, since it's not an issue of this library :)
