### ISSUE TITLE
Unable to compile examples with ESP Arduino v2.0.0

### ISSUE THREAD

**Issue by ashthespy** [Links2004/arduinoWebSockets#24]
I seem to be unable to compile any of the examples with v2.0.0. The error I get is

    \Arduino\libraries\arduinoWebSockets\src\WebSockets.cpp:28:35: fatal error:core_esp8266_features.h: No such file or directory  #include <core_esp8266_features.h>
                                
I am a bit new to git, so I am using this library with Arduino 1.6.5 along with the board manager. 
But according to commit 92a63e9129f2a4f8c5a0e4372736f9a95a2004d9, it should work right?

**Comment by Links2004** [comment]
the ESP core itself needs an update to, but this update is not released via board manager yet.
you can follow this:
https://github.com/esp8266/Arduino#using-git-version-
to get the latest core, then It will work again.

**Comment by ashthespy** [comment]
I initially tried manually including `core_esp8266_features.h` and the `lib64` folder contents, gave up and then used the current git version.

All is good now :)
