### ISSUE TITLE
Problem with broadcastPing - always returns true

### ISSUE THREAD

**Issue by philbowles** [Links2004/arduinoWebSockets#242]
I am trying to reduce heap usage as a result of the problem you identified for me earlier (issue #241). I have an issue with lack of notifications when a client disconnects (e.g. netwrok failure). I am trying to resolve this by pinging the client on a timer and then freeing up resources when the client disappears for whatever reason.

I have a 1-second timer that calls broadcastPing() [no params] , but it returns 'true' every time, no matter the status of the client(s) or browser - even when the browser is closed...

If I change my timer to sendPing(0) [ with only one client connected ] it works exactly as expected, returning 0 when the client goes away and 1 when present. I also receive the connect/disconnect events correctly in both cases, but I would like to be able to detect the case when the client disappears and these events do not occur - without broadcastPing() working as expected, I can't see how to do this.

I have looked at the code and it doesn't look right to me - unless I have missed something:

```cpp
bool WebSocketsServer::broadcastPing(uint8_t * payload, size_t length) {
    WSclient_t * client;
    bool ret = true;
    for(uint8_t i = 0; i < WEBSOCKETS_SERVER_CLIENT_MAX; i++) {
        client = &_clients[i];
        if(clientIsConnected(client)) {
            if(!sendFrame(client, WSop_ping, payload, length)) {
                ret = false;
            }
        }
#if (WEBSOCKETS_NETWORK_TYPE == NETWORK_ESP8266)
        delay(0);
#endif
    }
    return ret;
}
```

ret never gets set true if there are no clients, only if there appear to be, but one or more doesn't send a reply frame. Shouldn't the broadcast return false if no clients are connected?

Doesn't it make more sense to invert the logic thus:

```cpp
bool WebSocketsServer::broadcastPing(uint8_t * payload, size_t length) {
    WSclient_t * client;
    bool ret = false;
    for(uint8_t i = 0; i < WEBSOCKETS_SERVER_CLIENT_MAX; i++) {
        client = &_clients[i];
        if(clientIsConnected(client)) {
            if(sendFrame(client, WSop_ping, payload, length)) {
                ret = true;
            }
        }
#if (WEBSOCKETS_NETWORK_TYPE == NETWORK_ESP8266)
        delay(0);
#endif
    }
    return ret;
}
```

to return false unless at least one client replies?

When I use the modified code, it works exactly as I expected (i.e. same us using sendPing(0);)

Am I missing something?

**Comment by Links2004** [comment]
the return value of `broadcastPing` indicates if the command where executed successfully.
if no client is connected the command run still is successful.
changing the return logic will break existing code that is out there.

I think for your use case its better to ping each client on your own.
more or less:
```
bool someone_connected = false;
  for(uint8_t i = 0; i < WEBSOCKETS_SERVER_CLIENT_MAX; i++) {
        if(ws.sendPing(i)) {
                someone_connected = true;
        }
    }
```

**Comment by philbowles** [comment]
Thanks for the reply. For me, this is counterintuitive as the behaviour is different from sendPing but both routines have the comment " * @return true if ping is send out"...but only sendPing returns false if the pign is not replied to. Given that the ping appears to be successfully sent out even when no client exists, I cannot see any use for this function. Surely having the ping RETURNED is the important thing for a "ping" - in fact is this not its ONLY purpose? To me, "ping" suggests a way to test if clients are alive, so I find this confusing.

However, I shall take your advice and use the code you suggested, since I imagined that this was broadcastPing should have done anyway.

Can we add the suggested code to the API as "anyClientsAlive" or similar?

**Comment by Links2004** [comment]
may a ```int connectedClients()``` is a good idea this way its possible to get the number of connected clients too.
