### ISSUE TITLE
WebSocketsServer is not initialized correctly by the constructor and the desctructor crashes

### ISSUE THREAD

**Issue by baggior** [Links2004/arduinoWebSockets#244]
There is an evident bug if you you create a WebSocketsServer and the destroy it without calling begin() the destructor crashes in method disconnect() because client array is not conrrectly initialized

Solution:
in the WebSocketsServer constructor call begin()

**Comment by Links2004** [comment]
can you provide the Stacktrace?

calling begin in the constructor can easy end up to some strange problems since the socket is bind there.
but the constructor my is called before the network stack is ready.

this sure can be fixed a other way the calling begin.
may memset
```cpp
memset(&_clients[0], 0x00, (sizeof(WSclient_t)*WEBSOCKETS_SERVER_CLIENT_MAX));
```
will do the jop already.

**Comment by baggior** [comment]
yes is a good solution
i'll try with memset and let see what happens

**Comment by baggior** [comment]
OK I confirm
IT works
so please can you can add the line 
`memset(&_clients[0], 0x00, (sizeof(WSclient_t)*WEBSOCKETS_SERVER_CLIENT_MAX));`

just at the end of the WebSocketsServer constructor and commit changes?

**Comment by Links2004** [comment]
sure, done
