### ISSUE TITLE
Error while compiling 

### ISSUE THREAD

**Issue by romuye123** [Links2004/arduinoWebSockets#246]
/Hexfiles/WebSockets/WebSocketsServer.cpp.o:(.rodata._ZTV16WebSocketsServer[vtable for WebSocketsServer]+0x14): undefined reference to `WebSockets::write(WSclient_t*, unsigned char*, unsigned int)'
collect2: error: ld returned 1 exit status

**Comment by Links2004** [comment]
which version shows this error?
what IDE / OS do you using?
