### ISSUE TITLE
ESP8266 Websocket server not accepting more than 4 connections.

### ISSUE THREAD

**Issue by romuye123** [Links2004/arduinoWebSockets#247]
case WStype_CONNECTED:
        {
                IPAddress ip = webSocketServer.remoteIP(num);
                Serial.printf("[%u]SERVER: Connected !!! %d.%d.%d.%d \n", num, ip[0], ip[1], ip[2], ip[3]);
        }

Following is the output for first 4 connections.

[0]SERVER: Connected !!! 192.168.x.x
[1]SERVER: Connected !!! 192.168.x.x
[2]SERVER: Connected !!! 192.168.x.x
[3]SERVER: Connected !!! 192.168.x.x

I have set the max number of connections as **20** in **WebSocketsServer.h**

1) For the 5th connection i get disconnected or timed out. why so ?

2) How to handle multiple connections from the same incoming client ?

**Comment by Links2004** [comment]
20 is way over what the ESP network stack can handle.

how many are possible is on the memory location 0x600011FC
https://github.com/esp8266/Arduino/blob/4897e0006b5b0123a2fa31f67b14a3fff65ce561/tools/sdk/lwip/include/lwipopts.h#L247

last time I checked the max where 6.
not sure if you have other connetions or sockets open in you code but most likely you have two other sockets (the 4 ws not included) open.

**Comment by romuye123** [comment]
Thanks for your quick reply @Links2004.

In my example i have initialized **Websocket server and websocket client** as well, so client becomes 1 connection and server takes not more than 4 connections.
1) is it the case why i am unable to connect more than 4 connections ?
If i run simple websocket server example from your source i can connect max 5 clients to it.

2) What should be the ideal way if more than 5 people wants to take control of ESP? 
Websockets or TCP or UDP or anything else?

**Comment by romuye123** [comment]
How to disconnect all earlier connections if it reaches max number of connections ? 
This might be the way to handle the situation right ?

**Comment by Links2004** [comment]
Websockets and TCP share the same limitation since the Websockets use TCP ;)

6 TCP sockets max:
1x ws server socket (handles Incoming connections)
4x ws server clients
1x ws client

if you setup Constantins more then the ESP, some RPI or other server you can connect like this:

many clients <---WS---> websocket server on server <---WS---> ESP

the server needs to do some simple aggregation of the connections.
this can easy be achieved in nodejs for example.

alternative you can use UDP multicasts, that way you can connect many more clients.
but this is not possible from the browser.

**Comment by romuye123** [comment]
Hi @Links2004,
```
the server needs to do some simple aggregation of the connections.
this can easy be achieved in nodejs for example.
```
will you please help on above point in more detail, would like to understand how it works.

**Comment by Links2004** [comment]
you need a little server for this, a RPI zero w can handle this task easy for example.
(more or less any "pc" / Linux type board can handle this)

the connection will work like this:

- your RPI opens a WiFi AP
- the ESP connects via WiFi to it.
- the Browser clients connects via WiFi to the RPI.

1. all browser connect to RPI via WS
2. the RPI connects once to the ESP via WS
3. all commands are proxied via the RPI

by doing this you can connect as many clients as you need, but i will cost you additional hardware.
A rpi zero w is cheap s no big costs there.

if you not need to have this setup Portable, you can use you Local WiFi there is no need to open a new AP ;)

**Comment by karanmakharia** [comment]
@Links2004 @romuye123 Can you please elaborate on how to have multiple connections to ESP having WebSocket server. In my case there are 3-4 clients trying to connect to single ESP at the same time to exchange data. Can I have 3-4 parallel connections with ESP without having need to create 3-4 AP as my ESP and 3-4 clients are connected to same wifi connection

**Comment by farsajik** [comment]
He .how many paralell websocket connections can handle esp32 websocket server?
