### ISSUE TITLE
ESP8266 Websocket server crashes when client disconnects

### ISSUE THREAD

**Issue by moelha** [Links2004/arduinoWebSockets#248]
I have the ESP8266 on WiFi access point mode, with a server and websocket server on. It works fine when the client is connected, but when the client disconnects (android phone), the ESP crashes.

```
Exception (28):
epc1=0x40202087 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: cont 
sp: 3fff08e0 end: 3fff0dd0 offset: 01a0

>>>stack>>>
3fff0a80:  3fff2d0c 3fff3300 3fff32fc 4022a266  
3fff0a90:  000027ec 3fff2fc8 3fff32fc 40229ee5  
3fff0aa0:  3ffefcbc 000002e6 000002e6 4010020c  
3fff0ab0:  3ffefcbc 000003b8 000003b8 4010020c  
3fff0ac0:  3ffeeee0 3ffeeee0 3ffeef60 40208359  
3fff0ad0:  3ffeeee0 3ffe849c 3ffeef18 402084d1  
3fff0ae0:  3ffe849c 3ffeeee0 3fff33b4 40208fb0  
3fff0af0:  ffffffff 3fffc6fc 3ffeef18 40207122  
3fff0b00:  3ffeeee0 3ffeeee0 3ffeef18 402069f5  
3fff0b10:  00000001 00000000 000003bf 4010020c  
3fff0b20:  3ffee803 000002e3 000002e3 40206d98  
3fff0b30:  00000000 00000000 3ffeef18 40206ab8  
3fff0b40:  40220909 00000000 00000001 401072b4  
3fff0b50:  402287ca 4010149b 3ffed880 00000000  
3fff0b60:  3ffeef7d 3ffeeee0 3ffeef18 40206f88  
3fff0b70:  3ffed880 401016ce 00000001 00000000  
3fff0b80:  3fff2d24 3fff2d0c 3fff2d24 40204219  
3fff0b90:  402042d9 00000004 3ffefdb0 00000000  
3fff0ba0:  00000001 3ffeef18 3fff0c00 40206fd9  
3fff0bb0:  4010284d 3ffed118 00000000 40206caf  
3fff0bc0:  3ffeef7d 3ffeef18 3fff0c00 40206d5e  
3fff0bd0:  00015861 00000004 3ffeef18 401004d8  
3fff0be0:  00000000 0540488e 40102e1a 00000000  
3fff0bf0:  3ffeeee0 00000006 3ffeef18 40206ddb  
3fff0c00:  3fff27ac 05403d40 402066ac 40206fc0  
3fff0c10:  3ffeef7d 00000004 00000000 4000050c  
3fff0c20:  00000000 00000000 0000001f 00000000  
3fff0c30:  3ffeef7d 3ffeeee0 3ffeef18 40206f12  
3fff0c40:  40208add 00000030 0000001a ffffffff  
3fff0c50:  40208add 00000000 00000001 00000001  
3fff0c60:  402042d9 00000002 3ffefdb0 00000000  
3fff0c70:  00000001 3ffeef18 3fff0cd0 40206fd9  
3fff0c80:  3ffeeee0 3ffef29c 00000000 40206caf  
3fff0c90:  3ffeef7b 3ffeef18 3fff0cd0 40206d5e  
3fff0ca0:  00015861 00000002 3ffeef18 401004d8  
3fff0cb0:  40000ea3 00000023 00000001 00000000  
3fff0cc0:  3ffeeee0 00000002 3ffeef18 40206ddb  
3fff0cd0:  3fff3bd4 00000000 402066ac 40206fc0  
3fff0ce0:  3ffeef7b 00000002 3ffefd9c 00000030  
3fff0cf0:  ffffffff 3fffc6fc 00000001 000000b4  
3fff0d00:  3ffef29c 3ffeeee0 3ffeef18 40206f99  
3fff0d10:  00000000 3fffdad0 3ffefd9c 00000030  
3fff0d20:  00000001 00000000 3ffefdb0 3ffeeee0  
3fff0d30:  3ffef29c 000000b4 3ffef2bc 000000b4  
3fff0d40:  3ffef29c 3ffeeee0 3ffeef18 40206fb9  
3fff0d50:  3ffef29c 3ffeeee0 3ffeef18 40207b4e  
3fff0d60:  00000000 3ffefbd8 3ffef2bc 40205345  
3fff0d70:  3ffe86c0 00000000 000003e8 3ffefd9c  
3fff0d80:  3fffdad0 3ffefbd8 3ffeeee0 40207b94  
3fff0d90:  3fffdad0 3ffefbd8 3ffefbd8 40202544  
3fff0da0:  00000000 00000000 00000001 402026b0  
3fff0db0:  3fffdad0 00000000 3ffefd95 40208b08  
3fff0dc0:  feefeffe feefeffe 3ffefdb0 40100718  
<<<stack<<<

```

**Comment by Links2004** [comment]
Please provide the decoded stack
this links will help you to decode:

https://github.com/me-no-dev/EspExceptionDecoder
https://github.com/esp8266/Arduino/blob/master/doc/faq/a02-my-esp-crashes.rst

**Comment by Links2004** [comment]
ok, not really looks like exacted,
you maybe are running out of memory.
or the TCP layer tries to send when the connection is already dead.
which is in theory impossible:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.cpp#L613

which Verison of the WebSockets do you use?

**Comment by vithprodlet** [comment]
same problem here 

#include <WiFiClient.h>
#include <ESP32WebServer.h>
#include <WiFi.h>
#include <ESPmDNS.h>
//spiffs
#include "FS.h"
#include "SPIFFS.h"

``23:59:34.156 -> [1] Connected from 192.168.1.27 url: /
23:59:40.155 -> handleFileRead: /img/input_1.png
23:59:48.608 -> 
23:59:48.655 -> Guru Meditation Error: Core  1 panic'ed (LoadProhibited)
23:59:48.655 -> . Exception was unhandled.
23:59:48.655 -> Core 1 register dump:
23:59:48.655 -> PC      : 0x400014fd  PS      : 0x00060c30  A0      : 0x800ef618  A1      : 0x3ffd2460  
23:59:48.655 -> A2      : 0x00000000  A3      : 0xfffffffc  A4      : 0x000000ff  A5      : 0x0000ff00  
23:59:48.655 -> A6      : 0x00ff0000  A7      : 0xff000000  A8      : 0x00000000  A9      : 0x00000000  
23:59:48.655 -> A10     : 0x00000000  A11     : 0x3ffd2663  A12     : 0x00000000  A13     : 0x3ffdd9c8  
23:59:48.655 -> A14     : 0x3ffdd775  A15     : 0x3ffdd9c9  SAR     : 0x00000010  EXCCAUSE: 0x0000001c  
23:59:48.702 -> EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffff  
23:59:48.702 -> 
23:59:48.702 -> Backtrace: 0x400014fd:0x3ffd2460 0x400ef615:0x3ffd2470 0x400f6b46:0x3ffd2780 0x400f6b7e:0x3ffd2810 0x400d900c:0x3ffd2850 0x400d1c6a:0x3ffd28f0 0x4014203e:0x3ffd2970 0x401423f9:0x3ffd2990 0x400d7e4f:0x3ffd29c0 0x400d7665:0x3ffd29e0 0x400d7707:0x3ffd2a20 0x4014237d:0x3ffd2a50 0x400d790a:0x3ffd2a70 0x400d7997:0x3ffd2aa0 0x400d7ba5:0x3ffd2ad0 0x400d7c2e:0x3ffd2b10 0x400d790a:0x3ffd2b30 0x400d7997:0x3ffd2b60 0x400d79f9:0x3ffd2b90 0x400d7b42:0x3ffd2bd0 0x400d7c2e:0x3ffd2c10 0x400d790a:0x3ffd2c30 0x400d7997:0x3ffd2c60 0x400d79f9:0x3ffd2c90 0x400d7bea:0x3ffd2cd0 0x400d7c13:0x3ffd2d10 0x400d8add:0x3ffd2d30 0x400d8b1c:0x3ffd2d60 0x400d1e30:0x3ffd2d80 0x401285fe:0x3ffd2da0
23:59:48.749 -> 
23:59:48.749 -> Rebooting...
23:59:48.749 -> ets Jun  8 2016 00:22:57
23:59:48.749 -> 
23:59:48.749 -> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
23:59:48.749 -> configsip: 0, SPIWP:0xee
23:59:48.749 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
23:59:48.749 -> mode:DIO, clock div:1
23:59:48.749 -> load:0x3fff0018,len:4
23:59:48.749 -> load:0x3fff001c,len:956
23:59:48.749 -> load:0x40078000,len:0
23:59:48.749 -> load:0x40078000,len:13256
23:59:48.796 -> entry 0x40078a90
``

**Comment by Links2004** [comment]
I am sure this is not the same problem since we are taking esp8266 vs esp32 here,
and your includes does not show any Websockets includes.

the log lines:
```
23:59:34.156 -> [1] Connected from 192.168.1.27 url: /
23:59:40.155 -> handleFileRead: /img/input_1.png
```

sound like you have a problem with the normal HTTP web server (which is not part of this repo)
most likely you need to report you problem here:
https://github.com/espressif/arduino-esp32

**Comment by ajw685** [comment]
I don't know if this is related or not, but websockets crashes the esp8266 when I refresh my browser. It seems like a buffer is overflowing or something? I'm not good with C++

`Decoding stack results
0x4021ff63: ip_chksum_pseudo at core/inet_chksum.c line 395
0x40216be4: __ssputs_r at ../../../.././newlib/libc/stdio/nano-vfprintf.c line 180
0x40212a2d: _printf_common at ../../../.././newlib/libc/stdio/nano-vfprintf_i.c line 94
0x4020772d: webSocketEvent(unsigned char, WStype_t, unsigned char*, unsigned int) at C:\Users\Aaron\OneDrive\Arduino\sketch_oct23a/webSocketEvent.ino line 13
0x40216be4: __ssputs_r at ../../../.././newlib/libc/stdio/nano-vfprintf.c line 180
0x40212de8: _printf_i at ../../../.././newlib/libc/stdio/nano-vfprintf_i.c line 241
0x40211518: std::_Function_handler ::_M_invoke(std::_Any_data const&, unsigned char, WStype_t, unsigned char*, unsigned int) at c:\users\aaron\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2\xtensa-lx106-elf\include\c++\4.8.2/functional line 2073
0x40217044: _svfprintf_r at ../../../.././newlib/libc/stdio/nano-vfprintf.c line 641
0x4010020c: _umm_free at C:\Users\Aaron\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.2\cores\esp8266\umm_malloc\umm_malloc.c line 1295
0x401006dc: free at C:\Users\Aaron\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.2\cores\esp8266\umm_malloc\umm_malloc.c line 1755
0x40214a25: _vsnprintf_r at ../../../.././newlib/libc/stdio/vsnprintf.c line 73
0x40214a68: vsnprintf at ../../../.././newlib/libc/stdio/vsnprintf.c line 42
0x4020e54c: WebSocketsServer::clientDisconnect(WSclient_t*) at C:\Users\Aaron\Documents\Arduino\libraries\WebSockets\src\WebSocketsServer.cpp line 567
0x4020f51c: Print::printf(char const*, ...) at C:\Users\Aaron\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.2\cores\esp8266\Print.cpp line 63
0x40207b20: loop() at C:\Users\Aaron\OneDrive\Arduino\sketch_oct23a/sketch_oct23a.ino line 100
0x40207708: webSocketEvent(unsigned char, WStype_t, unsigned char*, unsigned int) at C:\Users\Aaron\OneDrive\Arduino\sketch_oct23a/webSocketEvent.ino line 7
0x4010020c: _umm_free at C:\Users\Aaron\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.2\cores\esp8266\umm_malloc\umm_malloc.c line 1295
0x4020f979: String::copy(char const*, unsigned int) at C:\Users\Aaron\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.2\cores\esp8266\WString.cpp line 175
0x40211518: std::_Function_handler ::_M_invoke(std::_Any_data const&, unsigned char, WStype_t, unsigned char*, unsigned int) at c:\users\aaron\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2\xtensa-lx106-elf\include\c++\4.8.2/functional line 2073
0x402118b4: WebSocketsServer::runCbEvent(unsigned char, WStype_t, unsigned char*, unsigned int) at C:\Users\Aaron\Documents\Arduino\libraries\WebSockets\src/WebSocketsServer.h line 182
0x4020e57e: WebSocketsServer::clientDisconnect(WSclient_t*) at C:\Users\Aaron\Documents\Arduino\libraries\WebSockets\src\WebSocketsServer.cpp line 585
0x402118f1: WebSocketsServer::clientIsConnected(WSclient_t*) at C:\Users\Aaron\Documents\Arduino\libraries\WebSockets\src\WebSocketsServer.cpp line 611
0x4020ef2d: WebSocketsServer::handleClientData() at C:\Users\Aaron\Documents\Arduino\libraries\WebSockets\src\WebSocketsServer.cpp line 671
0x4020a671: ESP8266WebServer::handleClient() at C:\Users\Aaron\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WebServer\src\ESP8266WebServer.cpp line 275
0x4020efb9: WebSocketsServer::loop() at C:\Users\Aaron\Documents\Arduino\libraries\WebSockets\src\WebSocketsServer.cpp line 135
0x40207b26: loop() at C:\Users\Aaron\OneDrive\Arduino\sketch_oct23a/sketch_oct23a.ino line 102
0x402104f4: loop_wrapper() at C:\Users\Aaron\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.2\cores\esp8266\core_esp8266_main.cpp line 125`
