### ISSUE TITLE
Error using void webSocketEvent()

### ISSUE THREAD

**Issue by DvDriel** [Links2004/arduinoWebSockets#250]
As in the WebSocketClient Arduino example we are calling the `webSocket.onEvent(webSocketEvent);` method passing the function `webSocketEvent` as parameter. We made this function static because otherwise it gave us the following error: `no matching function for call to 'WebSocketsClient::onEvent(<unresolved overloaded function type>)`

Making `webSocketEvent` static gave us the problem of not being able to make any calls to other class instances. Error: `invalid use of member 'OpenThermostat::Screen' in static member function` Is there any easy way to fix this?

onEvent call:
`
void OpenThermostat::begin() 
{
webSocket.onEvent(webSocketEvent);
}`

WebSocketEvent defintion:

`void webSocketEvent(WStype_t type, uint8_t * payload, size_t length);`

Call form static function to Screen instance

```
void OpenThermostat::webSocketEvent(WStype_t type, uint8_t * payload, size_t length)
{
	switch(type) {

		case WStype_DISCONNECTED:
			Serial.printf("[WSc] Disconnected!\n");
      Screen.removeSidebarIcon(SOCKET_ICON);
      Screen.drawSidebar();
			break;

		case WStype_CONNECTED: {
			Serial.printf("[WSc] Connected to url: %s\n", payload);
      Screen.addSidebarIcon(SOCKET_ICON);
      Screen.drawSidebar();
		}
			break;

		case WStype_TEXT:
			Serial.printf("[WSc] get text: %s\n", payload);
			break;

		case WStype_BIN:
			Serial.printf("[WSc] get binary length: %u\n", length);
			hexdump(payload, length);
			break;

	}
}
```

**Comment by Links2004** [comment]
you can use a non static function of your class like this:

```cpp
webSocket.onEvent(std::bind(&OpenThermostat::webSocketEvent, <your class instance here / may `this` >, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3);

```

**Comment by DvDriel** [comment]
Thank you so much! It worked perfectly.
