### ISSUE TITLE
wdt reset ??

### ISSUE THREAD

**Issue by VonalOrdu** [Links2004/arduinoWebSockets#254]
Why reset?
Many reset in version 2.0.9
Low reset in version 2.0.6

[code.txt](https://github.com/Links2004/arduinoWebSockets/files/1464934/code.txt)
[debuglog.txt](https://github.com/Links2004/arduinoWebSockets/files/1464935/debuglog.txt)
[stack.txt](https://github.com/Links2004/arduinoWebSockets/files/1464936/stack.txt)

**Comment by Links2004** [comment]
from a short look at the stack trace you have some sort of loop that exceeded the stack trace.

all the 
```
:wr !ERR_OK
:wr !ERR_OK
:wr !ERR_OK
:wr !ERR_OK
```
from the ESP core does not look good too.

which version of the core do you use?

**Comment by VonalOrdu** [comment]
`:wr !ERR_OK
:wr !ERR_OK
:wr !ERR_OK
:wr !ERR_OK`
This error gives webSocket 2.0.7, 2.0.8 and 2.0.9
This error is not 2.0.6.

-----------------------------------------------------------------------------------------------
> which version of the core do you use?
ESP-12F
Arduino 1.8.5
ESP8266 core for Arduino 2.3.0

**Comment by pariderp** [comment]
Same here, :wr !ERR_OK is present in webSocket 2.0.7, 2.0.8 and 2.0.9 but not in 2.0.6.
Any hint on how to handle it? Thanks
