### ISSUE TITLE
AVR function error on Controllino Mega ATmega 2560

### ISSUE THREAD

**Issue by bluelemonade** [Links2004/arduinoWebSockets#256]
hello,

I tried to compile the WebSocetClientAVR script for an Contollino Mega, with an ATmega 2560
https://controllino.biz/controllino/mega/ it uses a wiznet5100 controller.

I get an error: Documents\Arduino\libraries\arduinoWebSockets\src/WebSockets.h:35:22: fatal error: functional: No such file or directory

 #include <functional>

                      ^

Is there a way to compile it for this arduino?

**Comment by mysecondnameis** [comment]
I have the same problem, im using ENC28J60 and  mega2560

**Comment by habi3000** [comment]
same problem on arduino mega 

fatal error: functional: No such file or directory
 #include <functional>

                      ^
compilation terminated.
exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.

**Comment by Links2004** [comment]
sounds like you try to use the 2.x.x version of the lib.
for AVR you need the 1.x.x version (ATmega branch), since
Arduino for AVR not supports std namespace of c++.

https://github.com/Links2004/arduinoWebSockets/tree/ATmega
