### ISSUE TITLE
Connect ESP8266 socket client to a Python 2.7 socket server

### ISSUE THREAD

**Issue by gusantor** [Links2004/arduinoWebSockets#258]
Hello, thanks for this library, it works great

I'm trying to connect a bunch of clients to a main server

these clients mostly being ESP's and server being a microprocessor running Debian, in my case an Olimex A20, but I guess it can be a raspberry pi also

by now I have succed connecting a couple of ESP's client and server

I also have running a couple of python scripts, client and server again, working fine

when I try to connect an ESPs client to the Python server, I recive a response I don't expect, and no further messages, when it should be because thhe server is constantly broadcasting, every 10 secs, message says

		Waiting for connection ...
		Client connected from 192.168.10.157:21731
		192.168.10.157 > GET / HTTP/1.1
		Host: 192.168.10.123:8888
		Connection: Upgrade
		Upgrade: websocket
		Sec-WebSocket-Version: 13
		Sec-WebSocket-Key: UjBK8LZkdBw1IrOvOwyWPg==
		Origin: file://
		User-Agent: arduino-WebSocket-Client

maybe this a more python related question, but I can't find any info

so, please, any help on how to Connect ESP8266 socket client to a Python 2.7 socket server is very appreciated

thanks in advance

**Comment by gusantor** [comment]
ok, I have some sort of advance

for the python server , I made a first approach but when try to listen an ESP it doesn't respond appropriatetly for andshake, so I borrowed code from here

> [https://stackoverflow.com/questions/10152290/python-websocket-handshake-rfc-6455](https://stackoverflow.com/questions/10152290/python-websocket-handshake-rfc-6455)

then, the hand shake is made but receive (print data) just garbage, so I investigate how to Reading and Unmasking the Data, end up taking some code from here

> [https://stackoverflow.com/questions/35827248/solved-how-can-i-unmask-data-from-client-using-python](https://stackoverflow.com/questions/35827248/solved-how-can-i-unmask-data-from-client-using-python)

now I receive an AssertionError, and noticed my client is sending TEXT not FRAME, with

    webSocket.sendTXT(p);

so, can you give some hint on how to achieve this ?

is this, sending TEXT and not FRAME the AssertionError origin ?, how to solve ?

please help, thanks

# python server code

	#!/usr/bin/env python

	import socket
	import time
	from threading import Thread
	import re
	from base64 import b64encode
	from hashlib import sha1

	s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	ip = socket.gethostbyname(socket.gethostname())
	port = 8882
	address = (ip,port)
	s.bind(address)
	s.listen(2)

	websocket_answer = (
		'HTTP/1.1 101 Switching Protocols',
		'Upgrade: websocket',
		'Connection: Upgrade',
		'Sec-WebSocket-Accept: {key}\r\n\r\n',
	)

	GUID = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"

	print "Waiting for connection ..."

	client,addr = s.accept()

	print "Client connected from "+str(addr[0])+":"+str(addr[1])

	start_time = time.time()
	elapsed_time = 0

	AUTH_response=''
	key=''

	def listen():
		global s
		global client,addr
		global AUTH_response, key
		while True:
		  data = client.recv(1024)
		  #client_resp = unmask_data(data)
		  #client_resp = str(data.decode("utf-8"))

		  print data

		  #str(addr[0])+" > "+str(data)

		  key = (re.search('Sec-WebSocket-Key:\s+(.*?)[\n\r]+', data))
		  if key:
		    key = key.groups()[0].strip()

		    response_key = b64encode(sha1(key + GUID).digest())
		    AUTH_response = '\r\n'.join(websocket_answer).format(key=response_key)

		    print key

	def send():
		global s
		global client,addr
		global start_time, elapsed_time
		global AUTH_response, key
		while True:
		  if key:
		    print AUTH_response
		    client.send(AUTH_response)
		    key=''
		  
		  elapsed_time = time.time() - start_time
		  if False:#elapsed_time > 10:
		    start_time = time.time()
		    elapsed_time = 0
		    msg = "hola"#raw_input(">")
		    client.send(msg)

	def unmask_data(rcv_msg):
		# as a simple server, we expect to receive:
		#    - all data at one go and one frame
		#    - one frame at a time
		#    - text protocol
		#    - no ping pong messages
		data = bytearray(rcv_msg)
		if len(data) < 6:
		  raise Exception("Error reading data")
		# FIN bit must be set to indicate end of frame
		assert(0x1 == (0xFF & data[0]) >> 7)
		# data must be a text frame
		# 0x8 (close connection) is handled with assertion failure
		assert(0x1 == (0xF & data[0]))

		# assert that data is masked
		assert(0x1 == (0xFF & data[1]) >> 7)
		datalen = (0x7F & data[1])

		str_data = ''
		if datalen > 0:
		  mask_key = data[2:6]
		  masked_data = data[6:(6 + datalen)]
		  unmasked_data = [masked_data[i] ^ mask_key[i % 4] for i in range(len(masked_data))]
		  str_data = str(bytearray(unmasked_data).decode("utf-8"))
		
		return str_data

	if __name__=="__main__":
		Thread(target=listen).start()
		Thread(target=send).start()

# arduino client

	/*
	 * WebSocketClient.ino
	 *
	 *  Created on: 24.05.2015
	 *
	 */

	#include <Arduino.h>

	#include <ESP8266WiFi.h>
	#include <ESP8266WiFiMulti.h>
	#include <WebSocketsClient.h>
	#include <Hash.h>
	#include <ArduinoOTA.h>

	ESP8266WiFiMulti WiFiMulti;
	WebSocketsClient webSocket;

	#define USE_SERIAL Serial

	#define photo A0

	const unsigned long duracionCicloLed = 5000;
	unsigned long tiempoUltimoCiclo = 0;
	boolean ledStatus;
	int hayLuz;

	void setup() {
		USE_SERIAL.begin(115200);

		//Serial.setDebugOutput(true);
		USE_SERIAL.setDebugOutput(true);

		USE_SERIAL.println();
		USE_SERIAL.println("Inicio Cliente WebSocket");
		USE_SERIAL.println();

		pinMode(photo,INPUT);
		
		ota();

		for(uint8_t t = 4; t > 0; t--) {
			USE_SERIAL.printf("[SETUP] BOOT WAIT %d...\n", t);
			USE_SERIAL.flush();
			delay(1000);
		}

		WiFiMulti.addAP("ssid", "pass");

		//WiFi.disconnect();
		while(WiFiMulti.run() != WL_CONNECTED) {
			delay(100);
		}

		// server address, port and URL
		webSocket.begin("192.168.1.123", 8882, "/");//otro esp server

		// event handler
		webSocket.onEvent(webSocketEvent);

		// use HTTP Basic Authorization this is optional remove if not needed
		//webSocket.setAuthorization("user", "Password");

		// try ever 5000 again if connection has failed
		webSocket.setReconnectInterval(5000);

	}

	void loop() {
		ArduinoOTA.handle();
		
		webSocket.loop();
		if(cumpleCiclo()){
		  char p[32];
		  sprintf(p, "photo:%i", hayLuz);
		  webSocket.sendTXT(p);
		}
	}

	boolean cumpleCiclo(){
		boolean cumple = false;
		unsigned long tiempo = millis();
		
		if(millis() - tiempoUltimoCiclo >= duracionCicloLed){
		  tiempoUltimoCiclo = millis();
		  cumple = true;
		  hayLuz = analogRead(photo);
		}
		return cumple;
	}


	void webSocketEvent(WStype_t type, uint8_t * payload, size_t length) {

		switch(type) {
		  case WStype_DISCONNECTED:
		    USE_SERIAL.printf("[WSc] Disconnected!\n");
		    break;
		  case WStype_CONNECTED: {
		    USE_SERIAL.printf("[WSc] Connected to url: %s\n", payload);

		    // send message to server when Connected
		    webSocket.sendTXT("Connected");
		    break;
		  }
		  case WStype_TEXT:
		    USE_SERIAL.printf("[WSc] get text: %s\n", payload);

		    // send message to server
		    //webSocket.sendTXT("I, client, received messsge and send this back to server");
		    break;
		  case WStype_BIN:
		    USE_SERIAL.printf("[WSc] get binary length: %u\n", length);
		    hexdump(payload, length);

		    // send data to server
		    // webSocket.sendBIN(payload, length);
		    break;
		}

	}

	void ota(){

	// Port defaults to 8266
	// ArduinoOTA.setPort(8266);

	// Hostname defaults to esp8266-[ChipID]
	// ArduinoOTA.setHostname("myesp8266");

	// No authentication by default
	// ArduinoOTA.setPassword((const char *)"123");

		ArduinoOTA.onStart([]() {
		  Serial.println("Start");
		});
		ArduinoOTA.onEnd([]() {
		  Serial.println("\nEnd");
		});
		ArduinoOTA.onProgress([](unsigned int progress, unsigned int total) {
		  Serial.printf("Progress: %u%%\r", (progress / (total / 100)));
		});
		ArduinoOTA.onError([](ota_error_t error) {
		  Serial.printf("Error[%u]: ", error);
		  if (error == OTA_AUTH_ERROR) Serial.println("Auth Failed");
		  else if (error == OTA_BEGIN_ERROR) Serial.println("Begin Failed");
		  else if (error == OTA_CONNECT_ERROR) Serial.println("Connect Failed");
		  else if (error == OTA_RECEIVE_ERROR) Serial.println("Receive Failed");
		  else if (error == OTA_END_ERROR) Serial.println("End Failed");
		});
		ArduinoOTA.begin();
		Serial.println("OTA ready");
		//Serial.print("IP address: ");
		//Serial.println(WiFi.localIP());
	}

**Comment by Links2004** [comment]
I am not very good with python but it looks like you try to implement your own websocket server.

some example how to create a ws frame can be found here:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.cpp#L83

the decode part here, including the unmasking:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.cpp#L324
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.cpp#L410

but it may is easier to simple use a library, some fast googling brings up:
https://github.com/dpallot/simple-websocket-server
https://www.fullstackpython.com/websockets.html

if you really want to implement your one server reading the RFC will help to understand the protocol.
https://tools.ietf.org/html/rfc6455

**Comment by gusantor** [comment]
Great ! Thanks !

I didn't realize there were a python websocket server around

I went for SimpleWebSocketServer, and at first glance its working

now I just need adapt code to my needs

again,  thanks !

**Comment by ahmad7091** [comment]
hello, I have problem connecting ESP8266 to a socket.io server! I don't know what is the problem but  ESP8266 can't connect to server and continously issues "connect ws...[WS-Client] connection to 172.20.10.3:8000 Failed[WS-Client] client disconnected." error.

**Comment by rocketrobin777** [comment]
I've got the same issue
