### ISSUE TITLE
core_esp8266_features.h header file missing - Release 1.3

### ISSUE THREAD

**Issue by nccchirag** [Links2004/arduinoWebSockets#26]
fatal error: core_esp8266_features.h: No such file or directory

**Comment by nccchirag** [comment]
sorted using the master branch of esp8266 arduino library.
I was on v2.0.0 stable release

**Comment by Links2004** [comment]
you need latest git from core, there was a fix inside too.
more info here:
#24 
https://github.com/esp8266/Arduino/issues/776#issuecomment-162856295
