### ISSUE TITLE
Debug not working and WebSocket error

### ISSUE THREAD

**Issue by aj22r** [Links2004/arduinoWebSockets#260]
I did `#define DEBUG_WEBSOCKETS(...) Serial.printf( __VA_ARGS__ )` and `Serial.setDebugOutput(true);`, but it's still not showing debug output. I really need it because whenever i try to send some data to the client,  it disconnects the client, here's what the client sees: `WebSocket connection to 'ws://192.168.1.218:81/' failed: Could not decode a text frame as UTF-8.`

**Comment by aj22r** [comment]
I just realized that the websocket error may be caused because i used `broadcastTXT` to send binary data because when i used `broadcastBIN` I couldn't figure out how to read the data on the client side

**Comment by Links2004** [comment]
if you use the TXT functions you are limited to UTF-8.
This is a protocol limitation, thats why there is a second message format for Binary.
your client need to support Binary, without knowing what your client is its hard to say.
