### ISSUE TITLE
Disable WebSocketClient permanently?

### ISSUE THREAD

**Issue by DrP2016** [Links2004/arduinoWebSockets#263]
Hello people,

is it possible to permanently disalbe the Client, once it got a message? I want to use it for Customization for multiple Devices, so when a Device is connected to my Server (Nodejs) and received its data, the WebSocketClient should be disabled and get sort of 'locked', so it does not want to reconnect to the Server.

My Code is like the simple WebSocketClient example.

I hope my Problem is understandable and someone can help me

**Comment by Links2004** [comment]
sure, call ```disconnect``` and then never again the ```loop``` function.
