### ISSUE TITLE
Is the Amega RTL 8710 supported?

### ISSUE THREAD

**Issue by circuitry2** [Links2004/arduinoWebSockets#264]
I tried running a simpler version of the websocket server example and I'm getting "Hard Fault Error!" Is it possible to get this working with the RTL 8710 board?

**Comment by Links2004** [comment]
since I dont have a RTL 8710 hard to say, in theory yes but since you get a `Hard Fault Error!` some Debugging is needed.
If you can provide any Information regarding the `Hard Fault Error!` feel free to reopen.
