### ISSUE TITLE
How to sendTXT when some input change form 0 to 1?

### ISSUE THREAD

**Issue by ProximaB** [Links2004/arduinoWebSockets#268]
Could someone help me? I don't know how should i do it.

`void loop() {
	webSocket.loop();
...
	if (digitalRead(button) == 1 && _button == 0) {
		webSocket.sendTXT("8:OFF");
...
  It doesn't seem to work. 😫

**Comment by Links2004** [comment]
do you use there ESP as server or as client? 
you code looks good for the client part.

**Comment by ProximaB** [comment]
Yes this is client code. Anyway i decided to use POST request on click. Thanks for your time.
