### ISSUE TITLE
Connection to Java Websocket Server

### ISSUE THREAD

**Issue by lavancfc** [Links2004/arduinoWebSockets#270]
I have a [https://github.com/TooTallNate/Java-WebSocket](url) based server running on my android device which is connected to the same wifi local network as my ESP8266.

I am  hardcoding Ip address and port as below

 webSocket.begin("192.168.0.12", 8877) 

to connect to the android websocket server.

I want to know any other method possible so that I can avoid hardcoding of IP on client device. 

Thank you

**Comment by Links2004** [comment]
there are multible ways to do this.
If you want it to work at any wifi network I recommend to implement a udp broadcast based search.
something like this:

1. ESP send a search UDP broadcast
2. Android APP sends a UDP message back with the ip + port to connect to.
3. ESP connects via webSocket to the Phone

if connection gets lost start by 1

there are some protocols out there that implement this type of search (mDNS, UPnP)
but for your use case a simple udp socket based code will do the trick. 

if it only needs to work on you local wifi.
give the phone a DNS entry on you router (some do this automatic for the device host name)
program the DNS in to the ESP

**Comment by lavancfc** [comment]
Implemented this and working fine
Thankyou @Links2004

**Comment by janngabriel** [comment]
i am trying to use https://github.com/TooTallNate/Java-WebSocket on my Android Device as well and only get DISCONNECTED on ESP8266.

Server is running successfully on device as tested in NODE and "Simple Websocket Client" Chrome extension

help pleeeease
