### ISSUE TITLE
Websocket disconnects after a moment

### ISSUE THREAD

**Issue by artus9033** [Links2004/arduinoWebSockets#274]
I'm using an ESP8266 ESP12E module with the example server code. The websocket connects and can send/receive data, but only for about one second - after that time both the server and client get the socket disconnect event. I also tried to add some traffic between the server and client by sending some data every 200ms, but this didn't help either - the data were received during this about-one-second period, and then the socket disconnected as usual.

Arduino IDE v1.8.4
arduinoWebSockets: tried all 2.x.x version with no luck

```
[0] Connected from 192.168.4.2 url: /
[0] get Text: Connect Thu Jan 18 2018 23:01:33 GMT+0100
[0] Disconnected!
[0] Connected from 192.168.4.2 url: /
[0] Disconnected!

```

**Comment by artus9033** [comment]
Alright, finally got it working, after I analyzed ESP8266 debug output, I noticed that the ESP8266 tries to reconnect to the last configured wifi point every second, which failed in my case, as I'm using the ESP as an access point. For anybody experiencing this issue and using the ESP8266 as an access point, don't forget to set the mode to AP: 

`WiFi.mode(WIFI_AP);`

This fixes the problem

**Comment by tmarkson** [comment]
![Screenshot 2020-04-19 10 21 11](https://user-images.githubusercontent.com/896199/79690250-841c3d00-8227-11ea-82c7-1a3f632270d7.png)

I'm having this problem too but my ESP is in STA mode, not AP. Do you have any thoughts?

**Comment by Links2004** [comment]
if you need AP use:

```
WiFi.mode(WIFI_AP);
```

or for STA use:

```
WiFi.mode(WIFI_STA);
```

**Comment by tmarkson** [comment]
Thanks for replying Markus, 
I verified the mode is STA using `WiFi.getMode()`; it returned a value of 1.  STA is what I need, 

I have checked my server is stable with a client in Chrome browser. 

I'm using the example WebSocketClient.ino with these changes,
- Serial1 to Serial
- server address and port
- removed setAuthorization() call

I have also tried using `ESP8266WiFi` instead of `ESP8266WiFiMulti`

Do you have any other thoughts?

**Comment by Links2004** [comment]
first step is to get better logs by enabling debug output in the IDE.
with that we may see what is going on.

**Comment by tmarkson** [comment]
I have this line enabled, is that what you mean? 
`USE_SERIAL.setDebugOutput(true);`
There have not been any messages in serial monitor other than like my screenshot.

I also have Logging module on the python websockets server but have not seen any messages from that either.

**Comment by Links2004** [comment]
that is part of it, the IDE has a menu to enable build defines to get more logging.

https://arduino-esp8266.readthedocs.io/en/latest/Troubleshooting/debugging.html

if you not use the Arduino IDE then you need to set the defines yourself.

**Comment by tmarkson** [comment]
Good idea, I didn't know about the debug logging. 
Here is a copy of the first log -- after the logs stream very quickly like you see in the screenshot of my first post. 
I'm not sure what the short codes mean, for example `04:02:30.289 -> :abort` near the bottom of the log. 
I suspect the server is to blame. Although the server behaves fine with a browser, maybe it's not handling everything correctly and the browser is more forgiving than the ESP8266. It is written in python so I will write a quick one in nodejs. 

> SDK:2.2.2-dev(38a443e)/Core:2.6.3=20603000/lwIP:STABLE-2_1_2_RELEASE/glue:1.2-16-ge23a07e/BearSSL:89454af
> 04:02:29.724 -> IP Address: 10.0.0.227
> 04:02:29.724 -> [WS-Client] connect ws...
> 04:02:29.724 -> [hostByName] Host: 10.0.0.153 is a IP!
> 04:02:29.759 -> :ref 1
> 04:02:29.793 -> [WS-Client] connected to 10.0.0.153:5678.
> 04:02:29.793 -> [WS-Client][sendHeader] sending header...
> 04:02:29.793 -> [WS-Client][sendHeader] handshake GET / HTTP/1.1
> 04:02:29.793 -> Host: 10.0.0.153:5678
> 04:02:29.793 -> Connection: Upgrade
> 04:02:29.793 -> Upgrade: websocket
> 04:02:29.793 -> Sec-WebSocket-Version: 13
> 04:02:29.793 -> Sec-WebSocket-Key: KWSpHaFl36y9/g40DSAIYA==
> 04:02:29.793 -> Sec-WebSocket-Protocol: arduino
> 04:02:29.793 -> Origin: file://
> 04:02:29.793 -> User-Agent: arduino-WebSocket-Client
> 04:02:29.830 -> 
> 04:02:29.830 -> [write] n: 242 t: 8305
> 04:02:29.830 -> :wr 242 0
> 04:02:29.830 -> :wrc 242 242 0
> 04:02:29.830 -> [WS-Client][sendHeader] sending header... Done (35752us).
> 04:02:29.830 -> :ack 242
> 04:02:29.830 -> :rn 201
> 04:02:29.830 -> [WS-Client][handleHeader] RX: HTTP/1.1 101 Switching Protocols
> 04:02:29.830 -> [WS-Client][handleHeader] RX: Upgrade: websocket
> 04:02:29.830 -> [WS-Client][handleHeader] RX: Connection: Upgrade
> 04:02:29.830 -> [WS-Client][handleHeader] RX: Sec-WebSocket-Accept: 9d8Gxw13jMYEWgnS0+5tQNJl0Sc=
> 04:02:29.867 -> [WS-Client][handleHeader] RX: Date: Mon, 20 Apr 2020 08:02:29 GMT
> 04:02:29.867 -> [WS-Client][handleHeader] RX: Server: Python/3.8 websockets/8.1
> 04:02:29.867 -> :c0 1, 201
> 04:02:29.867 -> [WS-Client][handleHeader] Header read fin.
> 04:02:29.867 -> [WS-Client][handleHeader] Client settings:
> 04:02:29.867 -> [WS-Client][handleHeader]  - cURL: /
> 04:02:29.867 -> [WS-Client][handleHeader]  - cKey: KWSpHaFl36y9/g40DSAIYA==
> 04:02:29.867 -> [WS-Client][handleHeader] Server header:
> 04:02:29.867 -> [WS-Client][handleHeader]  - cCode: 101
> 04:02:29.902 -> [WS-Client][handleHeader]  - cIsUpgrade: 1
> 04:02:29.902 -> [WS-Client][handleHeader]  - cIsWebsocket: 1
> 04:02:29.902 -> [WS-Client][handleHeader]  - cAccept: 9d8Gxw13jMYEWgnS0+5tQNJl0Sc=
> 04:02:29.902 -> [WS-Client][handleHeader]  - cProtocol: arduino
> 04:02:29.902 -> [WS-Client][handleHeader]  - cExtensions: 
> 04:02:29.902 -> [WS-Client][handleHeader]  - cVersion: 0
> 04:02:29.902 -> [WS-Client][handleHeader]  - cSessionId: 
> 04:02:29.902 -> [WS-Client][handleHeader] Websocket connection init done.
> 04:02:29.902 -> [WS][0][headerDone] Header Handling Done.
> 04:02:29.939 -> [WSc] Connected to url: /
> 04:02:30.081 -> :rn 11
> 04:02:30.081 -> [WS][0][handleWebsocketWaitFor] size: 2 cWsRXsize: 0
> 04:02:30.081 -> [readCb] n: 2 t: 8570
> 04:02:30.081 -> :rd 2, 11, 0
> 04:02:30.081 -> :rdi 11, 2
> 04:02:30.081 -> [WS][0][handleWebsocketWaitFor][readCb] size: 2 ok: 1
> 04:02:30.081 -> [WS][0][handleWebsocket] ------- read massage frame -------
> 04:02:30.081 -> [WS][0][handleWebsocket] fin: 1 rsv1: 0 rsv2: 0 rsv3 0  opCode: 1
> 04:02:30.081 -> [WS][0][handleWebsocket] mask: 0 payloadLen: 5
> 04:02:30.081 -> [readCb] n: 5 t: 8587
> 04:02:30.081 -> :rd 5, 11, 2
> 04:02:30.081 -> :rdi 9, 5
> 04:02:30.115 -> [WS][0][handleWebsocket] text: ready
> 04:02:30.115 -> [WSc] get text: ready
> 04:02:30.115 -> [WS][0][handleWebsocketWaitFor] size: 2 cWsRXsize: 0
> 04:02:30.115 -> [readCb] n: 2 t: 8603
> 04:02:30.115 -> :rd 2, 11, 7
> 04:02:30.115 -> :rdi 4, 2
> 04:02:30.115 -> [WS][0][handleWebsocketWaitFor][readCb] size: 2 ok: 1
> 04:02:30.115 -> [WS][0][handleWebsocket] ------- read massage frame -------
> 04:02:30.115 -> [WS][0][handleWebsocket] fin: 1 rsv1: 0 rsv2: 0 rsv3 0  opCode: 8
> 04:02:30.115 -> [WS][0][handleWebsocket] mask: 0 payloadLen: 2
> 04:02:30.151 -> [readCb] n: 2 t: 8625
> 04:02:30.151 -> :rd 2, 11, 9
> 04:02:30.151 -> :rdi 2, 2
> 04:02:30.151 -> :c0 2, 11
> 04:02:30.151 -> [WS][0][handleWebsocket] get ask for close. Code: 1000
> 04:02:30.151 -> [WS][0][handleWebsocket] clientDisconnect code: 1000
> 04:02:30.151 -> [WS][0][sendFrame] ------- send message frame -------
> 04:02:30.151 -> [WS][0][sendFrame] fin: 1 opCode: 8 mask: 1 length: 2 headerToPayload: 0
> 04:02:30.151 -> [WS][0][sendFrame] pack to one TCP package...
> 04:02:30.151 -> [write] n: 8 t: 8655
> 04:02:30.151 -> :wr 8 0
> 04:02:30.151 -> :wrc 8 8 0
> 04:02:30.151 -> [WS][0][sendFrame] sending Frame Done (16244us).
> 04:02:30.289 -> :ack 8
> 04:02:30.289 -> :rcl
> 04:02:30.289 -> :abort
> 04:02:30.289 -> :ur 1
> 04:02:30.289 -> :del
> 04:02:30.289 -> [WS-Client] client disconnected.
> 04:02:30.289 -> [WSc] Disconnected!
>

**Comment by Links2004** [comment]
Hi,
yes its the server that closes the connection.

that can be seen by:
```
04:02:30.151 -> [WS][0][handleWebsocket] get ask for close. Code: 1000
04:02:30.151 -> [WS][0][handleWebsocket] clientDisconnect code: 1000
```

the server sends a opcode 8 (WSop_close) with reason code 1000 and no text

**Comment by tmarkson** [comment]
Thanks for the explanation Markus, 
the ESP is maintaining a connection with a Nodejs server using `express-ws`. 
Maybe this will help someone with the same symptoms.- ted

**Comment by tmarkson** [comment]
I recreated the same issue on the nodejs server as I did with the python server, that is fast repeating connect-disconnect cycles. 

In this case the client (ESP) is trying to connect to a route/path that is not defined in the server. So if you're seeing this behavior, I suggest making sure the server has a catch-all function to handle any routes that aren't specifically defined.

**Comment by sheterushi** [comment]
> Alright, finally got it working, after I analyzed ESP8266 debug output, I noticed that the ESP8266 tries to reconnect to the last configured wifi point every second, which failed in my case, as I'm using the ESP as an access point. For anybody experiencing this issue and using the ESP8266 as an access point, don't forget to set the mode to AP:
> 
> `WiFi.mode(WIFI_AP);`
> 
> This fixes the problem

can you explain whole process,i stuck in this part only
