### ISSUE TITLE
Problems when building the "num" IP variable of the Websockets server

### ISSUE THREAD

**Issue by enrutador** [Links2004/arduinoWebSockets#275]
Hi Links2004
Congratulations for your great job ¡¡¡

I have a problem that is not determined if it is a websockets architecture issue or because of an error in my code.

My intention is to send each client a message independently (By ip) outside the main function of the websocket. For that I save the connection variable "num"
of the websocket server in a structure, and when I want to send a message to the last connected device, I call the function webSocket.sendTXT (num, "message"), to send a message, and do not send the message
.

This only works for me within the webSocketEvent function. It does not work for me in the function Sendmsg () function but if it sends all the connected devices the broadcast webSocket.broadcastTXT ("message here")

I am using a nodeMcu. Is it a problem of building the IP? or i can make this call ?

```
//PART STRUCT
typedef struct
{
  String Nick; 
  String Mac;
  IPAddress Num;
} estructura;
estructura Sonda;


/// PART FUNCTIO WEBSOCKETS

    case WStype_CONNECTED:
      {
        IPAddress ip = webSocket.remoteIP(num);
        Sonda.Num=ip;
        Serial.printf("[%u] Connected from %d.%d.%d.%d url: %s\n", num, ip[0], ip[1], ip[2], ip[3], payload);
      }
      break;



funcionSendmsg(){
      Serial.print("Sonda.Num");Serial.println(Sonda.Num);      
      webSocket.sendTXT(Player.Num , "mensaje");   // This not send the message to the client
      webSocket.broadcastTXT("message BROADCAST"); // This work perfect for all the clients
}

///Output on server

Sonda.Num 192.168.4.2

```

Thank you very much

**Comment by Links2004** [comment]
the `num` is not the IP ;)
its a number / index of the client connected.
if you get the num 1 in the callback and 
you what to send something later to this client you put the number 1 in the `sendTXT` send function.

normally you shut get a compiler warning about not matching type `uint8_t` vs `IPAddress` / `int`.

**Comment by enrutador** [comment]
Thanks Markus

I understand that when you say number / index this does not correspond to the last octet of the IP?

```
    webserver.on("/SondaSetigns", []() {

      String ip= webserver.arg("IP");
      String msg= webserver.arg("value");
      
      int len = ip.length();
      uint8_t  IP4  = atoi (state.substring(10, len).c_str());
      Serial.println(IP4);
      
      webSocket.sendTXT( IP4 , msg);    // this not work
      webSocket.broadcastTXT("message BROADCAST");  // this Perfect
```
How does the client number relate to the client ip?

A lot of Thanks

**Comment by Links2004** [comment]
there is no direct corresponds the IP comes from the socket that is used.

the num is the index in the _clients array.

may this code paths makes it a little more clear:

https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsServer.cpp#L401
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsServer.cpp#L170
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsServer.h#L109

**Comment by enrutador** [comment]
Hi Markus
A lot of thaks for your time  and for your clarification. ¡¡¡¡
