### ISSUE TITLE
Esp32 support? 

### ISSUE THREAD

**Issue by hutje** [Links2004/arduinoWebSockets#279]
Are there plans to support esp32?
Thanks for this library on esp8266 it works flawless!

**Comment by Links2004** [comment]
there is some work ongoing form the community 
https://github.com/Links2004/arduinoWebSockets/tree/esp32

but it is not fully integrated, yet.
since merging it will break other platforms.

**Comment by baggior** [comment]
I'm very interested in this porting too
I've tryed the branch and is working enough on esp32

what is needed then to merge into master?
can you isolate the not working features of the other platforms?

**Comment by hutje** [comment]
@baggior How do you mean it is working? When I try I get: `C:\Users\xxxxx\Documents\Arduino\libraries\Hash\src\sha1\sha1.c:34:21: fatal error: c_types.h: No such file or directory`

**Comment by Links2004** [comment]
@baggior 
the Travis CI tests for ESP8266 build is currently failing, with compiler errors. 
https://github.com/Links2004/arduinoWebSockets/pull/265
will trigger a retest may its fixed by now.

SSL is not working properly for the ESP32.
non of the example will work with the ESP32 (wrong includes)

@baggior 
looks like you have a lib installed that is named "Hash"
the ESP provides its own, can you try to remove it?

**Comment by hutje** [comment]
@Links2004 I think you meant me ;-)
But now I deleted the hash lib asnd now got a whole bunch of other things... :-(
```C:\Users\Robin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/lib\libwpa_supplicant.a(sha1-internal.o): In function 'SHA1Transform':

/Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/wpa_supplicant/src/crypto/sha1-internal.c:180: multiple definition of 'SHA1Transform'

libraries\WebsocketsServer\libsha1\libsha1.c.o:C:\Users\Robin\Documents\Arduino\hardware\espressif\esp32\libraries\WebsocketsServer\src\libsha1/libsha1.c:58: first defined here

C:\Users\Robin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/lib\libwpa_supplicant.a(sha1-internal.o): In function 'SHA1Init':

sha1-internal.c:(.text.SHA1Init+0x0): multiple definition of 'SHA1Init'

libraries\WebsocketsServer\libsha1\libsha1.c.o:libsha1.c:(.text.SHA1Init+0x0): first defined here

C:\Users\Robin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/lib\libwpa_supplicant.a(sha1-internal.o): In function 'SHA1Update':

sha1-internal.c:(.text.SHA1Update+0x0): multiple definition of 'SHA1Update'

libraries\WebsocketsServer\libsha1\libsha1.c.o:libsha1.c:(.text.SHA1Update+0x0): first defined here

C:\Users\Robin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/lib\libwpa_supplicant.a(sha1-internal.o): In function 'SHA1Final':

sha1-internal.c:(.text.SHA1Final+0x0): multiple definition of 'SHA1Final'

libraries\WebsocketsServer\libsha1\libsha1.c.o:libsha1.c:(.text.SHA1Final+0x0): first defined here

collect2.exe: error: ld returned 1 exit status
```

**Comment by baggior** [comment]
i've checked out the branch esp32
it compiles and works 
I don't use SSL

i've defined this compilation directive: -D CORE_HAS_LIBB64

**Comment by hutje** [comment]
How do I need to edit this?

**Comment by baggior** [comment]
checkout the branch esp32 and define -D CORE_HAS_LIBB64 (i do this in platformio.ini)

**Comment by hutje** [comment]
I use Arduino IDE. do I need to just #define -D CORE_HAS_LIBB64 ?

**Comment by hutje** [comment]
How do I turn off the ssl? Because I don't need it, but this is causing the problem I think...

**Comment by baggior** [comment]
please help on merge the PR #281
I dont know how to edit travis ci scripts to be complatible on both ESP32 and ESP8266

**Comment by Links2004** [comment]
regarding CORE_HAS_LIBB64

may 

```cpp
#if defined(ESP32)
#define CORE_HAS_LIBB64
#endif
```

does the trick

**Comment by baggior** [comment]
I did the same in my platoformio.ini

build_flags=-DCORE_HAS_LIBB64


Marco Tombesi
marco.tombesi@gmail.com

2018-02-06 20:13 GMT+01:00 Markus <notifications@github.com>:

**Comment by hutje** [comment]
I saw you successfully merged the code... Does this mean I could just download the updated code?

**Comment by Links2004** [comment]
I try to get travis up for the ESP32 if this goes well I merge it in to master

**Comment by baggior** [comment]
travis is ok on the pull request #281

**Comment by Links2004** [comment]
yes for the esp8266, the same run for the esp32 is missing.
have change the `.travis.yml` to try to build for the esp32 too.
hope this goes well.

https://travis-ci.org/Links2004/arduinoWebSockets/builds/338161996

**Comment by hutje** [comment]
@Links2004 
> regarding CORE_HAS_LIBB64
> may
> ```
> #if defined(ESP32)
> #define CORE_HAS_LIBB64
> #endif
> ```
> does the trick

Where do I need to edit this?

**Comment by Links2004** [comment]
https://github.com/Links2004/arduinoWebSockets/commit/5e1f9b1c267ce0b780e597f620496c53183ff27e

**Comment by baggior** [comment]
Tests arent ported to esp32

**Comment by Links2004** [comment]
looks like it, at least one working example where good.

**Comment by hutje** [comment]
@Links2004 I tried it, but gives the same error... :-(

**Comment by hutje** [comment]
```
C:\Users\Robin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/lib\libwpa_supplicant.a(sha1-internal.o): In function `SHA1Transform':

/Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/wpa_supplicant/src/crypto/sha1-internal.c:180: multiple definition of `SHA1Transform'

libraries\WebsocketsServer\libsha1\libsha1.c.o:C:\Users\Robin\Documents\Arduino\hardware\espressif\esp32\libraries\WebsocketsServer\src\libsha1/libsha1.c:58: first defined here

C:\Users\Robin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/lib\libwpa_supplicant.a(sha1-internal.o): In function `SHA1Init':

sha1-internal.c:(.text.SHA1Init+0x0): multiple definition of `SHA1Init'

libraries\WebsocketsServer\libsha1\libsha1.c.o:libsha1.c:(.text.SHA1Init+0x0): first defined here

C:\Users\Robin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/lib\libwpa_supplicant.a(sha1-internal.o): In function `SHA1Update':

sha1-internal.c:(.text.SHA1Update+0x0): multiple definition of `SHA1Update'

libraries\WebsocketsServer\libsha1\libsha1.c.o:libsha1.c:(.text.SHA1Update+0x0): first defined here

C:\Users\Robin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/lib\libwpa_supplicant.a(sha1-internal.o): In function `SHA1Final':

sha1-internal.c:(.text.SHA1Final+0x0): multiple definition of `SHA1Final'

libraries\WebsocketsServer\libsha1\libsha1.c.o:libsha1.c:(.text.SHA1Final+0x0): first defined here

collect2.exe: error: ld returned 1 exit status

```

**Comment by Links2004** [comment]
https://github.com/Links2004/arduinoWebSockets/commit/46cff38287eda8594e20c5d03cb4b9d741840ca4

**Comment by hutje** [comment]
Thanks!

**Comment by Links2004** [comment]
looks like there are still problems with the ESP32.

```
In file included from /home/travis/Arduino/libraries/arduinoWebSockets/src/WebSocketsClient.h:28:0,
                 from WebSocketClient.ino:28:
/home/travis/Arduino/libraries/arduinoWebSockets/src/WebSockets.h:149:30: fatal error: WiFiClientSecure.h: No such file or directory
 #include <WiFiClientSecure.h>
                              ^
compilation terminated.
Error compiling.
Build failed (arduino)
```

need to take look later this week.

https://travis-ci.org/Links2004/arduinoWebSockets/jobs/338185392
https://travis-ci.org/Links2004/arduinoWebSockets/jobs/338185391

**Comment by hutje** [comment]
But this is only when you want to merge, right?
The changes you showed are good?

**Comment by Links2004** [comment]
the changes it self  are fine.

but I only will merge it to master if it builds the example without error.
If i merge it in this state there It will get frustrating for people since the think ESP32 support is fully working,
then they load the a example and nothing will work, which is a very bad experience.

more advanced users can use the esp32 branch until it is merged ;)

**Comment by hutje** [comment]
Okay

**Comment by baggior** [comment]
I've opened a new PR #282 that ports a couple f tests to esp32 too

travis script must be checked

**Comment by Links2004** [comment]
have it mostly working, only the newest IDE version (1.8.5) makes strange problems.

**Comment by Links2004** [comment]
finally done, feel free to test the master branch.
If all is good I will release a new Version for the Library Manager and PlatformIO.

**Comment by schlaegerz** [comment]
Thanks for all this work. What is remaining to get it working with SSL? I will be willing to help out, but I'm not sure how far away it is from working

**Comment by Links2004** [comment]
since I dont have a ESP32 at hand, hard to say.
the SSL example code compiles ;)

next step is some testing.
since the Interface is not much different to the ESP2866 it may work already.

most needed here is some testing.

**Comment by schlaegerz** [comment]
Ok well I will be testing it next week most likely so I will send feedback.

**Comment by schlaegerz** [comment]
So I haven't tested it thoroughly yet, but the basics with https seems to be working

**Comment by Keanhee** [comment]
@schlaegerz how is your testing? Everything fine? I've esp32 on hand. I could probably help you to test if there is any outstanding issues.

**Comment by schlaegerz** [comment]
I have had no issues yet, and it seems to work for my scenario.

**Comment by Links2004** [comment]
ok, will release a new version this weekend, Thanks for the testing.

**Comment by Links2004** [comment]
Version 2.1.0 is released

https://github.com/Links2004/arduinoWebSockets/releases/tag/2.1.0

**Comment by arlaor** [comment]
Hi @Links2004 @hutje 
My Problem is the same

Archiving built core (caching) in: C:\Users\ING~1.APO\AppData\Local\Temp\arduino_cache_414836\core\core_espressif_esp32_lolin32_FlashFreq_80,PartitionScheme_default,UploadSpeed_115200_d1483996e50f9d70c83a699dc4dcec81.a
Linking everything together...
"D:\ARDUINO\arduino-1.8.5\portable\packages\esp32\tools\xtensa-esp32-elf-gcc\1.22.0-80-g6c4433a-5.2.0/bin/xtensa-esp32-elf-gcc" -nostdlib "-LD:\ARDUINO\arduino-1.8.5\hardware\espressif\esp32/tools/sdk/lib" "-LD:\ARDUINO\arduino-1.8.5\hardware\espressif\esp32/tools/sdk/ld" -T esp32_out.ld -T esp32.common.ld -T esp32.rom.ld -T esp32.peripherals.ld -T esp32.rom.spiram_incompatible_fns.ld -u ld_include_panic_highint_hdl -u call_user_start_cpu0 -Wl,--gc-sections -Wl,-static -Wl,--undefined=uxTopUsedPriority  -u __cxa_guard_dummy -u __cxx_fatal_exception  -Wl,--start-group "C:\Users\ING~1.APO\AppData\Local\Temp\arduino_build_311965\sketch\WebSocketClient.ino.cpp.o" "C:\Users\ING~1.APO\AppData\Local\Temp\arduino_build_311965\libraries\WiFi\ETH.cpp.o" "C:\Users\ING~1.APO\AppData\Local\Temp\arduino_build_311965\libraries\WiFi\WiFi.cpp.o" "C:\Users\ING~1.APO\AppData\Local\Temp\arduino_build_311965\libraries\WiFi\WiFiAP.cpp.o" "C:\Users\ING~1.APO\AppData\Local\Temp\arduino_build_311965\libraries\WiFi\WiFiClient.cpp.o" "C:\Users\ING~1.APO\AppData\Local\Temp\arduino_build_311965\libraries\WiFi\WiFiGeneric.cpp.o" "C:\Users\ING~1.APO\AppData\Local\Temp\arduino_build_311965\libraries\WiFi\WiFiMulti.cpp.o" "C:\Users\ING~1.APO\AppData\Local\Temp\arduino_build_311965\libraries\WiFi\WiFiSTA.cpp.o" "C:\Users\ING~1.APO\AppData\Local\Temp\arduino_build_311965\libraries\WiFi\WiFiScan.cpp.o" "C:\Users\ING~1.APO\AppData\Local\Temp\arduino_build_311965\libraries\WiFi\WiFiServer.cpp.o" "C:\Users\ING~1.APO\AppData\Local\Temp\arduino_build_311965\libraries\WiFi\WiFiUdp.cpp.o" "C:\Users\ING~1.APO\AppData\Local\Temp\arduino_build_311965\libraries\WiFiClientSecure\WiFiClientSecure.cpp.o" "C:\Users\ING~1.APO\AppData\Local\Temp\arduino_build_311965\libraries\WiFiClientSecure\ssl_client.cpp.o" "C:\Users\ING~1.APO\AppData\Local\Temp\arduino_build_311965\libraries\arduinoWebSockets-master\WebSockets.cpp.o" "C:\Users\ING~1.APO\AppData\Local\Temp\arduino_build_311965\libraries\arduinoWebSockets-master\WebSocketsClient.cpp.o" "C:\Users\ING~1.APO\AppData\Local\Temp\arduino_build_311965\libraries\arduinoWebSockets-master\WebSocketsServer.cpp.o" "C:\Users\ING~1.APO\AppData\Local\Temp\arduino_build_311965\libraries\arduinoWebSockets-master\libb64\cdecode.c.o" "C:\Users\ING~1.APO\AppData\Local\Temp\arduino_build_311965\libraries\arduinoWebSockets-master\libb64\cencode.c.o" "C:\Users\ING~1.APO\AppData\Local\Temp\arduino_build_311965\libraries\arduinoWebSockets-master\libsha1\libsha1.c.o" "C:\Users\ING~1.APO\AppData\Local\Temp\arduino_build_311965/arduino.ar" -lgcc -lopenssl -lbtdm_app -lfatfs -lwps -lcoexist -lwear_levelling -lesp_http_client -lhal -lnewlib -ldriver -lbootloader_support -lpp -lmesh -lsmartconfig -ljsmn -lwpa -lethernet -lphy -lapp_trace -lconsole -lulp -lwpa_supplicant -lfreertos -lbt -lmicro-ecc -lcxx -lxtensa-debug-module -lmdns -lvfs -lsoc -lcore -lsdmmc -lcoap -ltcpip_adapter -lc_nano -lesp-tls -lrtc -lspi_flash -lwpa2 -lesp32 -lapp_update -lnghttp -lspiffs -lespnow -lnvs_flash -lesp_adc_cal -llog -lsmartconfig_ack -lexpat -lm -lc -lheap -lmbedtls -llwip -lnet80211 -lpthread -ljson  -lstdc++ -Wl,--end-group -Wl,-EL -o "C:\Users\ING~1.APO\AppData\Local\Temp\arduino_build_311965/WebSocketClient.ino.elf"
C:\Users\ING~1.APO\AppData\Local\Temp\arduino_build_311965/arduino.ar(HardwareSerial.cpp.o):(.bss.Serial1+0x0): multiple definition of `Serial1'

C:\Users\ING~1.APO\AppData\Local\Temp\arduino_build_311965\sketch\WebSocketClient.ino.cpp.o:(.bss.Serial1+0x0): first defined here

collect2.exe: error: ld returned 1 exit status

Usando librería WiFi con versión 1.0 en la carpeta: D:\ARDUINO\arduino-1.8.5\hardware\espressif\esp32\libraries\WiFi 
Usando librería WiFiClientSecure con versión 1.0 en la carpeta: D:\ARDUINO\arduino-1.8.5\hardware\espressif\esp32\libraries\WiFiClientSecure 
Usando librería arduinoWebSockets-master con versión 2.1.0 en la carpeta: D:\ARDUINO\arduino-1.8.5\portable\sketchbook\libraries\arduinoWebSockets-master 
exit status 1
Error compilando para la tarjeta WEMOS LOLIN32.

this error is for all boards esp32

**Comment by arlaor** [comment]
hi @Links2004 @hutje @baggior @schlaegerz @Keanhee 

when I remove the line 
```javascript
 HardwareSerial Serial1(2);
```
from the sketch, then the code is loaded 
I still do not verify that errors of interpretation of the code by the esp32, can be generated or that other lines of code are not legible or are omitted due to the lack of the retired line
