### ISSUE TITLE
error: 'WiFiClientSecure' does not name a type          WiFiClientSecure * ssl;

### ISSUE THREAD

**Issue by piux** [Links2004/arduinoWebSockets#28]
when i add this library it throws me this error when i verify it.

    In file included from C:\Program Files (x86)\Arduino\libraries\arduinoWebSockets-master\src/WebSocketsServer.h:29:0,
                 from WiFiMulti.ino:8:
    C:\Program Files (x86)\Arduino\libraries\arduinoWebSockets-master\src/WebSockets.h:120:9: error: 'WiFiClientSecure' does not name a type
         WiFiClientSecure * ssl;
         ^
    Error compiling.

**Comment by Links2004** [comment]
you need to add the ```ESP8266WiFi``` too,
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/WebSocketClient/WebSocketClient.ino#L10

**Comment by piux** [comment]
hi, thanks for your response. i tried that example too and it gave me the same error.

**Comment by Links2004** [comment]
which ESP8266 core version do you use?

**Comment by piux** [comment]
im not even compiling, im doing a verify and it gives this error.

**Comment by Links2004** [comment]
the arduino therm "verify" is miss leading
in background it do compile
and "upload" is 
compile + flashing

**Comment by piux** [comment]
well the error is when it compiles, should i try upload it without verifying the code first?

**Comment by Links2004** [comment]
will give you the same error ;)

which ESP8266 core version do you use?

**Comment by piux** [comment]
im using esp-01 module and http://prntscr.com/9g3dp9.

**Comment by piux** [comment]
1.6.5 version in the uploader

**Comment by Links2004** [comment]
the latest git for WebSockets work only with the git version of the core,
https://github.com/esp8266/Arduino#using-git-version-
#24

**Comment by piux** [comment]
thanks a lot, it worked. 

just in case someone else stumbles upon this problem, once you install the git version, you must select it in the board manager. i ended with 2 esp8266 modules.

thanks again.

**Comment by apanasara** [comment]
same error though using thru latest git

```cpp
#include <ESP8266WiFi.h>
	//#include <WiFiClientSecure.h>
#include <WiFiClientSecureAxTLS.h>

WiFiClientSecure iface;
```

**Error**
>error: 'WiFiClientSecure' does not name a type

**Comment by Umbrien** [comment]
Still getting this error
