### ISSUE TITLE
arduinoWebSockets running on Raspberry?

### ISSUE THREAD

**Issue by mysone** [Links2004/arduinoWebSockets#285]
is it difficult to change this WebSocketClient for raspberry?

https://github.com/Links2004/arduinoWebSockets/tree/master/src

Thx.

**Comment by Links2004** [comment]
there is a RPI core for Arduino, with this there is a good change to get it work.
https://github.com/me-no-dev/RasPiArduino

**Comment by MrXploder** [comment]
with rpi you got the full power of nodejs and javascript enviroment... why would you do that? xdxd
