### ISSUE TITLE
Version released by ArduinoIDE today has issue with Ethernet.h

### ISSUE THREAD

**Issue by hiphigi** [Links2004/arduinoWebSockets#287]
I apologize for not saving the exact error before hand. If you're unable to reproduce I can. Just wanted to make you aware that I had to go back to an old version to make it compile.

**Comment by Links2004** [comment]
which IDE version? the last release of the IDE is 1.8.5 from Oct 2, 2017.
which hardware / board do you use? 
ethernet.h means you try to use a w5100?

at least travis shows no errors, with IDE v1.8.5 and v1.6.5
https://travis-ci.org/Links2004/arduinoWebSockets/builds/347378642
