### ISSUE TITLE
Websocket Server does not get Static IP

### ISSUE THREAD

**Issue by williamesp2015** [Links2004/arduinoWebSockets#288]
I was trying to set my device IP but I had no progress using ESP32 and PlatformIo.

**Comment by Links2004** [comment]
the Websocket Server is bind to all IPs configured on the ESP.
can you ping the ESP?

if not then there is a more general problem with you setup.

**Comment by williamesp2015** [comment]
I appreciate your reply. I can ping to the router and everything is ok but previously my device IP was 192.16.1.31 and now is 192.168.1.4 without anything to do with static IP.

**Comment by Links2004** [comment]
you can fix this in two ways:

1. hard code the IP on the ESP (https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/examples/WiFiClientStaticIP/WiFiClientStaticIP.ino)
2. set a fixed IP in the router/DHCP server for the MAC of the ESP

**Comment by williamesp2015** [comment]
Thanks @Link2004. I was not working for me. I am using ArduinoWebsocket server. Could you please update it for static IP.
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp32/WebSocketServer/WebSocketServer.ino

**Comment by williamesp2015** [comment]
This example is working for static IP
const char *ssid = "SSID";
const char *password = "***";
IPAddress local_IP(192, 168, 1, 11);
IPAddress gateway(192, 168, 1, 10);
IPAddress subnet(255, 255, 255, 0);
.....
   /*****************************************************************/
Serial.print("Connecting to ");
Serial.println(ssid);
 WiFiMulti.addAP(ssid, password);
  while(WiFiMulti.run() != WL_CONNECTED) {
            delay(500);
        }
        WiFi.config(local_IP, gateway, subnet);
        Serial.print("AP IP address: ");
        Serial.println(local_IP);
       /*****************************************************************/
