### ISSUE TITLE
Cannot use JSON

### ISSUE THREAD

**Issue by KristianDukov** [Links2004/arduinoWebSockets#289]
Hello,

Trying to push some JSON using websocket but I got an error:

String(const char *cstr = "");

Here is a part of the output:
{"distance":8190,"rep":12,"set":1}

`JSONencoder["distance"] = measure.RangeMilliMeter;
      JSONencoder["rep"] = 12;
      JSONencoder["set"] = 1;
      JSONencoder.printTo(Serial);
webSocket.broadcastTXT(String(JSONencoder));
`
Any ideas how I can handle it?

**Comment by Links2004** [comment]
the answer depends on wich JSON lib you are using, look like ```ArduinoJson``` to me.
for https://github.com/bblanchon/ArduinoJson

```cpp
StreamString data;
JSONencoder.printTo(data); 
webSocket.broadcastTXT(data.c_str());
```

will do the trick.

**Comment by KristianDukov** [comment]
Thanks for the fast help: I asked as you proposed but now I get

`'StreamString' was not declared in this scope`

And you are right: this is the lib that I am using

**Comment by Links2004** [comment]
you still need to put your data in, like you did before.

```cpp
JSONencoder["distance"] = measure.RangeMilliMeter; 
JSONencoder["rep"] = 12; 
JSONencoder["set"] = 1; 

StreamString data;
JSONencoder.printTo(data); 
webSocket.broadcastTXT(data.c_str());
```
