### ISSUE TITLE
Ws_type always DISCONNECTED

### ISSUE THREAD

**Issue by VladHateganUt** [Links2004/arduinoWebSockets#290]
Well i am using the WebSocketServer from examples and i am trying to send a message from java, the connection between the 2 is established and when java sends the message the esp prints " [0] DISCONNECTED", i tried looking through your library code but i need further explanations to understand how my message gets to the webSocketEvent function and how to extract and print it.

Eventually i attach a java example which should send only one message.
I bet the problem conists of the pieces i miss when i try to understand your code.

```ava

        import java.io.IOException;
        import java.io.PrintWriter;
        import java.net.InetAddress;
        import java.net.ServerSocket;
        import java.net.Socket;
        import java.net.UnknownHostException;
        import java.util.Scanner;


        public class Start {

            public static void main(String[] args) throws UnknownHostException, IOException {

               
                
                PrintWriter output;
                Scanner input;
                String msg1;              
                
                
                String host = "192.168.1.9";
                int port = 81;	
                InetAddress address = InetAddress.getByName(host);
                Socket x = new Socket(address, port);
                System.out.println("connectin established");
                
                input = new Scanner(x.getInputStream());
                output = new PrintWriter(x.getOutputStream(), true);
                msg1 = "hello";
                output.println(msg1);
               
                x.close();

            }
        }

```

**Comment by Links2004** [comment]
your java code looks like it uses a TCP socket not a websocket.
you need to use a websocket implementation in java.

**Comment by sp9auv** [comment]
I use WebSocketsClient in my NODEMCU v 3 (ESP8266) sketch and it cooperating with 
TWSocketServer from ICS Overbyte in a Delphi program . On sketch this WebSocketsClient 
never occurs event WStype_CONNECTED  .  Try send string via  webSocket.sendTXT(BufForOneAnalogLine)   and string is not send .
Header information from this WebSocketsClient  as GET /socket.io/EIO and Connecting keep alive is recevied  , but not receive string from  webSocket.sendTXT(BufForOneAnalogLine) .
With NODEMCU WebSocketsClient  i try to send event what ocurs on NODEMCU board ( as turn
antenna rotor ) .
On NODEMCU sketch is also present ESP8266WebServer server(80), ant it cooperating very well
witch component  Twebdata in a Delphi from package TMS .
Where is my error.

**Comment by Links2004** [comment]
are you sure that your Delphi speaks socket.io and not plain ws?

the IDE has a DEBUG PORT option you can set it and get more info.
or set the define here:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L41

**Comment by sp9auv** [comment]
you asking ; are you sure that your Delphi speaks socket.io and not plain ws?

you asking ;  the IDE has a DEBUG PORT option you can set it and get more info.
or set the define here:
I am uncomented   #define DEBUG_WEBSOCKETS(...) os_printf( __VA_ARGS__ )  in a WebSockets.h 
as you tell and get this in a Serial monitor  ;
------------------------------------------------------
_[SETUP] BOOT WAIT 4...
[SETUP] BOOT WAIT 3...
[SETUP] BOOT WAIT 2...
[SETUP] BOOT WAIT 1...
Came to webSocket.begin IP = 192.168.1.8 
[WS-Client] connect ws...
[WS-Client] connected to 192.168.1.8:81.
[WS-Client][sendHeader] sending header...
[WS-Client][sendHeader] handshake GET /socket.io/?EIO=3&transport=polling HTTP/1.1
Host: 192.168.1.8:81
Connection: keep-alive
Origin: file://
User-Agent: arduino-WebSocket-Client

[write] n: 153 t: 31069
[WS-Client][sendHeader] sending header... Done (227228us).
Came to CreateWebpageForAnalogPin0_ 
-----------------------------------------------
Now I run my program from Delphi and get this ;
-----------------------------------------------------------
 _[WS][0][sendFrame] not in WSC_CONNECTED state!?_
-------------------------------------------------------------
Program from Delphi  after run is set inside my program state **WSocketServer1.state =  wsListening** 
In a program header is received and I can extract proper header but not appear the string 
what I send via webSocket.sendTXT(BufForOneAnalogLine) .

**Comment by Links2004** [comment]
looks like your Delphi code does not answer to the request.
you may try ```begin``` and not ```beginSocketIO```.

`sendTXT` only works after the connection where successful ;)

**Comment by sp9auv** [comment]
Hello !
I  try  **THttpServer**  component  in a Delphi but with this same negative result . 
Cooperating program with th browser Firefox as client

**Comment by Links2004** [comment]
your apache server is running a PHP backend with http/https communication.
this server does not speak the websocket protocol in you current configuration.
the server needs to answer with a the right headers (this is automaticly done when the server supports 
the websocket protocol).

a correct server answer looks for example like this:

```
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: HSmrc0sMlYUkAGmm5OPpG2HaGWk=
Sec-WebSocket-Protocol: arduino
```

if you need a ws server for testing or as base you can use
https://github.com/Links2004/arduinoWebSockets/tree/master/tests/webSocketServer

```
npm install
nodejs ./index.js
```

(nodejs required)
