### ISSUE TITLE
 ESP8266WiFi.h: No such file or directory

### ISSUE THREAD

**Issue by habi3000** [Links2004/arduinoWebSockets#293]
hi i am getting this error message when trying to compile your example
 ESP8266WiFi.h: No such file or directory

what i have tried so far 
1-added the esp8266 core to the arduino ide

best regards

**Comment by Links2004** [comment]
is a ESP8266 board selected in the IDE?

**Comment by habi3000** [comment]
why would i do that ? this library is for arduino, right?

**Comment by Links2004** [comment]
yes,
but if you use a example for the ESP8266 arduino core then you need to select the correct board in the arduino IDE.

**Comment by habi3000** [comment]
i tried that but now it is impossible to upload the code to a mega board

**Comment by Links2004** [comment]
if you want to use a AVR based board you need to use the version 1.x.x of the lib and the AVR example.

**Comment by habi3000** [comment]
ok thanks 
i will try that and inform you back
