### ISSUE TITLE
WStype_CONNECTED web socket event doesn't fire on connect 

### ISSUE THREAD

**Issue by chadham** [Links2004/arduinoWebSockets#297]
WebSocketEvent is called for the disconnect (WStype_DISCONNECTED) event but not for connected.

Runtime Serial output
STARTING
...Starting MDNS
WiFi IP is 10.0.1.83
Ready for socket connection
 // {pauses here until I stop the IOS app which causes a disconnect and the message below, but connect never gets called? }
Websocket Event of type 1
Disconnected

~~~

esp8266 code:

void webSocketEvent(uint8_t num, WStype_t type, uint8_t * payload, size_t lenght) {
  Serial.println("Websocket Event of type " + String(type));
  switch (type) {
    case WStype_DISCONNECTED:
      Serial.println("Disconnected");
      break;
    case WStype_CONNECTED:
      {
        Serial.println("connected");
        IPAddress ip = webSocket.remoteIP(num);
        Serial.println(ip);
      }
      break;
...

~~~

Am connecting from IOS using the SwiftWebSocket Library

        let socket = WebSocket("wss://10.0.1.83:80")
        socket.open()

Interestingly, if use a browser to visit 10.0.1.83 I get an error message in the browser "This is a Websocket server only!" which makes sense, but the output of my code is still 

Websocket Event of type 1
Disconnected

Shouldn't the connect fire first and then the disconnect?

Confirmed the IOS code is working fine by connecting to an external socket server with the same code..
 var socket = WebSocket("wss://echo.websocket.org")
 socket.open()

**Comment by Links2004** [comment]
there is no wss / tls support for the server part. 
with `"ws://10.0.1.83:80"` it will most likely work.

**Comment by chadham** [comment]
That was it. Thanks very much Markus!
