### ISSUE TITLE
WebSocketServer data not encrypted

### ISSUE THREAD

**Issue by versamodule** [Links2004/arduinoWebSockets#303]
Sorry, if this is not an issue.
Things are working just fine, but I am curious about one thing. 
When sending data from my web page to the "WebSocketServer" running on the ESP32 that the data is encrypted (via Wire Shark). However, when I send data from the ESP32 to the page it is in plain text. 
Why is it not encrypted as well ?  Did i miss something here ?

**Comment by Links2004** [comment]
Hi,

there is no encrypted, the data is scrambled / masked with a simple XOR key send with the message itself.
this is done to prevent caching in for example proxy (more details in the RFC6455).

do to hardware limitations (RAM) sometime it is not possible to create a full copy to do the XOR with then the key 0x00 0x00 0x00 0x00 is used which basically is plain ;)

for reverence:

TX:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.cpp#L197
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.cpp#L104

RX:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.cpp#L388
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.cpp#L419

hope this helps to understand it
