### ISSUE TITLE
Esp8266 slows down when websocket disconnects

### ISSUE THREAD

**Issue by nilavachowdhury** [Links2004/arduinoWebSockets#305]
Hey! Whenever the websocket gets disconnected from net , not wifi , all other function slows down , i have a code to turn on and off device's using webhook and also to turn it off and on using push button , everything works fine when internet is connected , but as its disconnected after pressing push button there is a lag of 2-3 sec after which the relay is turned on. However the issue happens around 5-7 seconds after disconnection from net.

**Comment by nilavachowdhury** [comment]
How to call it only when its running ? Also changing reconnect interval doesn't help. 
Whats async TCP variant ?

**Comment by Links2004** [comment]
the lib can use:
https://github.com/me-no-dev/ESPAsyncTCP
which makes the TCP calles (including the connect async)

https://github.com/Links2004/arduinoWebSockets#esp-async-tcp
