### ISSUE TITLE
WebsocketServer with STM32F1 and enc28j60 

### ISSUE THREAD

**Issue by zdila** [Links2004/arduinoWebSockets#307]
Hello,

Could this library be used to create websocket server on Maple Mini (STM32F1) with enc28j60?

Thank you

**Comment by Links2004** [comment]
I have not tried it but since there is Arduino for the STM32F1, you have a good change. 
There may some defines needed bit that is all.

https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L51-L167

**Comment by zdila** [comment]
Thank you.
