### ISSUE TITLE
Websocket client actively refuses server (python 10061)

### ISSUE THREAD

**Issue by BranchEnterprise** [Links2004/arduinoWebSockets#308]
I'm using a websocket library in Python.  I loaded your Webclient example for Esp8266(nodemcu). The output on my python terminal implies that I'm reaching my esp8266 client. I've also tested communication with another echoing client, echo.websocket (which works). I'm not so sure on your parameters for webSocket.begin(add,port,url). I've tried port 80,8080,4000,81. I've also tried my Ipv4 address, my public ip and other standard ipaddresses for routers (i want an internet-connected wifi server from my home). I've also tried disabling firewall on my computer. Any suggestions? I'm rather new to websockets and I want to control my esp(nodemcu) in realtime from python script. I am willing to attach files/screenshots if needed.

**Comment by Links2004** [comment]
which example do you use? 
```webSocket.begin(add,port,url)``` sound like you use the client.
from you message it sounds like the Python part is client too.

you need one server and one client. 

if the ESP is server (Python will connect to it) you need
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketServer/WebSocketServer.ino
or
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketServer_LEDcontrol/WebSocketServer_LEDcontrol.ino

if the Python part is the server you need 
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketClient/WebSocketClient.ino

the IP is the you local IP in the LAN / WiFi network.

**Comment by BranchEnterprise** [comment]
Thank you for the speedy reply. Uploading WebSocketServer.ino got me connected after I passed port 80 to the server object.

I want to ask you how the server can receive a message from the client. Should I post a different thread?

I know how to send messages with python, I just want the server to read them and use logic(if-then) to control my pins.

Does your library have a method for that?

**Comment by BranchEnterprise** [comment]
Thank for your help earlier. I was exploring the example today and found the webSocketEvent method (case WStype_Text). I just typecast the payload object and then I can use it to write my servos:

servoX.write(atoi((const char*)payload));
