### ISSUE TITLE
ESP32 WebSocketServer example does not compile (WStype_ERROR)

### ISSUE THREAD

**Issue by pandadom** [Links2004/arduinoWebSockets#319]
When running the ESP32 WebSocketServer example i get the following errors:

C:\Users\user\AppData\Local\Temp\arduino_modified_sketch_583664\WebSocketServer.ino: In function 'void webSocketEvent(uint8_t, WStype_t, uint8_t*, size_t)':

WebSocketServer:26: error: enumeration value 'WStype_ERROR' not handled in switch [-Werror=switch]

     switch(type) {

           ^

WebSocketServer:26: error: enumeration value 'WStype_FRAGMENT_TEXT_START' not handled in switch [-Werror=switch]

WebSocketServer:26: error: enumeration value 'WStype_FRAGMENT_BIN_START' not handled in switch [-Werror=switch]

WebSocketServer:26: error: enumeration value 'WStype_FRAGMENT' not handled in switch [-Werror=switch]

WebSocketServer:26: error: enumeration value 'WStype_FRAGMENT_FIN' not handled in switch [-Werror=switch]

cc1plus.exe: some warnings being treated as errors

Using library WiFi at version 1.0 in folder: C:\Users\user\Documents\Arduino\hardware\espressif\esp32\libraries\WiFi 
Using library WebSockets at version 2.1.0 in folder: C:\Users\user\Documents\Arduino\libraries\WebSockets 
Using library WiFiClientSecure at version 1.0 in folder: C:\Users\user\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure 
exit status 1
enumeration value 'WStype_ERROR' not handled in switch [-Werror=switch]

**Comment by per1234** [comment]
Note that you will need to set **File > Preferences > Compiler warnings** to "More" or "All" to reproduce this error. That's because the [ESP32 core sets](https://github.com/espressif/arduino-esp32/blob/master/platform.txt#L20-L21) the `-Werror=all` flag when those warning levels are selected but does not do this at lower warning levels.

**Comment by enrutador** [comment]
Hi Links2004

I have the same problem .The compilation in an esp8266 is perfect but when I use the esp32 it gives me the same error, I attached my "short" output of the" debug compiler warning All ":

Compilando programa...
"C:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++" -DESP_PLATFORM -DMBEDTLS_CONFIG_FILE="mbedtls/esp_config.h" -DHAVE_CONFIG_H "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/config" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/bluedroid" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/bluedroid/api" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/app_trace" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/app_update" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/bootloader_support" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/bt" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/driver" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/esp32" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/esp_adc_cal" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/esp_http_client" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/esp-tls" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/ethernet" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/fatfs" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/freertos" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/heap" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/jsmn" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/log" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/mdns" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/mbedtls" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/mbedtls_port" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/newlib" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/nvs_flash" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/openssl" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/spi_flash" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/sdmmc" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/smartconfig_ack" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/spiffs" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/tcpip_adapter" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/ulp" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/vfs" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/wear_levelling" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/xtensa-debug-module" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/coap" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/console" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/expat" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/json" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/lwip" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/newlib" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/nghttp" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/soc" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/wpa_supplicant" -std=gnu++11 -fno-exceptions -Os -g3 -Wpointer-arith -fexceptions -fstack-protector -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -mlongcalls -nostdlib -Wall -Werror=all -Wextra -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-sign-compare -fno-rtti -MMD -c -DF_CPU=240000000L -DARDUINO=10805 -DARDUINO_ESP32_DEV -DARDUINO_ARCH_ESP32 -DARDUINO_BOARD="ESP32_DEV" -DARDUINO_VARIANT="esp32"  -DESP32 -DCORE_DEBUG_LEVEL=0  "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32\cores\esp32" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32\variants\esp32" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32\libraries\WiFi\src" "-IC:\Users\admin\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure\src" "-IC:\Users\admin\Documents\Arduino\libraries\WebSockets\src" "C:\Users\admin\AppData\Local\Temp\arduino_build_179330\sketch\WebSocketClient.ino.cpp" -o "C:\Users\admin\AppData\Local\Temp\arduino_build_179330\sketch\WebSocketClient.ino.cpp.o"
C:\Users\admin\Documents\Arduino\libraries\WebSockets\examples\esp32\WebSocketClient\WebSocketClient.ino: In function 'void webSocketEvent(WStype_t, uint8_t*, size_t)':

WebSocketClient:39: error: enumeration value 'WStype_ERROR' not handled in switch [-Werror=switch]

  switch(type) {

        ^

WebSocketClient:39: error: enumeration value 'WStype_FRAGMENT_TEXT_START' not handled in switch [-Werror=switch]

WebSocketClient:39: error: enumeration value 'WStype_FRAGMENT_BIN_START' not handled in switch [-Werror=switch]

WebSocketClient:39: error: enumeration value 'WStype_FRAGMENT' not handled in switch [-Werror=switch]

WebSocketClient:39: error: enumeration value 'WStype_FRAGMENT_FIN' not handled in switch [-Werror=switch]

cc1plus.exe: some warnings being treated as errors

Se encontraron múltiples librerías para "WiFi.h"
Usado: C:\Users\admin\Documents\Arduino\hardware\espressif\esp32\libraries\WiFi
 No usado: C:\Program Files (x86)\Arduino\libraries\WiFi
Usando librería WiFi con versión 1.0 en la carpeta: C:\Users\admin\Documents\Arduino\hardware\espressif\esp32\libraries\WiFi 
Usando librería WiFiClientSecure con versión 1.0 en la carpeta: C:\Users\admin\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure 
Usando librería WebSockets con versión 2.1.0 en la carpeta: C:\Users\admin\Documents\Arduino\libraries\WebSockets 
exit status 1
enumeration value 'WStype_ERROR' not handled in switch [-Werror=switch]

**Comment by enrutador** [comment]
Hi Links2004
I solved the problem modify in the preferencess-> compiler warnigs-> to default
Thanks

**Comment by bharathsudharsan** [comment]
> Hi Links2004
> I solved the problem modify in the preferencess-> compiler warnigs-> to default
> Thanks

Perfect. Yes worked perfect. Thanks.
