### ISSUE TITLE
messageReceived how to use?

### ISSUE THREAD

**Issue by tahnaconus** [Links2004/arduinoWebSockets#324]
sorry to bother you, i'm newbie and i dont know how to read data from server nodejs (esp8266 client). Could you teach me? many thanks

**Comment by Links2004** [comment]
there is no "read".
the server needs to send data form it self, or you need to send a message bevor this.

if you get a message from the server it will end up in the `webSocketEvent` callback.
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketClient/WebSocketClient.ino#L35

to send a message to the server you can use `webSocket.sendTXT("message here");`

**Comment by tahnaconus** [comment]
thanks you so much. I did it! 👍
