### ISSUE TITLE
WebSocketClient reconnection freezes a few seconds

### ISSUE THREAD

**Issue by leventesen** [Links2004/arduinoWebSockets#326]
When my websocket server is offline and WebSocketClient tries to reconnect, NodeMCU freezes a few seconds.

**Comment by ThePaceMaker** [comment]
How long is a piece of string?

**Comment by leventesen** [comment]
Sorry, I couldn't understand your question.

**Comment by Links2004** [comment]
the freeze is exacted in the sync version, the TCP stack waits some time before the connect call returns.
there are two ways around this:

- only calling the `loop` function when you are sure to have a network connection
- using the async TCP lib for the ESP8266

**Comment by leventesen** [comment]
Second option will solve the problem. Thanks.
