### ISSUE TITLE
gpn18 merge into Master

### ISSUE THREAD

**Issue by ThePaceMaker** [Links2004/arduinoWebSockets#330]
I was just wondering if there is some sort of  E.T.A when (or even if) the gpn18 branch will be merged into master with a stable release spat out.

@Links2004 I imagine that this would be your decision at the end of the day.

**Comment by Links2004** [comment]
all stuff that is not part of the socket.IO implementation is part of the master branch.
the last problem is that the tests are brocken currently do to a BUG ESP8266 
https://github.com/esp8266/Arduino/issues/4740

**Comment by ThePaceMaker** [comment]
Thanks for the update. I will dev off the master branch for now.
