### ISSUE TITLE
Interaction of ESP8266 with VDS via WebSockets

### ISSUE THREAD

**Issue by DeltaVetal26** [Links2004/arduinoWebSockets#331]
Hi! There are many ESP8266 with sensors and relays connected to them, which can be scattered at different ends of the earth. There is a VDS (the main server) that is located in the data center (OVH). ESP will connect to the main server and exchange information with it (data transmission, receiving answers for switching on LEDs or relays). For several days I searched the Internet for ways to implement this idea and came across the WebSockets technology. ESP should be a client, and VDS as the main server, when the client connects to the server, it must transfer its client_id, through which the server will determine the name of the device and give commands. In ArduinoWebSockets, I did not find a clear example where ESP in the role of the client can receive / send data to my server and perform actions. Questions: are there any examples where ESP as a client takes values ​​from the server and for example turns on the LED? Is it possible to transfer the device key to the server? (like I saw in WebSocketClientIO.ino) Unfortunately, without documentation, I do not particularly understand the principle of work. I will be very glad to your help!

**Comment by Links2004** [comment]
Hi,

you clearly looking for the `WebSocketClient` example.

the Client get messages from the server, and will print them to serial (`get text`),
you simply need to switch the LED or Relay on when you get a message / text.

sending messages to the server is easy too, 
put this in you code when you want to send a message:

```cpp
 webSocket.sendTXT("message here");
```

https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketClient/WebSocketClient.ino

**Comment by DeltaVetal26** [comment]
Hi! Thanks for the help! Now I plan to install on the server Workerman and start experiments :)
