### ISSUE TITLE
How to open / close a connection to the WebSocketServer?

### ISSUE THREAD

**Issue by DeltaVetal26** [Links2004/arduinoWebSockets#333]
Hi! I use ESP8266 as a websocket client. Now I have connected to the WebSocket Server (WorkerMan) and have successfully exchanged messages. As I understand it, when you start ESP, a permanent connection is created between the client and the server. I want to close the connection between the client and the server when, for example, I end the execution of a certain action in the code
 Also, I would like to renew the connection at any time. In the description of ArduinoWebSocket, I saw that it can close the connection, but did not find a command for this. Is there a command to open / close a connection? I noticed that the client creates a new connection from the previous one:
https://imgur.com/a/xfeOaNa Thank you!

**Comment by Links2004** [comment]
call the `disconnect` function:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.h#L80
and not the `loop` function until you want to connect again.

as soon you call `loop` again the connection is established again.
