### ISSUE TITLE
haven't close() or end() server in async mode in ESP8266

### ISSUE THREAD

**Issue by tarzan115** [Links2004/arduinoWebSockets#336]
I have a problem when I create an AP with websocketserver after that I turn off, and turn on. but when I turn on again. I can't access websocket anymore.

**Comment by Links2004** [comment]
there is a close function in the current git version
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsServer.h#L52
but I not have tested it with the async variant

**Comment by Links2004** [comment]
can this be closed in favor of #340?
