### ISSUE TITLE
disconnecting problem after 15s

### ISSUE THREAD

**Issue by doit4fun** [Links2004/arduinoWebSockets#338]
I'm using WebSocketClientSocketIO.ino example and I noticed this:

when commenting hartbeat sentTXT message 
//webSocket.sendTXT("2");
and message 
 //webSocket.sendTXT("42[\"messageType\",{\"greeting\":\"hello\"}]");

then my client disconnects on every 15s.
this means that if I don't send any message to my socket server... in 15s then the client loses the connection with the server.
This is bad!... it means that every 15s I should send a fake message to server in order to keep my connection alive and this is no longer a good thing
is there a fix for this?

**Comment by Links2004** [comment]
do you have a SocketIO backend or a plain websocket server?

**Comment by doit4fun** [comment]
I have a SocketIO backend

**Comment by doit4fun** [comment]
the connection disconnecting ... solved it by adding to the server

var io = require('socket.io')(server, {
    //path: '/test',
    //serveClient: false,
    // below are engine.IO options
    pingInterval: 30000,
    pingTimeout: 5000,
    //cookie: false
  });

**Comment by doit4fun** [comment]
only the response RES:3 I couldn't figure out how to deactivate it

**Comment by doit4fun** [comment]
server setting transports: ['websocket'] just doesn't allow the connection of the client.

**Comment by Links2004** [comment]
for SocketIO the ping pong is required / specified in the SocketIO / engine IO Protokoll 

the first HTTP "polling" connection is used to get the cookies for the websocket connection.
if you change that you have no cookie and with that no auth for the websocket.

I have stated a more complete SocketIO Implementation in the gpn18 branch, but the work there is not finished yet.
https://github.com/Links2004/arduinoWebSockets/blob/gpn18/src/SocketIOclient.h
https://github.com/Links2004/arduinoWebSockets/blob/gpn18/src/SocketIOclient.cpp

the code there will handle all the "numbers" you see.

**Comment by Links2004** [comment]
new version with Socket.IO 2.0 support is released.
this will handle all the needed Ping / Pong and message decode.
