### ISSUE TITLE
receiving from server 

### ISSUE THREAD

**Issue by doit4fun** [Links2004/arduinoWebSockets#339]
I've noticed that when connecting to the server I receive a response from the server every time I send a message
[WSc] get text: 3
also if I don't send a message at all then the client will disconnect automatically every 15s

I have tried in several ways not to receive this response
1.modifying and forcing the parameters in
void WebSocketsClient::beginSocketIO 
_client.cIsUpgrade = true;
 _client.cIsWebsocket = true;

2. also forcing the transport to websocket and not pulling:
url += WEBSOCKETS_STRING("&transport=websocket&sid=");
url += client->cSessionId;

still I haven't get rid of response from the server
also I have this issue that if I don't send a message to the server...my connection closes on every 15s.

**Comment by Links2004** [comment]
please keep the problem in one issue:
#338
