### ISSUE TITLE
WiFiManager not compatible Tzapu

### ISSUE THREAD

**Issue by doit4fun** [Links2004/arduinoWebSockets#341]
The client in example keeps disconnecting when using it together with https://github.com/tzapu/WiFiManager

The client is connecting to the socket.io server but after that it disconnects rapidly. 
using it with wifiMulti like in your fast example it works but with tzapu WifiManager not.

The problem is that you are building a library on WifiMulti that is poses a lot of issues

**Comment by doit4fun** [comment]
problem solved!
don't ever comment the line 

  web_socketIO.sendTXT("5");

from the event declaration case

 case WStype_CONNECTED:
            {
              Serial.printf("[WSc] Connected to url: %s\n",  payload);
              isConnected = true;
  
              // send message to server when Connected
              // socket.io upgrade confirmation message (required)
               web_socketIO.sendTXT_srv("5");
            }

because it will connect and disconnect like hell

**Comment by Links2004** [comment]
yes the 5 is importierend

```
  eIOtype_UPGRADE = '5', ///< Before engine.io switches a transport, it tests, if server and client can communicate over this transport. If this test succeed, the client sends an upgrade packets which requests the server to flush its cache on the old transport and switch to the new transport.
```

https://github.com/Links2004/arduinoWebSockets/blob/gpn18/src/SocketIOclient.h#L24
