### ISSUE TITLE
event declared in other .cpp file

### ISSUE THREAD

**Issue by doit4fun** [Links2004/arduinoWebSockets#342]
the event "void webSocketEvent" you can't declare it in other .cpp because when accessing it with 
webSocket.onEvent(webSocketEvent); you get a compiler error that doesn't recognise the type of webSocketEvent

**Comment by Links2004** [comment]
you need to add it to a header file with the correct signature.

```cpp
void webSocketEvent(WStype_t type, uint8_t * payload, size_t length);
```

for the WStype_t you need too include the websocket header files.
