### ISSUE TITLE
malloc without free

### ISSUE THREAD

**Issue by remoteme** [Links2004/arduinoWebSockets#344]
Hello,
while sending lot of binary messages to my websocketClient i noticed that after some time my Wemos stop working
after some research I've found one thing
```
void RemoteMe::webSocketEvent(WStype_t type, uint8_t *payload, size_t length) {
		.....
		case WStype_BIN:
			if (length > 0) {
				RemoteMe::getInstance("", 0).processMessage(payload);
				free(payload); //after add this line my problem dissapear
			}
			
		}
```
I guess u malloc payload but its never free. Also You didnt free payload at your websocketClient examples so I dont know if what I've made is correct.
Thanks

**Comment by remoteme** [comment]
I think it was my fault :)

**Comment by MSofianHB** [comment]
Hi @remoteme 

I also have the same idea ,What was the fault please?
note: I traced the Heap size it's not accumulated ,but I didn't know where the free() function is called. 

Thanks in advanced
