### ISSUE TITLE
Esp8266- Websocket client have multiple connection

### ISSUE THREAD

**Issue by Amir24HG** [Links2004/arduinoWebSockets#346]
Hi 
I am trying to have multi websocket client connetion and each one connect to different websocket server.
The first way that i test and it did not work is to have multi object like blow:
WebSocketsClient webSocket1
WebSocketsClient webSocket2
And use them separately but it connect to only one websocket server.

Thanks in advance 
Best wishes

**Comment by Amir24HG** [comment]
im sorry i fixed problem as i said

**Comment by karanmakharia** [comment]
@Amir24HG How did you resolve this issue? Please tell us the solution
