### ISSUE TITLE
error rst cause:4, boot mode:(3,6)

### ISSUE THREAD

**Issue by dwc56** [Links2004/arduinoWebSockets#347]
when i am using the example on a esp8266 sometimes i get this error

 ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v614f7c32
~ld

**Comment by Links2004** [comment]
wdt reset, means that the ESP has been blocked for too long by something.
that can have many reasons.

first check if you Hardware is stable and make sure you run the latest Arduino IDE and core for the ESP8266
https://github.com/esp8266/Arduino/blob/master/doc/boards.rst#generic-esp8266-module
