### ISSUE TITLE
How to use Ping - Pong

### ISSUE THREAD

**Issue by Loucotolo** [Links2004/arduinoWebSockets#351]
Using ESP8266 E12 with arduinoWebSockets.
How can I make use of Ping to detect if the WebSocket server is down?
I am trying to send a Ping to the server expecting a Pong response before a defined timeout.
First on calling `webSocket.sendPing();` the client ESP8266 crashes: 
arduinoFatal exception 28(LoadProhibitedCause). (...)

Can someone pleas enlighten me how to use these functions correctly?
A brief example would be highly appreciated.

**Comment by Links2004** [comment]
calling ```webSocket.sendPing``` is the way to go if the connection is down the lib will automatically try to reconnect.

can you decode the stack trace of the crash?

**Comment by Loucotolo** [comment]
The stack trace:
[SETUP] BOOT WAIT 4...scandonestate: 0 -> 2 (b0)state: 2 -> 3 (0)state: 3 -> 5 (10)add 0aid 7cnt connected with IOLine, channel 1dhcp client start...[SETUP] BOOT WAIT 3...[SETUP] BOOT WAIT 2...ip:192.168.0.231,mask:255.255.255.0,gw:192.168.0.1[SETUP] BOOT WAIT 1...[WS-Server] Server Started.[WS-Server][0] new client from 192.168.0.200[WS-Server][0][handleHeader] RX: GET / HTTP/1.1[WS-Server][0][handleHeader] RX: Host: 192.168.0.231:81[WS-Server][0][handleHeader] RX: Connection: Upgrade[WS-Server][0][handleHeader] RX: Upgrade: websocket[WS-Server][0][handleHeader] RX: Sec-WebSocket-Version: 13[WS-Server][0][handleHeader] RX: Sec-WebSocket-Key: HQ4CLUMY3QlUtSck7I2NNA==[WS-Server][0][handleHeader] RX: Sec-WebSocket-Protocol: arduino[WS-Server][0][handleHeader] RX: Origin: file://[WS-Server][0][handleHeader] RX: User-Agent: arduino-WebSocket-Client[WS-Server][0][handleHeader] Header read fin.[WS-Server][0][handleHeader]  - cURL: /[WS-Server][0][handleHeader]  - cIsUpgrade: 1[WS-Server][0][handleHeader]  - cIsWebsocket: 1[WS-Server][0][handleHeader]  - cKey: HQ4CLUMY3QlUtSck7I2NNA==[WS-Server][0][handleHeader]  - cProtocol: arduinoFatal exception 28(LoadProhibitedCause):epc1=0x4020d158, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000
Exception (28):
epc1=0x4020d158 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000
ctx: cont sp: 3fff0ee0 end: 3fff13a0 offset: 01a0
>>>stack>>>3fff1080:  4020b874 3fff1180 3fff1122 40207c24  
3fff1090:  00000001 401022a8 3fffc200 00000022  
3fff10a0:  3ffe8304 00000000 0000000a 3ffe9d14  
3fff10b0:  3fff1123 3ffe95ba 7fffffff 00000000  
3fff10c0:  00000022 40103526 00040000 3ffe95dc  
3fff10d0:  00000000 3ffe8304 3fff1180 4020bcd4  
3fff10e0:  00000000 ffffffff 00000000 00000000  
3fff10f0:  00000001 0000002d 3f302073 00000022  
3fff1100:  40201c08 00000030 00000013 ffffffff  
3fff1110:  402059b5 00000000 00000057 0000007f  
3fff1120:  0030007e 6000001c 00000030 3fff10f9  
3fff1130:  00000080 3fff1230 00000000 3fff02b0  
3fff1140:  3fff12b0 3fff1280 00000010 00000001  
3fff1150:  3ffe95db 00000020 3fff12f8 00000030  
3fff1160:  4010372a 00000010 7fffffff 3fff1340  
3fff1170:  3fff02b0 3ffe8304 00000040 402096b5  
3fff1180:  3fff125d 00080000 00000012 ffff0208  
3fff1190:  3fff1230 0000003f 00002200 4000050c  
3fff11a0:  3fffc278 401022a8 3fffc200 00000022  
3fff11b0:  3fff11c0 3fff350c 00000001 3fff12f8  
3fff11c0:  402065a2 00000030 00000013 ffffffff  
3fff11d0:  40205339 3fff12f8 00000000 00000001  
3fff11e0:  00000000 00000019 ff000000 00000000  
3fff11f0:  00000066 00000008 3ffef8a0 402096f8  
3fff1200:  3fff12b0 3fff1280 00000008 40206dd0  
3fff1210:  3fff36a4 0000002c 3fff33cc 00000033

**Comment by Loucotolo** [comment]
The ping routine takes a long time to detect that the server is off.
How can I put this time smaller?
Example:
I have the client ping the server, I disconnect the server, and the ping still continues to return true, it's only a few seconds past, and it returns false. is there any way for it to return fake immediately?

**Comment by Links2004** [comment]
the Time comes from the TCP stack.
and some aspects can be changed via setTimeout on the TCP client.
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.cpp#L696

which can be controlled via the define here:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L82

But the setTimeout will not effact all timeouts the TCP stack has,
but it may helps in your case.
