### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by gudaja** [Links2004/arduinoWebSockets#36]
Arduino 1.6.7
core_esp8266_features.h: No such file or directory

**Comment by Links2004** [comment]
for the latest version you need the git version of the core.
#32, #30

**Comment by Galilei11** [comment]
i think, It works only with Arduino !!! 1.6.5 !!!!!  You need downgrade, try it , it help me :)

**Comment by gudaja** [comment]
In 1.6.5 does't work.
This is the resolve problem https://github.com/Links2004/arduinoWebSockets/issues/32.
