### ISSUE TITLE
Q: How to enable debug messages in WebSockets

### ISSUE THREAD

**Issue by gufonero** [Links2004/arduinoWebSockets#365]
Hello,

I have been struggling for a few days with a memory leak which seems to be caused by some inner component under WebSocketsServer. To help in diagnosing the problem I have been trying to enable the debug messages. I was expecting to be able to do it by somehow #defining DEBUG_WEBSOCKETS, either as a global build flag or even modifying the library, but after several attempts and many searches for instructions on the topic I could not make it work. I must be missing something obvious; could anybody please point me to some concrete instructions on how to do it? 

My development environment is platformio, with ESP8266 as target microcontroller.

**Comment by Links2004** [comment]
you need to set the DEBUG_ESP_PORT define global via compiler comandline
```-DDEBUG_ESP_PORT=Serial``` not sure how you do it with platformio but there sure is a option.

Alternative you need to edit the file here:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L46

**Comment by gufonero** [comment]
Ok, that one was easy. Works like a charm! Thank you very much!

Anybody else needing to enable debug tracing in platformio, just add `-DDEBUG_ESP_PORT=Serial` in the build_flags section of your `platformio.ini` file.

If I may make a suggestion, I think it would be useful for other people to have that hint you just gave to me in a more visible place, maybe in the readme or even in the code itself.

Thank you again for your effort in developing and maintaining this library!
