### ISSUE TITLE
Websocket Server example: only client diconnect generates websocket event

### ISSUE THREAD

**Issue by Molyo** [Links2004/arduinoWebSockets#366]
Hi,

I downloaded the [WebsocketServer ](https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketServer/WebSocketServer.ino )example to my ESP8266 device. Enabled the debug and tested it with Hercules TCP client program (www.HW-group.com).
I could connect to the ESP send binary and ASCII data and disconnect also, but only the disconnect generates  websocketEvent in the code ([0] Disconnected!)
In debug mode I can see all event is recieved by ESP but they don't generates websocketEvent.

Could you tell me what did I wrong, what is missing?

Below you can see  Arduino serial monitor. First I connect to the ESP server, then I send ASCII data binary data and finally I disconnect.

```
[SETUP] BOOT WAIT 4...
wifi evt: 2
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 1
cnt 

connected with Agica, channel 1
dhcp client start...
wifi evt: 0
[SETUP] BOOT WAIT 3...
[SETUP] BOOT WAIT 2...
ip:192.168.1.70,mask:255.255.255.0,gw:192.168.1.254
wifi evt: 3
[SETUP] BOOT WAIT 1...
[WIFI][APlistAdd] add SSID: Agica
[WS-Server] Server Started.
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
WS:ac
:ref 1
WS:av
:ref 2
:ur 2
[WS-Server][0] new client from 192.168.1.69
:rn 8
:c0 1, 8
[WS-Server][0][handleHeader] RX: abcdefgh
wifi evt: 7
wifi evt: 7
wifi evt: 7
:rn 8
[WS-Server][0][handleHeader] RX: 
:c0 1, 8
[WS-Server][0][handleHeader] RX: 
:rcl
:abort
[WS-Server][0] client connection lost.
:ur 1
WS:dis
:del
[WS-Server][0] client disconnected.
[0] Disconnected!
```

Thank you for your help!

**Comment by Links2004** [comment]
you need a websocket client not a TCP client ;)
you can try to use:
https://websocket.org/echo.html

most languages have a websocket client.
your browser has one build in.

**Comment by Molyo** [comment]
Aaah, yes you are right!
I tought TCP socket and Websocket are compatible, but now I see it is not. :-)

Thank you for your help!

Regards:

Balazs
