### ISSUE TITLE
How to break/split the received payload into separate variables ?

### ISSUE THREAD

**Issue by denden4444** [Links2004/arduinoWebSockets#367]
Hi all 
I am sending this from the client 
`#,tank,pond,1537272000,1537272000,Normal,4789,12`

I received here in the code:
`case WStype_TEXT:
    Serial.printf("[%u] get Text: %s\n", num, payload);`
this is the result of what I receive
`[0] here it is: #,tank,pond,1537272000,1537272000,Normal,4789,12`

I am using a hash(#) to mark the start of the data.
What is the fastest most elegant way to split this up into different variables so that they can be compared?

I hope someone can help.

Thank you

**Comment by Links2004** [comment]
you most likely looking for ```strtok```.
http://www.cplusplus.com/reference/cstring/strtok/

**Comment by denden4444** [comment]
Hi Link2004 
Thanks a million for a great library and the useful info it offers by the way.

I'm sure there are many options to accomplish what I am asking : 
strtok .. would work I guess but that needs a char array not so ?
sscanf would probably also work but i'm not having great results with that either.

I have been battling for nearly two weeks or more with this conversion thing and seems like I'm just going in circles all the time.

Where I am stuck is here `void webSocketEvent(uint8_t num, WStype_t type, uint8_t * payload, size_t lenght) { // When a WebSocket message is received` 
What format is payload in to begin with ?
And what happens to it ?
Is it a character buffer ?
Can't it be broken/split up directly ?
I know what I'm sending and I know what I need done to the received data but how ?
Would you happen to have a simple example to get me going ?

I look forward to your reply or any others

Den

**Comment by Links2004** [comment]
the payload is ```uint8_t *``` which is the same as ```unsigned char *```.
the pointer will contain you text that is send form you client.

not tested code, but it will help to get the idea:

```cpp
void webSocketEvent(uint8_t num, WStype_t type, uint8_t * payload, size_t lenght) {
  Serial.printf ("Splitting string \"%s\" into tokens:\n", payload);
  char * pch = strtok ((char*)payload, ",");
  while (pch != NULL)
  {
    Serial.printf ("%s\n", pch);
    // TODO store the values where you need them
    pch = strtok (NULL, ",");
  }
}
```

**Comment by denden4444** [comment]
@Links2004

Thank you very much for taking the time to reply, I really appreciate it bigtime...you rock!
I will test that as soon as I get a chance and feedback on results.

Kind regards 
Den

**Comment by denden4444** [comment]
Hi Markus .. solved this by using sscanf ..thanks again.
