### ISSUE TITLE
App android not connect to websocket server in esp8266

### ISSUE THREAD

**Issue by PhuongNguyenETIT** [Links2004/arduinoWebSockets#368]

**Comment by Links2004** [comment]
please add debug log, and some more description.
like this its impossible to help you.

**Comment by PhuongNguyenETIT** [comment]
Thank you for responding. I have a problem on the Android app. I can not use the app to connect to mDNS of eps8266. But I connect by IP address then my app is connected.

**Comment by Links2004** [comment]
looks like a mDNS problem, not a websocket problem.
have you verified that the mDNS is working at all?
you may need to ask in the ESP8266 forum.
