### ISSUE TITLE
Websockets server and websockets client on same esp8266

### ISSUE THREAD

**Issue by denden4444** [Links2004/arduinoWebSockets#371]
@Links2004 

Hi Markus ... what is the major difference between websockets client and websockets server ? 

More specifically can i initiate a client connect from the sever without having to load the client library ?

The reason for this is server to server communications.

Can I run both server and client one same esp without having to load the client library ?

Can both client and server co-exist happily on same library ?

I look forward to your replies

**Comment by Links2004** [comment]
server and client are in one library, they reuse most of the code base internally ;)
you can have a client and server in the same program with out any problems.
multiple client is possible too.

#136 will give you a example

**Comment by denden4444** [comment]
Hi Markus 

Thanks a million for this reply :-) Finally getting to test it and apologies for the late reply 

Den

**Comment by denden4444** [comment]
Hi Markus
I have loaded and been trying the example here on #136 but I just keep getting 
`[WSc] Disconnected!
`
The message just repeats every 3000 ms as per the code.

Could you possible shed some light as to why or perhaps what I could change for it to generate something useful like  a ping pong test ?

Kind regards 
Den

**Comment by denden4444** [comment]
Is there anyone reading this who can please help me with server and client on same server ? this is the final phase of my project and I'm stuck here :-(

**Comment by me21** [comment]
Your function needs to be rewritten. Currently it looks like:

```
  void tx_esp(char* payload) {
  // server address, port and URL
  webSocketClient.loop();// constantly check for websocket CLIENT events
  webSocketClient.begin("192.168.1.193", 81, "/");
  Serial.println("WebSocket Client started ..sending message");
  Serial.printf("[WSc] get text: %s\n", payload);
  webSocketClient.sendTXT("^");
  
  webSocketClient.disconnect();
  };
```
It calls `begin` and then `sendTXT`. But WebSocket Client hasn't yet got a chance to connect! You need to watch the events of WebSocket Client (in `webSocketClientEvent`) and call `sendTXT` only AFTER you get a succesful connection to server B.

Hope this helps!

**Comment by denden4444** [comment]
> Your function needs to be rewritten. Currently it looks like:
> 
> ```
>   void tx_esp(char* payload) {
>   // server address, port and URL
>   webSocketClient.loop();// constantly check for websocket CLIENT events
>   webSocketClient.begin("192.168.1.193", 81, "/");
>   Serial.println("WebSocket Client started ..sending message");
>   Serial.printf("[WSc] get text: %s\n", payload);
>   webSocketClient.sendTXT("^");
>   
>   webSocketClient.disconnect();
>   };
> ```
> It calls `begin` and then `sendTXT`. But WebSocket Client hasn't yet got a chance to connect! You need to watch the events of WebSocket Client (in `webSocketClientEvent`) and call `sendTXT` only AFTER you get a succesful connection to server B.
> 
> You need to watch the events of WebSocket Client (in `webSocketClientEvent`)
> 
> Hope this helps!

@me21 

Thanks  million for the reply.

Could you please elaborate on this : You need to watch the events of WebSocket Client (in `webSocketClientEvent`)
?
and 
regarding this : In addition, you need to call `loop` function of WebSocket Client not here, but in the main application loop, so that it constantly gets and takes care of new events.
I can't keep it in the main loop since the plan is to connect,establish a webSocket , send data and then drop/close the connection.

I would appreciate any further advice/help/tips etc

Den

**Comment by me21** [comment]
But you need it to be in the main loop. Just call it on some condition, when needed.

The events of websocket client are watched by handler function you register with `webSocketClient.onEvent(webSocketClientEvent);`

You just need to write `webSocketClientEvent` function which will receive various events like connection, disconnection, data reception, etc.

**Comment by denden4444** [comment]
@me21 
Hi Thank you for the reply .. it does  sort of make sense .. could you possibly add a stub of code as an example ? 
I basically need to send one packet though from wsClient to wsServer and then close/end the the wsCleint connection.

Kind regards

Den

**Comment by me21** [comment]
Hey @denden4444, is it possible to close this issue now? I believe we have solved your question in Gitter.

**Comment by denden4444** [comment]
@me21 Yes please close this now as it is solved .. thank you kindly

**Comment by me21** [comment]
@denden4444 I cannot. You're the author of the issue, and you should close it ;-)
