### ISSUE TITLE
Arduino connects and disconnects from Socket IO server

### ISSUE THREAD

**Issue by amirduran** [Links2004/arduinoWebSockets#372]
I have a simple scenario where I want to connect my mobile app and my arduino through Socket IO server. 

I implemented code that connects my Arduino UNO with SocketIO server. The problem is that Arduino connects for a few seconds and then disconnects again and this scenario repeats.

On my router I can see that Arduino is connected to my WiFi with correct IP address (which I can see in serial window of arduino too). My mobile app connects to Socket IO server and can send data without any problem (I can see that I'm receiving that data on the server side).

So the only problem is that Arduino disconnects from my Socket IO server without any reason and I can't receive any data. 

I'm using example code from your library: 

https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketClientSocketIO/WebSocketClientSocketIO.ino

Any ideas what could be the reason?

**Comment by Links2004** [comment]
does the same happen with the ESP8266?
Unfortunately debugging on the Arduino UNO is a little hard since it does not support Serial printf.

**Comment by amirduran** [comment]
At the end it worked like a charm. We uploaded older version of code and that was the problem. Thank you for support.
