### ISSUE TITLE
Websocket Client Doesn't Reach WStype_DISCONNECTED Callback When Server Disconnects Using ESP8266 Async

### ISSUE THREAD

**Issue by ianwillianb** [Links2004/arduinoWebSockets#373]
In the async implementation the client is able to reconnect as soon as the server becomes available, but when the server is off the callback WStype_DISCONNECTED is not being executed. 
How can I get the connection status, since the flag isconnected used in the client exemple is not being set as false because the program never reaches the WStype_DISCONNECTED.

The code I'm using is shown below:
```cpp
#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>
#include <WebSocketsClient.h>
#include <ESPAsyncTCP.h>
#include <Hash.h>

ESP8266WiFiMulti WiFiMulti;
WebSocketsClient webSocket;

#define MESSAGE_INTERVAL 30000
#define HEARTBEAT_INTERVAL 25000

uint64_t messageTimestamp = 0;
uint64_t heartbeatTimestamp = 0;
bool isConnected = false;

void webSocketEvent(WStype_t type, uint8_t * payload, size_t lenght) {

    switch(type) {
        case WStype_DISCONNECTED:
            Serial.printf("[WSc] Disconnected!\n");
            isConnected = false;
            break;
        case WStype_CONNECTED:
            {
                Serial.printf("[WSc] Connected to url: %s\n",  payload);
                isConnected = true;

                // send message to server when Connected
                // socket.io upgrade confirmation message (required)
                webSocket.sendTXT("5");
            }
            break;
        case WStype_TEXT:
            Serial.printf("[WSc] get text: %s\n", payload);

            // send message to server
            // webSocket.sendTXT("message here");
            break;
        case WStype_BIN:
            Serial.printf("[WSc] get binary lenght: %u\n", lenght);
            hexdump(payload, lenght);

            // send data to server
            // webSocket.sendBIN(payload, lenght);
            break;
    }

}

void setup() {
    // USE_SERIAL.begin(921600);
    Serial.begin(115200);

    //Serial.setDebugOutput(true);
    //USE_SERIAL.setDebugOutput(true);

    Serial.println();
    Serial.println();
    Serial.println();

      for(uint8_t t = 4; t > 0; t--) {
          Serial.printf("[SETUP] BOOT WAIT %d...\n", t);
          //Serial.flush();
          delay(1000);
      }

    //WiFiMulti.addAP("estacaoBase", "senhasenha123");
      WiFiMulti.addAP("net", "password");
    //WiFi.disconnect();
    while(WiFiMulti.run() != WL_CONNECTED) {
        delay(100);
    }

    //webSocket.beginSocketIO("192.168.0.5",8555,"/ws");
    webSocket.begin("192.168.0.5",8555,"/ws");
    //webSocket.setAuthorization("user", "Password"); // HTTP Basic Authorization
    webSocket.onEvent(webSocketEvent);

}

void loop() {
    webSocket.loop();

    if(isConnected) {

        uint64_t now = millis();

        if(true) {
            messageTimestamp = now;
            // example socket.io message with type "messageType" and JSON payload
            webSocket.sendTXT("C0");
            printf("Inicio do delay!\n");
            delay(5000);
            printf("fim do delay!\n");
        }
        if((now - heartbeatTimestamp) > HEARTBEAT_INTERVAL) {
            heartbeatTimestamp = now;
            // socket.io heartbeat message
            //webSocket.sendTXT("2");
        }
    }
}
```

**Comment by Links2004** [comment]
please enable debug logging, may we see the problem there.
the TCP stack can only detect a disconnect when you send data, but from you code it looks like you send data already around every 5sec. 
may its the fact that you stop calling the loop for 5sec with the `delay`, 
you can try to implement the timer with millis like for the heartbeat.

**Comment by ianwillianb** [comment]
I enable debug logging setting Serial.setDebugOutput(true), is that correct?
LOG:
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 18
cnt 

connected with NetBolf, channel 11
dhcp client start...
ip:192.168.0.15,mask:255.255.255.0,gw:192.168.0.1
[SETUP] BOOT WAIT 3...
[SETUP] BOOT WAIT 2...
[SETUP] BOOT WAIT 1...
[WSc] Connected to url: /ws
Delay Start!
[WSc] get text: Client Connected To Server! --Receive Message From Server When Connection Was Established
[WSc] get text: C5 -- Received Message From Server
Delay End!
Delay Start!
pm open,type:2 0
[WSc] get text: C5
Delay End!
//At this point the server was off, and the client doesn't reach WStype_DISCONNECTED
Delay Start!
Delay End!
Delay Start! 
Delay End!
Delay Start! 
Delay End!

When using the **sync** mode and the server is down, I get the message [WSc] Disconnected. 

However in **async mode**, the code never reaches  WStype_DISCONNECTED, setting the isConnected flag as false when the server is down.  The loop shouldn't matter since I'm using asynchronous mode. 
The interesting fact is that as soon as the server is up again, the client/ESP8266 reconnects automatically. Is it possible to detect when server is off in the asynchronous client implementation?

**Comment by TuxRobotics** [comment]
See #363 for possible solution
