### ISSUE TITLE
How to send data but with a name so the webpage can differentiate from other data

### ISSUE THREAD

**Issue by Aggeloz** [Links2004/arduinoWebSockets#375]
i want to send data (humidity and temperature) to the webpage but i want them to have a name so the webpage can differentiate them

**Comment by Links2004** [comment]
best way to do this is sending them as json ;)

```js
{ "humidity": 66, "temperature": 21.2 }
```
Note:
on the ESP side you will create this string, and the browser can read it via ```json.parse()```.

**Comment by Aggeloz** [comment]
> best way to do this is sending them as json ;)
> 
> ```js
> { "humidity": 66, "temperature": 21.2 }
> ```
> 
> Note:
> on the ESP side you will create this string, and the browser can read it via `json.parse()`.

thank you very much

**Comment by Aggeloz** [comment]
> { "humidity": 66, "temperature": 21.2 }

How do i create the json string inside the ESP?

**Comment by Aggeloz** [comment]
You helped me alot Links thank you very much <3
