### ISSUE TITLE
How to enable Debug and Ratchet?

### ISSUE THREAD

**Issue by diegocpires** [Links2004/arduinoWebSockets#38]
Sorry for the noob question.

I see many times in issues the line for enable debug. In line 30 in WebSockets.h
But, i dont understand what i need put in line 30 for debug works.
I tried Serial, Serial1, Serial2, Serial3... But no ones works. In all cases i got an error in compilation.

I need to debug because Arduino is not connecting the WebSocket server made in Ratchet (PHP).
I see the connection in Ratchet console, but Arduino disconnects immediately following.

Anyone Can help me?

**Comment by diegocpires** [comment]
Replacing DEBUG_WEBSOCKETS with Serial.println i can see the moment of error.

When call function acceptKey. The validation it is not working.

From Firefox I connect in WebSocket Server. Any ideas for resolve this problem?

**Comment by diegocpires** [comment]
For Example

For send Web-Socket-Key **17Gf8QiZr8lDr/aU9ePVFQ==** the correct Sec-WebSocket-Accept is **rssLO9/Rz1QGFYktqTxzJ5viYUc=**, but the function acceptKey returns **Kfh9QIsMVZcl6xEPYxPHzW8SZ8w=**

**Comment by Links2004** [comment]
do you use the ESP8266 or a ATmega?
for ESP8266 will work:
```cpp
/// Serial
#define DEBUG_WEBSOCKETS(...) Serial.printf( __VA_ARGS__ )
/// Serial1
#define DEBUG_WEBSOCKETS(...) Serial1.printf( __VA_ARGS__ )
```

the avr not support printf for print class.
but you can use printf.
```cpp
#include <stdio.h>
static FILE uartout = {0} ;
static int uart_putchar (char c, FILE *stream)
{
    Serial.write(c) ;
    return 0 ;
}

void setup(void)
{
   Serial.begin(115200);
   fdev_setup_stream (&uartout, uart_putchar, NULL, _FDEV_SETUP_WRITE);
   stdout = &uartout ;
}
```

```cpp
#define DEBUG_WEBSOCKETS(...) printf( __VA_ARGS__ )
```

with printf you will see the acceptKey that is send to the server and the AcceptKey

**Comment by diegocpires** [comment]
Hi @Links2004, thanks for the answer.
Im using ATmega with AVR.

But, replacing and testing, I got the problem above.
https://github.com/Links2004/arduinoWebSockets/issues/38#issuecomment-169505126

**Comment by Links2004** [comment]
try to change
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.cpp#L400
too:
```cpp
    clientKey += "258EAFA5-E914-47DA-95CA-C5AB0DC85B11";
```

look like the + and = are mixed

**Comment by diegocpires** [comment]
Wow @Links2004 .

This Works like a charm! Very Very Thanks.

**Comment by arbuzmaster** [comment]
Start WS Server with params -  webSocket.begin( ip,port, "/","");
