### ISSUE TITLE
different versions: github vs platformio

### ISSUE THREAD

**Issue by sovcik** [Links2004/arduinoWebSockets#381]
Seems github v2.1.1 is flagged as 2.1.2 in Platformio.

**Comment by Links2004** [comment]
Not sure where the problem is:
both say 2.1.2 here:

https://github.com/Links2004/arduinoWebSockets/blob/master/library.properties
https://github.com/Links2004/arduinoWebSockets/blob/master/library.json

feel free to reopen with a more information when the problem still exists.

**Comment by sovcik** [comment]
When I tried to install version 2.1.2 using Platformio I was getting source code, which contained 2.1.1 in library.json... No clue how that happened, but it works now... 
Sorry for bothering.

**Comment by sovcik** [comment]
Ok, remembered the issue:
Your latest release at Github is 2.1.1 (commit 2626b263153629e3d95efa32ea50957355067102). library.json version for this commit is 2.1.1
But Platformio does not contain 2.1.1 version of your library - only 2.1.0 and 2.1.2
And no 2.1.2 exists in your releases at Github.
So it was only my confusion. Again, no real issue.
