### ISSUE TITLE
What is the good way of implementing ping/pong from WSClient?

### ISSUE THREAD

**Issue by sovcik** [Links2004/arduinoWebSockets#382]
Both ping/pong messages seems to be implemented.
1) pong reply to ping from server is implemented
2) you can send ping from client, but , but you won't receive notification pong reply was received as it seems to get lost/ignored while processing incoming frame https://github.com/sovcik/arduinoWebSockets/blob/master/src/WebSockets.cpp#L439

Is there any way of how can this be used?

**Comment by sovcik** [comment]
I have forked this lib to implement automated detection of line disconnect using ping/pong, but maybe I'm getting usage of this library wrong...
So asking first before bothering with pull requests :-)

Just FYI this is how I implemented mentioned feature: https://github.com/sovcik/arduinoWebSockets

**Comment by sovcik** [comment]
And I have seen the discussion in #203 :-)

**Comment by me21** [comment]
I agree, there should be a way to know if we've received pong in response to our ping.

**Comment by Links2004** [comment]
events added and example updated.
