### ISSUE TITLE
Unreliable when data size > MTU

### ISSUE THREAD

**Issue by davepl** [Links2004/arduinoWebSockets#384]
Long story short, I'm pushing a lot of data to bunch of wifi ESP32 WebSocket clients.  I've found if I split the data up into chunks of 1500 bytes or less, I can send as much data as fast as I want.  If I have packets more like 4K, I get disconnections and socket error (usually 54, which is peer disconnect).

It's rock solid at 1200 bytes though.  

I wish I had a simple repro but it'd be hard to extract.  In short, it's open a socket on the ESP32 and then send 6K to it 30 times per second evenly spaced.

**Comment by Links2004** [comment]
the lib has a configurable limit on which data length is accepted but this is 15K for the ESP's
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L60
but this is only a soft limit to stop external DOS via RAM overload.
in your case it looks more like a network stack problem, may the internal network buffer is full or you are out of free RAM.

can you reproduce this with a plain TCP socket?
