### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by fabricedesre** [Links2004/arduinoWebSockets#39]
This is probably more a doc request, but anyway...

I installed the library by cloning it under ~/Arduino/libraries

Compiling sketches that #include <WebSocketsServer.h> fail with:
/home/fabrice/Arduino/libraries/arduinoWebSockets/src/WebSockets.cpp:28:35: fatal error: core_esp8266_features.h: No such file or directory
 #include <core_esp8266_features.h>

core_esp8266_features.h is present at  ~/soft/arduino-1.6.7/hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_features.h

What am I doing wrong?

**Comment by Links2004** [comment]
for the latest version,you need the string version of the ESP core, then it work.
#36, #32, #30

**Comment by fabricedesre** [comment]
Ok, I had both the git version of esp core and the stable one, but the git one wasn't picked up. It's all good now.
