### ISSUE TITLE
ESP8266 - Error: record overflow

### ISSUE THREAD

**Issue by ABB13** [Links2004/arduinoWebSockets#390]
I'm using the file "WebSocketClientSSL.ino" with a few modifications. When I run it I get the following output: 
[WSc] Disconnected! 
Error: record overflow.

I guess the problem is the size of what I receive is too big for "payload", but I am a newbee in this field and I don't know how to fix it 

This is my code: 
```cpp
#include <Arduino.h>

#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>

#include <WebSocketsClient.h>

#include <Hash.h>

ESP8266WiFiMulti WiFiMulti;
WebSocketsClient webSocket;


#define USE_SERIAL Serial

void webSocketEvent(WStype_t type, uint8_t * payload, size_t length) {


    switch(type) {
        case WStype_DISCONNECTED:
            USE_SERIAL.printf("[WSc] Disconnected!\n");
            break;
        case WStype_CONNECTED:
            {
                USE_SERIAL.printf("[WSc] Connected to url: %s\n",  payload);
				
			    // send message to server when Connected
				webSocket.sendTXT("Connected");
            }
            break;
        case WStype_TEXT:
            USE_SERIAL.printf("[WSc] get text: %s\n", payload);

			// send message to server
			   //webSocket.sendTXT("message here");
            break;
        case WStype_BIN:
            USE_SERIAL.printf("[WSc] get binary length: %u\n", length);
            hexdump(payload, length);

            // send data to server
            // webSocket.sendBIN(payload, length);
            break;
    }

}

void setup() {
    // USE_SERIAL.begin(921600);
    USE_SERIAL.begin(115200);

    //Serial.setDebugOutput(true);
    USE_SERIAL.setDebugOutput(true);

    USE_SERIAL.println();
    USE_SERIAL.println();
    USE_SERIAL.println();

      for(uint8_t t = 4; t > 0; t--) {
          USE_SERIAL.printf("[SETUP] BOOT WAIT %d...\n", t);
          USE_SERIAL.flush();
          delay(1000);
      }

    WiFiMulti.addAP("Redmi", "A!nT3N1ox-");

    //WiFi.disconnect();
    while(WiFiMulti.run() != WL_CONNECTED) {
        delay(100);
    }

    webSocket.beginSSL("demo.signalk.org", 80, "/signalk/v1/stream");
    webSocket.onEvent(webSocketEvent);

}

void loop() {
    webSocket.loop();
}
```

As I understand, the server should send me a json like that:
```json
{
  "context": "vessels.urn:mrn:imo:mmsi:234567890",
  "updates": [
    {
      "source": {
        "label": "N2000-01",
        "type": "NMEA2000",
        "src": "115",
        "pgn": 128275
      },
      "values": [
        {
          "path": "navigation.trip.log",
          "value": 43374
        },
        {
          "path": "navigation.log",
          "value": 17404540
        }
      ]
    }
  ]
}
```
P.S. sorry for my bad English

**Comment by Links2004** [comment]
your json is around 390 chars which normally is no problem I have send much bigger data via websocket.
the error itself does not come from the Websocket lib itself. 
you are hitting a SSL error, most likely this one here:
https://github.com/esp8266/Arduino/blob/5137d4da11f4a5824a5ab283a66037346f784dd4/tools/sdk/include/bearssl/bearssl_ssl.h#L4271

you may need to change the port for **80** to **443** since **80** normally is **http** and not **https.**

**Comment by ABB13** [comment]
Really thanks for your reply :) .
I followed your help and I fix it, but now I have another error: 
"_Error: SSL error 80_" 

This is the changed line code: 
`webSocket.beginSSL("demo.signalk.org", 443, "/signalk/v1/stream");` 

P.S. Anyway you are very kind, I really appreciate it :)

**Comment by Links2004** [comment]
*80* is `BR_ALERT_INTERNAL_ERROR`, not very helpful at all.

but its most likely the webserver that has a problem, if you try to open https://demo.signalk.org/signalk/v1/stream the browser has a SSL error too.
ssllabs fails also: https://www.ssllabs.com/ssltest/analyze.html?d=demo.signalk.org&s=34.246.221.52

**Comment by ABB13** [comment]
So the problem is the webserver D: anyway ty for your help :) and I'm sorry, I wasted your time ^^''
