### ISSUE TITLE
not opening the URL after connecting WEmose D1 mini to wifi

### ISSUE THREAD

**Issue by SRISAIKUMARMUDI** [Links2004/arduinoWebSockets#392]
The code has successfully uploaded to WEmose D1 mini. But I uploaded the code which you given in the CANVAS, it was uploaded successfully and also connecting to the wifi and also generating the URL but while browsing that url it is showing that "can't reach this page"... #391 
![screenshot 35](https://user-images.githubusercontent.com/44809582/48071337-1a110300-e200-11e8-94eb-a216999218ca.png)
![screenshot 36](https://user-images.githubusercontent.com/44809582/48071344-1e3d2080-e200-11e8-95d5-c14019c4a576.png)

**Comment by VSneg** [comment]
Can you uncomment this USE_SERIAL.setDebugOutput(true); 
and send serial monitor screenshoot?

**Comment by Links2004** [comment]
@SRISAIKUMARMUDI based on you log the ESP is connected to the AP, can you ping the ESP?

@VSneg your log shows that the ESP is not finding your AP.

free free to reopen if this still is a Problem.
