### ISSUE TITLE
#define WEBSOCKETS_SERVER_CLIENT_MAX  (1) doesn't make any effect

### ISSUE THREAD

**Issue by edautz** [Links2004/arduinoWebSockets#397]

**Comment by edautz** [comment]
Found this great library for controlling a robotarm with a webpage using websockets instead of http calls. I am using an ESP32 devkit module als robotarm controller for the servo's.

I want to limit the websocket access to my ESP32 to 1, so the arm could only controlled by 1 browser session.

I used:

#define WEBSOCKETS_SERVER_CLIENT_MAX  (1) in my arduino code for a ESP32 module to limit the number of websockets connections to one.

But doesn't work. I still can open 5 concurrent connections.

Tried also
#define WEBSOCKETS_SERVER_CLIENT_MAX  1
#define WEBSOCKETS_SERVER_CLIENT_MAX    (1)

but nothing changed.

I could solved this in the arduino code to intercept the connections after the first and terminate them but using this define is a better solution.

**Comment by per1234** [comment]
WebSocketsServer.cpp is a separate translation unit from your sketch so macros you define in your sketch will have no effect on the .cpp file. When WebSocketsServer.cpp includes WebSocketsServer.h, `WEBSOCKETS_SERVER_CLIENT_MAX` will not have been defined and so it will be set to 5.

The options for configuring the library:
- Edit WebSocketsServer.h.
- Pass the `-DWEBSOCKETS_SERVER_CLIENT_MAX=1` flag to the compiler.
- Move all the code dependent on the value of `WEBSOCKETS_SERVER_CLIENT_MAX` to the .h file and define the macro in your sketch before the `#include` directive for the .h file.

**Comment by Links2004** [comment]
@per1234 has the correct answer for you ;)

**Comment by owenmcateer** [comment]
Here is a simple workaround I used to limit the number of connected users to 1.
Inside the "WStype_CONNECTED" case of your "webSocketEvent()" function add:
`
  case WStype_CONNECTED:
    // Only allow client num zero
    if (num != 0) {
      webSocket.sendTXT(num, "Busy");
      Serial.printf("[%u] Blocked client: %d.%d.%d.%d url: %s\r\n", num, ip[0], ip[1], ip[2], ip[3], payload);
      // Disconnect user
      webSocket.disconnect(num);
    }
    ...
`
