### ISSUE TITLE
code freezes when wifi disconnected and sending websocket.sendTXT(string)

### ISSUE THREAD

**Issue by mars000** [Links2004/arduinoWebSockets#398]
I am current version of library

I have found that when WiFi is disconnected and I execute `websocket.sendTXT(string) `the code freezes at this point.

Why does this happen ? 
not event my software WDT is triggered to reset the ESP....it just stops.
How can I fix this ?
I try to use `WiFi.status() == WL_CONNECTED` before I run the` sendTXT()` but that does not seem to pick the change in wifi status quick enough.

Can anyone help please ?

**Comment by sovcik** [comment]
Technically it does not "freeze" it only waits for TCP timeout, which is quite long (minutes). If you wait long enough you will see sendTXT failing afterwards.

As for "lost-connection" detection - I suggest using websocket ping/pong protocol (see #383).

**Comment by Links2004** [comment]
@sovcik is correct, the reason is the TCP stack handling of the ESP.
