### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by UNUMobile** [Links2004/arduinoWebSockets#4]
Hi,
Try to compile WebSocketClient, I got this message. Could you help me?
I am using ESP8266 Arduino IDE and ESP-12Module on MAC.
thanks.

WebSocket/WebSockets.cpp.o:(.text+0x1c): undefined reference to `base64_init_encodestate'
WebSocket/WebSockets.cpp.o:(.text+0x20): undefined reference to `base64_encode_block'
WebSocket/WebSockets.cpp.o:(.text+0x24): undefined reference to `base64_encode_blockend'
WebSocket/WebSockets.cpp.o: In function `WebSockets::base64_encode(unsigned char*, unsigned int)':
WebSockets.cpp:(.text+0x6b): undefined reference to `base64_init_encodestate'
WebSockets.cpp:(.text+0x79): undefined reference to `base64_encode_block'
WebSockets.cpp:(.text+0x83): undefined reference to `base64_encode_blockend'
collect2: error: ld returned 1 exit status
Error compiling.

**Comment by Links2004** [comment]
did you copy the libb64 too?
the missing functions are there:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/libb64/cencode.c#L12

**Comment by UNUMobile** [comment]
hi Links2004

Yes, I did copy all file to libraries folder include libb64. when I remove libb64 folder then got this message. I try to  google this issue, maybe is compiler problem, but I don't know how to change. 
thanks Links2004.

/Users/KensonChiang/Documents/Arduino/libraries/WebSocket/WebSockets.cpp:28:28: fatal error: libb64/cencode.h: No such file or directory
 #include "libb64/cencode.h"
                            ^
compilation terminated.
Error compiling.

**Comment by UNUMobile** [comment]
Thanks, Links2004

I just copy src folder to Arduino IDE libraries\WebSocket and open WebSocketServer.ino from other folder. 
got the compiling error.

Try to make WebSocket folder and put all file in, and open example from Arduino IDE. It's work...!!!
thank you very much.
