### ISSUE TITLE
Server and client in same ESP8266

### ISSUE THREAD

**Issue by denden4444** [Links2004/arduinoWebSockets#401]
I have this loaded but sadly there is zero communication between the server and the client , has anyone managed to get this working ? I'd really appreciate some feedback comments suggestions etc.

Kind regards

Den

_Originally posted by @denden4444 in https://github.com/Links2004/arduinoWebSockets/issues/315#issuecomment-448199491_

**Comment by denden4444** [comment]
@Links2004 

Please could you advise on this topic I have been battling with this for a while now and am still not able to get both client and server working on same ESP8266.
Kind regards
Den

**Comment by Links2004** [comment]
you can rund a Server and a Client on the same ESP8266.
what is not possible with the ESP TCP stack is to connect with the client to the Server on the same ESP.
with out knowing more about your usecase its hart to tell whats the problem.

please attache debug logs and may some code.

**Comment by denden4444** [comment]
@Links2004 Markus 

Please see attached diagram. 

I have previously attached code but can't seem to find it in the issues anymore..is it perhaps archived ?

Questions are 1. and 2. in diagram.

I will attach code soon , for reference please see https://github.com/Links2004/arduinoWebSockets/issues/315#issuecomment-448199491

I look forward to your reply.

Kind regards

Den

**Comment by denden4444** [comment]
@Markus 

Hi any updates on this please ?

Kind regards

Dens

**Comment by Links2004** [comment]
Hi,
the use case is possible.
but most a little overkill ;) a simple TCP proxy on the ESP on the ESP in the mid may is easier, and needs less resources.

the main problem that I see in you current code is that ```webSocket.loop();``` is not called often which may end in a disconnect.
