### ISSUE TITLE
BSSL: Connection *will* fail, no authentication method is setup - ESP8266

### ISSUE THREAD

**Issue by kimble** [Links2004/arduinoWebSockets#402]
I'm trying to get the wss example working on a esp8266, but I'm running into this

"SSL: Connection *will* fail, no authentication method is setup:wr 254 0"

Any ideas?

**Comment by Apaezmx** [comment]
Did you find a solution? I'm hitting the same issue. My best guess so far is that there's some issue with the public / private keys and the certifcate

**Comment by kimble** [comment]
I had a look at the code and it looked like it had something to do with passing of the certificate checksum, but I never got to the bottom of it.

**Comment by ooi6** [comment]
I had the same issue, but setting **client.setInsecure();** resolved it.
Sorry for the none code formatting but it removes the line breaks ??


  message.concat("\n");
  **client.setInsecure();**
  if(bot.sendMessage(CHAT_ID, message, "")){
    Serial.println("TELEGRAM successfully sent");
  }

**Comment by Links2004** [comment]
will be fixed with df3ef524b6b481939c184f2a044dcbaf00b83a6f
