### ISSUE TITLE
Connect to ESP websocket server by URL not not using IP

### ISSUE THREAD

**Issue by williamesp2015** [Links2004/arduinoWebSockets#403]
I am wondering if possible to connect Websocket  server using WiFi.softAP but in the browser user type url like internet and connect to the saved HTML on SPIFF.

**Comment by denden4444** [comment]
Hi have you seen this ?
[https://tttapa.github.io/ESP8266/Chap14%20-%20WebSocket.html](url)
I think thats what you're after..

**Comment by sovcik** [comment]
And this https://tttapa.github.io/ESP8266/Chap08%20-%20mDNS.html :-)
