### ISSUE TITLE
(SOLVED) How to get text from WebSocketsServer.loop()?

### ISSUE THREAD

**Issue by wieb18** [Links2004/arduinoWebSockets#405]
Hello,

Maybe this is a dumb question, but I am not real programmer (just copy paste programmer) and this is beyond my knowledge. 

```
void loop() {
    webSocketServer.loop();
}
```

Right now I am successfully send "LED ON" message from webSocketClient to webSocketServer but  don't know how to get that text from WebSocketsServer.loop().

Tried with this code:

 ```
void loop() {
       webSocketServer.loop();
       String header;
       header = webSocketServer.loop();
       if (header.indexOf("LED ON") >= 0) {
          Serial.println("Turn LED on... ");
       } 
}
```
 
Did not work, Arduino IDE compiler shows error.

Please help.

**Comment by denden4444** [comment]
Hi 
may I suggest the following : 
Have you seen this tutorial ? https://tttapa.github.io/ESP8266/Chap14%20-%20WebSocket.html
Once you've gone through and understood the workings of that go here : 
https://github.com/Links2004/arduinoWebSockets/issues/113

I hope that helps :)

**Comment by wieb18** [comment]
> Hi
> may I suggest the following :
> Have you seen this tutorial ? https://tttapa.github.io/ESP8266/Chap14%20-%20WebSocket.html
> Once you've gone through and understood the workings of that go here :
> #113
> 
> I hope that helps :)

Already read the tutorial and forum discussion, it really help me to understand. Finally I am able to get the text from message received by WebSocketsServer.loop()

Thanks a lot denden4444 for the guidance, much appreciated.
