### ISSUE TITLE
Web sockets. How to send JSON on the server.

### ISSUE THREAD

**Issue by zykovkirill** [Links2004/arduinoWebSockets#406]
Hello. Im need help. How to send json data on the server. im can send this data format:
webSocket.sendTXT("{"type":"usermsg","name":"d","message":"nu","color":"null"}");
but when i send this data
webSocket.sendTXT("{"type":"usermsg","name":"%c %s",'d',"","message":"nu","color":"null"}"); server dont read this data. I want to send int data on server using json format

**Comment by denden4444** [comment]
Hi there 
Have you read these :
https://arduinojson.org/v5/doc/encoding/ 
https://arduinojson.org/v5/doc/decoding/
And perhaps double check your formatting .. at sites like this one : https://jsonlint.com/
Google for JSON formatter

Kind regards

Den

**Comment by b4dnewz** [comment]
Take a look also to this https://github.com/Links2004/arduinoWebSockets/issues/192#issuecomment-301829352by the author on another issue
