### ISSUE TITLE
How to send 0x85 command

### ISSUE THREAD

**Issue by fabbbio986** [Links2004/arduinoWebSockets#408]
Hi everyone!
I'm trying to develop a wireless joystick to move manually a laser head on a laser CNC machine running GRBL on an arduino UNO. The arduino has an ESP8266 on it that receives the commands and sends them to the serial port of arduino.
Here there is the configuration and the code on the ESP8266 module: https://github.com/arkypita/ESP8266-SerialWebSocket

At the moment I'm using this configuration with no problem with LaserGRBL running on my PC.

Now I'm trying to use a wemos D1 mini board that reads some buttons state and sends differents command via wi-fi to the CNC laser.

Basically I'm following these instructions: https://github.com/gnea/grbl/wiki/Grbl-v1.1-Jogging#joystick-implementation

In short I have to send commands like "$J=G91 Xx Yz Fzzzz \n" when I press a button and then wait for an "ok" response from the GRBL before sending another one. 
At this point everything works fine, I can send commands using the websocket.sendTXT function ( e.g.: webSocket.sendTXT("$J=G91X0Y10F6000 \n")) and I receive and read the "ok" message from GRBL.

Now, when I release the push button I have to send Grbl a jog cancel real-time command to have a low-latency feel.
This will stop motion immediately somewhere along the programmed jog path with virtually zero-latency and automatically flush Grbl's planner queue.

As described here: https://github.com/gnea/grbl/wiki/Grbl-v1.1-Commands#extended-ascii-realtime-command-descriptions
I have to send a 0x85 command to perform this action but I can't find a way to send it.
Do you have any idea?

Thank for your help!

**Comment by Links2004** [comment]
you can try:

```cpp
uint8_t buf[] = { 0x85 };
webSocket.sendTXT(buf, 1);
```

**Comment by fabbbio986** [comment]
It works! Thank you so much!
