### ISSUE TITLE
ESP8266 Fatal exception 28(LoadProhibitedCause) in DEBUG_WEBSOCKETS(...)

### ISSUE THREAD

**Issue by ATho95** [Links2004/arduinoWebSockets#409]
When DEBUG_WEBSOCKETS is #defined:
The WebSocketsServer crashes when a web page request from Firefox is made.

In file WebSocketsServer.cpp LINE 786 throws the exception:
"DEBUG_WEBSOCKETS("[WS-Server][%d][handleHeader]  - cExtensions: %s\n", client->num, client->cExtensions.c_str());"

replace with the following fix solves the problem:
"DEBUG_WEBSOCKETS("[WS-Server][%d][handleHeader]  - cExtensions: %s\n", client->num, client->cExtensions == NULL ? "NULL" : client->cExtensions.c_str());"

This is a debug output containing my fix:
[WS-Server][0] new client from 192.168.1.4
[WS-Server][0][handleHeader] RX: GET / HTTP/1.1
[WS-Server][0][handleHeader] RX: Host: 192.168.1.30
[WS-Server][0][handleHeader] RX: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
[WS-Server][0][handleHeader] RX: Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
[WS-Server][0][handleHeader] RX: Accept-Language: de,en-US;q=0.7,en;q=0.3
[WS-Server][0][handleHeader] RX: Accept-Encoding: gzip, deflate
[WS-Server][0][handleHeader] RX: DNT: 1
[WS-Server][0][handleHeader] RX: Connection: keep-alive
[WS-Server][0][handleHeader] RX: Upgrade-Insecure-Requests: 1
[WS-Server][0][handleHeader] Header read fin.
[WS-Server][0][handleHeader]  - cURL: /
[WS-Server][0][handleHeader]  - cIsUpgrade: 0
[WS-Server][0][handleHeader]  - cIsWebsocket: 0
[WS-Server][0][handleHeader]  - cKey:
[WS-Server][0][handleHeader]  - cProtocol:
[WS-Server][0][handleHeader]  - cExtensions: **NULL**
[WS-Server][0][handleHeader]  - cVersion: 0
[WS-Server][0][handleHeader]  - base64Authorization:
[WS-Server][0][handleHeader]  - cHttpHeadersValid: 1
[WS-Server][0][handleHeader]  - cMandatoryHeadersCount: 0
[WS-Server][0][handleHeader] no Websocket connection close.
[WS-Server][0] client disconnected.
Client-Nr.: [0]  WStype: 1 payload:
[0] Disconnected!
[WS-Server][0] new client from 192.168.1.4
[WS-Server][0][handleHeader] RX: GET / HTTP/1.1
[WS-Server][0][handleHeader] RX: Host: 192.168.1.30
[WS-Server][0][handleHeader] RX: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
[WS-Server][0][handleHeader] RX: Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
[WS-Server][0][handleHeader] RX: Accept-Language: de,en-US;q=0.7,en;q=0.3
[WS-Server][0][handleHeader] RX: Accept-Encoding: gzip, deflate
[WS-Server][0][handleHeader] RX: Sec-WebSocket-Version: 13
[WS-Server][0][handleHeader] RX: Origin: http://192.168.1.30
[WS-Server][0][handleHeader] RX: Sec-WebSocket-Extensions: permessage-deflate
[WS-Server][0][handleHeader] RX: Sec-WebSocket-Key: jqVXMYN3mGmVvQNZ8yik8g==
[WS-Server][0][handleHeader] RX: DNT: 1
[WS-Server][0][handleHeader] RX: Connection: keep-alive, Upgrade
[WS-Server][0][handleHeader] RX: Pragma: no-cache
[WS-Server][0][handleHeader] RX: Cache-Control: no-cache
[WS-Server][0][handleHeader] RX: Upgrade: websocket
[WS-Server][0][handleHeader] Header read fin.
[WS-Server][0][handleHeader]  - cURL: /
[WS-Server][0][handleHeader]  - cIsUpgrade: 1
[WS-Server][0][handleHeader]  - cIsWebsocket: 1
[WS-Server][0][handleHeader]  - cKey: jqVXMYN3mGmVvQNZ8yik8g==
[WS-Server][0][handleHeader]  - cProtocol:
[WS-Server][0][handleHeader]  - cExtensions: permessage-deflate
[WS-Server][0][handleHeader]  - cVersion: 13
[WS-Server][0][handleHeader]  - base64Authorization:
[WS-Server][0][handleHeader]  - cHttpHeadersValid: 1
[WS-Server][0][handleHeader]  - cMandatoryHeadersCount: 0
[WS-Server][0][handleHeader] Websocket connection incoming.
[WS-Server][0][handleHeader]  - sKey: /098JMn5w6AgV5DVLdx40za7t28=
[WS-Server][0][handleHeader] handshake HTTP/1.1 101 Switching Protocols
Server: arduino-WebSocketsServer

**Comment by Links2004** [comment]
most likely you are out of RAM, please log the free RAM.
if its still a Problem please attache the trace and the decode of it.
feel free to reopen.
