### ISSUE TITLE
8266 Unable to receive new messages after running for a while

### ISSUE THREAD

**Issue by Hackxiaoya** [Links2004/arduinoWebSockets#411]
Unable to receive new messages after running for a while.

The 8266 periodically sends a ping to prove that the connection is still there.
However, 8266 cannot receive new messages;
If the socket service is turned off, the 8266 can respond to the service shutdown command;
That is, new messages cannot be obtained.

**Comment by Links2004** [comment]
if this still is a problem then please enable Debug in the Arduino IDE an attache the debug log.
