### ISSUE TITLE
specific protocol 

### ISSUE THREAD

**Issue by Gior80** [Links2004/arduinoWebSockets#413]
I'm new to web socket and trying to run the example without success:  
my problem is that my server need to have specific protocol on connection:

here the scenario: 
I have a ws exposed at: ws://myserver:8080/run/websocket/system/

testing with another platform I'm seeing web socket constructor url adds this parameter in connection string. 

ws://myserver:8080/run/websocket/system/, ["protocol 1.2"]. <------- here

if I not specify the protocol server not handshake

I'm really confused on how can I adapt this to the this web socket client.

**Comment by Hackxiaoya** [comment]
Then you may need to modify your websocket protocol, because modifying the esp library is not sensible.

**Comment by Links2004** [comment]
where the protocol needs to go HTTP headers?
if yes take a look at:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.cpp#L308
