### ISSUE TITLE
Particle Photon compiling Error

### ISSUE THREAD

**Issue by uldis34** [Links2004/arduinoWebSockets#416]
I added library inParticle web IDE and an error on compiling appears (using Particle Photon)
"lib/WebSockets/WebSocketsBase.cpp:35:32: libb64/cencode_inc.h: No such file or directory"

**Comment by Links2004** [comment]
may @Carouelle can help you, he has ported the lib for Particle.
I dont have the development environment or Hardware of Particle.

**Comment by Carouelle** [comment]
When I worked on my Particle project, I didn't use the web IDE so I don't know how it works unfortunately. I don't have the hardware anymore either.

However the `libb64/cencode_inc.h` file is in this very project, so the obvious question is did you import it with your project files? If I remember correctly it was flaws in the web IDE for importing multiple files in the same project that made me look away from it.

Sorry if I can't be of a more direct help.

**Comment by derrickrc** [comment]
If anyone else is running into the same issue, I was able to get this compiled (and seemingly working) on my Particle Photon using this version of the library: https://docs.particle.io/reference/device-os/libraries/w/WebSockets/

And then manually downloading the library and adding in the lib64 files and changing the import references to: 

- cdecode.h
- cdecode_inc.c
- cencode.h
- cencode_inc.c
- libsha1.c
- libsha1.h

Hope this helps someone else.
