### ISSUE TITLE
WebSocket message not sent when client connects

### ISSUE THREAD

**Issue by mdathersajjad** [Links2004/arduinoWebSockets#418]
I have created a simple arduino program which starts a websocket and sends a message when ever a websocket client is connected.

I am using NodeMCU(ESP8266) Board when ever a client connects the message hello client is not sent. I am trying to connect to the socket using ARC Rest Client. The websocket connects but the message "Hello Client" is not sent.

If i connect to the websocket and send a message to it and then disconnect and reconnect again means the message hello client is received.

**Comment by Links2004** [comment]
please attache your code and debug output, or nobody is able to take a look and help you.
