### ISSUE TITLE
Loop transmitting in ASYNC mode?

### ISSUE THREAD

**Issue by Stasikiii** [Links2004/arduinoWebSockets#424]
UDP
Ok, i readed another issues, and was used ASYNC TCP library.
Now my program based on events. But how to realise broadcast-like system on events? 

Something like:
Client connects and program starts to stream?
```cpp
case WStype_CONNECTED:{
  while(1){
     webSocket.sendTXT(0,"1", 1);
   }
}
```
This moments i have to use ask-answer system, to iniziate one packet from server.
WStype_TEXT case helps on that.
```cpp
case WStype_TEXT:{
    webSocket.sendTXT(0,"1", 1);
}
```
Server await one packet and send answer, but i think it's can be more elegand solution?

When i use void.loop as is for sendTXT, then data streams transmit with big (100ms) delay, and i supose that this is not ASYNC mode at all.

Hello,
if you interrupt a session with hardware methods (for example, turn off wifi connection on client side while websocketBrokastTXT function is running) Esp8266 starts terribly slow down whole program and does not return to normal operation when it is reconnected to it.

I edited #define WEBSOCKETS_TCP_TIMEOUT    (15) but it's not helped.
I try to use **sendPing**
```cpp
 if (joined == true){
      if (webSocket.sendPing(0)==0){
        Serial.println("Client not responds");
        webSocket.disconnect(0);
        joined=false;
      }
```
sendPing take more as 2 secons to detect that is no clients enymore. How to set ping timeout for this situation?

**Comment by Links2004** [comment]
the Ping timeout detection is relaying on the TCP stack of the ESP to detect that the Ping sending has failed, but this can be slow in some cases.
calling sendTXT in a hard loop will most likely overload the the TCP stack and the RAM ;)

the 100ms most likely come from a delayed ACK, windows for example is know to show this.
more technical details:
https://github.com/esp8266/Arduino/issues/1577

hope this helps, feel free to reopen.
