### ISSUE TITLE
WebSocketClient SSL issue

### ISSUE THREAD

**Issue by francesco98** [Links2004/arduinoWebSockets#425]
I have made a websocket server on tomcat that listens on port **8443** and that seems to work properly using any client by connecting to: _wss://address:8443_.
I'm going to use my esp8266 as a client, but using the **beginSSL** function, I get the following error:
**SSL error 40**.

This is the Connector on Tomcat server.xml file:
```xml
<Connector
                port="8443" protocol="org.apache.coyote.http11.Http11NioProtocol"
                maxThreads="200" SSLEnabled="true">
                <SSLHostConfig>
                        <Certificate
                                certificateFile="${catalina.base}/conf/cert.pem"
                                certificateKeyFile="${catalina.base}/conf/privkey.pem"
                                certificateChainFile="${catalina.base}/conf/chain.pem" />
                </SSLHostConfig>
</Connector>
```

And this is the code for esp8266:
```cpp
const String serverAddress = "";
const unsigned int serverPort = 8080;
const String serverPath = "";

configTime(3 * 3600, 0, "pool.ntp.org", "time.nist.gov");
webSocket.begin(serverAddress, serverPort, serverPath);
webSocket.onEvent(webSocketEvent);
webSocket.setReconnectInterval(5000);
```

Could you help me? Thank you.

**Comment by Links2004** [comment]
error 40 is ```BR_ALERT_HANDSHAKE_FAILURE``
https://github.com/esp8266/Arduino/blob/f6dd8264377c5ba5fce1e33db1610118623bdae2/tools/sdk/include/bearssl/bearssl_ssl.h#L4285

please check your SSL setup may the crypto is not compatible.
feel free to reopen if you have more Info.
