### ISSUE TITLE
WebSocketsClient::beginSSL incompatible with new ESP8266 Arduino v2.5.0

### ISSUE THREAD

**Issue by jukkas** [Links2004/arduinoWebSockets#428]
New ESP8266 Arduino v2.5.0 uses new SSL/TLS stack (BearSSL).

WiFiClientSecure connection now requires to either validate X509 certificate or to explicitly set connection not to verify server (with WiFiClientSecure::setInsecure()).

So currently WebSocketsClient::beginSSL fails to connect, when using latest ESP8266 Arduino.

My dirty quick fix in `WebSocketsClient::loop(void)`:
```
    ...
        _client.ssl = new WiFiClientSecure();
    #ifdef wificlientbearssl_h
        _client.ssl->setInsecure();
    #endif
        _client.tcp = _client.ssl;
    ...
```

**Comment by ali32b** [comment]
I have same problem since using latest ESP8266 Arduino, beginSSL does not connect.

**Comment by huzhiren** [comment]
I have the same issue, can not connect to wss, below is the log:

[WS-Client] connect wss...
[hostByName] Host: 172.24.1.1 is a IP!
:ref 1
BSSL: Connection *will* fail, no authentication method is setup:wr 215 0
:wrc 215 215 0
:ack 215
:rn 536
:rd 5, 536, 0
:rdi 536, 5
:rd 89, 536, 5
:rdi 531, 89
:rch 536, 536
:rch 1072, 536
:rch 1608, 45
:rd 5, 1653, 94
:rdi 442, 5
:rd 1207, 1653, 99
:rdi 437, 437
:c 437, 536, 1653
:rdi 536, 536
:c 536, 536, 1117
:rdi 536, 234
[WS-Client] connection to 172.24.1.1:443 Faild
:ur 1
:close
:del
[WS-Client] client disconnected.
[WSc] Disconnected!

**Comment by huzhiren** [comment]
I know @jukkas mentioned a dirty quick fix, but is this make the connection insecure?

I find example code in https doing this:
`
    std::unique_ptr<BearSSL::WiFiClientSecure>client(new BearSSL::WiFiClientSecure);
    client->setFingerprint(fingerprint);

    HTTPClient https;
    Serial.print("[HTTPS] begin...\n");
    if (https.begin(*client, "https://172.24.1.1/")) {  // HTTPS
`

**Comment by jukkas** [comment]
setInsecure() does make connection insecure in a sense that client does not verify server certificate, but that same happened with old Arduino TLS stack too. Connection is still encrypted, but man-in-the-middle attack is possible.

Using client->setFingerprint(fingerprint) would be too painful, since server fingerprints often change every few months.

Proper solution would be to use BearSSL::CertStore(), but looks it would be a bit of hassle to handle. (CA cert(s) in SPIFFS)

**Comment by huzhiren** [comment]
In my case, because it is a self-sign certificate, so the fingerprint never change.  I think the better way would be in Arduino side, we can flash the certificate in the sketch, then it can verify the server.  The Arduino can't do a full CA root chain I think.

**Comment by mana147** [comment]
> New ESP8266 Arduino v2.5.0 uses new SSL/TLS stack (BearSSL).
> 
> WiFiClientSecure connection now requires to either validate X509 certificate or to explicitly set connection not to verify server (with WiFiClientSecure::setInsecure()).
> 
> So currently WebSocketsClient::beginSSL fails to connect, when using latest ESP8266 Arduino.
> 
> My dirty quick fix in `WebSocketsClient::loop(void)`:
> 
> ```
>     ...
>         _client.ssl = new WiFiClientSecure();
>     #ifdef wificlientbearssl_h
>         _client.ssl->setInsecure();
>     #endif
>         _client.tcp = _client.ssl;
>     ...
> ```

thanks , i love you hahahahah

**Comment by Links2004** [comment]
CA support is in the works see #434.
```setInsecure``` will be used if no CA or fingerprint is set.

**Comment by ellavas** [comment]
The method setInsecure is still not used when neither CA, nor fingerprint are defined.
Do you plan to add it ?

**Comment by Links2004** [comment]
its in the master branch:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.cpp#L764-L768
