### ISSUE TITLE
socket.io namespace

### ISSUE THREAD

**Issue by farsajik** [Links2004/arduinoWebSockets#438]
hi.i can connect socket.io but unable to connect socket.io namespace.please help.
server side
`io.of("/node1").on("connection", (socket) => {
    console.log("New client connected");
});`

arduino
i tried this 
`webSocket.beginSocketIO("192.168.1.120", 3000, "/node1");`
and this
`webSocket.beginSocketIO("192.168.1.120", 3000, "/node1/?EIO=3");`

but there no connection

**Comment by Links2004** [comment]
currently namespaces are not tested, if
```cpp
webSocket.beginSocketIO("192.168.1.120", 3000, "/socket.io/node1/?EIO=3");
```
is not working too, may a Implementation change is needed.
a better abstaraction for socketIO is WIP but currently there is no finish date.
