### ISSUE TITLE
Error: 'class WebSocketsClient' has no member named 'enableHeartbeat'

### ISSUE THREAD

**Issue by vedmant** [Links2004/arduinoWebSockets#439]
I used an example esp8266/WebSocketClient and cannot compile the code, I have the error: 
Error: 'class WebSocketsClient' has no member named 'enableHeartbeat'. Installed version is 2.1.1.

**Comment by Links2004** [comment]
it looks like you have mixed the master examples with the 2.1.1 release.
version 2.1.1 has no enableHeartbeat function.
