### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Vitorbnc** [Links2004/arduinoWebSockets#44]
Hi,
This library sounds great, but I can't compile on Arduino IDE. It gives me 
>fatal error: core_esp8266_features.h: No such file or directory 
I have esp8266 core version 2.0, and it's working fine.

**Comment by Links2004** [comment]
Is it now working or not, you post is not fully clear to me.

the latest git version needs 2.1.0-rc2 of the ESP core (when you use an ESP).

**Comment by Vitorbnc** [comment]
Thanks! It was not working with version 2.0, I meant all the other sketches were. Just updated ESP core and now it's compiling.
