### ISSUE TITLE
Olimex ESP32-Gateway Ethernet support?

### ISSUE THREAD

**Issue by hrodenburg** [Links2004/arduinoWebSockets#443]
Hi,

I'm trying to use this library on an [Olimex ESP32-Gateway](https://www.olimex.com/Products/IoT/ESP32/ESP32-GATEWAY/open-source-hardware) using it's integrated wired ethernet connection. However, it seems that the LAN chip is not supported at this time. If I'm correct, this board is using an LAN8710 as ethernet chip. The library seems to be een extension on the default wifi library used on an ESP32. The [example code](https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/examples/ETH_LAN8720/ETH_LAN8720.ino) works without a problem, but I cannot get it to work with this websockets library. Is there any chance to get this working together?

BTW, I tried to get this working myself (offcourse), but unfortunately I'm not experienced enough to get this solved.
Any hints or help is much appreciated!

**Comment by Links2004** [comment]
you can try to change the includes here:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L120

to

```cpp
#elif defined(ESP32)
#include <ETH.h>
#elif defined(ESP31B)
```
if the LAN8710 lib is full compatible to WiFiClient / WiFiClientSecure than that is all that is needed.
if its not compatible you will get a compile error or the connection will not work.
if so more adaption is needed.

**Comment by hrodenburg** [comment]
Thanks for your suggestion. Changing those lines indeed made it work, so I'm pretty happy with that!

And regarding your side-note, that sounds to make sense.
I've selected the board because it has integrated ethernet connection and therefore no extra wiring and external ethernet module is needed.

Thanks for helping out!

**Comment by liamcharmer** [comment]
> example code

Hi where is this sample code, i clicked the link and couldn't find. Would be cool to see if there is a way to do this with having ethernet instead of wifi.
