### ISSUE TITLE
beginSSL

### ISSUE THREAD

**Issue by sephyrah** [Links2004/arduinoWebSockets#444]
Hello,

I'm using beginSSL() to connect my esp32 to my websocket server. Like the example.
It works fine but when i close the server the esp32 doesn't disconnect and kinda crashes.
I am using the websocket.onEvent too. If I use normal websockets the Event function works just fine, with SSL it doesn't disconnect. Are they not compatible?  
This is my code:
```cpp
my Setup():

  { ... WiFi settings...
Serial.println("Setting Certficate....");
      client.setCertificate((char*)cert); // for client verification
    Serial.println("\nStarting connection to server...");
      ws.beginSSL("192.168.43.68", 3000); 
      ws.onEvent(webSocketEvent);}

loop():
   { ws.loop();}

onEvent():
void webSocketEvent(WStype_t type, uint8_t * payload, size_t length) {

  switch(type) {
    case WStype_DISCONNECTED:
      Serial.printf(".");
      break;

    case WStype_TEXT:
      Serial.printf("[WSc] get text: %s\n", payload);
      ws.sendTXT("Hello Server!");
      break;

    // ignore all
    case WStype_CONNECTED:
    case WStype_BIN:
    case WStype_ERROR:
    case WStype_FRAGMENT_TEXT_START:
    case WStype_FRAGMENT_BIN_START:
    case WStype_FRAGMENT:
    case WStype_FRAGMENT_FIN:
      break;
  }
} 
```

**Comment by Links2004** [comment]
may the SSL layer does not provide the correct events.

you can try to use ```enableHeartbeat```
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketClient/WebSocketClient.ino#L92

this will actively testing the connection via ping / pong.

**Comment by sephyrah** [comment]
> may the SSL layer does not provide the correct events.
> 
> you can try to use `enableHeartbeat`
> https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketClient/WebSocketClient.ino#L92
> 
> this will actively testing the connection via ping / pong.

It worked!!! Ty so much :smiley: 
I had to download this library again thou, didn't have that function.

Ty so much :grinning:
