### ISSUE TITLE
Timeout on TCP connect causes deadlock or crash.

### ISSUE THREAD

**Issue by william-ferguson-au** [Links2004/arduinoWebSockets#446]
When a WebSocket client is connected to a WebSocket is the WiFi AP drops out, the current behaviour of the WebsocketClient is to immediately attempt to reconnect in the #loop method. When it reconnects, it does so using the indefinite timeout tcp#connect method.

This causes either deadlock or a crash when the WiFI station finally re-establishes itself when the WiFi AP comes back up (at least on the ESP32).

The solution is to use #connect with a timeout so that the select is released on the socket handle.

Solutions is provided as #445

**Comment by Links2004** [comment]
fix is integrated in master
