### ISSUE TITLE
Board Continuously Resets if code parses "Payload"

### ISSUE THREAD

**Issue by coolguycoolstory** [Links2004/arduinoWebSockets#460]
I'm running into an issue that occurs when I include code to parse the payload, similar to the LEDcontrol example:

```cpp
void webSocketEvent(uint8_t num, WStype_t type, uint8_t * payload, size_t length) { // When a WebSocket message is received
  switch (type) {
    case WStype_DISCONNECTED:             // if the websocket is disconnected
		Serial.printf("[%u] Disconnected!\n", num);
		break;
    case WStype_CONNECTED: {              // if a new websocket connection is established
        IPAddress ip = webSocket.remoteIP(num);
        Serial.printf("[%u] Connected from %d.%d.%d.%d url: %s\n", num, ip[0], ip[1], ip[2], ip[3], payload);
        }
        break;
    case WStype_TEXT:                     // if new text data is received
      Serial.printf("[%u] get Text: %s\n", num, payload);
      LEDMode = 2;
      /*if (payload[0] == 'A') {     // the browser sends an "A" when animation is selected
        Serial.print("Animation Command converted to Integer: ");
        }*/
      break;
    }
}
```
The code runs beautifully as posted above, but to do anything meaningful I need to access what's in the payload, with the ultimate goal of extracting 2 or 3 integers from the payload to feed into commands for the FastLED library.  However, if I uncomment the commented out area, the board begins to reset continuously with the following output:

```
17:17:09.553 -> 
17:17:09.553 ->  ets Jan  8 2013,rst cause:2, boot mode:(3,6)
17:17:09.553 -> 
17:17:09.553 -> load 0x4010f000, len 1384, room 16 
17:17:09.553 -> tail 8
17:17:09.553 -> chksum 0x2d
17:17:09.553 -> csum 0x2d
17:17:09.553 -> vac02aff5
17:17:09.553 -> ~ld
```

I get no other serial messages as the board doesn't appear to enter the setup portion of the code... Lacking other knowledge I'd think it's some sort of interaction with another library, but the code still works just fine until I add code to parse that first byte of the payload. Reset cause 2 appears to be watchdog related, but I would think this comes into play more while the program is running.

I'm running a Wemos D1 mini, esp8266 version 2.5.2, with the following libraries:

```cpp
#include <ESP8266WiFi.h>
#include <WiFiClient.h>
#include <ESP8266WiFiMulti.h>
#include <ESP8266WebServer.h>
#include <ESP8266mDNS.h>
#include <WebSocketsServer.h>
#include <Hash.h>
#include <FS.h> //SPIFFS Library
#include <EEPROM.h>
#include <Wire.h> //D2 is SDA and D1 is SCL
#include <RTClib.h>
#include <FastLED.h>
```

Happy to post more of the relevant code if nothing jumps out immediately.

**Comment by Links2004** [comment]
Hi,

sounds a little strange,
I only can think of two reasons:

1. you are out of RAM you can for example try to move strings to flash or `F()`
or (which is very unlikely)
2. you need to check the length parameter (it is possible that you get a message with no payload)

but this problem Is hard to debug with this little information.

**Comment by coolguycoolstory** [comment]
Hello,

I haven't been able to solve all of my problems, but it is looking like I'm out of RAM; removing all unnecessary parts of my sketch to test this specific portion results in a successful connection with data coming through. I'll use your recommendation for moving strings to flash or F() and hopefully this will fully resolve the issue.

Thanks!

**Comment by coolguycoolstory** [comment]
One last question, since the issue hasn't been formally "closed" yet...

On the Webpage side, I'm sending a string in the form #000255255, where each set of three integers goes from 0 top 255. (I would also like to send an alternate format, A25501 with the second set of two going from 0 to however much). 

In my sketch I have the following, which only looks at the first 255 value (payload 4 thru 6).  I've been struggling to extract this value into a usable format for use elsewhere in my sketch. Here are the last three methods I tried to print the information out to Serial:

`      if (payload[0] == '#') {
		   Serial.println("Static Command converted to Integer: ");         

       Serial.print(payload[4]);
       Serial.print(payload[5]);
       Serial.println(payload[6]);

       int Prev1 = char(payload[4]);
       int Prev2 = char(payload[5]);
       int Prev3 = char(payload[6]);
       Serial.print(Prev1);
       Serial.print(Prev2);
       Serial.println(Prev3);
       
       Serial.print(char(payload[4]));
       Serial.print(char(payload[5]));
       Serial.println(char(payload[6]));
      
        LEDMode = 2;
	  }`



21:18:05.531 -> [WS][0][handleWebsocket] text: #000255255
21:18:05.531 -> [0] get Text: #000255255
21:18:05.531 -> Static Command converted to Integer: 
21:18:05.531 -> 505353
21:18:05.531 -> 505353
21:18:05.531 -> 255

So clearly, Serial.print(char(payload[i])) successfully displays the information, but trying to convert this to a different data format (or getting the individual bytes into one string of "255") has been a struggle. Would you have any recommendations for doing this?

Lastly, I've discovered that for some reason this also works:
`Serial.print(payload[4]-48);
       Serial.print(payload[5]-48);
       Serial.println(payload[6]-48);`

Returns:
21:37:32.991 -> 255

Appreciate all the help, apologies for the basic questions!

**Comment by Links2004** [comment]
in hex its easy, you can look  in the examples here:
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketServer_LEDcontrol/WebSocketServer_LEDcontrol.ino#L50

there I use a HEX RGB value to control a LEDs.

**Comment by coolguycoolstory** [comment]
Last question, related to the solution to the issue; in troubleshooting, I've found that only certain inline strings trigger the error; for example, Serial.print("AlarmNum") is no good, while Serial.print("AlarmMode") is perfectly fine. The strings that cause the chip to crash appear to be completely random, regardless of string length. Even the name for my WiFi SSID was being rejected.

I can't explain the cause, and it seems to happen regardless of how big the Sketch (or the string) are, but the solution was to instead use Serial.print(F("AlarmNum");, as you recommended.

However, I do have some arrays of strings that are being stubborn. This array:
`
const char* GlobalNLVariables[] PROGMEM = {"AlarmNum","AlarmMode"...}
`
is still being rejected, and using F() inside the array is not possible. Does that syntax look right to you or am I screwing it up?

Thanks again!

**Comment by Links2004** [comment]
in regards to some trigger the problem and others not, the compiler optimizes where ever possible so if you use a string multible times for example it will be only once in memory.

the 
```cpp
const char* GlobalNLVariables[] PROGMEM= {"AlarmNum","AlarmMode" };
```
will only place the pointers to the strings in  ```PROGMEM```

check https://www.arduino.cc/reference/en/language/variables/utilities/progmem/ "Arrays of strings" ;)
