### ISSUE TITLE
Uploading spiffs

### ISSUE THREAD

**Issue by Buzzardbait** [Links2004/arduinoWebSockets#464]
In attempting to use the WebSocketServerAllFunctionsDemo.ino the Biginner's Guide says - "upload the spiffs files using Tools > ESP8266 Sketch Data Upload". But the Arduino IDE has no such function. Did you mean use the ESP flash programming tool? Also, where do the .png, .ico and .json files come from? They are not in the sketch folder. Thanks

**Comment by Links2004** [comment]
to which beginner guide do you referring?

the example here:
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketServerAllFunctionsDemo/WebSocketServerAllFunctionsDemo.ino
is self contained, no png, ico, json or anything required.
so no spiffs upload needed.

the upload can be found here:
![spdiff](http://www.deloarts.com/img/scripts/esp8266/spiffs/ide.jpg "spiffs upload")
but I have no Idea why you will need it with my example code.

**Comment by Buzzardbait** [comment]
Ok, that's the same sketch (same date as the one I downloaded). Good to know those files are not needed. With regard to the Beginner's Guide, it was "Pieter P, 08-03-2017" that talked about uploading the spiffs. With regard to the Arduino IDE, I have version 1.8.9 and the ESP8266/NodeMCU libraries loaded but when I view the Tools drop down list I see WiFi101/WiFiNina Updater not ESP8266 Sketch Data Upload. The "Programmer:" settings under Tools give no ESP8266 option. I'm not sure how to fix that.

**Comment by KilianB** [comment]
@Buzzardbait the sketch data uploader is a plugin which has to be installed separately
https://github.com/esp8266/arduino-esp8266fs-plugin

**Comment by Buzzardbait** [comment]
Yes, got that. Thanks!
