### ISSUE TITLE
Protocol errors due to WebSockets::readCb misreading inbound data

### ISSUE THREAD

**Issue by ZaragonArt** [Links2004/arduinoWebSockets#470]
I am still investigating this but posting this before I fully understand it because I am having to understand the library code to work out what's happening and hopefully more knowledgeable people can look/suggest things. 

The symptom is that a client on an ESP32 sends a 1002 protocol error and usually, but not always, restarts the protocol. This is because it is, instead of reading the frame header reads frame data expecting it to be the header and then very soon afterwards the protocol breaks down either directly or via timeouts.

I can see this occurring from the debug, (and with additional statements inserted into the library) where the handleWebsocketWaitFor requests 2 bytes and gets 8 caused by a negative 1 response from client->tcp->read(). I haven't checked to see if this exceeds the buffer pointed to by out.

console log:
[WS][0][handleWebsocketWaitFor] size: 2 cWsRXsize: 0
[readCb] n: 2 t: 92050
n:2
[MJG][WebSockets.read :⸮0I
Receive -1 left 3!
n:3
[MJG][WebSockets.read :
Receive -1 left 4!
n:4
[MJG][WebSockets.read :({"
Receive 4 left 0!
[WS][0][handleWebsocketWaitFor][readCb] size: 2 ok: 1
[WS][0][handleWebsocket] ------- read massage frame -------
[WS][0][handleWebsocket] fin: 0 rsv1: 1 rsv2: 1 rsv3 1  opCode: 11
[WS][0][handleWebsocket] mask: 0 payloadLen: 34
[readCb] n: 34 t: 92057

I have no idea where the first four bytes are coming from at the moment as they are not in the websocket data stream captured as sent from the server by wireshark. The `(` is the correct header. Examining the wireshark capture the transmitted data is correct protocol and is correctly decoded by wireshark.

There is perhaps something time/speed related as without any debug messages the protocol error occurs very quickly and it feels that with more messages it is longer between fails. So the time taken to transfer data to the console does have an impact. But this is purely subjective.

The code section from the library with modified debug messages just to verify that I'm not affecting variables. My changes are tagged [MJG] so I know what to back out later:

```
bool WebSockets::readCb(WSclient_t * client, uint8_t * out, size_t n, WSreadWaitCb cb) {
#if(WEBSOCKETS_NETWORK_TYPE == NETWORK_ESP8266_ASYNC)
    if(!client->tcp || !client->tcp->connected()) {
        return false;
    }

    client->tcp->readBytes(out, n, std::bind([](WSclient_t * client, bool ok, WSreadWaitCb cb) {
        if(cb) {
            cb(client, ok);
        }
    },
                                       client, std::placeholders::_1, cb));

#else
    unsigned long t = millis();
    size_t len;
    DEBUG_WEBSOCKETS("[readCb] n: %zu t: %lu\n", n, t);
    while(n > 0) {
        DEBUG_WEBSOCKETS("n:%d\n",n);
        if(client->tcp == NULL) {
            DEBUG_WEBSOCKETS("[readCb] tcp is null!\n");
            if(cb) {
                cb(client, false);
            }
            return false;
        }

        if(!client->tcp->connected()) {
            DEBUG_WEBSOCKETS("[readCb] not connected!\n");
            if(cb) {
                cb(client, false);
            }
            return false;
        }

        if((millis() - t) > WEBSOCKETS_TCP_TIMEOUT) {
            DEBUG_WEBSOCKETS("[readCb] receive TIMEOUT! %lu\n", (millis() - t));
            if(cb) {
                cb(client, false);
            }
            return false;
        }

        if(!client->tcp->available()) {
#if(WEBSOCKETS_NETWORK_TYPE == NETWORK_ESP8266)
            delay(0);
#endif
            continue;
        }

        len = client->tcp->read((uint8_t *)out, n);
        if(len) {
          //[MJG]
            DEBUG_WEBSOCKETS("[MJG][WebSockets.read :%.*s\n",len,out);
            t = millis();
            out += len;
            n -= len;
            DEBUG_WEBSOCKETS("Receive %d left %d!\n", len, n); //[MJG]
        } else {
            //DEBUG_WEBSOCKETS("Receive %d left %d!\n", len, n);
        }
#if(WEBSOCKETS_NETWORK_TYPE == NETWORK_ESP8266)
        delay(0);
#endif
    }
    if(cb) {
        cb(client, true);
    }
#endif
    return true;
}

```

**Comment by ZaragonArt** [comment]
The call to WiFiClient::read is returning -1 because there is no data available to read when it calls _rxBuffer->read() this call doesn't return a failure because the error message associated is not printed to the console (I've debug level set at WARN). Plus failure would immediately cause the WiFi client to disconnect which it isn't.

I don't know what the proper return is for no data available.
The Arduino Ethernet library appears to return -1 for no data available and 0 for connection closed. The ESP8266 appears to return 0 for no data available (and also if there the buffer pointer is 0).

If -1 is an appropriate response then it may just need this section of code modifying to handle both conditions without using pre-compiler directives:
```
        if(len) {
            t = millis();
            out += len;
            n -= len;
            //DEBUG_WEBSOCKETS("Receive %d left %d!\n", len, n);
        } else {
            //DEBUG_WEBSOCKETS("Receive %d left %d!\n", len, n);
        }

```
to:
`        if(len>0) {
`

**Comment by ZaragonArt** [comment]
OK since len is defined as size_t that won't work ;)
It either needs to be defined as int or ssize_t for the comparison to work.
Changing the definition to ssize_t does appear, together with the change to the if statement does appear to make WebSockets::readCb operate correctly.

**Comment by simap** [comment]
This is definitely a bug on the esp32 as well, and @ZaragonArt's fix seems to be stable.
