### ISSUE TITLE
esp8266 socket.io ssl fails: Certificate is expired or not yet valid.

### ISSUE THREAD

**Issue by maxim-devlop** [Links2004/arduinoWebSockets#474]
Hello Markus,

thank you for your great project and lots of support.

I am trying to connect my esp8266 to my nodejs socket.io server, which is behind nginx, but the connection fails. After i activated debug level ssl and more, i can see the following output:

```
11:02:45.969 -> [SETUP] BOOT WAIT 3...
11:02:46.987 -> [SETUP] BOOT WAIT 2...
11:02:47.971 -> [SETUP] BOOT WAIT 1...
11:02:48.993 -> [WIFI][APlistAdd] add SSID: MYWIFI
11:02:48.993 -> 
11:02:48.993 -> [WIFI] STATION Mode, SSID: MYWIFI, IP address: 192.168.1.134
11:02:48.993 -> [WS-Client] connect wss...
11:02:48.993 -> [hostByName] request IP for: xserver.exampleserver.com
11:02:49.947 -> [hostByName] Host: xserver.exampleserver.com IP: 173.XXX.XXX.XXX
11:02:49.947 -> :ref 1
11:02:49.981 -> BSSL:_connectSSL: start connection
11:02:49.981 -> BSSL:Connection *will* fail, no authentication method is setup
11:02:50.015 -> :wr 225 0
11:02:50.015 -> :wrc 225 225 0
...
11:02:50.151 -> :rd 6, 398, 13
11:02:50.151 -> :rdi 385, 6
11:02:50.151 -> BSSL:_wait_for_handshake: failed
11:02:50.151 -> BSSL:Couldn't connect. Error = 'Certificate is expired or not yet valid.'
11:02:50.151 -> [WS-Client] connection to xserver.exampleserver.com:443 Failed
```

the certificate on the server recognized with firefox as valid:

![2019-09-17 11_23_43-Window](https://user-images.githubusercontent.com/55436286/65029469-1aa91880-d93e-11e9-8810-c156d290908a.png)
![2019-09-17 11_26_20-Window](https://user-images.githubusercontent.com/55436286/65029475-1e3c9f80-d93e-11e9-8053-594466c742a5.png)

If i connect with my own javascript socket.io client from the nodejs, the connection will be established. 

The nginx-server is configured like you descriped in previous issues:

```
        location @socketio {
                proxy_pass http://socketioweb:8080;

                proxy_redirect off;
                # enable WebSockets
                proxy_http_version      1.1;
                proxy_set_header        Upgrade                 $http_upgrade;
                proxy_set_header        Connection              "upgrade";
                proxy_set_header        Connection              keep-alive;

                proxy_set_header Host $host;
                proxy_set_header X-Real-IP  $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host:$server_port;
                proxy_set_header Host $http_host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-NginX-Proxy false;
                proxy_set_header X-Frame-Options SAMEORIGIN;
        }
```

I used following code to connect:
```
   webSocket.beginSocketIOSSL("xserver.exampleserver.com", 443);
    webSocket.onEvent(webSocketEvent);
```
I have also tried with begin, beginssl, socketio, socketioclient.begin... but the connection fails.

Could it be a bug? Or is it the misconfiguration of my server?

I have latest stand from github from master branch

**Comment by Links2004** [comment]
Hi,

its most likely the fact that you did not provide a fingerprint or CA.
the new bare SSL implementation for the ESP8266 require that.

https://github.com/esp8266/Arduino/blob/5d609fd29475c44c7b752b6cbf4128527f4977d3/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp#L1064

the signature for CA support can be found here:

https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.h#L57

**Comment by maxim-devlop** [comment]
Thank you Markus, i will check the ca
