### ISSUE TITLE
WebSocketsClient.cpp use deprecated function of BearSSL::WiFiClientSecure

### ISSUE THREAD

**Issue by Romocitto** [Links2004/arduinoWebSockets#477]
Hi, 
I've imported your library in my project:
- platform = espressif8266
- board = esp_wroom_02
- framework = arduino
When I build all, there are 2 problem:

'bool BearSSL::WiFiClientSecure::verify(const char*, const char*)' is deprecated (declared at C:\spb_data\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266WiFi\src/WiFiClientSecureBearSSL.h:180): This is deprecated AxTLS API, check https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/WiFiClientSecure.h#L25-L99 [-Wdeprecated-declarations]

'bool BearSSL::WiFiClientSecure::verify(const char*, const char*)' is deprecated (declared at C:\spb_data\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266WiFi\src/WiFiClientSecureBearSSL.h:180): This is deprecated AxTLS API, check https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/WiFiClientSecure.h#L25-L99 [-Wdeprecated-declarations]

How can I solve it?

**Comment by Links2004** [comment]
Hi,
this is not a problem by itself, the IDE is telling you that the used ```verify``` of the ESP SSL lib may is removed in a later version.
but for now there is no functional problem this is only a warning.
if the  ```verify``` is removed on the ESP this lib will be update to remove the calls too.
but for now there is no reason to break existing code that is out there.

the deprecated verify is only used if you use the old SSL API of the lib.
if you use the CA SSL commands all is fine in the future.

if you dont use SSL at all you can simply ignore the warning ;)
