### ISSUE TITLE
no 'Husarnet.h' file

### ISSUE THREAD

**Issue by barthex** [Links2004/arduinoWebSockets#478]
Error: WebSockets.h:177:22: fatal error: Husarnet.h: No such file or directory

**Comment by barthex** [comment]
Error during building in PlatformIO IDE 4.0.3

**Comment by Links2004** [comment]
this library does not include any file called ```Husarnet.h```
https://github.com/Links2004/arduinoWebSockets/search?q=Husarnet.h&unscoped_q=Husarnet.h
please give more details about the problem, and code to reproduce it.

**Comment by barthex** [comment]
Hi, this is problem with fork of your project https://github.com/husarnet/arduinoWebSockets.
