### ISSUE TITLE
won't compile on esp8266/arduino 2.0.0 (stable)

### ISSUE THREAD

**Issue by hellerchr** [Links2004/arduinoWebSockets#48]
Hi,

the code relies on "core_esp8266_features.h", which is not available in the current stable version. 
It has been introduced in the staging version (2.1.0)
see: https://github.com/esp8266/Arduino/commit/d9a7a816d51535b21fec38cb5db30cc8511075c3

Is that intended?

Cheers,
Chris

**Comment by Links2004** [comment]
yes "core_esp8266_features.h" where added short after 2.0.0 release
since the core have the same base64 code then the libary.
it added to avoid compiling problems with doubled functions.
the 2.0.0 release will not work.
