### ISSUE TITLE
Sec-WebSocket-Accept is wrong on W5100 connected to arduino Mega

### ISSUE THREAD

**Issue by oehoe** [Links2004/arduinoWebSockets#491]
If I try to connect to the websocket server echo.websocket.org I get the following response:

[WS-Client] connected to echo.websocket.org:80.
[WS-Client][sendHeader] sending header...
[WS-Client][sendHeader] sending header... Done (3800us).
[WS-Client][handleHeader] RX: HTTP/1.1 101 Web Socket Protocol Handshake
[WS-Client][handleHeader] RX: Connection: Upgrade
[WS-Client][handleHeader] RX: Date: Tue, 12 Nov 2019 17:29:37 GMT
[WS-Client][handleHeader] RX: Sec-WebSocket-Accept: laNKvpONja19va3frzg09VXT5r8[WS-Client][handleHeader] RX: Server: Kaazing Gateway
[WS-Client][handleHeader] RX: Upgrade: websocket
[WS-Client][handleHeader] Header read fin.
[WS-Client][handleHeader] Client settings:
[WS-Client][handleHeader]  - cURL: /
[WS-Client][handleHeader]  - cKey: NUguGpy+IHnzGoT7z40vlg==
[WS-Client][handleHeader] Server header:
[WS-Client][handleHeader]  - cCode: 101
[WS-Client][handleHeader]  - cIsUpgrade: 1
[WS-Client][handleHeader]  - cIsWebsocket: 1
[WS-Client][handleHeader]  - cAccept: laNKvpONja19va3frzg09VXT5r8=
[WS-Client][handleHeader]  - cProtocol: 
[WS-Client][handleHeader]  - cExtensions: 
[WS-Client][handleHeader]  - cVersion: 0
[WS-Client][handleHeader] Sec-WebSocket-Accept is wrong
[WS-Client][handleHeader] no Websocket connection close.
[WS-Client] client disconnected.
[WSc] Disconnected!

I have the same issue on my own websocket server. Other device have no problem connecting. What is causing the Sec-Websocket-Accept is wrong message?

Thanks for your help!

**Comment by Hilmanzhy** [comment]
try a library websocketsocketIO if thats server are http ws
https://github.com/Links2004/arduinoWebSockets/tree/master/examples/esp8266/WebSocketClientSocketIO

**Comment by oehoe** [comment]
@Hilmanzhy Could you confirm that the library you refer to is [https://github.com/timum-viw/socket.io-client/blob/master/SocketIoClient.h](url)? I have tried to use the library but it seem to be written for ESP8266 and I need to use a Arduino Mega with an ethernet shield. I'm unable to fix the "<map>" issues with the instructions of the read.me of the library. For code I'm using the example WebSocketClientAVR of this library.

**Comment by jeffrson** [comment]
Had the same problem. It turned out that in WebSockets::acceptKey there's a typo: "=+" instead of "+=".

Came over here to report this bug. However, I had to realize that in branches "master" as well as in "ATMega" this bug had been fixed long time ago. Unfortunately, the version I installed from Arduino IDE (even 1.8.10) still has it.

**Comment by oehoe** [comment]
@jeffrson Thank you very much! I'll close this item and download the library from github.
