### ISSUE TITLE
Some warnings

### ISSUE THREAD

**Issue by cristiancs** [Links2004/arduinoWebSockets#50]
warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
   bool connect(char hostname[], char path[] = "/", int port = 80);
                                               ^
warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
   bool connect(char hostname[], char path[] = "/", int port = 80);
                                               ^
WebSocketClient.cpp:51:29: note: in expansion of macro 'pgm_read_word'
     strcpy_P(buffer, (char*)pgm_read_word(&(WebSocketClientStringTable[index])));

Arduino 1.6.7

**Comment by Links2004** [comment]
which version and micro do you use?
the code has no function called "connect" or use the "strcpy_P" function.

**Comment by cristiancs** [comment]
I have a mess with the folders, I think it's not your code.
