### ISSUE TITLE
WEBSOCKETS_TCP_TIMEOUT too short when connecting to a server using ECC certificates

### ISSUE THREAD

**Issue by amrbekhit** [Links2004/arduinoWebSockets#500]
On the ESP32, when connecting to a websocket server that uses an ECC certfiicate (256-bit), it takes longer than the default 2000ms to establish a connection, which results in the `beginSSL` and `beginSslWithCA` commands failing due to `start_ssl_client` returning -1 due to the timeout, giving the following error message:

`WiFiClientSecure.cpp:132] connect(): start_ssl_client: -1`

It wasn't obvious from the error messages printed in the terminal what the cause of the problem was. It wasn't until I dug further into the source code that I identified the issue to be the code timing out [on this line](https://github.com/espressif/arduino-esp32/blob/91e095f5a76ec35f06c86689a87892425395b8db/libraries/WiFiClientSecure/src/ssl_client.cpp#L205).

On the ESP32, establishing a connection with ECC certs takes a lot longer than with RSA certs (about 1.5s more). As such, I think it would be a good idea to increase the default value of `WEBSOCKETS_TCP_TIMEOUT` to 5000 to ensure the code works by default.

**Comment by sovcik** [comment]
Having the same issue.
Took me two hours to come to the same conclusion :-)
