### ISSUE TITLE
 How to check connection availability?

### ISSUE THREAD

**Issue by Portia-Lin** [Links2004/arduinoWebSockets#503]
I want to send data to the client if there is a client connected. 
How can I check the connection and send data if the client has a connection?

**Comment by Links2004** [comment]
not sure if you talk about the server or client part of the lib, but the server has a function to check how many clients are connected.

https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsServer.h#L93

**Comment by Portia-Lin** [comment]
I think it will help me. I will send data if clients are more than 0.
But maybe I have the wrong approach to solve my problem.

https://github.com/Portia-Lin/esp8266-websocket/blob/master/esp8266-websocket.ino

**Comment by Links2004** [comment]
the ```broadcastTXT``` will send data only when there are clients.
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsServer.cpp#L222

checking for clients makes sense when you have to do bigger computation for the data to send to save CPU time, in your case its looks fine to simply always call `broadcastTXT`.

some side notes:

- may remove ```broadcastState``` from the `loop`, you will spam the client ;) (send updates only on change)
- not sure what the ```client``` in the loop will do but if you want to provide a HTML page may use the ESP webserver that you have defined.

may this example give you some hints and ideas:
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketServer_LEDcontrol/WebSocketServer_LEDcontrol.ino

**Comment by Portia-Lin** [comment]
How can i send 3 different variables to client and then display this variables on a web page? For example, temperature, humidity, pressure.
I tried:
`temperature = "1\:" + String(bme.readTemperature());
humidity = "2\:" + String(bme.readHumidity());
pressure = "2\:" + String(bme.readPressure() / 100.0F);
webSocket.broadcastTXT(temperature);
webSocket.broadcastTXT(humidity);
webSocket.broadcastTXT(pressure);`
And on the client side, for example:
`if(evt.data.slice(0,2)=="2:\") document.getElementById('state').value = evt.data.slice(2);`
But for some reason it doesn't work( Can you give me example of these or other implementation?
