### ISSUE TITLE
upgrading ESP8266 core to 2.6.3 breaks working AWS iot setup

### ISSUE THREAD

**Issue by WeaVaer** [Links2004/arduinoWebSockets#509]
My ESP8266 setup with core 2.4.2 uses ArduinoWebSockets 2.1.2 and also AwsMqttWebsockets library to connect to AWS iot and this works for more than a year without any problem.
I upgraded the ESP8266 core to 2.6.3 and wham! 
it stopped connecting with error (-2)
The new BearSSL methodology in WifiClientSecure class does not accept connection anymore.
I upgraded ArduinoWebSockets to 2.1.4 to see if the tweak about client.setInsecure() works but it does not. Debug says BearSSL *will* refuse the connection attempt to AWS because no auth method set and it does so, refusing the connection.
So I had to tweak WifiClientSecure class to use axTLS instead of BearSSL and ArduinoWebSockets  could connect once again.
I very much wonder what is the proper way of  making ArduinoWebSockets to connect to AWS over websockets (no certs, AwsMqttWebsockets library will use self-signed ones to initiate connection) and do some mqtt (with pubsubslient) on a successful connection.

**Comment by Links2004** [comment]
please test with 2.3.0 release and new ESP8266 Arduino core ( BareSSL support ).
feel free to reopen, if problem still exists.
