### ISSUE TITLE
Git Tag Version != library.properties / library.json version

### ISSUE THREAD

**Issue by sivar2311** [Links2004/arduinoWebSockets#510]
Hi Markus,

thanks for your great work!

Is there a reason why GIT Version Tag is different to library.properties / library.json version?
This is a bit confusing.

**Comment by Links2004** [comment]
the master is work in progress and the version in the files is not fixed
but v2.1.4 for example has a tag and correct version in the files.
https://github.com/Links2004/arduinoWebSockets/tree/2.1.4
https://github.com/Links2004/arduinoWebSockets/blob/2.1.4/library.json
https://github.com/Links2004/arduinoWebSockets/blob/2.1.4/library.properties
