### ISSUE TITLE
WebSockets Performance Issues

### ISSUE THREAD

**Issue by DasHammer** [Links2004/arduinoWebSockets#52]
I have noticed that I have to have my web socket server send a response to the client for every message the the client sends in order to get good performance. Is this expected? 

For example, the loop below runs on the client. This loop takes 2-3 seconds if the web socket server sends a response for every message that it receives.

If the server doesn't send a response for each message received then the loop below takes 200-300 seconds.

Loop running on the client:
 `
uint32_t numMsgs = 1000;
for(int i = 0; i < numMsgs; ++i)
{
   webSocket.loop();
   webSocket.sendTXT("Test Message");
}
`

I noticed this behavior when I was sending large files with your webSockets library. Do you have an example that shows the optimal method for sending large amounts of data?

**Comment by DasHammer** [comment]
Sorry about the formatting of the code snippet. This is what I mean to send:
```
uint32_t numMsgs = 1000;
for(int i = 0; i < numMsgs; ++i)
{
   webSocket.loop();
   webSocket.sendTXT("Test Message");
}
```

**Comment by Links2004** [comment]
yes the problem comes from the ack handling for the Sync TCP class.
for a faster sending try the async TCP handling.
https://github.com/Links2004/arduinoWebSockets/tree/async
https://github.com/me-no-dev/ESPAsyncTCP

**Comment by DasHammer** [comment]
I tried using the asynchronous webSocket library but I ran into a different problem. With the async webSocket the client no longer requires the server to send a response for each message but the application crashes after a few iterations of my loop. I also noticed that I have to call yield() every time I call webSocket.loop();

```
void loop()
{
   uint32_t numMsgs = 1000;
   unsigned long start = micros();
   for(int i = 0; i < numMsgs; ++i)
   {
      webSocket.loop();
      webSocket.sendTXT("Test Message");
      yield();
   }
   double transmitTime = ((double)micros() - start)/1E6;
   Serial.print("imageTransmitTime: ");Serial.println(transmitTime);
   yield();
   delay(1000);
}
```

Here's what the output looks like:


imageTransmitTime: 0.28
imageTransmitTime: 0.33
imageTransmitTime: 0.37

Exception (29):
epc1=0x4000df82 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: cont 
sp: 3fff0160 end: 3fff0450 offset: 01a0

>>>stack>>>
3fff0300:  3ffe84c4 00000008 3fffbf7c 40107a08  
3fff0310:  abc325a5 4c957f2d 3fff10e4 40205a48  
3fff0320:  00000002 00000000 3ffe84c0 0000000c  
3fff0330:  3ffe84c4 00000008 3fff10e4 40205084  
3fff0340:  3fffbf7c 0000028c 0000028c 40227bb7  
3fff0350:  40205638 00000001 3fff18f4 0000000c  
3fff0360:  00000000 00000001 3ffe84c0 402031ad  
3fff0370:  00008c81 00000000 00000000 00000000  
3fff0380:  00000000 00000000 3ffe84a8 402075e8  
3fff0390:  3ffef138 00000001 00000001 00000001  
3fff03a0:  00000003 3fff1906 00000006 40207848  
3fff03b0:  3ffe84a8 00000001 3ffe86b1 0000000c  
3fff03c0:  00000000 3ffe84c0 3ffef124 40203c18  
3fff03d0:  00000001 00000000 3ffef360 402058e1  
3fff03e0:  3ffef138 4010609b 3ffef430 3ffe8368  
3fff03f0:  3ffef124 007b5271 40205d94 007b5271  
3fff0400:  3ffef124 3ffe8368 000002d9 40203c34  
3fff0410:  00000003 415b03cd 00000000 40202717  
3fff0420:  00000000 00000000 00000001 3ffef41c  
3fff0430:  3fffdad0 00000000 3ffef415 40205de0  
3fff0440:  feefeffe feefeffe 3ffef430 40100b98  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 1264, room 16 
tail 0
chksum 0x42
csum 0x42
~ld


The transmission time is much faster! But the crash is problematic... Any suggestions?

**Comment by Links2004** [comment]
for async the loop call is not needed (the function is empty)

there is a tool to decode the stack dump:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.md

at the first look i can image too problems:
 - usage of a null ptr
 - internal tcp send buffer full (to many sendTXT calls in a short time).

the TCP has a debug too:
https://github.com/me-no-dev/ESPAsyncTCP/blob/master/src/ESPAsyncTCPbuffer.h#L28

may you get some usefull infos from it.

**Comment by DasHammer** [comment]
Thanks for the debugging tips!

I found that the exception is thrown from the following call:
[https://github.com/me-no-dev/ESPAsyncTCP/blob/master/src/ESPAsyncTCPbuffer.cpp#L114](https://github.com/me-no-dev/ESPAsyncTCP/blob/master/src/ESPAsyncTCPbuffer.cpp#L114)

It seems that I am overflowing the TX buffer. 

I modified my code so that it will wait until a certain amount of heap memory is available before calling sendTXT():

```
void loop()
{
   int numMsgs = 1000;
   int i = 0;
   unsigned long start = micros();
   while(i < numMsgs)
   {
      if(ESP.getFreeHeap()>3288)
      {
         webSocket.sendTXT("Test Message");
         i++;
      }
      yield();
   }
   double transmitTime = (micros() - start)/1E6;
   Serial.print("imageTransmitTime: ");Serial.println(transmitTime);
   yield();
}
```

This is a nasty hack but it works (so far). I found the magic number "3288" experimentally. If I use a smaller value than 3288 then the crash starts happening again. Maybe the webSocketsClient class could expose an entry point that would give us the remaining size of the TX buffer?

Unfortunately, the performance ends up being the same as what I was seeing with the synchronous webSocket. Here is some sample output:

imageTransmitTime: 0.32
imageTransmitTime: 0.41
imageTransmitTime: 1.75
imageTransmitTime: 2.67
imageTransmitTime: 2.49
imageTransmitTime: 2.45
imageTransmitTime: 2.70
imageTransmitTime: 2.49
imageTransmitTime: 2.67
imageTransmitTime: 2.64
imageTransmitTime: 2.61
imageTransmitTime: 2.69
imageTransmitTime: 2.48
imageTransmitTime: 2.53
imageTransmitTime: 3.11
imageTransmitTime: 2.48
imageTransmitTime: 2.47

It's difficult to tell where the performance bottle neck is here. However, I can improve performance if I send the message sets less often or if I increase the free heap threshold.

Thanks again!

**Comment by DasHammer** [comment]
I am seeing some strange behavior with another async webSocketClient application. In this application I am sending an image from the ESP8266 to a websocket server. This image is 250kB and is sent in multiple "chunks". If the server doesn't send a response for each image "chunk" sent by the ESP then it takes about 30 seconds to send the image. If the server does send a response for each chunk then it takes about 1.5 sends to send the image. Do you know what might be causing this behavior?

**Comment by Links2004** [comment]
its may linked to this:
https://github.com/esp8266/Arduino/issues/1577
