### ISSUE TITLE
namespace not supported

### ISSUE THREAD

**Issue by q-bird** [Links2004/arduinoWebSockets#520]
Hi,
This is socket.io namespace feature: https://socket.io/docs/rooms-and-namespaces/
In nodejs server I setup namespace like that and it's working well with webapp client. But I couldn't make it work with ESP32

So the question is how can I get connection with server via namespace using this library for ESP32 client?

Thanks,

**Comment by q-bird** [comment]
@Links2004 Please help

**Comment by q-bird** [comment]
Hi, I got it done already :)
Thanks

**Comment by coma0815** [comment]
Hi, could you tell us how you did make this work? Could you please share your code? 
Thank you!

**Comment by alaa-fouzai** [comment]
> Hi, I got it done already :)
hi, can you help me with implementing namespaces in esp client side of things ? or at least tell me how it works ? 
a sample code would be highly appreciated 
thanks !

**Comment by q-bird** [comment]
Hi

Suppose that `_nsp` is your namespace
Once you receive connection event from server, pls feedback as the following:
```C++
case WStype_CONNECTED:
	{
		...
		webSocket.sendTXT("5");
		if(_nsp != "") {
			webSocket.sendTXT("40/" + _nsp); // request connection with namespace to server
		} else {
			//without namespace, do something here
		}
		...
	}
	break;
```
From socketio documentation, you will notice that without namespace the package will be `42["event-name", payload]`
But with namespace it will be: `42/your_namespace,["event-name", payload]`
So just write a function to do it

```C++
void yourEmit(const char* event, const char * payload) {
	...
	String msg = _nsp != "" ? String("42/" + _nsp + ",[\"") : String("42[\"");
	msg += event;
	msg += "\"";
	if(payload) {
		msg += ",";
		msg += payload;
	}
	msg += "]";
	webSocket.sendTXT(msg);
	...
}
```

p/s: I'm using the old version so I can build the `msg` before sending it. I'm not sure if you can do it with the latest version or not. Or you may need to add those things to the library.
Hope @Links2004 can add this feature

**Comment by alaa-fouzai** [comment]
thx it was a huge help ....
i did as you told me and it worked 
i did however hard code the name space as im very short on time for now 
thx very much

**Comment by q-bird** [comment]
@alaa-fouzai 
Glad to hear :)
BTW you using the latest lib?

**Comment by alaa-fouzai** [comment]
yes its the latest lib 
i changed the lib as you told me to do and it worked 
i did although hard code the namespace into the lib 
my namespace was /Sensor/UpdateRelay ,if anyone decides to they just need to change that in this code 
```
case` WStype_CONNECTED:
				{
					_webSocket.sendTXT("5");
					String _nsp="12233";
					if(_nsp != "") {
						_webSocket.sendTXT("40/Sensor/UpdateRelay"); // request connection with namespace to server
					} else {
						//without namespace, do something here
					}
				`}
```
and added a new function
```
void SocketIoClient::EmitToNameSpace(const char* event, const char * payload) {
	String _nsp = "new";
	String msg =_nsp != "" ? String("42/Sensor/UpdateRelay,[\"") : String("42[\"");
	msg += event;
	msg += "\"";
	if(payload) {
		msg += ",";
		msg += payload;
	}
	msg += "]";
	_webSocket.sendTXT(msg);
}
```
i know this is not a good way to do it but im very short on time and i need a working demo soon 
i cant thank you enough you saved me alot of valuable time

**Comment by xdien** [comment]
Added more clarity on how it works with socket.io@2.4.1

```
./Websockets/src/SocketIOclient.cpp


void SocketIOclient::emitToNameSpace(const char * payload, String &nsp) {
	String msg = nsp != "" ? String("42" + nsp + ",") : String("42[\"");
	if(payload) {
		msg += payload;
	}
	WebSocketsClient::sendTXT(msg);
}

```
Append line after public
```
./Websockets/src/SocketIOclient.h

public:
    void emitToNameSpace(const char * payload, String &nsp);

```
