### ISSUE TITLE
cant connect to ratchet socket server

### ISSUE THREAD

**Issue by darkworks** [Links2004/arduinoWebSockets#523]
Hi i had created socket server in core php socket library and my nodeMCU was able to connect with it , but recently i switched to ratchet and my nodeMCU is not able to connect to it am getting  Disconnected message every time in serial terminal.   looks like something wrong with ratchet handshake 

```
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: s/HKLennCtR1jWTCNlUocA==
Sec-WebSocket-Protocol: arduino
Origin: file://
User-Agent: arduino-WebSocket-Client

[write] n: 269 t: 5580
[WS-Client][sendHeader] sending header... Done (303089us).
[WS-Client][handleHeader] RX: HTTP/1.1 426 No Sec-WebSocket-Protocols requested supported
[WS-Client] connection lost.
[WS-Client] client disconnected.
[WSc] Disconnected!
[WS-Client] connect ws...

```

**Comment by Links2004** [comment]
your server does not like the "Sec-WebSocket-Protocol" header,
you can disable it by setting the ```protocol``` parameter to empty string ```""```

https://github.com/Links2004/arduinoWebSockets/blob/c64f2b81e5fbb0b341ebeddf3536da0be69881f9/src/WebSocketsClient.cpp#L42

**Comment by Links2004** [comment]
feel free to reopen if this still is a problem.

**Comment by darkworks** [comment]
ya the problem is solved . sorry i forogt to update u back on it
