### ISSUE TITLE
ESP8266 WebSocketServer unable to access 192.168.4.1

### ISSUE THREAD

**Issue by TheAngusBurger** [Links2004/arduinoWebSockets#529]
I have an ESP8266 (cheap ESP-01), which I put in flash mode. I then upload the WebSocketServer.ino example, and then after resetting the ESP8266 I connect to the new open wifi network.

From what I understand, at this point I should connect the ESP8266 to my home network by accessing 192.168.4.1 through a browser, although this doesn't seem to work? Any ideas?

I am following this tutorial here:
http://lasergrbl.com/usage/wifi-with-esp8266/

**Comment by Links2004** [comment]
the tutorial you linked is not using the WebSocketServer.ino example of my lib it has its own code.
https://github.com/arkypita/ESP8266-SerialWebSocket/blob/master/websocketserver/websocketserver.ino

in the case of my example you simply write the SSID and password in the code:
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketServer/WebSocketServer.ino#L73
