### ISSUE TITLE
'class SocketIOclient' has no member named 'send'

### ISSUE THREAD

**Issue by chanon0078** [Links2004/arduinoWebSockets#532]
I need to send Acknowledge from socket.io on my nodejs server to arduino client 
 
I follow on ESP8266  example > WebSocketClientSocketIOack.ino  so I got error like this below

```
error: 'class SocketIOclient' has no member named 'send'
socketIO.send(sIOtype_ACK,output);
```

So, How to solve this I want to response acknowledge to node js server or  I can use 

> .sendEvent()

 instead ??

thank you

**Comment by Links2004** [comment]
that is strange, the code is here:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/SocketIOclient.h#L62

what version of the lib do you use?

**Comment by chanon0078** [comment]
> that is strange, the code is here:
> https://github.com/Links2004/arduinoWebSockets/blob/master/src/SocketIOclient.h#L62
> 
> what version of the lib do you use?

I Install library via Manage Libraries option in ArduinoIDE then I go to MyDocument > Arduino > WebSocket > SocketIOClient.h I found only sendEvent() 

So, I download code from github and replace src folder then I can build without error 👍 
Thank for you reply.

P.S. I Installed IRremoteESP8266 version 2.7.6 library via Manage Libraries in IDE that run me to problem
