### ISSUE TITLE
When I used esp32, I reported an error

### ISSUE THREAD

**Issue by clothesack** [Links2004/arduinoWebSockets#538]
I tried to replace all versions of Ethernet and always reported an error. How can I solve this problem? Or if there is an example of esp32, let me refer to it. Thanks
![image](https://user-images.githubusercontent.com/39519250/81385944-c6f67400-9146-11ea-8fdd-132000ad0b75.png)

**Comment by Links2004** [comment]
not sure why but normally the Ethernet.h is not included for ESP32.
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L173
its only used for STM32 and W5100.

are you sure that you have select the correct board in your IDE?

ESP32 examples are included in the libary:
https://github.com/Links2004/arduinoWebSockets/tree/master/examples/esp32

**Comment by clothesack** [comment]
Thank you for your reply. I only saw the websocketclientstop sample of esp8266, but I did not find the websocketclientstop sample of esp32.
