### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by thomascoding** [Links2004/arduinoWebSockets#54]
Just try to compile WebSocketClient example

` Arduino:` 1.6.7 (Mac OS X), Плата:"Generic ESP8266 Module, Serial, 80 MHz, 40MHz, DIO, 921600, 4M (3M SPIFFS), ck"

/Users/artem/Documents/Arduino/libraries/WebSockets/src/WebSockets.cpp:28:35: fatal error: core_esp8266_features.h: No such file or directory
 #include <core_esp8266_features.h>

compilation terminated.
exit status 1

`

**Comment by hellerchr** [comment]
see: https://github.com/Links2004/arduinoWebSockets/issues/48

**Comment by wdereski** [comment]
HELP!
I get this error as well and I don't understand how to fix it.
/Users/hahunt42/Documents/Arduino/libraries/arduino_55659/src/WebSockets.cpp:28:35: fatal error: core_esp8266_features.h: No such file or directory
 #include <core_esp8266_features.h>

                                   ^
compilation terminated.
exit status 1
Error compiling.

**Comment by Links2004** [comment]
for the latest version, you need the staging version of the ESP core, then it work.
https://github.com/esp8266/Arduino#staging-version-
see: #48, #44, #36, #32, #30
