### ISSUE TITLE
Sync Mode Loop function when disconnected

### ISSUE THREAD

**Issue by n9wxu** [Links2004/arduinoWebSockets#541]
When executing the loop while the library is disconnected, a large number of DNS checks are attempted and fail.

The loop should check for an active connection and stop trying to do stuff before the connection is started.

I had to add an "active" flag that was set on the ::begin method and cleared on the disconnect event to govern the loop call.  This is sloppy and required digging a bit to be somewhat sure that this was a reasonable fix.

**Comment by Links2004** [comment]
can you define "a large number", the expectation is a connection attempt every 500ms.
which can be configured via `setReconnectInterval`
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.cpp#L353

and is handled by 
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.cpp#L154

can you give more details for  `before the connection is started`?
is `loop` called before `begin`? 
which is a use case I never tested, 
since Arduino code is normally designed that begin is called before loop.

**Comment by n9wxu** [comment]
Loop is called before begin.
In my application, the websocket is "begun" when a specific event occurs.  I need to call the loop to manage the socket.  If the event has not arrived, then I need to do something with loop().  i.e. not-call it.
So If I am suppose to manage calling or not_calling the loop function, I suppose I start calling at BEGIN, but when do I stop?  End calls disconnect.  Should there be a few loops() to complete the disconnection?  the is_connected() call is private so I cannot simply check that.  It would be best if loop simply did the right thing and I call loop ALL THE TIME.
That is until ASYNC works nicely for ESP32.

**Comment by n9wxu** [comment]
A large number is defined as one every time I call loop.  Probably 1000/sec in my application.

**Comment by Links2004** [comment]
```diff
diff --git a/src/WebSocketsClient.cpp b/src/WebSocketsClient.cpp
index c67b706..967bc9d 100644
--- a/src/WebSocketsClient.cpp
+++ b/src/WebSocketsClient.cpp
@@ -31,6 +31,8 @@ WebSocketsClient::WebSocketsClient() {
     _client.cIsClient    = true;
     _client.extraHeaders = WEBSOCKETS_STRING("Origin: file://");
     _reconnectInterval   = 500;
+    _port                = 0;^M
+    _host                = "";^M
 }
 
 WebSocketsClient::~WebSocketsClient() {
@@ -148,6 +150,9 @@ void WebSocketsClient::beginSocketIOSSLWithCA(const char * host, uint16_t port,
  * called in arduino loop
  */
 void WebSocketsClient::loop(void) {
+    if(_port == 0) {^M
+        return;^M
+    }^M
     WEBSOCKETS_YIELD();
     if(!clientIsConnected(&_client)) {
         // do not flood the server
diff --git a/src/WebSocketsClient.h b/src/WebSocketsClient.h
index ed3f630..77d83d7 100644
--- a/src/WebSocketsClient.h
+++ b/src/WebSocketsClient.h
@@ -90,13 +90,13 @@ class WebSocketsClient : protected WebSockets {
 
     void enableHeartbeat(uint32_t pingInterval, uint32_t pongTimeout, uint8_t disconnectTimeoutCount);
     void disableHeartbeat();
+    ^M
+    bool isConnected(void);^M
 
   protected:
     String _host;
     uint16_t _port;
 
-    bool isConnected(void);
-
 #if defined(HAS_SSL)
     String _fingerprint;
     const char * _CA_cert;
```
