### ISSUE TITLE
Number of Websocket clients

### ISSUE THREAD

**Issue by iivan19** [Links2004/arduinoWebSockets#543]
Hi, I am using the library to communicate a server with different clients. I have seen that according to the library the maximum is 5 but only 4 connect to me (the number 0,1,2,3) the fifth does not connect and I do not understand why.

The problem is twofold because I would need to have 6 clients connected, is that possible?

**Comment by Links2004** [comment]
do you have other network connections open in you code?
the TCP stack on the ESP limited and can only a specific amount (based on which lwip you select in the IDE)

if you are using the ESP in AP mode, then the ESP is limited to 4 WiFi clients by default.
see `max_connection` here:
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/ESP8266WiFiAP.h#L40

**Comment by iivan19** [comment]
> do you have other network connections open in you code?
> the TCP stack on the ESP limited and can only a specific amount (based on which lwip you select in the IDE)
> 
> if you are using the ESP in AP mode, then the ESP is limited to 4 WiFi clients by default.
> see `max_connection` here:
> https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/ESP8266WiFiAP.h#L40

As far as I know I have no more open connections.

If I am using an AP mode MCU node ... and I wanted to connect 6 clients (5 nodeMCU clients and a mobile application) .. I don't know what the solution would be ..

**Comment by Links2004** [comment]
something like this:
```cpp
WiFI.softAP("ssid", "password", 3, 0, 6);
```

and https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsServer.h#L31 need to be changed, but not sure what the current max TCP client limit is for the different LwIP versions.
