### ISSUE TITLE
Ethernet W5100 with ESP8266

### ISSUE THREAD

**Issue by Jono72** [Links2004/arduinoWebSockets#544]
Hi Markus

I apologise in advance if this may seem like a silly question, not being an experienced developer, I am currently trying to use you Web socket server library (using ESP07S), however I am not using WIFI (this has been disabled in my code), I am using Ethernet interface (W5100); there is very little on using ESP with hardwired Ethernet as everything seems to be based on the WIFI connection. I found the define in websockets.h of your library for defining network type (I assume this is where I change it), I commented out ESP8266 and uncommented W5100 line.
Then using slightly modified example to allow for Ethernet connection, the web browser fails on the Handshake connection, websocket then displays connection type as disconnected in the serial monitor.

I have attached code (test sketch) and java script call for the web socket (this is all uploaded from the SPIFFs)

[Websocket Test ESP07S.txt](https://github.com/Links2004/arduinoWebSockets/files/4778037/Websocket.Test.ESP07S.txt)
[Java WebSocket Call.txt](https://github.com/Links2004/arduinoWebSockets/files/4778038/Java.WebSocket.Call.txt)

I am sure I'm probably missing something obvious, I would be grateful for any help this is driving me mad.

many thanks

John

**Comment by k-zhai** [comment]
I am also having this issue, but with an ESP32 and W5500
