### ISSUE TITLE
Combining data requested from webpage and pushing from esp32

### ISSUE THREAD

**Issue by videobuff** [Links2004/arduinoWebSockets#545]
Hi,

I have build an antenna rotor controller using the websockets library and really happy with the functioning. However, there is one issue i cannot get to work.

In my project, the webpage switches and requests status of a couple of switches, but I also have to push data from the ADC output as soon as the output changes. 
I have it working for one client, but if i use the second client, the switches keep working but the ADC values are not coming in.
In the routine  
`void onWebSocketEvent(uint8_t client_num,
                      WStype_t type,
                      uint8_t * payload,
                      size_t length) {`

I use the command `webSocket.sendTXT(client_num, msg_buf)`

In the loop routine i check the value of the ADC and like to send it as `webSocket.sendTXT(client_num, rotor) `but i get the error
`client_num' was not declared in this scope`

How can I push data to all of the clients independent of the websocket event routine ?

Hope you can help.

Erik

Here is my repository. The code is not yet cleaned up.
https://github.com/videobuff/ESP32-Remote-Rotor-Control

**Comment by Links2004** [comment]
If I understand you question correct you want so send the data to all connected clients here:

```cpp
void sent_bearing_ws(){
     // compare last & current value of bearing. Only sent new data if > 2 degrees.
    read_rotor_bearing();
    if (analog_val < analog_val_old-1 || analog_val > analog_val_old +1 ) {
              String rotor = String(analog_val);
              rotor = "Bearing :"+rotor,
              webSocket.sendTXT(0, rotor);
              Serial.print("Current Rotor bearing is :");
              Serial.println(analog_val);  
              //Serial.print("Previous Rotor bearing is :");
              //Serial.println(analog_val_old);  
              analog_val_old = analog_val;
  }
}
```

to send to all connected clients you can use:

```cpp
webSocket.broadcastTXT(rotor);
```

in short `sendTXT` is for sending messages to one specific client,
and `broadcastTXT` will send it to all connected clients.

**Comment by videobuff** [comment]
Thank you very much. Modified the sketch and all is working absolutely fantastic. I need to read on the library to see what else is possible....
