### ISSUE TITLE
Extracting data from string sent by client over websocket

### ISSUE THREAD

**Issue by videobuff** [Links2004/arduinoWebSockets#548]
I have been at it now for over a week, and can't get it sorted.
In my antenna rotor project, a message is sent over the websocket from the client to the ESP32 which reads as: MANUAL:123
I am trying to extract the number.  

Under the routine ` case WStype_TEXT:`

```
void onWebSocketEvent(uint8_t client_num,
                      WStype_t type,
                      uint8_t * payload,
                      size_t length) {
```
```

     // Print out raw message
       Serial.printf("Received text from: [%u] Payload: %s\n", client_num, payload);`

```
gives me  `Received text from: [0] Payload: MANUAL:123`
So the payload contains `MANUAL:123`

But using a substring function on payload fails.
(B.t.w. the numerical value changes from 0 to 359.)

How do i recognize this string, or in fact the first 7 characters, since they are always the same and extract the number to do a comparison function  ?
Your help is grreatly appreciated.

Erik, PA0ESH

**Comment by Links2004** [comment]
The `payload` is not a string its a `uint8_t` array,
to use the Arduino string functions on it it a String needs to be prepared.

not tested code as hint:

```cpp
// create String
String str = String(payload);

// split key and value
String key  = str.substring(0, str.indexOf(':'));
String value = str.substring(str.indexOf(':') + 1);

if(key.equalsIgnoreCase("manual")) {
    // convert value to Int
    uint16_t valueInt = value.toInt();
}
```

**Comment by videobuff** [comment]
Thanks for pointing me out. I will work on it and let you know if i succeeded.

**Comment by videobuff** [comment]
Got it working, but only after i put the code in the unknown message part.
I tried to figure out how to make the code run in a separate. If statement but not successfully. However, i can live with the current solution. Thank you very much.

**Comment by Links2004** [comment]
you may need to create a new scope, since creating new variables in switch case is not possible without a new scope.

```cpp
case WStype_TEXT: {
    // create String
    String str = String(payload);

    // split key and value
    String key  = str.substring(0, str.indexOf(':'));
    String value = str.substring(str.indexOf(':') + 1);

    if(key.equalsIgnoreCase("manual")) {
        // convert value to Int
        uint16_t valueInt = value.toInt();
    }
}
break;
```

**Comment by mrdsn3** [comment]
I use this code but I get error (""call of overloaded 'String(uint8_t*&)' is ambiguous
"")
how I can read received data as string and use it for creating json file?

case WStype_TEXT: {
    // create String
    String str = String(payload);

    // split key and value
    String key  = str.substring(0, str.indexOf(':'));
    String value = str.substring(str.indexOf(':') + 1);

    if(key.equalsIgnoreCase("manual")) {
        // convert value to Int
        uint16_t valueInt = value.toInt();
    }
}
break;

**Comment by Links2004** [comment]
looks like something changed for the `String` class, try:
```cpp
String str = String((const char*) payload);
```

**Comment by Links2004** [comment]
```cpp
String str = String((const char*) payload);
```
