### ISSUE TITLE
handle authentification

### ISSUE THREAD

**Issue by sabativi** [Links2004/arduinoWebSockets#55]
if using WebSocketClient on arduino with a non arduino Socket server, what's the best way to handle authentification ?
Can an example be provided ? ( or just explain and i will write a PR for this )

**Comment by Links2004** [comment]
have add HTTP Basic Auth support to the client and server.

example setup:
```cpp
    webSocket.begin("192.168.0.123", 81);
    webSocket.setAuthorization("user", "Password"); // HTTP Basic Authorization
    webSocket.onEvent(webSocketEvent);
```

**Comment by lrusnac** [comment]
nice work by implementing basic authentication

**Comment by sabativi** [comment]
Indeed Thanks !

**Comment by Programming4life** [comment]
How do I add auth to the web socket server?
I've tried this and it does not work.
Server
```
webSocket.begin();
webSocket.setAuthorization("test", "test");
webSocket.onEvent(webSocketEvent);
```

Client
```
var Socket = new WebSocket('ws://test:test@192.168.0.3');
Result: failed: Error during WebSocket handshake: Unexpected response code: 400
````

**Comment by Links2004** [comment]
currently most browsers not supports adding username + password to the ws URLs, on the `new WebSocket` call.
but it will work if you use the same Authorization for the webpage of the ESP.

more can be found example in the chromium bug tracker:
https://bugs.chromium.org/p/chromium/issues/detail?id=123862

#116
