### ISSUE TITLE
Websockets compiling in Arduino IDE but not PlatformIO

### ISSUE THREAD

**Issue by ringmybell** [Links2004/arduinoWebSockets#550]
I have recently started using PlatformIO (so it is still a bit unfamiliar to me). As part of my testing I have ported over some known code that uses the Websockets library but getting errors when building in PlatformIO.

```
Compiling .pio\build\pico32\liba80\WebSockets\SocketIOclient.cpp.o
In file included from .pio\libdeps\pico32\WebSockets\src\SocketIOclient.cpp:8:0:
.pio\libdeps\pico32\WebSockets\src\WebSockets.h:165:18: fatal error: WiFi.h: No such file or directory 
```

It still compiles in Arduino, but I am using libraries i previously downloaded as zip files nd loaded into Arduino IDE

I have downloaded the same version of libraries from the PlatformIO library, saved them locally, changed librairy headers to be local and added arduino.h but not working.

I noticed the websocket build is failing according to Github, I am assuming that (somehow) the previous version I saved as a zip file is working but the library downloaded today through PlatformIO is currently not working?

Thanks

![image](https://user-images.githubusercontent.com/30030587/87142617-23614580-c2e8-11ea-8938-0c3b4ae5eb62.png)

**Comment by Links2004** [comment]
I am using PlatformIO with vscode my self and its working fine there.
the build fail is unrelated 
https://travis-ci.com/github/Links2004/arduinoWebSockets/jobs/358985116
the build is using the master branch of the esp8266 core and the esp8266 master is broken at the moment, ESP32 is building fine.

https://travis-ci.com/github/Links2004/arduinoWebSockets


what version of the library do you have installed?
the "WebSockets.h:165" does not match with the latest release 
https://github.com/Links2004/arduinoWebSockets/blob/2.2.0/src/WebSockets.h#L165


example platformio.ini

```ini
[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino

monitor_port = /dev/ttyUSB0
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0

upload_port = /dev/ttyUSB0
upload_speed = 460800
```

**Comment by ringmybell** [comment]
Thanks a bunch for replying.

Yes I had old versions of libraries in order to trouble shoot against the working Arduino version (that had older libraries)

Closing the circle on this, it appears that adding "lib_ldf_mode = deep+" to the platform.ini file was causing the problem. I am not sure why - any ideas why? Previously in other completely unrelated non-wifi projects I have had problems with builds that could only be resolved with this deep+ command, it seems on this project it was causing an issue.

**Comment by Links2004** [comment]
ok i never used `lib_ldf_mode` in any of my projects, and I have a lot ;)
when I had problems with libraries not found I always where able to solve it 
by adding a include of a header file of it to the "main.cpp" (where the setup and loop is)

**Comment by ringmybell** [comment]
Thanks for the tip - and appreciate the library you put together for us code challenged individuals :-)
