### ISSUE TITLE
ESP8266 SSL connection doesn't work

### ISSUE THREAD

**Issue by gbaranski** [Links2004/arduinoWebSockets#555]
Hello, can anyone show me how You connect with websocket using SSL? I do same as example does and it doesn't want to work, but that works on ESP32. I don't add fingerprint or CA, but even with SHA1 fingeprint which is formatted like that 00:00 it doesn't want to work. I've got 2.2.1 version from platformio library.

**Comment by Links2004** [comment]
most likely fixed via #557 please recheck.
feel free to reopen when this does not fix the Problem.
