### ISSUE TITLE
Connected on Flask SocketIO Server but still disconnected on esp8266

### ISSUE THREAD

**Issue by leond08** [Links2004/arduinoWebSockets#559]
SOCKETIO server: Flask SocketIO

I encountered a weird error when connecting to my flask socketio server
On my flask socketio server it says "connected" but on my esp8266
the connection is "disconnected".
The error is "[IOc] Disconnected!"

Here is my code:

```
SocketIOClient socketIO;

void socketIOEvent(socketIOmessageType_t type, uint8_t * payload, size_t length) {
    switch(type) {
        case sIOtype_DISCONNECT:
           Serial.printf("[IOc] Disconnected!\n");
            break;
        case sIOtype_CONNECT:
            Serial.printf("[IOc] Connected to url: %s\n", payload);
            break;
        case sIOtype_EVENT:
            Serial.printf("[IOc] get event: %s\n", payload);
            break;
        case sIOtype_ACK:
            Serial.printf("[IOc] get ack: %u\n", length);
            hexdump(payload, length);
            break;
        case sIOtype_ERROR:
            Serial.printf("[IOc] get error: %u\n", length);
            hexdump(payload, length);
            break;
        case sIOtype_BINARY_EVENT:
            Serial.printf("[IOc] get binary: %u\n", length);
            hexdump(payload, length);
            break;
        case sIOtype_BINARY_ACK:
            Serial.printf("[IOc] get binary ack: %u\n", length);
            hexdump(payload, length);
            break;
    }
}

socketIO.begin("192.168.0.1", 5001);
socketIO.onEvent(socketIOEvent);

```
Flask:

```
@socketio.on('event')
def event_message(message):
logging.info(message)

@socketio.on('connect')
def event_connect():
mac = get_mac_address(ip=request.remote_addr, network_request=False)
emit('event', {'data': 'connected', 'mac': mac}, broadcast=False)

@socketio.on('disconnect')
def event_disconnect():
emit('event', {'data': "disconnected", 'mac': ""}, broadcast=False
```

On my Flask server It say's connected:
f497ae608950497cb85403b54e3d9c51: Sending packet OPEN data {'sid': 'f497ae608950497cb85403b54e3d9c51', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
emitting event "event" to f497ae608950497cb85403b54e3d9c51 [/]
f497ae608950497cb85403b54e3d9c51: Sending packet MESSAGE data 2["event",{"data":"connected","mac":"fc:f5:c4:94:7c:7f"}]

But on nodemcu: Got this
[IOc] Disconnected!
[IOc] Disconnected!
[IOc] Disconnected!
[IOc] Disconnected!
[IOc] Disconnected!

**Comment by 3omer** [comment]
Had same problem:
Here what I done to solve it:
1- https://stackoverflow.com/a/62774684
2- Run the server as mentioned in the docs "python server.py" for example. Not by flask run

**Comment by Links2004** [comment]
no need to edit files :)
the `setExtraHeaders` function can be used to overwrite the extra headers.
and CORS problems is exactly why `Origin` is in there, in a way that allows the user to overwrite or remove it.

```cpp
socketIO.setExtraHeaders("");
```
https://github.com/Links2004/arduinoWebSockets/blob/a71a4806764c1c1fcd63bcbfd0c48c0a96226177/src/WebSocketsClient.cpp#L344-L346

side note:

`file://` is the default since the websocket connection does not come from a webpage, and its a value that works with almost any servers that allow any (`*`) origin.
