### ISSUE TITLE
ESP32 - Packets somehow lost?

### ISSUE THREAD

**Issue by ArosPrince** [Links2004/arduinoWebSockets#568]
Hi, I have this very weird problem which is difficult to debug.

I am sending 480 016 bytes of data from either a browser or and Android hybrid app to ESP. Those data are split to 1506-byte-long chunks and I send them as fast as possible. It works well most of the time. More specifically, it works flawlessly from any browser and most Android phones. But doing this from one specific (Chinese something) Android 9, some of the data get lost somewhere. And it seems that exactly 6 of those chunks do not make it to ESP32, but I get no error on either sides (which is odd considering this is in fact a TCP connection). When I debug the app from the Chrome console, I can see that everything was sent OK, and there is no error. But counting the bytes received on ESP32 gives me 470 980 bytes. Which corresponds to 6 packets being lost somewhere.

Could this somehow happen with this WebSocket library? The data would have to be dropped somewhere between replying ACK to the sender and calling the handler, right?

WStype_ERROR is never passed in the handling function.

Also, it seems that those are always the same packets that get lost.

It can possibly also be the Chinese phone, but the there is no error in the console whatsoever...

Any ideas what I could try?

**Comment by Links2004** [comment]
ok, sounds very strange, did you check via wireshark / tcpdump that the packets are send out on the phone? 
the WebSocket library does not contain any code to filter messages, all valide data is handed over to the callback, and if a invalide WebSocket package the library will disconnect.

So my current best best guess is that you loss a full TCP packet (including WS header + you payload) somewhere between the chrome APP and the ESP.
Most likely in the Chinese phone OS / Kernel drivers.
This can easy be checked by using wireshark when you capture the "Air".

**Comment by ArosPrince** [comment]
Thanks for the tip. I will try that. May take a while though, I have never used Wireshark to capture packets outside of the machine it runs on. Also after trying two few more phones I actually also suspect the Chinese phone is behind that.
