### ISSUE TITLE
LmacRxBlk:1 when receiving messages too fast

### ISSUE THREAD

**Issue by renno-bih** [Links2004/arduinoWebSockets#57]
I'm using this library for exchanging JSON messages between ESP8266 and servers. But it is very frustrating to see my ESP freeze when I try to send messages too fast. 
What I'm trying to do is to send is 73 characters long JSON message every three seconds from server to ESP. ESP also broadcasts JSON message to servers every two seconds.

After some time (few seconds) I get `LmacRxBlk:1` message and my ESP freezes for few seconds and sometimes even resets.

I'm using esp8266 core version: 2.1.0-rc2.
Any idea to prevent ESP crashing if it receives too many messages from server?

**Comment by Links2004** [comment]
with every 3 seconds a message with 73byte payload, you are fare away from the maximum i get in may benchmarks which is around 800-900 messages per second.
how does your code look like,
and which version and mode of the WebSockets you use?
may you call the loop function too less (too many time spend doing other stuff).

**Comment by renno-bih** [comment]
Here is simplified code I'm using:
https://gist.github.com/renno-bih/2f23f2a32df80a150e0b

I can notice that I can transfer more messages if there is less code in loop but still with this simple code I cannot transfer more than 20-30 messages per second.
I tried code from master and async branches. Same problem.
Version is 2.0

**Comment by Links2004** [comment]
you can try to set it to async mode (default is sync in all branches).
the the loop call is not needed my this helps in your case.

https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L57-L58

**Comment by renno-bih** [comment]
Strange thing is that I cannot compile, `ESPAsyncTCP.h` cannot be find. But ESPAsyncTCP library is downloaded.

> /home/xodjel/Documents/arduino-1.6.6/libraries/arduinoWebSockets/src/WebSocketsServer.h:29:0,
                 from nHomeBridge_ESP_0.2.ino:6:
/home/xodjel/Documents/arduino-1.6.6/libraries/arduinoWebSockets/src/WebSockets.h:78:25: fatal error: ESPAsyncTCP.h: No such file or directory
 #include <ESPAsyncTCP.h>
                         ^
compilation terminated.
Error compiling.

If I include `ESPAsyncTCP.h` in main sketch here is what I get:

> /home/xodjel/Documents/arduino-1.6.6/libraries/ESPAsyncTCP/src/SyncClient.cpp: In destructor 'virtual SyncClient::~SyncClient()':
/home/xodjel/Documents/arduino-1.6.6/libraries/ESPAsyncTCP/src/SyncClient.cpp:51:30: error: 'class cbuf' has no member named 'next'
     _rx_buffer = _rx_buffer->next;
                              ^
/home/xodjel/Documents/arduino-1.6.6/libraries/ESPAsyncTCP/src/SyncClient.cpp: In member function 'SyncClient& SyncClient::operator=(const SyncClient&)':
/home/xodjel/Documents/arduino-1.6.6/libraries/ESPAsyncTCP/src/SyncClient.cpp:96:21: error: 'class cbuf' has no member named 'next'
     _rx_buffer = b->next;
                     ^
/home/xodjel/Documents/arduino-1.6.6/libraries/ESPAsyncTCP/src/SyncClient.cpp: In member function 'size_t SyncClient::_sendBuffer()':
/home/xodjel/Documents/arduino-1.6.6/libraries/ESPAsyncTCP/src/SyncClient.cpp:126:34: error: 'class cbuf' has no member named 'available'
   size_t available = _tx_buffer->available();
                                  ^
/home/xodjel/Documents/arduino-1.6.6/libraries/ESPAsyncTCP/src/SyncClient.cpp: In member function 'void SyncClient::_onData(void*, size_t)':
/home/xodjel/Documents/arduino-1.6.6/libraries/ESPAsyncTCP/src/SyncClient.cpp:147:16: error: 'class cbuf' has no member named 'next'
       while(p->next != NULL)
                ^
/home/xodjel/Documents/arduino-1.6.6/libraries/ESPAsyncTCP/src/SyncClient.cpp:148:16: error: 'class cbuf' has no member named 'next'
         p = p->next;
                ^
/home/xodjel/Documents/arduino-1.6.6/libraries/ESPAsyncTCP/src/SyncClient.cpp:149:10: error: 'class cbuf' has no member named 'next'
       p->next = b;
          ^
/home/xodjel/Documents/arduino-1.6.6/libraries/ESPAsyncTCP/src/SyncClient.cpp: In member function 'virtual int SyncClient::available()':
/home/xodjel/Documents/arduino-1.6.6/libraries/ESPAsyncTCP/src/SyncClient.cpp:209:13: error: 'class cbuf' has no member named 'available'
     a += b->available();
             ^
/home/xodjel/Documents/arduino-1.6.6/libraries/ESPAsyncTCP/src/SyncClient.cpp:210:12: error: 'class cbuf' has no member named 'next'
     b = b->next;
            ^
/home/xodjel/Documents/arduino-1.6.6/libraries/ESPAsyncTCP/src/SyncClient.cpp: In member function 'virtual int SyncClient::read(uint8_t*, size_t)':
/home/xodjel/Documents/arduino-1.6.6/libraries/ESPAsyncTCP/src/SyncClient.cpp:224:64: error: 'class cbuf' has no member named 'available'
   while(_rx_buffer != NULL && (len - readSoFar) >= _rx_buffer->available()){
                                                                ^
/home/xodjel/Documents/arduino-1.6.6/libraries/ESPAsyncTCP/src/SyncClient.cpp:226:30: error: 'class cbuf' has no member named 'next'
     _rx_buffer = _rx_buffer->next;
                              ^
/home/xodjel/Documents/arduino-1.6.6/libraries/ESPAsyncTCP/src/SyncClient.cpp:227:24: error: 'class cbuf' has no member named 'available'
     size_t toRead = b->available();
                        ^
/home/xodjel/Documents/arduino-1.6.6/libraries/ESPAsyncTCP/src/SyncClient.cpp: In member function 'virtual void SyncClient::flush()':
/home/xodjel/Documents/arduino-1.6.6/libraries/ESPAsyncTCP/src/SyncClient.cpp:247:21: error: 'class cbuf' has no member named 'available'
   while(_tx_buffer->available() || !_client->canSend()){
                     ^
/home/xodjel/Documents/arduino-1.6.6/libraries/ESPAsyncTCP/src/SyncClient.cpp:248:20: error: 'class cbuf' has no member named 'available'
     if(_tx_buffer->available() && _client->canSend())
                    ^
Error compiling.

On what version of esp8266 core have you tested it?

**Comment by Links2004** [comment]
you ESP core version is too old.
you need 2.1.0 the 2.0.0 dont have the "next" in the cbuf.

**Comment by renno-bih** [comment]
I was using staging version 2.1.0 rc2 and for some reason it was using old version of cbuf library. I tried with stable version 2.1.0 and it works now :)

**I don't get `LmacRxBlk:1` messages anymore and I can transfer more messages than I need..**
Thank you @Links2004
