### ISSUE TITLE
How do i can add extraHeaders on transport

### ISSUE THREAD

**Issue by ilomon10** [Links2004/arduinoWebSockets#570]
I'm working on a project, where this project needs to add an extra header for authentication, maybe you can add options like on socket.io-client [docs](https://socket.io/docs/client-api/#With-extraHeaders).

Thanks

**Comment by Links2004** [comment]
are you looking for `setExtraHeaders`?
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.h#L92

```
webSocket.setExtraHeaders("header1: test\r\nheader2: value2"); 
```

**Comment by ilomon10** [comment]
how i call `setExtraHeaders` on `SocketIOClient`? its protected, can u make some example please.

**Comment by Links2004** [comment]
for `SocketIOClient` you are right there its protected, but you can use something like thiscode here:

```cpp
class mySocketIOclient : public SocketIOclient {
public:
    void setExtraHeaders(const char * extraHeaders = NULL) {
        WebSocketsClient::setExtraHeaders(extraHeaders);
    }
}
```
