### ISSUE TITLE
Failed compile: error: WebSocketsClient

### ISSUE THREAD

**Issue by st599** [Links2004/arduinoWebSockets#571]
Hi
I'm getting an error:

_error: expected class-name before '{' token class SocketIOclient : protected WebSocketsClient {_

Does anyone know how to fix?

**Comment by Links2004** [comment]
feel free to reopen with more Info to your setup, versions and name of IDE in use.
all I can say with this little info is that the Arduino IDE and platformio + vscode is working. 

[![Build Status](https://travis-ci.com/Links2004/arduinoWebSockets.svg?branch=master)](https://travis-ci.com/Links2004/arduinoWebSockets)
