### ISSUE TITLE
Socket.IO 3 Support

### ISSUE THREAD

**Issue by Links2004** [Links2004/arduinoWebSockets#576]
new version on Socket.IO 3 has been released, with changes to the protocol.

Task:
add support with out killing Socket.IO v2 :)

https://socket.io/docs/v3/migrating-from-2-x-to-3-0/index.html

https://github.com/socketio/socket.io-protocol#difference-between-v5-and-v4
https://github.com/socketio/engine.io-protocol#difference-between-v3-and-v4

**Comment by skillgamer** [comment]
how can I use it ?

**Comment by Links2004** [comment]
this is a issue to track that the Socket.IO 3 Support needs to be developed.
can you give a bit more details what you questions is?

**Comment by skillgamer** [comment]
how can I use for example socketio.on("message",msg) I'm not sure how I should use the callback because it's a bit different than in js or swift. (I managed it to connect to my server because of your example huge thanks for that)

**Comment by skillgamer** [comment]
and or socketio.emit()

**Comment by Links2004** [comment]
a full example with `emit`, `on` and `ack` (callback) can be found here:
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketClientSocketIOack/WebSocketClientSocketIOack.ino

every event (`emit` on the server) that comes in ends up here:
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketClientSocketIOack/WebSocketClientSocketIOack.ino#L51
there you can Implement a `if` to manage different `eventName`s.

`socketio.emit()`
comes down to the code path at:
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketClientSocketIOack/WebSocketClientSocketIOack.ino#L140-L157

you need to build the json to send and then send it via `socketIO.sendEVENT`,
most of the code is to build the JSON, since this is not as easy in C++ then in JS ;)

**Comment by skillgamer** [comment]
thank you I'll look into it

**Comment by skillgamer** [comment]
is there a documentation because I couldn't find one ?

**Comment by skillgamer** [comment]
I only need one about the socektio.on(event,callback) that's basically the only thing I need since I don't really wanna get stuff from the arduino

**Comment by skillgamer** [comment]
sorry if I annoy you

**Comment by Links2004** [comment]
there is no full text only Dokumentation, but all functions have doxygen style documentation.

for your use case I highly recommend you start with the code in this example: https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketClientSocketIOack/WebSocketClientSocketIOack.ino

simple put you WIFI and server ip / port in and start from there.

the code will print all Incoming events to Serial, this will help to get a understanding how it works.

for working with the json `doc` you get here:
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketClientSocketIOack/WebSocketClientSocketIOack.ino#L50

look at the `arduinojson` documentation at https://arduinojson.org/ and https://arduinojson.org/v6/api/

**Comment by skillgamer** [comment]
are you sure it print all events because it doesn't show something when i'm sending something to the server in js for example I can get the messages with that socket.on('message' function (msg){})

**Comment by Links2004** [comment]
if you send something from JS client to your server, the ESP will not see it thats normal that is how Socket.IO works.

if you do `socket.emit('test_event', 'test_data');` on the server (on the socket the ESP opened) then you will see Serial messages.

**Comment by skillgamer** [comment]
ah ok

**Comment by skillgamer** [comment]
I use a python server and only use emit on the app I made and not on the website I hope that's the problem

**Comment by Links2004** [comment]
if you want to forward data from socket.io client to a other socket.io client, check the socket.io chat example here:
https://github.com/socketio/chat-example/blob/master/index.js

how this is done in the python socket.io server may is in the documentation of it.

**Comment by skillgamer** [comment]
still nothing and I'm using emit this time

**Comment by skillgamer** [comment]
I'm making a log on the ios app maybe there's something

**Comment by Links2004** [comment]
Support for Socket.IO 3 Implemented

**Comment by Links2004** [comment]
Released with version 2.3.1

**Comment by skillgamer** [comment]
can you already install it ?

**Comment by skillgamer** [comment]
why did you remove the socketio example ?

**Comment by Links2004** [comment]
@skillgamer to which files do you refere?


https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketClientSocketIO/WebSocketClientSocketIO.ino
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketClientSocketIOack/WebSocketClientSocketIOack.ino

**Comment by skillgamer** [comment]
> @skillgamer to which files do you refere?
> 
> https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketClientSocketIO/WebSocketClientSocketIO.ino
> https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketClientSocketIOack/WebSocketClientSocketIOack.ino

nvm I was at the directory for esp32
