### ISSUE TITLE
SinricPro connection issues after 2.3.0 update

### ISSUE THREAD

**Issue by Boomnu** [Links2004/arduinoWebSockets#580]
ESP32 will not connect to SinricPro after an update to Version 2.3.0
Version 2.2.0 does not have the issue

**Comment by Links2004** [comment]
can you please provide the debug log output with v2.3.0 and v2.2.0.
with that we may see what is going wrong.

**Comment by Boomnu** [comment]
> can you please provide the debug log output with v2.3.0 and v2.2.0.
> with that we may see what is going wrong.

Seems I had a DELAY at the end of my code that the Version 2.3.0 did not like. The Awesome guys at SinricPro were able to optimize may code and get it working :)

**Comment by Boomnu** [comment]
Thank You SinricPro, you guys are AWESOME as always
