### ISSUE TITLE
ERRO ESP-01 + MYSQL + ARDUINO + BMP180 + DHT11 = PROBLEMAS!!!!

### ISSUE THREAD

**Issue by lumes001** [Links2004/arduinoWebSockets#584]
Boa tarde, estou com problemas com o ESP-01, eu estava usando esses códigos para enviar o ID do sensor e a temperatura para o MYSQL: https://blog.eletrogate.com/salvando-dados-do-arduino.../...
Até ai tudo bem estava funcionando, mas eu preciso trocar esse ID do sensor por outra variavel, no meu caso seria a pressão atmosférica, fiz todas as alterações no banco de dados e nos códigos mas no monitor serial agora aparece a seguinte mensagem: 

**
Exception (28):
epc1=0x40208836 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000
>>>stack>>>
ctx: cont
sp: 3ffffd20 end: 3fffffc0 offset: 0190
3ffffeb0: 00000000 3fffdad0 3ffee5b4 00000030
3ffffec0: 00000000 3fffdad0 3ffee5b4 00000000
3ffffed0: 00000000 400be933 3ffee44c 3ffee5b4
3ffffee0: 3ffe8304 004f4944 3ffed0f8 40230dc3
3ffffef0: 3ffef24c 40230dec 00000001 00000000
3fffff00: 65736f72 34333231 00000000 40201a54
3fffff10: 000006d8 8c93cc16 00000000 feefeffe
3fffff20: 40204ef2 00000001 3ffef114 3ffee5b4
3fffff30: 00000000 3ffe8304 00000020 40100900
3fffff40: 3fffff94 3fffff90 00000000 3ffee5b4
3fffff50: 3fffff94 3fffff90 3ffe869c 402095b4
3fffff60: 3ffe869c 3fffff90 3ffee53c 4020752c
3fffff70: 3fffff94 3fffff90 3ffe869c 40201074
3fffff80: 3fffdad0 00000000 3ffee574 40201239
3fffff90: 3fffdad0 00000000 3ffee574 40201117
3fffffa0: feefeffe feefeffe feefeffe 40204088
3fffffb0: feefeffe feefeffe 3ffe8570 40100b85
<<<stack<<<
--------------- CUT HERE FOR EXCEPTION DECODER ---------------
**

Esse é o código:
```#include <ESP8266WiFi.h>          
#include <MySQL_Connection.h>
#include <MySQL_Cursor.h>
 
IPAddress server_addr(54, 39, 75, 7); // O IP DO SERVIDOR DA CLEVER CLOUD
char user[] = "ID";              // Usuario MySQL
char password[] = "SENHA";        //   Senha MySQL
 
char ssid[] = "REDE";         //  Nome de rede Wifi
char pass[] = "SENHA";     //            Senha Wi-Fi
 
char INSERT_DATA[] = "INSERT INTO bc0acsacix15fjwisnly.Temperatura (PressaoAT, Temperatura) VALUES (%s,%s)"; 
//   EXEMPLO ACIMA:  "INSERT INTO b3d3z8bggux9ngtdusfw.Temperatura (ID_SENSOR, Temperatura) VALUES (%d,%s)"; 
 
WiFiClient client;             
MySQL_Connection conn(&client);
MySQL_Cursor* cursor;
 
void setup() {
  Serial.begin(9600);
  VerificaWiFi();
}
 
void loop() {
  float PressaoAT;
  float Temperatura;
 
  AguardaDados();
  Leitura(&PressaoAT, &Temperatura);
  delay(100);
  EnviaDados(PressaoAT, Temperatura);
  Serial.println();
}
 
void AguardaDados() {
  while (!(Serial.available() > 0)) {}
}
void Leitura(float *PressaoAT, float *Temperatura) {
  char  mensagem[20];
  byte atual, i = 0;
  atual = 255;
 
  if (Serial.available() > 0) {
    while (atual != 10) {
      if (Serial.available() > 0) {
        atual = Serial.read();
        //     Serial.print((char)leitura);
        mensagem[i] = (char)atual;
        i++;
      }
    }
    i = 0;
    *PressaoAT = atof(strtok(NULL, "|"));
    *Temperatura = atof(strtok(NULL, "|"));
  }
 
}
void EnviaDados(float PressaoAT, float Temperatura) {
 
  char query[128];
  char pressao[10];  
  char temperatura[10];
  
  VerificaWiFi();
  if (conn.connect(server_addr, 3306, user, password)) {
    delay(1000);
    MySQL_Cursor *cur_mem = new MySQL_Cursor(&conn);
    // Save
    
    dtostrf(PressaoAT, 1, 1, pressao); 
    dtostrf(Temperatura, 1, 1, temperatura);  //converte float em array
    
    sprintf(query, INSERT_DATA, pressao, temperatura); //enviar para mysql
    // Execute the query
    cur_mem->execute(query);
    // Note: since there are no results, we do not need to read any data
    // Deleting the cursor also frees up memory used
    delete cur_mem;
    Serial.println(); Serial.println("Data recorded."); //
  }
  else
    Serial.println(); Serial.println("Connection failed."); //
  conn.close();
}
 
void VerificaWiFi() {
  if (WiFi.status() != WL_CONNECTED) {
    //Serial.println("Sem conexão"); //
    WiFi.disconnect();
    delay(1000);
    WiFi.begin(ssid, pass);
    // Serial.println();Serial.println("Conectando ao WiFi."); //
    while (WiFi.status() != WL_CONNECTED) {
      delay(500);
    }
    // Serial.println();Serial.println("Conectado a rede!"); //
  }
}```

**Comment by Links2004** [comment]
Hi, 
I am unable to read your language, so its hard to help.
In you code I don't see any web socket related parts, is this a question related to the arduinoWebSockets lib?
