### ISSUE TITLE
ESP32 using arduinoWebSockets on the same port as AsyncWebServer

### ISSUE THREAD

**Issue by zekageri** [Links2004/arduinoWebSockets#585]
Is there some workaround to this problem?
This library is more stable than the AsyncSocket and i would like to use it but on the same port as my server.
This is required because if i want to port forward my esp to the outter network i would have to forward to ports instead of one.

**Currently i'm trying like this**:

`WebSocketsServer syncSocket = WebSocketsServer(80,"MyESP");`

**And using the AsyncServer like this:**

`AsyncWebServer server(80);`

**Try to connect from JS like this:**

`ws = new RobustWebSocket('ws://' + window.location.hostname + '/MyESP'); `

or

`ws = new RobustWebSocket('ws://' + window.location.hostname + ':80/MyESP'); `

_without success. It is working properly and stable on port 81 for example, so no problem with that._

**Comment by Links2004** [comment]
currently there is no `server.addHook` for the ESP32 like in the ESP8266 that I am aware of.
so this use case not plug and play to get working.

**Comment by zekageri** [comment]
Thank you for the response! I will close this than.
