### ISSUE TITLE
ESP8266 restarting with websocket error if new client wants to connect

### ISSUE THREAD

**Issue by OzRib** [Links2004/arduinoWebSockets#588]
My ESP8266 restart when the client try to create a new connection and a the serial port output sends a message log with a lot of numbers in HEX `value
 
`--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Exception (29):
epc1=0x40211f97 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

>>>stack>>>

ctx: cont
sp: 3ffffb10 end: 3fffffc0 offset: 0190
3ffffca0:  00000001 40103be6 3ffed378 3ffef530  
3ffffcb0:  40104057 00000003 3ffef680 00000001  
3ffffcc0:  3ffe8304 00000001 3ffffda0 40215faa  
3ffffcd0:  40103b1f 3ffe860c 00000002 00040000  
3ffffce0:  00002200 3ffef680 3fff0f0c 3ffe860f  
3ffffcf0:  00000000 3ffe860e 3ffffda0 402163db  
3ffffd00:  00000000 ffffffff 00000000 00000000  
3ffffd10:  3fff11d8 00000001 4030206e 3fffc278  
3ffffd20:  401026d0 3fffc200 00000022 40100c1c  
3ffffd30:  4020f73a 00000030 00000010 ffffffff  
3ffffd40:  00204ae2 3fff06c4 4020ff78 4020f724  
3ffffd50:  00000001 00000001 00000000 0000042c  
3ffffd60:  3ffffe30 3ffffe20 00000010 3ffe8304  
3ffffd70:  3ffeeaa8 00000009 00000001 00000030  
3ffffd80:  00000000 00001a3d 00000000 3ffeeaec  
3ffffd90:  3ffeeaec 3ffe8304 0000003c 402126f5  
3ffffda0:  3ffffe61 00000000 0000003a ffff0208  
3ffffdb0:  3ffffe60 0000003b 000001db 4010095f  
3ffffdc0:  00000860 3fff08e0 3fff0960 3ffffe90  
3ffffdd0:  00000001 00000000 00000020 40100be7  
3ffffde0:  00000000 00000000 4bc6a7f0 00000000  
3ffffdf0:  007a1200 c250bd5d 3fff0600 402164c5  
3ffffe00:  00000000 4bc6a7f0 3ffffe30 3ffffe20  
3ffffe10:  0000000c 00000000 00000000 00000002  
3ffffe20:  3ffeeaec 3ffeeaa8 3ffeead8 00000000  
3ffffe30:  0000000a 00000000 3ffffeb0 40204aec  
3ffffe40:  3ffeead8 3ffeeaa8 00000000 40201137  
3ffffe50:  00000000 0000006b 3ffeeaec 00000000  
3ffffe60:  007a125b c2502525 3fff0600 00000002  
3ffffe70:  3ffeead8 00000000 00000000 40203d82  
3ffffe80:  00000001 00000000 00000000 000000be  
3ffffe90:  00000089 00000000 00000000 00000000  
3ffffea0:  00000000 3fff0bf4 00000020 4020e1a6  
3ffffeb0:  40210098 6b00000a 3ffeeaa8 00000009  
3ffffec0:  3ffeeaec 3ffeeaa8 3ffeead8 4020f608  
3ffffed0:  3ffe8699 3fffff0c 3ffeead8 4020f71d  
3ffffee0:  3fff0bf4 3ffeeaa8 3ffeead8 40205132  
3ffffef0:  00000000 00000000 4bc6a7f0 4021a4be  
3fffff00:  3fff0900 001e001f 80ff068c 3fff0bf4  
3fffff10:  00be00bf 00ff06c4 3fff09c4 001c001f  
3fffff20:  0000000a 3fff06c4 3fff06c4 4020c744  
3fffff30:  3ffeeed4 3fff06c4 3fffff50 000000cc  
3fffff40:  3ffeeed4 3ffeeaa8 3ffeead8 40205223  
3fffff50:  3fff0000 00000000 80000000 4020db58  
3fffff60:  3fffdad0 00000000 00000000 3ffef1f4  
3fffff70:  3fffdad0 00000000 3ffeeaa8 402052b9  
3fffff80:  3fffdad0 00000000 3ffeeaa8 402052e5  
3fffff90:  3fffdad0 00000000 3ffef1b4 40203904  
3fffffa0:  3fffdad0 00000000 3ffef1b4 4020dc70  
3fffffb0:  feefeffe feefeffe 3ffe84e4 40100ea1  
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 3584, room 16 
tail 0
chksum 0xb0
csum 0xb0
v2843a5ac
~ld`
This is the serial output.
What I can do?

Thanks. The API is incredible. But, I can not use. :´(

**Comment by OzRib** [comment]
The code in the sketch is:
`#include <WebSocketsClient.h>
#include <WebSockets.h>
#include <WebSocketsServer.h>

#include <ESP8266WiFi.h>
#include <WiFiClient.h>
#include <ESP8266WebServer.h>
#include <ESP8266mDNS.h>

#define ssid "SSID"
#define psswd "****************"
#define led LED_BUILTIN

ESP8266WebServer server(80);
WebSocketsServer webSocket = WebSocketsServer(81);

void webSocketEvent(uint8_t num, WStype_t type, uint8_t *payload, size_t length){
  switch(type){
    case WStype_DISCONNECTED:
      Serial.print(num);
      Serial.println(F("Desconectado"));
      break;
    case WStype_CONNECTED:
      {
        IPAddress Ip = webSocket.remoteIP(num);
        char notify[60];
        snprintf(notify, 60, "[%n] Conectado a %d.%d.%d.%d URL: %s\n", num, Ip[0], Ip[1], Ip[2], Ip[3], payload);
        Serial.println(notify);
        webSocket.sendTXT(num, "Connected");
      }
      break;
    case WStype_TEXT:
    {
      char message[80];
      snprintf(message, 80, "[%n] get text: %s", num, payload);
      Serial.println(message);
      break;
    }
  }
}

void handleRoot(){
  char root[840];
  snprintf(root, 840, 
  "<!DOCTYPE html>\
  <html>\
  <head>\
  <title>ESP8266</title>\
  <meta charset='UTF-8'>\
  <style type='text/css'>*{font-size:45px;}\
  :root{box-sizing:border-box;height: 100vh;width:100vw;}\
  html, body{background:rgb(80,80,80);display:flex;justify-content:center;}\
  #container{align-self:center;justify-content:center;display:flex;height:80vh;width:70vw;border:solid black 1px;border-radius:40px;background:rgb(110,170,255);}\
  .button{margin-top:1rem;height:5%%;min-width:40%%; border:solid black 1px; border-radius:20px;}\
  #b1{background:rgb(250,250,250);}\
  </style>\
  </head>\
  <body><div id='container'>\
  <input type='button' onClick='req.led()' value='Clique aqui para trocar o led' id='b1' class='button'>\
  </button>\
  </div>\
  </body>\
  </html>\
  <script type='text/javascript'>\
  const req={\
    'led':() =>{\
      fetch('led')\
    }\
  }</script>");
  server.send(200, "text/html", root);
}
void turnLed(){
  digitalWrite(led, !digitalRead(led));
  String message = "led status: ";
  message += !digitalRead(led);
  server.send(200, "text/plain", message);
}

void handleNotFound(){
  String message = "File not found\n\nURL: ";
  message += server.uri();
  message += "\nMethod: ";
  message += (server.method() == HTTP_GET) ? "GET":"POST";
  message += "\nArguments: ";
  message += server.args();
  message += "\n";
  for(uint8_t i=0; i<server.args(); i++){
    message += " "+server.argName(i)+server.arg(i)+"\n";
  }
  server.send(404, "text/plain", message);
}

void setup() {
  pinMode(led, OUTPUT);
  digitalWrite(led, LOW);
  Serial.begin(115200);
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, psswd);
  Serial.println();
  while(WiFi.status() != WL_CONNECTED){
    Serial.print('.');
    delay(400);
  }
  Serial.println();
  Serial.print(F("Conectado a: "));
  Serial.println(ssid);
  server.begin();
  Serial.println(F("Servidor iniciado"));
  Serial.print(F("Endereço IP: "));
  Serial.println(WiFi.localIP());
  webSocket.begin();
  webSocket.onEvent(webSocketEvent);
  if(MDNS.begin("esp8266")){
    Serial.println(F("MDNS responder iniciado"));  
  }
  server.on("/", handleRoot);
  server.on("/led", turnLed);
  server.onNotFound(handleNotFound);
  server.begin();
  MDNS.addService("http", "tcp", 80);
  MDNS.addService("ws", "tcp", 81);
  for(byte i=0;i<4;i++){
    digitalWrite(led, !digitalRead(led));
    delay(100);
  }
}

void loop() {
  webSocket.loop();
  server.handleClient();
  MDNS.update();
}`

**Comment by devyte** [comment]
It says right there:
> `--------------- CUT HERE FOR EXCEPTION DECODER ---------------`

You're supposed to use the exception decoder to see what the hex values mean. 

Off the top of my head, you're likely blowing up the stack. You have a 840 byte buffer, plus other stuff, and the stack is only 4KB total. 
In addition, I'm not sure whether passing in a local buffer is ok. 
In addition, you have a 400ms delay every time the handleRoot function is called.
In addition, your web string is in sram instead of progmem. 

You should look into a static html doc and a dynamic tiny piece of dynamic data, e. g. a json, as a secondary request.

To me, this looks like user error.

**Comment by OzRib** [comment]
Thanks
