### ISSUE TITLE
How to connect websocket with host address?

### ISSUE THREAD

**Issue by ikbalkazanc** [Links2004/arduinoWebSockets#591]
I tried many way for this but i couldn't connect with host. how should I connect?
`websocket.begin("echo.websocket.org", 80, "/");`

**Comment by Links2004** [comment]
please provide code and debug logs.
with this Info in your question I am not really able to understand your question.

may you want to us a IP?
```
websocket.begin("1.2.3.4", 80, "/");
```

**Comment by ikbalkazanc** [comment]
I'm sorry for uncertainty and time waste. I found my mistake. it was reason for a stupid address mistake. Once again sorry.
