### ISSUE TITLE
DDNS WebSocket Unexpected response code: 200 (ESP8266)

### ISSUE THREAD

**Issue by LuckHermsen** [Links2004/arduinoWebSockets#594]
Hi everyone,

I've implemented websockets into my ESP8266 project.
It works fine as long as I access the device via it's local IP. However if I use DDNS, the Websockets don't work. The Chrome console shows:

`WebSocket connection to 'ws://abc.def.ghi.com:81/' failed: Error during WebSocket handshake: Unexpected response code: 200`

The DDNS is handled by a NGINX proxy manager running on my Synology NAS. Websockets are enabled. Disabling/reenabling it doesn't change anything. Also I am confused by the error code. 200 usually means the connection is OK, right?
It's worth mentioning that I earlier used the async websockets integrated in the ESPAsyncWebServer and did not have this issue there. I stopped using the async library as it messed with my Serial commucation.

I haven't been able to find much info regarding this issue. Maybe someone here knows how to tackle the issue.
I'd prefer to be able to access the device by it's DDNS if possible.

Any help appreciated!

**Comment by LuckHermsen** [comment]
Allright so I just realized the issue, the ddns name in my NGINX manager forwards to port 80.
The async socket server which I previously used runs on port 80, but ads a suffix /ws.
This socket server runs on port 81, thus the issue.
Is there any workaround to make the server run on port 80 as well and add a /suffix as well?

**Comment by Links2004** [comment]
you are looking for ```webSocket.hookForWebserver```
example code:

https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketServerHooked/WebSocketServerHooked.ino

and may this comes in handy too:
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/Nginx/esp8266.ssl.reverse.proxy.conf

**Comment by LuckHermsen** [comment]
Thank you Links2004,
Sorry for not looking closer at the source files.

I just tried it with "WebSockets4WebServer" and I'm getting the error: `#error Your current Framework / Arduino core version does not support Webserver Hook Functions`

I have the ESP8266 Community vore version 2.7.4 installed
Do you know if I need another core version, or am I facing another issue?

Appreciate your help!

**Comment by LuckHermsen** [comment]
Okay so I have downloaded the ESP8266WebServer source files and put them in the arduino/libaries folder. Added `#define WEBSERVER_HAS_HOOK 1` but the Arduino IDE keeps using the library in AppData\Local\...
Is the only solution to rename the files?

**Comment by LuckHermsen** [comment]
Allright so I added `#define WEBSERVER_HAS_HOOK 1` to the library in Appdata just to get things going for now, but ran into the next problem. The compiler now throws me an error 
`C:\Users\Luck\Documents\Arduino\libraries\WebSockets\src/WebSockets4WebServer.h: At global scope:
C:\Users\Luck\Documents\Arduino\libraries\WebSockets\src/WebSockets4WebServer.h:40:5: error: 'HookFunction' in 'using ESP8266WebServer = class esp8266webserver::ESP8266WebServerTemplate<WiFiServer> {aka class esp8266webserver::ESP8266WebServerTemplate<WiFiServer>}' does not name a type
     ESP8266WebServer::HookFunction hookForWebserver(const String & wsRootDir, WebSocketServerEvent event) {
     ^
`

I do use a template processor in my own project (by including <ESPTemplateProcessor.h>) but it gives me the same error when I use the code from your first [link](https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketServerHooked/WebSocketServerHooked.ino).

**Comment by Links2004** [comment]
you need to install the latest core version not only the webserver.

this will most likely help you:
https://arduino-esp8266.readthedocs.io/en/latest/installing.html#using-git-version

**Comment by LuckHermsen** [comment]
Thanks!
I had 2.7.4. installed, but to make sure all files were okay I reverted back to 2.7.3 and then installed 2.7.4 again.
When opening the local ESP8266WebServer.h file on my machine (which was in the 2.7.4. folder as excpected), the `#define WEBSERVER_HAS_HOOK 1` was missing (among other things as you pointed out). I just don't understand why that is. 2.7.4 is the latest version?

If I look up the source on Github I can see it's different. [The Webhook definition is in line 53](https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WebServer/src/ESP8266WebServer.h) on the master branch. However on the 2.7.4. branch it's missing as well as in the 2.7.3 branch. 

I installed the 2.7.2 and 2.7.1 core versions in the boards manager, but none of them contain the Webhook definition on line 53.

It feels like I'm missing something obvious...

**Comment by Links2004** [comment]
2.7.4. is the latest release (from 2 aug) but the git master is around 220 commit (changes) newer for the core.
and in this commits the define is include, thats the reason why I linked the git install steps ;)

with that you are able to get the latest version with is currently only 2 days old.
`master` is always the newest you can get and a 
version/release basically is a snapshot of the master branch.

**Comment by LuckHermsen** [comment]
Hi Links2004,

Thanks for your help, I managed to get the code to compile after following the GIT steps.
Unfortunately I'm having different stability issues with te rest of my code now, such as the WiFiManager and http.get to download the .html files I use to SPIFFS. Guess the newest core isn't very stable yet? I think I'll revert to the 'stock' 2.7.4 for now and check back in the future hoping if the webhooks will be supported by then.

I really do like the possibility of using the websockets on the same port as the webserver. Appreciate all the work you put into this!

**Comment by Links2004** [comment]
Hi,

having the newest code can have stability issues, 
in my use cases I have not seen any lately.
But I dont use the the ESP8266 as webserver to provide a GUI (have them all integrate via websocket to my home automation).
That is most likely the reason why there where no release since august.

if you have some info regarding stability and problems or ways to reproduce
may report it in https://github.com/esp8266/Arduino to get them fixed.

**Comment by LuckHermsen** [comment]
Interestingly enough everything seems to work fine when running the ESP in 80mhz mode. I always had it running in 160mhz to speed up the webserver a bit. 
Running it on 160mhz with the core from github/master results in the problems I mentioned. Will create an issue per your suggestion.
At least the websockets are now working properly. Very happy with this feature.
