### ISSUE TITLE
WebSocket Connecting on ESP32 but NodeJS Socket.IO API with JWT

### ISSUE THREAD

**Issue by dipan29** [Links2004/arduinoWebSockets#598]
Hello @Links2004 , I am working on a Socket Based Application, which will capture the data on a ESP32 and perform actions as per required. This is one of my college project and I have to submit this quite soon, and I am hence raising this issue as I think, I am missing out something. 

I have made a Socket API with NodeJS and Socket.IO ver 3+. Here is the code -

```js
// declaration and other routes...

const server = app.listen(port, () => {
    console.log(`Listening to requests on ${port}`);
});

const socketio = require('socket.io');
const io = socketio(server, {
    cors: {
    handlePreflightRequest: function (req, res) {
        var headers = {
            'Access-Control-Allow-Headers': 'Content-Type, Authorization',
            'Access-Control-Allow-Origin': req.headers.origin,
            'Access-Control-Allow-Credentials': true
        };
        res.writeHead(200, headers);
        res.end();
    }
});
io.use(async (socket, next) => {
    try {
        const token = socket.handshake.query.token;
        console.log("New Socket Authenticated");
        const payload = await jwt.verify(token, process.env.SECRET);
        socket.user_id = payload.user_id;
        next();
    } catch (err) {
        // TO DO ERRORS
        console.log(err)
    }
});

// Socket Connection
io.on('connection', socket => {
    console.log("Connected: " + socket.user_id);

    socket.on("disconnect", () => {
        console.log("Disconnected: " + socket.user_id);
    });

    socket.on("subscribe", ({ endpoint }) => {
        socket.join(endpoint);
        console.log("A device subscribed to: " + endpoint);
    });

    socket.on("unsubscribe", ({ endpoint }) => {
        socket.leave(endpoint);
        console.log("A device disconnected from: " + endpoint);
    });

    socket.on("update", async ({ endpoint, value }) => {
        console.log("Transaction:", endpoint, "<-", value);
        // Some actions and an emit function here
    });
});
```
The server is hosted on a ubuntu server with all ports open.

The code that I have used on ESP32 is as follows and all the used libraries are on the latest build only.

```cpp
#include <WiFi.h>
#include <DNSServer.h>
#include <WebServer.h>
#include <WiFiManager.h>
#include <WebSocketsClient.h>

/*====== Defining API Endpoints ====== */
static String HOST = "HOST IP"; // hosted on a linux machine with all ports open.
static int PORT = 3050;
static boolean useSSL = false;
static String socketRoute = "/socket.io/?token=TOKEN_HERE&transport=websocket";
// Transport = Polling made it connect disconnect again and again, but that was working on Unity or Other Angular Applications.

/*====== Defining Variables ====== */
#define LED 2
WebSocketsClient webSocket;
uint32_t chipId = 0;


/*====== Helper Functions ====== */
void APModeCallback(WiFiManager* manager) {
  Serial.println("Entered config mode, Please login with your WiFi/AP Credentials..");
  Serial.println(WiFi.softAPIP());
  Serial.println(manager->getConfigPortalSSID());
}

void hexdump(const void *mem, uint32_t len, uint8_t cols = 16) {
  const uint8_t* src = (const uint8_t*) mem;
  Serial.printf("\n[HEXDUMP] Address: 0x%08X len: 0x%X (%d)", (ptrdiff_t)src, len, len);
  for(uint32_t i = 0; i < len; i++) {
    if(i % cols == 0) {
      Serial.printf("\n[0x%08X] 0x%08X: ", (ptrdiff_t)src, i);
    }
    Serial.printf("%02X ", *src);
    src++;
  }
  Serial.printf("\n");
}

void webSocketEvent(WStype_t type, uint8_t * payload, size_t length) {

  switch (type) {
    case WStype_DISCONNECTED:
      Serial.printf("[WSc] Disconnected!\n");
      break;
    case WStype_CONNECTED:
      Serial.printf("[WSc] Connected to url: %s\n", payload);

      // send message to server when Connected
      // webSocket.sendTXT("Connected");
      break;
    case WStype_TEXT:
      Serial.printf("[WSc] get text: %s\n", payload);

      // send message to server
      // webSocket.sendTXT("message here");
      break;
    case WStype_BIN:
      Serial.printf("[WSc] get binary length: %u\n", length);
       hexdump(payload, length);

      // send data to server
      // webSocket.sendBIN(payload, length);
      break;
    case WStype_ERROR:
    case WStype_FRAGMENT_TEXT_START:
    case WStype_FRAGMENT_BIN_START:
    case WStype_FRAGMENT:
    case WStype_FRAGMENT_FIN:
      break;
  }

}


/*====== Socket Functions ====== */
void socket_Connected(const char * payload, size_t length) {
  Serial.println("Socket.IO Connected!");
}


void socket_event(const char * payload, size_t length) {
  Serial.print("got message: ");
  Serial.println(payload);
}

void setup() {
  // Set pin mode
  pinMode(LED, OUTPUT);
  Serial.begin(115200);
  Serial.setDebugOutput(true);
  /*======= Get ESP Chip ID =======*/
  for (int i = 0; i < 17; i = i + 8) {
    chipId |= ((ESP.getEfuseMac() >> (40 - i)) & 0xff) << i;
  }

  /*======= WiFi Manager Setup =======*/
  WiFiManager wifiManager;
  wifiManager.setAPCallback(APModeCallback);
  // Let it sleep into the eternal world of darkness after 5 minutes
  wifiManager.setTimeout(300);
  //On connection Failure
  if (!wifiManager.autoConnect("MY_AP", "12345678")) {
    Serial.println("Failed Connection to remote Access Point");
    ESP.restart();
    delay(5000);
  }

  /*======= Socket Setup =======*/
  
  webSocket.beginSocketIO(HOST, PORT, socketRoute);
  webSocket.onEvent(webSocketEvent);
  webSocket.setReconnectInterval(3000);
//  webSocket.setExtraHeaders("Authorization: Bearer ");
}

void loop() {
  webSocket.loop();
}
```

I am unable to get this work, but as I saw, the socket is connecting to the endpoint and when the endpoint API is stopped, the socket is instantly disconnecting on ESP32.

*Please help me with a suggested solution to get the same working.*

**Comment by Links2004** [comment]
based on your js code you need to provide some sort of jwt token to the query.
typically its a bad idea to put a auth token in a URL query for security reasons.
I recommend to move it to the HTTP headers.

something like:
```cpp
webSocket.setExtraHeaders("Authorization: Bearer TOKEN_HERE");
```

based on this:
https://www.npmjs.com/package/socketio-jwt
using Bearer HTTP Authorization is possible.


alternative you can try to change:
```cpp
static String socketRoute = "/socket.io/?token=TOKEN_HERE&transport=websocket";
```
to:
```
static String socketRoute = "/socket.io/?EIO=3&token=TOKEN_HERE";
```

the transport is appended automatically based on the phase of the connection establishment. 
see here:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.cpp#L609-L617

**Comment by dipan29** [comment]
Thank you for the reply, I am trying and getting back to you.

**Comment by dipan29** [comment]
I used log on the server, what I realized is, the socket is not even going into the middleware. It keeps connecting and disconnecting after some time. I removed the entire token concept even its the same. I saw in my router, the requests are sent and established but there is no log on the web server. @Links2004 

I will be trying the other method, I mean SOCKETIO-JWT in sometime and revert back.

**Comment by Links2004** [comment]
may enabling debug in the IDE helps you, since then the lib will print the HTTP connection headers and many use full Infos for debugging.

**Comment by dipan29** [comment]
I could only do that in the setup part, is thre anything else to do except ```Serial.setDebugOutput(true);``` ?

**Comment by Links2004** [comment]
in the arduino IDE its a setting in the menu where you configure your board.
for more advanced IDEs you need to set a compile define options.
for example platform IO:

```
build_flags = -D DEBUG_ESP_PORT=Serial
```

**Comment by dipan29** [comment]
![image](https://user-images.githubusercontent.com/38533808/103778576-75e1ab80-5058-11eb-9798-b491daf6177f.png)

I am not sure what to change, sorry I am bothering a bit, as I have to get this socket running soon.

**Comment by Links2004** [comment]
https://arduino-esp8266.readthedocs.io/en/latest/Troubleshooting/debugging.html

**Comment by mijanov** [comment]
I had a similar problem and realize that socket.io from node and websocket from ESP32 are not compatible and can't exchange the messages. On:
https://www.npmjs.com/package/socket.io
you can find this note:
"Note: Socket.IO is not a WebSocket implementation. Although Socket.IO indeed uses WebSocket as a transport when possible, it adds some metadata to each packet: the packet type, the namespace and the ack id when a message acknowledgement is needed. That is why a WebSocket client will not be able to successfully connect to a Socket.IO server, and a Socket.IO client will not be able to connect to a WebSocket server (like ws://echo.websocket.org) either. Please see the protocol specification [here](https://github.com/socketio/socket.io-protocol)."
