### ISSUE TITLE
Can't connect ESP8266 to node socketIo server

### ISSUE THREAD

**Issue by Itox001** [Links2004/arduinoWebSockets#599]
Hi! I have been searching around for quite some time but can't get the esp to connect to the socketIO node server. A react client can connect alright with no problems. I am using the 2.3.1 version of this lib, which should have support for Socket.IO 3 (I'm using 3.0.5) according to [this comment](https://github.com/Links2004/arduinoWebSockets/issues/579#issuecomment-731594049), and the [examples ](https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketClientSocketIO/WebSocketClientSocketIO.ino) should be current according to #576.

The debug output I get when I try to use the example from the above link, just changing the server IP address, port and wifi credentials, is the following:

> [SETUP] WiFi Connected 192.168.1.112
> [WS-Client] connect ws...
> [WS-Client] connected to 192.168.1.126:4001.
> [WS-Client][sendHeader] sending header...
> [WS-Client][sendHeader] handshake GET /socket.io/?EIO=3&transport=polling HTTP/1.1
> Host: 192.168.1.126:4001
> Connection: keep-alive
> Origin: file://
> User-Agent: arduino-WebSocket-Client
> 
> [write] n: 157 t: 15093
> [WS-Client][sendHeader] sending header... Done (1799us).
> [write] n: 6 t: 15094
> [write] n: 2 t: 15095
> [write] n: 28 t: 15095
> ["event_name",{"now":15094}]
> [WS-Client][handleHeader] RX: HTTP/1.1 200 OK
> [WS-Client][handleHeader] RX: Access-Control-Allow-Origin: *
> [WS-Client][handleHeader] RX: Content-Type: text/plain; charset=UTF-8
> [WS-Client][handleHeader] RX: Content-Length: 96
> [WS-Client][handleHeader] RX: Date: Wed, 06 Jan 2021 21:21:53 GMT
> [WS-Client][handleHeader] RX: Connection: keep-alive
> [WS-Client][handleHeader] Header read fin.
> [WS-Client][handleHeader] Client settings:
> [WS-Client][handleHeader]  - cURL: /socket.io/?EIO=3
> [WS-Client][handleHeader]  - cKey: E1ZXrje7Vu/fVLgOax/ByQ==
> [WS-Client][handleHeader] Server header:
> [WS-Client][handleHeader]  - cCode: 200
> [WS-Client][handleHeader]  - cIsUpgrade: 0
> [WS-Client][handleHeader]  - cIsWebsocket: 1
> [WS-Client][handleHeader]  - cAccept:
> [WS-Client][handleHeader]  - cProtocol: arduino
> [WS-Client][handleHeader]  - cExtensions:
> [WS-Client][handleHeader]  - cVersion: 0
> [WS-Client][handleHeader]  - cSessionId:
> [WS-Client][handleHeader] no Websocket connection close.
> [write] n: 27 t: 15121
> [WS-Client] client disconnected.
> [IOc] Disconnected!
> [wsIOc] Disconnected!
> [WS-Client] connect ws...
> [WS-Client] connected to 192.168.1.126:4001.
> [WS-Client][sendHeader] sending header...
> [WS-Client][sendHeader] handshake GET /socket.io/?EIO=3&transport=polling HTTP/1.1
> Host: 192.168.1.126:4001
> Connection: keep-alive
> Origin: file://
> User-Agent: arduino-WebSocket-Client
> 
> [write] n: 157 t: 15625
> [WS-Client][sendHeader] sending header... Done (1629us).
> [WS-Client][handleHeader] RX: HTTP/1.1 200 OK
> [WS-Client][handleHeader] RX: Access-Control-Allow-Origin: *
> [WS-Client][handleHeader] RX: Content-Type: text/plain; charset=UTF-8
> [WS-Client][handleHeader] RX: Content-Length: 96
> [WS-Client][handleHeader] RX: Date: Wed, 06 Jan 2021 21:21:54 GMT
> [WS-Client][handleHeader] RX: Connection: keep-alive
> [WS-Client][handleHeader] Header read fin.
> [WS-Client][handleHeader] Client settings:
> [WS-Client][handleHeader]  - cURL: /socket.io/?EIO=3
> [WS-Client][handleHeader]  - cKey: bydKP/F9m4JHwBGpqFsMIg==
> [WS-Client][handleHeader] Server header:
> [WS-Client][handleHeader]  - cCode: 200
> [WS-Client][handleHeader]  - cIsUpgrade: 0
> [WS-Client][handleHeader]  - cIsWebsocket: 0
> [WS-Client][handleHeader]  - cAccept:
> [WS-Client][handleHeader]  - cProtocol: arduino
> [WS-Client][handleHeader]  - cExtensions:
> [WS-Client][handleHeader]  - cVersion: 0
> [WS-Client][handleHeader]  - cSessionId:
> [WS-Client][handleHeader] no Websocket connection close.
> [write] n: 27 t: 15646
> [WS-Client] client disconnected.
> [IOc] Disconnected!
> [wsIOc] Disconnected!

It seems to me that for some reason the esp client is never sending a connection upgrade header, and only keep-alives so the server never acknowledges that a websocket connection is trying to be opened. This happens on repeat endlessly. Any idea what am I doing wrong or why could this be the case?

Node server is extremely basic, and responds to the react client websocket connections alright:

> const express = require("express");
> const http = require("http");
> const socketIo = require("socket.io");
> 
> const port = process.env.PORT || 4001;
> const app = express();
> const server = http.createServer(app);
> const io = socketIo(server, {
>   cors: {
>     origin: "*"
>   }
> });
> 
> io.on("connection", (socket) => {
>   console.log("New client connected!");
> 
>   socket.on("disconnect", () => {
>     console.log("Client disconnected!");
>   });
> });
> 
> server.listen(port, () => console.log(`Listening on port ${port}`));

Thank you!

**Comment by Links2004** [comment]
Hi,

yes Socket.IO 3 is supported, for some reason the code path for V3 is not triggert in you case.

normally this code here detects socket.IO V3:
https://github.com/Links2004/arduinoWebSockets/blob/074a6748337518e0187eb7cdcba009d06d84ef9a/src/WebSocketsClient.cpp#L763-L769

which than parses the JSON body for the SID here:
https://github.com/Links2004/arduinoWebSockets/blob/074a6748337518e0187eb7cdcba009d06d84ef9a/src/WebSocketsClient.cpp#L684-L696

**Comment by Links2004** [comment]
can you please retest with version `2.3.2`

**Comment by Itox001** [comment]
Hi @Links2004, 2.3.2 addressed the issue. I must have been doing something else wrong when I tested it, since that is what I tried initially before rolling back to 2.3.1, believing it would be "safer" since it was the version mentioned to be working in several different issues. Thank you for the quick response and for your excellent work with this library, closing now.
