### ISSUE TITLE
Websocket client handshake is failed

### ISSUE THREAD

**Issue by janaka120** [Links2004/arduinoWebSockets#602]
Hi all,

I tried to connect with a remote node server which is running in glitch.me.  But I can't succeed with a handshake.  I can connect to that server by using the browser client(This is working fine). I can not figure out why it's failing. The remote host is something like this "example.glitch.me", and the port is 80.

This is the tutorial I followed 
https://esp8266-shop.com/blog/websocket-connection-between-esp8266-and-node-js-server/

**Comment by Links2004** [comment]
please enable debug and post the output here.

**Comment by janaka120** [comment]
Hi @Links2004,

Thanks for yourr reply. Here is my  debug output

![Screenshot from 2021-01-11 22-20-56](https://user-images.githubusercontent.com/10891893/104212887-b6c43080-545b-11eb-9106-320f9af768bf.png)

![Screenshot from 2021-01-11 22-21-23](https://user-images.githubusercontent.com/10891893/104212897-bc217b00-545b-11eb-9970-7705f4306ee3.png)

**Comment by Links2004** [comment]
ok this looks like a error on the SSL level, so may enable the SSL debug output.
the `Handshake failed` is a SSL error.

**Comment by janaka120** [comment]
@Links2004 ,
I enabled debug level ==> SSL+TSL_MEM+HTTP_CLIENT+HTTP_SERVER+CORE+WIFI+HTTP_UPDATE

------------------------------------ OUTPUT------------------------------------

`load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v951aeffa
~ld

SDK:3.0.0-dev(c0f7b44)/Core:2.5.0=20500000/lwIP:STABLE-2_1_2_RELEASE/glue:1.1/BearSSL:6778687
wifi evt: 2


Connecting to janaka-Inspiron-5570
sta config unchangedscandone
.....scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 2
cnt 

connected with janaka-Inspiron-5570, channel 1
dhcp client start...
wifi evt: 0
ip:10.42.0.205,mask:255.255.255.0,gw:10.42.0.1
wifi evt: 3
.
WiFi connected
IP address: 
10.42.0.205
[hostByName] request IP for: mighty-wave-72190.herokuapp.com
[hostByName] Host: mighty-wave-72190.herokuapp.com IP: 54.167.125.52
:ref 1
Connected
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 31 0
:wrc 31 31 0
:wr 2 0
:wrc 2 2 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 24 0
:wrc 24 24 0
:wr 2 0
:wrc 2 2 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 2 0
:wrc 2 2 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 1 0
:wrc 1 1 0
:wr 2 0
:wrc 2 2 0
Waiting...
:ack 1
Waiting...
Waiting...
Waiting...
:ack 195
:rn 536
:rch 536, 179
:rcl
:abort
Waiting...
:c 1, 536, 715
:c0 1, 179
Handshake failed.
`

**Comment by Links2004** [comment]
ok, I had hoped to get more info.
but with that output I only can say the there is a problem at the TLS/SSL level of the connection.
before any data comes to this lib.

the code is at this step here:
https://github.com/Links2004/arduinoWebSockets/blob/410489f7c5234690e5874e6731ed34cfe1305e9d/src/WebSocketsClient.cpp#L263
which points to the `WiFiClientSecure` class

**Comment by janaka120** [comment]
@Links2004 Thank very much for your support. Do you have any clue to slove this problem. If you have any working example, please let me know.

Thank you.

**Comment by Links2004** [comment]
any of the examples in this lib is working ;)
but i have never used herokuapp so most likely it has todo with how they have setup there https servers.
have you tried to run the nodejs code locally?
that may fixes it or helps you to debug the server side.

in my setups I have a nodejs server and a nginx as a reverse ssl proxy and this is working fin.
code can be found in the examples.
