### ISSUE TITLE
Sec-WebSocket-Accept is wrong when connecting

### ISSUE THREAD

**Issue by schlaegerz** [Links2004/arduinoWebSockets#604]
On latest version of the library I consistently get an error:

Sec-WebSocket-Accept is wrong

[WS-Client][sendHeader] sending header...
[WS-Client][sendHeader] handshake GET /websocket HTTP/1.1
Host: toyboxtest.herokuapp.com:80
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: RCYYiihv1c5j+qglR6C5oA==
Sec-WebSocket-Protocol: arduino
Origin: file://
User-Agent: arduino-WebSocket-Client

[write] n: 263 t: 116611
[WS-Client][sendHeader] sending header... Done (337652us).
[WS-Client][handleHeader] RX: HTTP/1.1 101 Switching Protocols
[WS-Client][handleHeader] RX: Connection: Upgrade
[WS-Client][handleHeader] RX: Upgrade: websocket
[WS-Client][handleHeader] RX: Sec-Websocket-Accept: QEFMhxzLTip8aJkbmocIGNEeOB8=
[WS-Client][handleHeader] RX: Via: 1.1 vegur
[WS-Client][handleHeader] Header read fin.
[WS-Client][handleHeader] Client settings:
[WS-Client][handleHeader]  - cURL: /websocket
[WS-Client][handleHeader]  - cKey: RCYYiihv1c5j+qglR6C5oA==
[WS-Client][handleHeader] Server header:
[WS-Client][handleHeader]  - cCode: 101
[WS-Client][handleHeader]  - cIsUpgrade: 1
[WS-Client][handleHeader]  - cIsWebsocket: 1
[WS-Client][handleHeader]  - cAccept: QEFMhxzLTip8aJkbmocIGNEeOB8=
[WS-Client][handleHeader]  - cProtocol: arduino
[WS-Client][handleHeader]  - cExtensions: 
[WS-Client][handleHeader]  - cVersion: 0
[WS-Client][handleHeader]  - cSessionId: 
[WS-Client][handleHeader] Sec-WebSocket-Accept is wrong
[WS-Client][handleHeader] no Websocket connection close.
[WS-Client] connection lost.
[WS-Client] client disconnected.

My exact same code worked in 2.3.0 but no longer works in 2.3.1 or 2.3.2

I have tried to dive into the changes to figure out what may be happening but haven't been able to figure out what it could be.

**Comment by Links2004** [comment]
based on your logs the error is correct,
your server is answering with the wrong value for `Sec-Websocket-Accept`.

```
base64(sha1("RCYYiihv1c5j+qglR6C5oA==" + "258EAFA5-E914-47DA-95CA-C5AB0DC85B11")) === "5WQdLwdYf0ahB70uBxPU8tJ9lxE="
```

but your server is answering with `QEFMhxzLTip8aJkbmocIGNEeOB8=` and the correct value is `5WQdLwdYf0ahB70uBxPU8tJ9lxE=`

**Comment by schlaegerz** [comment]
Ok makes sense, but my server didn't change, only the package version. 

So what could be causing this?

It works fine on 2.3.0 but upgrading to 2.3.1 breaks it.

**Comment by Links2004** [comment]
that is quit strange, I am currently unsure. we need to add more debugging code to get a better look.

please modify:
https://github.com/Links2004/arduinoWebSockets/blob/410489f7c5234690e5874e6731ed34cfe1305e9d/src/WebSocketsClient.cpp#L796-L806
to
```cpp

                String sKey = acceptKey(client->cKey);
                if(sKey != client->cAccept) {
                    DEBUG_WEBSOCKETS("[WS-Client][handleHeader] client->cKey: '%s'\n", client->cKey.c_str());
                    DEBUG_WEBSOCKETS("[WS-Client][handleHeader] expected sKey: '%s'\n", sKey.c_str());
                    DEBUG_WEBSOCKETS("[WS-Client][handleHeader] get cAccept: '%s'\n", client->cAccept.c_str());
                    DEBUG_WEBSOCKETS("[WS-Client][handleHeader] Sec-WebSocket-Accept is wrong\n");
                    ok = false;
                }
```

**Comment by schlaegerz** [comment]
This is what I got:
[WS-Client][sendHeader] sending header... Done (337119us).
WAITING_FOR_CONNECT to WAITING_FOR_HEADER took 575
[WS-Client][handleHeader] RX: HTTP/1.1 101 Switching Protocols
[WS-Client][handleHeader] RX: Connection: Upgrade
[WS-Client][handleHeader] RX: Upgrade: websocket
[WS-Client][handleHeader] RX: Sec-Websocket-Accept: UcqDJHrr41g+yS6K/dBCv6OPU1A=
[WS-Client][handleHeader] RX: Via: 1.1 vegur
[WS-Client][handleHeader] Header read fin.
[WS-Client][handleHeader] Client settings:
[WS-Client][handleHeader]  - cURL: /websocket
[WS-Client][handleHeader]  - cKey: T+sht5xuj3bJfIW7dRJfIg==
[WS-Client][handleHeader] Server header:
[WS-Client][handleHeader]  - cCode: 101
[WS-Client][handleHeader]  - cIsUpgrade: 1
[WS-Client][handleHeader]  - cIsWebsocket: 1
[WS-Client][handleHeader]  - cAccept: UcqDJHrr41g+yS6K/dBCv6OPU1A=
[WS-Client][handleHeader]  - cProtocol: arduino
[WS-Client][handleHeader]  - cExtensions: 
[WS-Client][handleHeader]  - cVersion: 0
[WS-Client][handleHeader]  - cSessionId: 
[WS-Client][handleHeader] client->cKey: 'T+sht5xuj3bJfIW7dRJfIg=='
[WS-Client][handleHeader] expected sKey: 'c3w47IdXEDBuMDPcPMtrG+xFRYQ='
[WS-Client][handleHeader] get cAccept: 'UcqDJHrr41g+yS6K/dBCv6OPU1A='
[WS-Client][handleHeader] Sec-WebSocket-Accept is wrong
[WS-Client][handleHeader] no Websocket connection close.
[WS-Client] connection lost.
[WS-Client] client disconnected.

My best guess is that one of those keys is getting regenerated for some reason, so when we check it again it is already out of date.

**Comment by schlaegerz** [comment]
Do you have an idea of which changes would have affected this? I've tried to go through the commit history, but haven't found anything relevant

**Comment by Links2004** [comment]
I am very confused too, since the code that generate the key is not changes since multiple years :confused: 
https://github.com/Links2004/arduinoWebSockets/blob/410489f7c5234690e5874e6731ed34cfe1305e9d/src/WebSockets.cpp#L541-L560

and when I generate the code manually based on the debug logs the expected code is correct.

can you compare the ```sending header...``` part for the old and new version.
example from your logs:
```
[WS-Client][sendHeader] handshake GET /websocket HTTP/1.1
Host: toyboxtest.herokuapp.com:80
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: RCYYiihv1c5j+qglR6C5oA==
Sec-WebSocket-Protocol: arduino
Origin: file://
User-Agent: arduino-WebSocket-Client

```
may there is a difference in this which the server does not like.

**Comment by schlaegerz** [comment]
Yeah everything is the same.

I am very confused as well. I know my particular implementation is a bit more invasive than normal, so I might just have skipped over some initialization step or something. 

for context my server uses MeteorJs which should just be using standard webocket libraries, 
If no one else is running into this issue then maybe something in my implementation is missing, but I'm still having a hard time figuring out what it could be.

Are there any changes related to regenerating that key or some other reconnecting flow? My implementation is pretty complicated and not something I can boil down to a reproduceable bug.

**Comment by schlaegerz** [comment]
Ok dived more into,

 what appears to be happening is I end up calling connectedCb twice due to my weird implmentation. My guess is either there was some check to make sure it didn't send header twice before or didn't reset the key, or the connected flow of what happens before other things changed. 
 
 This is not an issue with the package it appears it is just my implementation, there just happened to be some non-expected behavior change, probably related to adding in the socketIO code and I was using non-suggested APIs to accomplish what I needed.
