### ISSUE TITLE
How to enable debug output?

### ISSUE THREAD

**Issue by brandonros** [Links2004/arduinoWebSockets#609]
Trying to debug a nasty issue where something I'm doing elsewhere in `loop()` (GPIO RX/TX) is "blocking" so long that the WebSocket client is getting closed.

**Comment by CKRS2** [comment]
If you're working in the Arduino IDE you could place one of the following lines of code in `void setup()`:
    `Serial.setDebugOutput(true);`
or
    `USE_SERIAL.setDebugOutput(true);`

**Comment by Links2004** [comment]
that is not all that is needed.

in the arduino IDE its a setting in the menu where you configure your board.
https://arduino-esp8266.readthedocs.io/en/latest/Troubleshooting/debugging.html

for more advanced IDEs you need to set a compile define options.
for example platform IO:

```
build_flags = -D DEBUG_ESP_PORT=Serial
```
