### ISSUE TITLE
EIO4 support

### ISSUE THREAD

**Issue by potados99** [Links2004/arduinoWebSockets#611]
Hi.
Thank you for this great library :)

I found that engine.io 4 had a [breaking change](https://socket.io/blog/engine-io-4-release/): ` ping packets will now be sent by the server, and the client will respond with a pong packet.`

Currently I found no client side `ping` handling mechanism in `void SocketIOclient::loop(void)` or anywhere.

It would be nice if I can receive `ping` in `SocketIOclientEvent` callback or `loop` handles it automatically.

Thanks.

**Comment by Links2004** [comment]
both the websocket ping and the engine.io ping are implemented with a pong response.
or is there a new ping in the protocol that I missed?

engine.io:
https://github.com/Links2004/arduinoWebSockets/blob/900d81e5345fe2dbe74fd175749c80e2bbda2f00/src/SocketIOclient.cpp#L179-L183

websocket:
https://github.com/Links2004/arduinoWebSockets/blob/900d81e5345fe2dbe74fd175749c80e2bbda2f00/src/WebSockets.cpp#L486-L491

**Comment by potados99** [comment]
Oh it was there... thanks :)

**Comment by potados99** [comment]
I've been suffering on an unstable connection issue, like [this](https://github.com/Links2004/arduinoWebSockets/issues/592) or [that](https://github.com/Links2004/arduinoWebSockets/issues/586), and I found the reason.

https://github.com/Links2004/arduinoWebSockets/blob/900d81e5345fe2dbe74fd175749c80e2bbda2f00/src/SocketIOclient.cpp#L148-L156

The `sendTXT` call in line 154 breaks a socket connection when the socket uses EIO 4(passed `"/socket.io/?EIO=4"` to `url` param).

After commenting out that line it works well.

**Additional info**

Even with `"/socket.io/?EIO=3"` the connection is unstable, but I couldn't find a solution for this case.

Sorry I have no debug output. I couldn't get managed to make the debug output work(replaced `DEBUG_ESP_PORT` with `Serial` and got compile error that `unsigned long` is not expected for `%d` format string).

**Comment by Links2004** [comment]
I think I have a version that will not brake old code and can handle the `EIO=4` can you please test the `eio_4_ping_handling` branch in you use case?
https://github.com/Links2004/arduinoWebSockets/tree/eio_4_ping_handling

**Comment by potados99** [comment]
I've tested it. It works well for me. Thank you!

**Comment by Links2004** [comment]
version 2.3.3 released with fix
