### ISSUE TITLE
Not able to provide relative path of external websocket server inside the websocketclient code

### ISSUE THREAD

**Issue by jatayu86** [Links2004/arduinoWebSockets#62]
If my server host and path is ws://wildfly-xxxx.rhcloud.com:8000/test, I am not able to provide the relative path (test) in websocket.begin("<domain>",<port>) within the websocketclient code. The connection to url works fine with websocket.begin("wildfly-xxxx.rhcloud.com",8000). But i need to provide the path too,ie websocket.begin("wildfly-xxxx.rhcloud.com/test",8000). Is there some configuration i am missing?

**Comment by Links2004** [comment]
the first name is only the host name.
you can give a url on parameter 3.
```cpp
websocket.begin("wildfly-xxxx.rhcloud.com", 8000, "/test");
```

https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.h#L43-L44

**Comment by jatayu86** [comment]
Thanks..works great :)
