### ISSUE TITLE
how I can read received data as string and use it for creating json file?

### ISSUE THREAD

**Issue by mrdsn3** [Links2004/arduinoWebSockets#622]
I use this code but I get error (""call of overloaded 'String(uint8_t*&)' is ambiguous
"")
how I can read received data as string and use it for creating json file?
( esp8266 )

case WStype_TEXT: {
    // create String
    String str = String(payload);

    // split key and value
    String key  = str.substring(0, str.indexOf(':'));
    String value = str.substring(str.indexOf(':') + 1);

    if(key.equalsIgnoreCase("manual")) {
        // convert value to Int
        uint16_t valueInt = value.toInt();
    }
}
break;

**Comment by Links2004** [comment]
looks like something changed for the `String` class, try:
```cpp
String str = String((const char*) payload);
```

for reading a json string check out:
https://arduinojson.org

side node you dont need a `String` for that :)


example:
https://github.com/Links2004/arduinoWebSockets/blob/f55bf8d4ededd2d7acf36788e5cfe6e6393dd235/examples/esp8266/WebSocketClientSocketIOack/WebSocketClientSocketIOack.ino#L45-L54
