### ISSUE TITLE
The library cannot be compiled when `NO_GLOBAL_INSTANCES` is defined

### ISSUE THREAD

**Issue by MohammedNoureldin** [Links2004/arduinoWebSockets#624]
When I am trying to build my project hat uses arduinoWebSocket, I get many errors similar to the following error (I am showing only one to keep the things simple):

```
Compiling .pio\build\esp8266_dev\FrameworkArduino\IPAddress.cpp.o
C:\Users\USER\.platformio\packages\framework-arduinoespressif8266@src-c835c6c49fde81f72fb810b45552d8a2\libraries\Ethernet\src\Ethernet.cpp: In static member function 'static int EthernetClass::begin(uint8_t*, long unsigned int, long unsigned int)':
C:\Users\USER\.platformio\packages\framework-arduinoespressif8266@src-c835c6c49fde81f72fb810b45552d8a2\libraries\Ethernet\src\Ethernet.cpp:36:2: error: 'SPI' was not declared in this scope; did you mean 'GPI'?
   36 |  SPI.beginTransaction(SPI_ETHERNET_SETTINGS);
      |  ^~~
      |  GPI
```

The problem apparently is that the extern SPI is not declared anymore, and thus cannot be used by the library. Is there any suggestion to solve this properly?

I am using ESP8266, so the part of the code that causes the problem seems to not be included in the compilation, but even though I am getting these errors, I am pretty confused. Any suggestions?

P.S. I am using the library as PlatformIO package.

**Comment by Links2004** [comment]
the only time the lib is doing something with the `Ethernet` and `SPI` is when 
`WEBSOCKETS_NETWORK_TYPE == NETWORK_W5100` can you give a example of how you use the lib?

**Comment by MohammedNoureldin** [comment]
I am not able to test it now, I will probably do it next week, but thanks for pointing out to `chain+`, I thought that it will by default evaluate the preprocessors to exclude the unnecessary code.
