### ISSUE TITLE
Connecting to AWS Gataway API websocket

### ISSUE THREAD

**Issue by MohammedNoureldin** [Links2004/arduinoWebSockets#625]
I am trying to connect to the following test AWS endpoint (API Gateway websocket):

wss://iztrssu94e.execute-api.us-east-1.amazonaws.com/dev

I tried to connect to this endpoint using https://www.websocket.org/echo.html and that works fine. However, when I try to connect to the endpoint using my ESP8266, I get errors like following:

```
StackThunk malloc(6200)
StackThunk stack_thunk_ptr: 0x3fff31ac
[hostByName] request IP for: wss://iztrssu94e.execute-api.us-east-1.amazonaws.com
[hostByName] Host: wss://iztrssu94e.execute-api.us-east-1.amazonaws.com lookup error: -5!
[WS-Client] connection to wss://iztrssu94e.execute-api.us-east-1.amazonaws.com:443 Failed
[WS-Client] client disconnected.
[WSc] Disconnected!
```

This is how I am trying to connect:

    webSocket.beginSSL("wss://iztrssu94e.execute-api.us-east-1.amazonaws.com", 443, "/dev");

I also tried with `begin`, `beginSocketIO` (I am not sure how is this different), but that did not work too.

Could you help me please to be able to connect to that endpoint? I am not sure what am I doing wrong here to not be able to connect to that endpoint.

**Comment by Links2004** [comment]
the first parameter is only the host name no protocol in front, try:

```cpp
webSocket.beginSSL("iztrssu94e.execute-api.us-east-1.amazonaws.com", 443, "/dev");
```

**Comment by MohammedNoureldin** [comment]
Thank you Markus, ok that was simpler as I thought. I should have definitely tried that. It is working now, I will give it some more time for further tests.

Best regards and LG
