### ISSUE TITLE
Unable to connect to server when reading analog input

### ISSUE THREAD

**Issue by wrcsubers** [Links2004/arduinoWebSockets#628]
Hello,

Using 2.3.4.  I'm running the following code on my WebSocket Server, trying to get two NodeMCUs to communicate.  Using the following code:

`void loop() {
  pinValue = analogRead(Analog_Pin);
  webSocket.loop();
}`

I am unable to connect to the server from the client and getting a '[WSc] Disconnected!' message on the client. However, when I comment out the `pinValue = analogRead(Analog_Pin);` line, everything works without issue and I'm able to connect and transmit/receive data between server/client.

**Comment by Links2004** [comment]
Hi,
most likely the `analogRead` needs to much time and the ESP has not time to handle WiFi or the websocket code.
this is a common problem with `analogRead` in many projects. 
you can print the `millis`  before and after the `analogRead` to see how much time it is blocking.
but most likely the ESP spends most of the time in the `analogRead`.
do you really need to read the value each loop? may its a option to only read it every 100ms (at less a possible).

**Comment by wrcsubers** [comment]
That's what I was thinking too.  However, I've changed the code to the following:

`void loop() {
  Serial.println("=======");
  Serial.println(millis());
  pinValue = analogRead(Analog_Pin);
  Serial.println(millis());
  webSocket.loop();
}`

And now communication is working fine!  So that's confusing... 

By the way, there is about 9ms of delay between the two millis();

**Comment by Links2004** [comment]
the printing needs time too, may this little timing change is on the edge to working, since the serial code give the ESP a little time for the network stuff.
80Mhz vs 115200 Baud (~21khz on required instructions)

**Comment by wrcsubers** [comment]
Seems this issue is totally related to timing as mentioned above.

Limiting analogRead() to 50ms+ solves the problem with communication.

Thanks for the help =)

**Comment by sostenesapollo** [comment]
how to implement it ?
I can't read the sensor, actually it keeps the same always
```
void loop() {
    unsigned long currentMillis = millis();

    if (currentMillis - previousMillis >= interval) {
        previousMillis = currentMillis;

        // Read sensor value
        int sensorValue = analogRead(2);
        int percentage = map(sensorValue, 352, 637, 100, 0);

        // Create message
        char message[50];
        sprintf(message, "reading,4,%d,%d", sensorValue, percentage);

        // Log message
        USE_SERIAL.printf("[LOOP] Sending sensor reading to server... %s\n", message);

        // Send message
        webSocket.sendTXT(message);
    }

    webSocket.loop();
}

```

**Comment by wrcsubers** [comment]
How long is your 'interval' variable set for?

**Comment by sostenesapollo** [comment]
@wrcsubers 1 second

**Comment by wrcsubers** [comment]
@sostenesapollo I don't remember how I had my code setup when I originally encountered this issue, but you can look at the code for the project I was working on as it is now.  I'm using analog read and websockets, everything works perfectly fine now.

[https://github.com/wrcsubers/Arduino_BabyMonitor](https://github.com/wrcsubers/Arduino_BabyMonitor)
