### ISSUE TITLE
error: 'bind' is not a member of 'std'

### ISSUE THREAD

**Issue by jackthemaker** [Links2004/arduinoWebSockets#63]
/Documents/Arduino/libraries/WebSockets/src/WebSocketsClient.cpp: In member function 'void WebSocketsClient::begin(const char_, uint16_t, const char_)':
/Documents/Arduino/libraries/WebSockets/src/WebSocketsClient.cpp:43:5: error: '_fingerprint' was not declared in this scope
     _fingerprint = "";

using - arduino uno - arduino ide 1.6.7 - atmel version

**Comment by Links2004** [comment]
try to change the lines to:
```cpp
#if (WEBSOCKETS_NETWORK_TYPE == NETWORK_ESP8266)
_fingerprint = "";
#endif
```
if it fix it i will create a new version

**Comment by jackthemaker** [comment]
well it solves the error but now we have this situation

Sketch uses 43,140 bytes (133%) of program storage space. Maximum is 32,256 bytes.
Global variables use 783 bytes (38%) of dynamic memory, leaving 1,265 bytes for local variables. Maximum is 2,048 bytes.
processing.app.debug.RunnerException: Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
	at cc.arduino.Compiler.size(Compiler.java:315)
	at cc.arduino.Compiler.build(Compiler.java:156)
	at processing.app.Sketch.build(Sketch.java:1108)
	at processing.app.Sketch.build(Sketch.java:1083)
	at processing.app.Editor$BuildHandler.run(Editor.java:2011)
	at java.lang.Thread.run(Thread.java:745)
Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.

:/

**Comment by Links2004** [comment]
will take a look later this week, do you run a example or do you have some more code inside?

**Comment by jackthemaker** [comment]
`/*
 * WebSocketClientAVR.ino
 *
 *  Created on: 10.12.2015
 *
 */




#include <WebSocketsClient.h>


WebSocketsClient webSocket;

void webSocketEvent(WStype_t type, uint8_t * payload, size_t length) {


    switch(type) {
        case WStype_DISCONNECTED:
            Serial.println("[WSc] Disconnected!\n");
            break;
        case WStype_CONNECTED:
            {
                Serial.print("[WSc] Connected to url: ");
                Serial.println((char *)payload);
                // send message to server when Connected
                webSocket.sendTXT("Connected");
            }
            break;
        case WStype_TEXT:
            Serial.print("[WSc] get text: ");
            Serial.println((char *)payload);
            // send message to server
            // webSocket.sendTXT("message here");
            break;
        case WStype_BIN:
            Serial.print("[WSc] get binary length: ");
            Serial.println(length);
           // hexdump(payload, length);

            // send data to server
            // webSocket.sendBIN(payload, length);
            break;
    }

}

void setup()
{
    // Open serial communications and wait for port to open:
    Serial.begin(115200);
    while (!Serial) {}

    // start the Ethernet connection:
    if (Ethernet.begin(mac) == 0) {
      Serial.println("Failed to configure Ethernet using DHCP");
      // no point in carrying on, so do nothing forevermore:
      // try to congifure using IP address instead of DHCP:
  
    }

    webSocket.begin("192.168.0.123", 8011);
    webSocket.onEvent(webSocketEvent);

}


void loop()
{
    webSocket.loop();
}`

**Comment by jackthemaker** [comment]
this is it, its one of the demos

**Comment by Links2004** [comment]
https://github.com/Links2004/arduinoWebSockets/issues/115
