### ISSUE TITLE
SSL without CA fails to connect on arduino-esp32 v1.0.5

### ISSUE THREAD

**Issue by sivar2311** [Links2004/arduinoWebSockets#632]
Hi Markus!

Since arduino-esp32 1.0.5 connecting to SSL-Server fails if no CA has been set.
I think `WiFiClientSecure.setInsecure()` must be called somewhere if ESP32 is used without CA.
Please see [me-no-dev's answer in arduino-esp32 repo](https://github.com/espressif/arduino-esp32/issues/4745#issuecomment-790554585)

**Comment by Links2004** [comment]
you can try to change https://github.com/Links2004/arduinoWebSockets/blob/f55bf8d4ededd2d7acf36788e5cfe6e6393dd235/src/WebSocketsClient.cpp#L232-L241
to:

```cpp
#if defined(ESP32)
           } else if(!_fingerprint) {
                _client.ssl->setInsecure();
            }
#elif defined(SSL_BARESSL)
            } else if(_fingerprint) {
                _client.ssl->setFingerprint(_fingerprint);
            } else {
                _client.ssl->setInsecure();
            }
            if(_client_cert && _client_key) {
                _client.ssl->setClientRSACert(_client_cert, _client_key);
                DEBUG_WEBSOCKETS("[WS-Client] setting client certificate and key");
#endif
```

**Comment by sivar2311** [comment]
Hi Markus,

thanks for your help! This "nearly" worked.
There is another main issue with your code:
`if (!_fingerprint)` will always return `false` and never gets executed
The reason for this is because `_fingerprint` is a `String` type.

This is the code which is working for me:
```C++
#if defined(ESP32)
            } else if(!_fingerprint.length()) {
                _client.ssl->setInsecure();
#elif defined(SSL_BARESSL) 
            } else if(_fingerprint.length()) {
                _client.ssl->setFingerprint(_fingerprint);
            } else {
                _client.ssl->setInsecure();
            }
            if(_client_cert && _client_key) {
                _client.ssl->setClientRSACert(_client_cert, _client_key);
                DEBUG_WEBSOCKETS("[WS-Client] setting client certificate and key");
#endif
```

I found 2 other lines which needs to be changed to `.length()` check:
- https://github.com/Links2004/arduinoWebSockets/blob/f55bf8d4ededd2d7acf36788e5cfe6e6393dd235/src/WebSocketsClient.cpp#L233
- https://github.com/Links2004/arduinoWebSockets/blob/f55bf8d4ededd2d7acf36788e5cfe6e6393dd235/src/WebSocketsClient.cpp#L875

**Comment by Links2004** [comment]
please test with:
https://github.com/Links2004/arduinoWebSockets/pull/634

**Comment by sivar2311** [comment]
Works like a charm :)
Thank you very much!

**Comment by Links2004** [comment]
version 2.3.5 with the fix is released
