### ISSUE TITLE
exec: "/bin/xtensa-lx106-elf-g++": file does not exist. Error in Arduino 1.8.13

### ISSUE THREAD

**Issue by Abi-sha** [Links2004/arduinoWebSockets#642]
exec: "/bin/xtensa-lx106-elf-g++": file does not exist
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

how to solve this error?

**Comment by Links2004** [comment]
sounds like the esp8266 core is not installed correct,
try following the steps at:
https://github.com/esp8266/Arduino#installing-with-boards-manager

**Comment by Abi-sha** [comment]
> sounds like the esp8266 core is not installed correct,
> try following the steps at:
> https://github.com/esp8266/Arduino#installing-with-boards-manager

ya got it .....Thankyou!

**Comment by ayazurrehman786** [comment]
Anyone resolved the issue?
