### ISSUE TITLE
compile errors with 2.3.5 but not 2.3.4

### ISSUE THREAD

**Issue by societyofrobots** [Links2004/arduinoWebSockets#648]
Version 2.3.4 works fine with Arduino + ESP32. The latest version gives me this below error message during compile. Downgrading back to 2.3.4 makes it go away.

```
C:\Users\x\Documents\Arduino\libraries\WebSockets\src\WebSocketsClient.cpp: In member function 'void WebSocketsClient::loop()':
C:\Users\x\Documents\Arduino\libraries\WebSockets\src\WebSocketsClient.cpp:234:30: error: 'class WiFiClientSecure' has no member named 'setInsecure'
                 _client.ssl->setInsecure();
```

**Comment by Links2004** [comment]
is your ESP32 core uptodate?
the CI and my local tests show no errors
https://github.com/Links2004/arduinoWebSockets/runs/2144717850?check_suite_focus=true

**Comment by rk9uba** [comment]
esp32 ssl client support?

**Comment by Links2004** [comment]
yes the ESP32 supports SSL.

for updating the ESP32 core / board check the instructions here:
https://github.com/espressif/arduino-esp32#installation-instructions

**Comment by rk9uba** [comment]
ESP32 core  1.05
    webSocket.beginSSL("echo.websocket.org", 443);
    webSocket.onEvent(webSocketEvent);
  
 [WSc] Disconnected!

**Comment by rk9uba** [comment]
I updated the kernel via ARDUINO IDE is it fundamentally? Or is it necessary according to the instructions?

**Comment by rk9uba** [comment]
I updated everything, rebooted the computer. Connected to the test server!

**Comment by Zeron** [comment]
Version 2.3.5 will not compile will not ESP-32 core 1.0.4 or older.

**Comment by societyofrobots** [comment]
> for updating the ESP32 core / board check the instructions here:
> https://github.com/espressif/arduino-esp32#installation-instructions

I had this in my additional boards manage url:
https://dl.espressif.com/dl/package_esp32_index.json

So I changed it to this as you recommend:
https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

2.3.4 compiles great. But, 2.3.5 gives me this error:

```
C:\Users\x\Documents\Arduino\libraries\esp8266-esp32-sdk-master\src\extralib\Crypto\AESLib.cpp: In member function 'String AESLib::encrypt(String, byte*, byte*)':
C:\Users\x\Documents\Arduino\libraries\esp8266-esp32-sdk-master\src\extralib\Crypto\AESLib.cpp:63:32: warning: 'sizeof' on array function parameter 'key' will return size of 'byte* {aka unsigned char*}' [-Wsizeof-array-argument]
   aes.set_key( key , sizeof(key));
                                ^
C:\Users\x\Documents\Arduino\libraries\esp8266-esp32-sdk-master\src\extralib\Crypto\AESLib.cpp:59:45: note: declared here
 String AESLib::encrypt(String msg, byte key[], byte my_iv[]) {
                                             ^
C:\Users\x\Documents\Arduino\libraries\WebSockets\src\WebSocketsClient.cpp: In member function 'void WebSocketsClient::loop()':
C:\Users\x\Documents\Arduino\libraries\WebSockets\src\WebSocketsClient.cpp:234:30: error: 'class WiFiClientSecure' has no member named 'setInsecure'
                 _client.ssl->setInsecure();
                              ^
Multiple libraries were found for "WiFi.h"
 Used: C:\Users\x\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi
 Not used: C:\Program Files (x86)\Arduino\libraries\WiFi
exit status 1
Error compiling for board Adafruit ESP32 Feather.
```

**Comment by Links2004** [comment]
your error shows ESP32 taht your IDE is using 1.0.4 of the ESP32 board but 1.0.5 is the latest that you need.

**Comment by societyofrobots** [comment]
You were right, it was still on 1.0.4. Fixed!

I went to Tools -> Board... -> Boards Manager and updated to 1.0.5.
