### ISSUE TITLE
Returning "(-9984) X509 - Certificate verification failed, e.g. CRL, CA or signature check failed"

### ISSUE THREAD

**Issue by Nasrudin78** [Links2004/arduinoWebSockets#649]
Hi,
I modified your "**Secured Esp32 Client**" to point a local server using self-signed-certificate. I've added a correct CA-key (since I've tested with "ws4py" python module and it works. But when using in Arduino with your library, it yields all time:
**Returning "(-9984) X509 - Certificate verification failed, e.g. CRL, CA or signature check failed"**
I've checked a lot of things without success.

This is my code: (with a fake cert  :)  ):
I've tested both with secure and insecure flag (none of them worked :( )
This is weird, because using your Secured Esp32 .ino file that points to echo server, it works like a charm.

```

#ifdef CORE_DEBUG_LEVEL
#undef CORE_DEBUG_LEVEL
#endif

#define CORE_DEBUG_LEVEL 3
#define LOG_LOCAL_LEVEL ESP_LOG_DEBUG

#include "esp_camera.h"
#include <WiFi.h>
#include <ArduinoWebsockets.h>
#define CAMERA_MODEL_AI_THINKER
#include "camera_pins.h"

const char* ssid = "myssid";
const char* password = "mypass";
const char* websocket_server_host = "wss://192.168.1.79:444/";


#include "esp_log.h"


const char ssl_ca_cert[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDYjCCAkoCCQDlahQZUefJ5zANBgkqhkiG9w0BAQsFADBxMQswCQYDVQQGEwJT
RTEOMAwGA1UECAwFU3BhaW4xETAPBgNVBAcMCFNhYmFkZWxsMRswGQYDVQQKDBJH
YXJkZW5DYXN0ZWxsYXJuYXUxCzAJBgNVBAsMAkNBMRUwEwYDVQQDDAwxOTIuMTY4
LjEuNzkwHhcNMjEwMzI4MDewNzE3WhcNMjIwMzI4MDYwNzE3WjB1MQswCQYDVQQG
EwJTRTEOMAwGA1UECAwFU3BhaW4xETAPBgNVBAcMCFNhYmFkZWxsMRswGQYDVQQK
DBJHYXJkZW5DYXN0ZWxsYXJuYXUxDzANBgNVBAsMBlNlcnZlcjEVMBMGA1UEAwwM
MTkyLjE2OC4xLjc5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsKXw
E6UyQ7jJEcpdc45c9bTTP50MDLDfJt4tCulIIZB0rYlkMihkeXDFDbEwpfPCjdDc
pq6LOZ7vGK2Zf+r7yYx+TPoyjNOFQu6RAe7Mc+c0MiiG95e13O2+fcGk16KaT6E4
8Q4KmScoZDFSBMHi3b94w4tcXBk8/gblydCg6TgwRF63+L7lknv8pliB9LgrJd1c
FygYSeQ6PfzGNkn5kOELTQ1amlwDZU8+V7lEtMVvHrNcPDOY7Z1jhVTx6FSlYMbC
mDbkCBWtTsATKTjbifpYcVqLGH9JfvuY/l3FAnFmNY6yZgGW1F/bZ5+3xo7R1l6s
niJY9Br08pvJBnSARwIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBhP19qDDeDffux
uI/lNaYedJnSjUAlOCx1RqL1BpM4/zGJOXhu0pV4We2wwGXSFDiiyHbzjkXoBhQ8
gHBMzElykvzAxCBwq8de6pYWzQsk6LzeZdo4KrYQ9H/WC2Rx0I7ogun0JakesqPq
96oPcnlbK/MPobvbeQR2d+DSkPN7K4IvRdvLqJMKBdstO2S0NWeLr+qmaUcvsDQQ
UMObEVNWw6pQr66lrYeV/YdVPvRL2ijn3lyCUVEL6YgRfAX4T/BoMgnKQPpNwpRL
AijWHZP3dTvkJuS+CkiuwwxiprpdO0tm1dyz5iJRBwzlmUwWJIaefBqpGj8QUoha
mCHGsN2V
-----END CERTIFICATE-----
)EOF";



using namespace websockets;
WebsocketsClient client;
bool isWebSocketConnected;

void onEventsCallback(WebsocketsEvent event, String data){
  if(event == WebsocketsEvent::ConnectionOpened){
    Serial.println("Connection Opened");
    isWebSocketConnected = true;
  }else if(event == WebsocketsEvent::ConnectionClosed){
    Serial.println("Connection Closed");
    isWebSocketConnected = false;
    webSocketConnect();
  }
}

void setup() {
  
  //esp_log_level_set("*", ESP_LOG_ERROR);        // set all components to ERROR level
  isWebSocketConnected = false;
  Serial.begin(115200);
  Serial.println();

  camera_config_t config;
  config.ledc_channel = LEDC_CHANNEL_0;
  config.ledc_timer = LEDC_TIMER_0;
  config.pin_d0 = Y2_GPIO_NUM;
  config.pin_d1 = Y3_GPIO_NUM;
  config.pin_d2 = Y4_GPIO_NUM;
  config.pin_d3 = Y5_GPIO_NUM;
  config.pin_d4 = Y6_GPIO_NUM;
  config.pin_d5 = Y7_GPIO_NUM;
  config.pin_d6 = Y8_GPIO_NUM;
  config.pin_d7 = Y9_GPIO_NUM;
  config.pin_xclk = XCLK_GPIO_NUM;
  config.pin_pclk = PCLK_GPIO_NUM;
  config.pin_vsync = VSYNC_GPIO_NUM;
  config.pin_href = HREF_GPIO_NUM;
  config.pin_sscb_sda = SIOD_GPIO_NUM;
  config.pin_sscb_scl = SIOC_GPIO_NUM;
  config.pin_pwdn = PWDN_GPIO_NUM;
  config.pin_reset = RESET_GPIO_NUM;
  config.xclk_freq_hz = 10000000;
  config.pixel_format = PIXFORMAT_JPEG;
  config.frame_size = FRAMESIZE_VGA;
  config.jpeg_quality = 40;
  config.fb_count = 2;

  // camera init
  esp_err_t err = esp_camera_init(&config);
  if (err != ESP_OK) {
    Serial.printf("Camera init failed with error 0x%x", err);
    return;
  }


 

  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.println("WiFi connected!");

  client.setInsecure();
  client.setCACert(ssl_ca_cert);

  client.onEvent(onEventsCallback);
  webSocketConnect();
}

void webSocketConnect(){
  
  while(!client.connect(websocket_server_host)){
    delay(500);
    Serial.print(".");
  }
  Serial.println("Websocket Connected!");
}

void loop() {

  if(client.available()){
    client.poll();
  }
  
  if(!isWebSocketConnected) return;
  
  camera_fb_t *fb = esp_camera_fb_get();
  if(!fb){
    Serial.println("Camera capture failed");
    esp_camera_fb_return(fb);
    return;
  }

  if(fb->format != PIXFORMAT_JPEG){
    Serial.println("Non-JPEG data not implemented");
    return;
  }
  


  client.sendBinary((const char*) fb->buf, fb->len);
  esp_camera_fb_return(fb);
}
```

This is the way I'm creating my keys:

 **openssl req -x509 -nodes -sha256 -newkey rsa:2048 -subj "$SUBJECT_CA"  -days 365 -keyout server.key -out server.crt** 

And then I copied-pasted the content of server.crt in the code above...

Any ideas?
Thx in advance

**Comment by Links2004** [comment]
Hi,
I have no idea what code you using I see many calls to the `WebsocketsClient`class with functions that are not implemented in this lib / repo.

SSL example:
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp32/WebSocketClientSSL/WebSocketClientSSL.ino

you simply can set the CA via the function.
https://github.com/Links2004/arduinoWebSockets/blob/a14b6b73b4f05e189ca49d6e84202c2b55db528a/src/WebSocketsClient.h#L55

**Comment by Nasrudin78** [comment]
Sorry , totally agree. I used another library and post in the wrong place. 
I've updated the code in accordance to the links above, but still it doesn't work. Maybe is for using a self-signed-certificate?


`#ifdef CORE_DEBUG_LEVEL
#undef CORE_DEBUG_LEVEL
#endif

#define CORE_DEBUG_LEVEL 3
#define LOG_LOCAL_LEVEL ESP_LOG_DEBUG

#include "esp_camera.h"

#include <Arduino.h>

#include <WiFi.h>
#include <WiFiMulti.h>
#include <WiFiClientSecure.h>
#include <WebSocketsClient.h>


WiFiMulti WiFiMulti;
WebSocketsClient webSocket;
#define CAMERA_MODEL_AI_THINKER
#include "camera_pins.h"

const char* ssid = "myssid";
const char* password = "mypass"
const char* websocket_server_host = "wss://192.168.1.79";


#include "esp_log.h"


const char ssl_ca_cert[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDYjCCAkoCCQDlahQZUefJ5zANBgkqhkiG9w0BAQsFADBxMQswCQYDVQQGEwJT
RTEOMAwGA1UECAwFU3BhaW4xETAPBgNVBAcMCFNhYmFkZWxsMRswGQYDVQQKDBJH
YXJkZW5DYXN0ZWxsYXJuYXUxCzfJBgNVBAsMAkNBMRUwEwYDVQQDDAwxOTIuMTY4
LjEuNzkwHhcNMjEwMzI4MDYwNzf3WhcNMjIwMzI4MDYwNzE3WjB1MQswCQYDVQQG
EwJTRTEOMAwGA1UECAwFU3BhaW4xETAPBgNVBAcMCFNhYmFkZWxsMRswGQYDVQQK
DBJHYXJkZW5DYXN0ZWxsYXJuYXUxDzANBgNVBAsMBlNlcnZlcjEVMBMGA1UEAwwM
MTkyLjE2OC4xLjc5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsKXw
E6UyQ7jJEcpdc45c9bTTP50MDLDCJt4tCulIIZB0rYlkMihkeXDFDbEwpfPCjdDc
pq6LOZ7vGK2Zf+r7yYx+TPoyjNOFQu6RAe7Mc+c0MiiG95e13O2+fcGk16KaT6E4
8Q4KmScoZDFSBMHi3b94w4tcXBk8/gblydCg6TgwRF63+L7lknv8pliB9LgrJd1c
FygYSeQ6PfzGNkn5kOELTQ1amlwDZU8+V7lEtMVvHrNcPDOY7Z1jhVTx6FSlYMbC
mDbkCBWtTsATKTjbifpYcVqLGH9JfvuY/l3FAnFmNY6yZgGW1F/bZ5+3xo7R1l6s
niJY9Br08pvJBnSARwIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBhP19qDDeDffux
uI/lNaYedJnSjUAlOCx1RqL1BpM4/zGJOXhu0pV4We2wwGXSFDiiyHbzjkXoBhQ8
gHBMzElykvzAxCBwq8Mf6pYWzQsk6LzeZdo4KrYQ9H/WC2Rx0I7ogun0JakesqPq
96oPcnlbK/MPobvbeQR2d+DSkPN7K4IvRdvLqJMKBdstO2S0NWeLr+qmaUcvsDQQ
UMObEVNWw6pQr66lrYeV/YdVPvRL2ijn3lyCUVEL6YgRfAX4T/BoMgnKQPpNwpRL
AijWHZP3dTvkJuS+CkiuwwxiprpdO0tm1dyz5iJRBwzlmUwWJIaefBqpGj8QUoha
mCHGsN2V
-----END CERTIFICATE-----
)EOF";




bool isWebSocketConnected = false;

void hexdump(const void *mem, uint32_t len, uint8_t cols = 16) {
  const uint8_t* src = (const uint8_t*) mem;
  Serial.printf("\n[HEXDUMP] Address: 0x%08X len: 0x%X (%d)", (ptrdiff_t)src, len, len);
  for(uint32_t i = 0; i < len; i++) {
    if(i % cols == 0) {
      Serial.printf("\n[0x%08X] 0x%08X: ", (ptrdiff_t)src, i);
    }
    Serial.printf("%02X ", *src);
    src++;
  }
  Serial.printf("\n");
}

void webSocketEvent(WStype_t type, uint8_t * payload, size_t length) {


    switch(type) {
        case WStype_DISCONNECTED:
            Serial.printf("[WSc] Disconnected!\n");
            break;
        case WStype_CONNECTED:
            {
                Serial.printf("[WSc] Connected to url: %s\n",  payload);
                isWebSocketConnected = true;

          // send message to server when Connected
        webSocket.sendTXT("Connected");
            }
            break;
        case WStype_TEXT:
            Serial.printf("[WSc] get text: %s\n", payload);

      // send message to server
      // webSocket.sendTXT("message here");
            break;
        case WStype_BIN:
            Serial.printf("[WSc] get binary length: %u\n", length);
            hexdump(payload, length);

            // send data to server
            // webSocket.sendBIN(payload, length);
            break;
    case WStype_ERROR:      
    case WStype_FRAGMENT_TEXT_START:
    case WStype_FRAGMENT_BIN_START:
    case WStype_FRAGMENT:
    case WStype_FRAGMENT_FIN:
      break;
    }

}
void setup() {
  
  //esp_log_level_set("*", ESP_LOG_ERROR);        // set all components to ERROR level
  isWebSocketConnected = false;
  Serial.begin(115200);
  Serial.setDebugOutput(true);
  Serial.println();

  camera_config_t config;
  config.ledc_channel = LEDC_CHANNEL_0;
  config.ledc_timer = LEDC_TIMER_0;
  config.pin_d0 = Y2_GPIO_NUM;
  config.pin_d1 = Y3_GPIO_NUM;
  config.pin_d2 = Y4_GPIO_NUM;
  config.pin_d3 = Y5_GPIO_NUM;
  config.pin_d4 = Y6_GPIO_NUM;
  config.pin_d5 = Y7_GPIO_NUM;
  config.pin_d6 = Y8_GPIO_NUM;
  config.pin_d7 = Y9_GPIO_NUM;
  config.pin_xclk = XCLK_GPIO_NUM;
  config.pin_pclk = PCLK_GPIO_NUM;
  config.pin_vsync = VSYNC_GPIO_NUM;
  config.pin_href = HREF_GPIO_NUM;
  config.pin_sscb_sda = SIOD_GPIO_NUM;
  config.pin_sscb_scl = SIOC_GPIO_NUM;
  config.pin_pwdn = PWDN_GPIO_NUM;
  config.pin_reset = RESET_GPIO_NUM;
  config.xclk_freq_hz = 10000000;
  config.pixel_format = PIXFORMAT_JPEG;
  config.frame_size = FRAMESIZE_VGA;
  config.jpeg_quality = 40;
  config.fb_count = 2;

  // camera init
  esp_err_t err = esp_camera_init(&config);
  if (err != ESP_OK) {
    Serial.printf("Camera init failed with error 0x%x", err);
    return;
  }

  WiFiMulti.addAP(ssid, password);

  //WiFi.disconnect();
  while(WiFiMulti.run() != WL_CONNECTED) {
      delay(100);
  }
  
  Serial.println("");
  Serial.println("WiFi connected!");
  
  webSocket.beginSSL(websocket_server_host, 444, ssl_ca_cert);
  webSocket.onEvent(webSocketEvent);

}



void loop() {

  webSocket.loop();
  if(!isWebSocketConnected) return;
  
  camera_fb_t *fb = esp_camera_fb_get();
  if(!fb){
    Serial.println("Camera capture failed");
    esp_camera_fb_return(fb);
    return;
  }

  if(fb->format != PIXFORMAT_JPEG){
    Serial.println("Non-JPEG data not implemented");
    return;
  }


  webSocket.sendBIN((uint8_t *) fb->buf,(size_t) fb->len);
  esp_camera_fb_return(fb);
}`

Output is:

[E][WiFiClientSecure.cpp:141] connect(): start_ssl_client: -1
[WSc] Disconnected!


Can help me please? I don't know what to do. Working with python client but not with Arduino ... :(
Thanks in advance

**Comment by Links2004** [comment]
you are using `beginSSL` but `beginSslWithCA` is needed.

```cpp
webSocket.beginSslWithCA(websocket_server_host, 444, "/", ssl_ca_cert);
```

**Comment by Nasrudin78** [comment]
xddd. Ok. 
I've replaced with correct one. Same problem with certificate. 

[WS-Client] connect wss...
[WS-Client] setting CA certificate[E][ssl_client.cpp:45] _handle_error(): [start_ssl_client():225]: (-9984) X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
[E][WiFiClientSecure.cpp:141] connect(): start_ssl_client: -9984
[WS-Client] connection to 192.168.1.79:444 Failed
[WS-Client] client disconnected.
[WSc] Disconnected!

If I launch it in python , it works:


```

from ws4py.client.threadedclient import WebSocketClient
import time, requests
import base64
import ssl

esp8266host = "wss://192.168.1.79:444/"





class DummyClient(WebSocketClient):
    def opened(self):
        print("Websocket open")
    def closed(self, code, reason=None):
        print ("Connexion closed down", code, reason)
    def received_message(self, m):
        print (m)

if __name__ == '__main__':
    try:

        ssl_options = {}
        ssl_options['cert_reqs'] = ssl.CERT_REQUIRED

        # Root Certificate Store
        ssl_options['ca_certs'] = './keys/server.cert'

        ws = DummyClient(esp8266host,ssl_options=ssl_options)
        ws.connect()
        print("Ready !")
        
        i = 0
        while i < 101:
            # opening the image file and encoding in base64
            with open("mediamarkt1.jpg", "rb") as image_file:
                encoded_string = base64.b64encode(image_file.read())

            # printing the size of the encoded image which is sent
            print("Encoded size of the sent image: {0} bytes".format(len(encoded_string)))

            # sending the encoded image
            ws.send(encoded_string)



        ws.close()
        exit()

    except KeyboardInterrupt:
        ws.send("led0:0")
        ws.close()
```

where **"server.cert"** is the content attached to the arduino variable (const char ssl_ca_cert[] PROGMEM)
The server side is the same for both clients (arduino or python) and it's coded in node.js (with express and https modules)
And if it's working for python client, then it's not a server problem, but arduino client.
Do I forget doing something?


Thanks a lot!

**Comment by Links2004** [comment]
the SSL handling comes from the ESP32 core, same goes for the error message.
for some reason the ESP is not able to check the cert against the CA.

you can try to increase the DebugLevel for the ESP core may this gives more details.

one bad workaround is to not check the cert ;)
or you create a issue in the ESP32 core project. https://github.com/espressif/arduino-esp32
from the websocket lib side of thinks there is nothing that can be done.

**Comment by Nasrudin78** [comment]
Fixed!!!! finally!!!!
 
I've regenerated my keys following:[]( https://gist.github.com/suru-dissanaike/4344f572b14c108fc3312fc4fcc3d138)
And copy/paste the ca.crt in my  **const char ssl_ca_cert[] PROGMEM**
Now it works!!!
It seems that it ssl_client.cpp checks the "/OU=" literal to assure that is "CA" and not "Server"
Thank you for point me to the solution.

**Comment by Links2004** [comment]
you are welcome
