### ISSUE TITLE
WebSocketsClient.cpp:234:30: the class WiFiClientSecure has no member named 'setInsecure'

### ISSUE THREAD

**Issue by WernerMauss** [Links2004/arduinoWebSockets#652]
With version 2.3.5, I am getting the above error when trying to compile the example code from this location: https://akuzechie.blogspot.com/2020/12/esp32-websocket-server.html
When I revert back to 2.3.1, the error does not occur. 
I did not try the versions between 2.3.1 and 2.3.5.

**Comment by Links2004** [comment]
that indicates that you ESP32 core is not up to date.

for updating the ESP32 core / board check the instructions here:
https://github.com/espressif/arduino-esp32#installation-instructions

or the infos in here:
https://github.com/Links2004/arduinoWebSockets/issues/648

**Comment by WernerMauss** [comment]
Thank you for your fast response and the helpful feedback! 
I have updated the ESP core from 1.0.4 to 1.0.6. 
Version 2.3.5 does indeed not cause a compile error afterwards.

**Comment by WernerMauss** [comment]
Solved.
