### ISSUE TITLE
How to send continuous data from server to client's text field.

### ISSUE THREAD

**Issue by sumbasu** [Links2004/arduinoWebSockets#66]
Hi,

I am new to Arduino based Websocket library.
My requirement is - in WebSocket Server, a random number will be generated with an interval of say 2 ms. 
In Client html page , I will have a text field (place holder). The generated random number should be displayed to browser html page in real time. As per the sample code, Server can only send text message to client's console, only when some event is initiated by client. webSocket.onEvent(webSocketEvent);
My question is, when connection is established, can I continuously send value to client, as mentioned above. If yes, please let me know, how to achieve this.

Regards
Sumanta

**Comment by Links2004** [comment]
the function you search is:
```cpp
 webSocket.broadcastTXT
````
you can call it from every code part you like until its no interrupt.

**Comment by sumbasu** [comment]
Hi,
Thanks for your comment. I have used it, and what I observe, it is sending the value into browser console. How should I display it on the browser itself ?

Regards
Sumanta

**Comment by Links2004** [comment]
at the browser you need to use javascript to add it to a input box or a div.
simple example function:
```html
<div id="data"></div >
<script>
function addDataToDiv(data){
    document.getElementById("data").innerHTML += data";
}
</script>
```

**Comment by sumbasu** [comment]
Many thanks, it did work. I was missing basics !! :)

Regards
Sumanta
