### ISSUE TITLE
What version of EngineIO is being used by this library?

### ISSUE THREAD

**Issue by ujjwalbe** [Links2004/arduinoWebSockets#663]
I would like to know the version of EngineIO that is being used by this library is it compatible with EngineIO 4.x

**Comment by Links2004** [comment]
it is compatible with V4 and V3.
the switch is done based on the URL / path provided.

https://github.com/Links2004/arduinoWebSockets/blob/a14b6b73b4f05e189ca49d6e84202c2b55db528a/src/WebSocketsClient.h#L58-L59

EIO=3 = V3
EIO=4 = V4

**Comment by ujjwalbe** [comment]
Thanks for the answer and a big Thank your for this awesome library,
