### ISSUE TITLE
[Question]: use JSON format for incomming Websocket meassages

### ISSUE THREAD

**Issue by hasenradball** [Links2004/arduinoWebSockets#666]
Hi,

having on question.
I am using actual a ESP8266Webserver and I want to use a websocket protocol.
is it also possible to receive a json format for the meassage, or does the js websocket part the data transfer to the payload txt format?

**Comment by Links2004** [comment]
Hi, 

yes you can unse JSON in the payload, since JSON == text == String == bytes (on TCP layer).
this library will not encode or decode you data but you can easy use the `ArduinoJson` lib for that.

examples:

```cpp
DynamicJsonDocument doc(1024);
DeserializationError error = deserializeJson(doc, payload, length);
// work with JSON
```

```cpp
DynamicJsonDocument docOut(1024);

// work with JSON

// JSON to String (serializion)
String output;
serializeJson(docOut, output);

// Send JSON        
webSocket.sendTXT(output);
```

**Comment by hasenradball** [comment]
Hi I tried the example WebsocketServer_LEDcontrol...
having some Questions:
1.) Do I need WiFiMulti when accepting only 1 client?
2.) For what  doe I need MDNS?

**Comment by Links2004** [comment]
WiFiMulti to allow to connect detect and use to different WiFi APs, if you only use und AP you dont need it.
MDNS is a way to have auto discovery of devices in the network, not needed for the web socket. 
its only there to easy find the ESP IP.

**Comment by hasenradball** [comment]
I used the example on LED with json 
great!

**Comment by hasenradball** [comment]
Is the esp8266 only a one direction example?
Or can I use this example also for send Infos to the client?

**Comment by Links2004** [comment]
a web socket is bidirectional.
you are free to send any data you like in any direction.

**Comment by hasenradball** [comment]
Hi Markus, 

can i make another question?
in the ESP LED control example there is a num value existing.
I interprete it as a number of clients.
How does this play a role when sending meassages to clients?

Does the websocket Object know which numer does have which ip?
Or do I have to handle it by myself?

Best regards
Frank

**Comment by Links2004** [comment]
yes the `num` is a reference to the connected client its like a ID of the connection.
the server keep track of where to send the data for you, you only need to know the `num` of the client.

if you want to send data to one client you need to provide the `num`
https://github.com/Links2004/arduinoWebSockets/blob/a14b6b73b4f05e189ca49d6e84202c2b55db528a/src/WebSocketsServer.h#L56-L60

for simply sending to any connected client you can use the `broadcast` function.
https://github.com/Links2004/arduinoWebSockets/blob/a14b6b73b4f05e189ca49d6e84202c2b55db528a/src/WebSocketsServer.h#L62-L66

**Comment by hasenradball** [comment]
Hi Markus thanks a lot!
Great stuff :-)
Is it necessary to use the `lenght` Parameter when sending jsons?

**Comment by Links2004** [comment]
if you have a 0x00 terminated string / char * then the code will auto detect the length via `strlen`.
for most of the use cases its fine to not provide it.

some examples when you use length is:
 - no termination
 - for speed optimization
 - sending binary data  
 - sending only a part of the data
