### ISSUE TITLE
Retern masage to server

### ISSUE THREAD

**Issue by harymk** [Links2004/arduinoWebSockets#668]
From servere "is that light on?", I want to sent retern with response code 200. How can i do that

**Comment by harymk** [comment]
Is there any option please tell me

**Comment by Links2004** [comment]
the web socket does not not have the concept of response codes,
response code exists only at the HTTP level.

with the little information you provided its unclear what trying to achieve.

a websocket connection is bidirektional so the server or client can send a message any time.

**Comment by harymk** [comment]
OK i understand
