### ISSUE TITLE
Issue with ESP8266 V3.0.0

### ISSUE THREAD

**Issue by J-Arnold** [Links2004/arduinoWebSockets#669]
Hi,

I tryed to update in Arduino IDE to the ESP8266 to V3.0.0 but when I Use the Web Sockets Server example I get the folowing Error:
C:\Users\xxx\Documents\Arduino\libraries\arduinoWebSockets\src\WebSocketsClient.cpp: In member function 'void WebSocketsClient::connectedCb()':
C:\Users\xxx\Documents\Arduino\libraries\arduinoWebSockets\src\WebSocketsClient.cpp:704:26: error: 'class BearSSL::WiFiClientSecure' has no member named 'verify'
  704 |         if(!_client.ssl->verify(_fingerprint.c_str(), _host.c_str())) {
      |                          ^~~~~~

**Comment by Links2004** [comment]
which IDE are you using for the build?
my test with platformio / vscode are working fine,
same goes for the CI pipeline
https://github.com/Links2004/arduinoWebSockets/actions/runs/899172612
which is running on ESP8266 master (https://github.com/esp8266/Arduino)

```
PLATFORM: Espressif 8266 (3.0.0) > Espressif ESP8266 ESP-12E
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 3.30000.210519 (3.0.0) 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.30000.201119 (3.0.0) 
 - toolchain-xtensa 2.100200.0 (10.2.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain+, Compatibility ~ soft
Found 60 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ESP8266WiFi> 1.0
|-- <WebSockets> 2.3.6
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <Hash> 1.0
```

**Comment by consolacion** [comment]
I have a similar problem using 'verify'.  Happened directly after going from 2.7.4 to 3.0. Problem disappears when i revert back to 2.7.4
Using IDE 1.8.13

**Comment by Links2004** [comment]
I retested with the Arduino IDE but it builds fine for me.
tested with clean install of IDE and esp8266 core.

![image](https://user-images.githubusercontent.com/974709/121564785-1f6c0500-ca1c-11eb-9fc1-70c397590a02.png)

can you check what happens when clean up the the Arduino dirs.
currently I have the feeling that the IDE update process has problems with the core update.
but I am not able to reproduce them on any of my Linux machines.

https://support.arduino.cc/hc/en-us/articles/360012076960-Where-are-the-installed-cores-located-
https://support.arduino.cc/hc/en-us/articles/360018448279-Where-can-I-find-the-Arduino15-folder-

**Comment by consolacion** [comment]
It's a pretty fresh install, with just a few project files and minimal libraries so there really isn't that much to clean up.
i am using Linux.
i guess i will just stay with 2.7.4 for the time being. Thank you for your help

**Comment by rikki78** [comment]
I have the same problem, I'm using platform IO:

```
PACKAGES:
 - framework-arduinoespressif8266 3.30000.210519 (3.0.0)       
 - tool-esptool 1.413.0 (4.13)
 - tool-esptoolpy 1.30000.201119 (3.0.0)
 - toolchain-xtensa 2.100200.0 (10.2.0)
``` 
Let me know what other information I should provide in order to help

**Comment by Links2004** [comment]
can you give more details?
my test with the same versions is working fine.

```
$ platformio --version
PlatformIO Core, version 5.1.1
```

```
PLATFORM: Espressif 8266 (3.0.0) > Espressif ESP8266 ESP-12E
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 3.30000.210519 (3.0.0) 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.30000.201119 (3.0.0) 
 - toolchain-xtensa 2.100200.0 (10.2.0)
```

**Comment by rikki78** [comment]
I think I found the issue already. I'm using RemoteDebug which has an older version of this library included in its package.

**Comment by Links2004** [comment]
@consolacion and @J-Arnold are you using RemoteDebug too?

feel free to reopen if you have any details or new infos on how to reproduce this.
currently I am unable to reproduce the issue.

**Comment by abdullahmahboob** [comment]
@Links2004 I'm having the same issue after updating ESP8266 to version 3.0.0 & 3.0.1.

I'm using arduinoWebsockets version 2.3.5 and Arduino IDE 1.8.15.

**Comment by abdullahmahboob** [comment]
Also I can't find 2.3.6 version of the websockets library you used here:

> which IDE are you using for the build?
> my test with platformio / vscode are working fine,
> same goes for the CI pipeline
> https://github.com/Links2004/arduinoWebSockets/actions/runs/899172612
> which is running on ESP8266 master (https://github.com/esp8266/Arduino)
> and is tested with Arduino IDE 1.6.13 and 1.8.13
> 
> ```
> PLATFORM: Espressif 8266 (3.0.0) > Espressif ESP8266 ESP-12E
> HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
> PACKAGES: 
>  - framework-arduinoespressif8266 3.30000.210519 (3.0.0) 
>  - tool-esptool 1.413.0 (4.13) 
>  - tool-esptoolpy 1.30000.201119 (3.0.0) 
>  - toolchain-xtensa 2.100200.0 (10.2.0)
> LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
> LDF Modes: Finder ~ chain+, Compatibility ~ soft
> Found 60 compatible libraries
> Scanning dependencies...
> Dependency Graph
> |-- <ESP8266WiFi> 1.0
> |-- <WebSockets> 2.3.6
> |   |-- <Hash> 1.0
> |   |-- <ESP8266WiFi> 1.0
> |-- <Hash> 1.0
> ```

**Comment by Links2004** [comment]
2.3.6 is the master branch (not released yet), but with no related changes.
https://github.com/Links2004/arduinoWebSockets/compare/2.3.5...master

can you check with a clean install of the IDE (remove any dirs and files in the Home dir).
the most likely problem I see are that the IDE did not clean up some files during the update of the ESP8266 core, resulting in the existing of old files that then get included in to the build.
