### ISSUE TITLE
slowness with iPhone client

### ISSUE THREAD

**Issue by tal118** [Links2004/arduinoWebSockets#67]
Discovered arduinoWebSockets and it seems to be exactly what I've been looking for.

The WebSocketsServer appears to be working great, allowing me to send messages from ESP8266 to multiple connected web browser clients.

However, when I add a web browser client coming from an iPhone (iOS 9.2.1), everything slows down. It's as if the iPhone is perhaps slow to respond to the messages sent by the server (I'm not doing any WebSocket.sends from the browser clients -- just receiving from the server).

WebSocketServer doing a broadcastTXT(about 300 bytes) runs speedy with these connected clients:

Chrome browser (on OS X mac #1)
Firefox browser (on OS X mac #1)
Safari browser (on OS X mac #1)
Safari browser (on OS X mac #2)
Safari browser (on iPad, iOS 9.2.1)

But if I substitute an iPhone (iOS 9.2.1) for any of the above clients, responsiveness goes out the window (messages from the WebSocketServer can sometimes take multiple seconds to appears at some or all of the clients).

Same sluggish behavior from the iPhone when it's the only connected client.

Roughly same behavior, whether running Safari on iPhone or Google Chrome browser on iPhone.

No other apps running on iPhone. Cellular turned off (Airplane mode). Background App refresh turned off. Fresh reboot of phone. No difference.

Any ideas on how to address this?

Is the issue that WebSockets are reliable, so the server is waiting for an ack from the client, and for some reason the iPhone is slow to provide one?

FWIW, I don't need reliability, just looking for way to broadcast from ESP8266 to multiple connected browser clients. Data loss would be OK, but quick delivery is needed....

**Comment by Links2004** [comment]
the sync mode will wait for each client to ack.
the async mode will not wait.

i not own any apple device so its hard to test on may side, but try the async mode.
it sends the data in parallel
https://github.com/Links2004/arduinoWebSockets#esp-async-tcp

**Comment by tal118** [comment]
Thanks very much for the quick response and tip about async, Markus.

Based on some preliminary testing, it looks like that has solved the problem with the _other_ clients (i.e., they no longer appear to be blocked by the sluggish iPhone, which makes sense).

However, the iPhone appears to run into different problems now -- initially it's still sluggish in its reception & processing of messages, but then it appears to either slow way down or perhaps just give up & break entirely. Perhaps a backlog of incoming messages that it hasn't had a chance to ack is causing it troubles. 

Will try to do some more testing and further simplification of what it's doing in JS with the received messages to see if I can get any more insight (it's already pretty trivial, but will try to make it even more so).
