### ISSUE TITLE
Socket.io - Send message and response

### ISSUE THREAD

**Issue by Josua2012** [Links2004/arduinoWebSockets#672]
A question.
From the client side, arduino, can you send a message that returns a response?
I have not seen this functionality in your library.
Socket.io v3 and higher supports the following:

```
// on one side
socket.emit("updateitem", "1", { name: "updated" }, (response) => {
  console.log(response.status); // ok
});
// on the other
socket.on("updateitem", (arg1, arg2, callback) => {
  console.log(arg1); // 1
  console.log(arg2); // { name: "updated" }
  callback({
    status: "ok"
  });
});
```

From your library I have not found a way to send a message with the possibility of obtaining a response.

From the server's point of view if I send a message in this way, the client (arduino) receives it, but the client does not return a response to the server, this code is not executed:
`console.log(response.status); // ok`

In our test server code it would look something like this:

```
const app = require('express');
const http = require('http').createServer(app);
const io = require('socket.io')(http);

io.on('connection', (socket) => {

  console.log('Connected');
  console.log(socket.id);
  console.log("JWT token test: ",socket.handshake.headers)

  socket.on('event_name', (data, res) => {

    console.log(`Message from Client (${socket.id}): `, data);

    io.emit("Send Message io.emit Broadcasted : ", data);
    socket.emit('enviar-mensaje', data);

    socket.emit("updateitem", "1", { name: "updated" }, (response) => {
      console.log(response.status); // ok
    });
  
  })
  
  socket.on('disconnect', () => {

    console.log('Disconnected');

  })

  socket.on('error', () => {
    console.log('error desconocido');
  })

})

http.listen(8080, () => {

  console.log("Server launched on port 8080");
})
```

This could be implemented in your library?

Thanks.

**Comment by Links2004** [comment]
Hi,

looks like you referieren to the ACK feature of socket.IO

a example to how to send the ACK is here:
https://github.com/Links2004/arduinoWebSockets/blob/a14b6b73b4f05e189ca49d6e84202c2b55db528a/examples/esp8266/WebSocketClientSocketIOack/WebSocketClientSocketIOack.ino#L56-L73

to send a message that the other side can to ACK on you need to, add a ID to your message.
the ID is the first in the payload.
https://github.com/Links2004/arduinoWebSockets/blob/a14b6b73b4f05e189ca49d6e84202c2b55db528a/examples/esp8266/WebSocketClientSocketIOack/WebSocketClientSocketIOack.ino#L39-L44

the full format can be found here:
https://github.com/socketio/socket.io-protocol#encoding-format

so you need to add the ID to the output, something like this: (not tested code)
```cpp
                // JSON to String (serializion)
                String output;
                output += id; //< your msg ID here
                serializeJson(docOut, output);

                // Send event        
                socketIO.send(sIOtype_EVENT, output);
```

the ACK from the other side will end up in the `socketIOEvent` callback in the `sIOtype_ACK` case.
you can decode it the same way you decode the `sIOtype_EVENT`

**Comment by Josua2012** [comment]
Hi,

I think that what you tell me is not what I want.
What I would need is something like this:

void loop()
        {
                String response;
        	response = webSocket.send("get-time");  // It would have to return a json with the server time 
        	delay(500);
        	webSocket.loop();
        }

I need that sending a message can simultaneously return a response.
I do not know if I have explained myself clearly. 

Thank you very much for your help.

**Comment by Links2004** [comment]
looks like what you want is a equivalent to a `async` function in JS?
the ESP has no concept like this, directly.
best you can do is to something like this which will be blocking any other task on the CPU until you get the response.

```cpp
uint32_t id = 0;
bool get_answer = false;
String answer = "";

void socketIOEvent(socketIOmessageType_t type, uint8_t * payload, size_t length) {   
  switch(type) {
   ....
   case sIOtype_ACK:
   ...
    if (id == payload_id) {
        get_answer = true;
        answer = payload_data;
        ...
    }
    ....
    break;
    ....
  }


String get_time() {
  id++;
  answer = "";
  get_answer = false;
  socketIO.send(....); // send msg with ID
  while(!get_answer) {
       webSocket.loop();
  }
  return answer;
}
```

side node delaying the `webSocket.loop` for longer times will get you in to problems since the connection needs to be answer to keep alive or the other side will close the connection. 
using `delay(500)` in you main loop is a bad idea :)

**Comment by Josua2012** [comment]
I will try your solution, although it is not the most elegant, it is a pity that this functionality does not exist in your library, as it exists in socket.io, since it would be very interesting and very useful.
Thank you very much for all your help. 💯

**Comment by Links2004** [comment]
yes it is a nice functionality,
but its more a limitation of the, Architektur of the ESP and language.
the ESP is running in cooperative multitasking with IRQs for the Hardware part.
and all Arduino code runs in one thread.

**Comment by Josua2012** [comment]
Again, thank you very much for all your help. 🥇
