### ISSUE TITLE
Websocket connection not work with esp8266-arduino 3.0

### ISSUE THREAD

**Issue by Ciapas-Linux** [Links2004/arduinoWebSockets#674]
Hello!
Im using yours library for make realtime connection between web browser or apk android  and my application running on esp8266 . With older versions up to 2.7.4 everythink work ok, but after upgrade to 3.0 no connection. I check from android smartphone apk also no connection. Maybe somebody now somthink about this behaviour. Maybe is something wrong with my application on esp ? who nows, for now.

Best regards.

**Comment by Links2004** [comment]
with out any debug logs its hard to help you :)

**Comment by Links2004** [comment]
feel free to reopen with more info
