### ISSUE TITLE
Arduino with ethernet

### ISSUE THREAD

**Issue by Josua2012** [Links2004/arduinoWebSockets#676]
Hi Markus,

Could you recommend a cheap model of arduino with ethernet or combination of arduino with pluggable ethernet shield that supports socket.io with your library? 

Thank you very much for your advice. 

Regards,
Jose

**Comment by Links2004** [comment]
Hi,

last I used Ethernet it where a enc28j60 module manually wired to a esp8266.
and that only for testing, all my current setups are a ESP via WiFi :)

and adding ethernet to the esp8266 costs most of the PINs.
with a ESP32 there will be more PINs free but I never tested this.

**Comment by Josua2012** [comment]
Ok. Thanks Markus.
