### ISSUE TITLE
Can i use socket.io with esp32 not esp8266

### ISSUE THREAD

**Issue by MYB-Dev** [Links2004/arduinoWebSockets#677]
I want to use socket.io as communication between esp32 "client" node js server but the only think that i found is for esp8266 not esp32

**Comment by Links2004** [comment]
is possible to use the ESP32 there code for the socket.io is the same.
you only need to replace the WiFi and Hardware code in the esp8266 example with code for the ESP32.

basicly mix the WiFi and HW init from here (ESP32)
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp32/WebSocketClient/WebSocketClient.ino
and the socketio example for the esp8266
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketClientSocketIOack/WebSocketClientSocketIOack.ino

**Comment by MYB-Dev** [comment]
Tanks
