### ISSUE TITLE
platformio Espressif 32 - v3.2.1 (arduino-esp32) ssl fails

### ISSUE THREAD

**Issue by dpasirst** [Links2004/arduinoWebSockets#678]
Using the websockets library, older versions of the arudino-esp32 worked fine; however, recent versions fail to establish a connection when not using a ca cert, fingerprint, etc...

The resulting **error** when the websocket _loop()_ is called is:
`[E][WiFiClientSecure.cpp:133] connect(): start_ssl_client: -1`

Essentially, upon looking at the code, it seems that newer versions of the WiFFiClientSecure.cpp need _setInsecure()_ to be explicitly set when not using the ca cert, cert, private key, etc...

A simple patch seems to do the trick although I'm not sure if this is the best way to handle it:
arduinoWebSockets/src/**WebSocketsClient.cpp**

Around line 238 - adding the following seems to fix it:

            if(_client_cert && _client_key) {
                _client.ssl->setClientRSACert(_client_cert, _client_key);
                DEBUG_WEBSOCKETS("[WS-Client] setting client certificate and key");
            }
    #else
            } else {
                DEBUG_WEBSOCKETS("[WS-Client] setting insecure");
                _client.ssl->setInsecure();
            }
    #endif
        } else {
            DEBUG_WEBSOCKETS("[WS-Client] connect ws...\n");
            if(_client.tcp) {
                delete _client.tcp;

I only have an esp32, so I'm not sure if this is applicable or would cause problems for others.

**Comment by Links2004** [comment]
which version of the websocket lib are you running?
setInsecure is used for the ESP32 here:

https://github.com/Links2004/arduinoWebSockets/blob/a14b6b73b4f05e189ca49d6e84202c2b55db528a/src/WebSocketsClient.cpp#L232-L235

**Comment by dpasirst** [comment]
I'm using 2.3.4.  Guessing that change is in 2.3.5?  I'll take it for a spin...

**Comment by Links2004** [comment]
correct its a 2.3.5 change.
https://github.com/Links2004/arduinoWebSockets/compare/2.3.4...2.3.5

**Comment by dpasirst** [comment]
Just tested and confirmed.   Thank You!
