### ISSUE TITLE
socket.IO client for esp32 keep disconnecting 

### ISSUE THREAD

**Issue by MYB-Dev** [Links2004/arduinoWebSockets#679]
I've tried many times but socket.io client with esp32 didn't connect to my node.JS server 
my code for ESP32
```
#include <Arduino.h>
#include <WiFi.h>
#include <WebSocketsClient.h>
#include <SocketIOclient.h>

SocketIOclient socketIO;

void hexdump(const void *mem, uint32_t len, uint8_t cols = 16)
{
  const uint8_t *src = (const uint8_t *)mem;
  Serial.printf("\n[HEXDUMP] Address: 0x%08X len: 0x%X (%d)", (ptrdiff_t)src, len, len);
  for (uint32_t i = 0; i < len; i++)
  {
    if (i % cols == 0)
    {
      Serial.printf("\n[0x%08X] 0x%08X: ", (ptrdiff_t)src, i);
    }
    Serial.printf("%02X ", *src);
    src++;
  }
  Serial.printf("\n");
}

void socketIOEvent(socketIOmessageType_t type, uint8_t *payload, size_t length)
{
  switch (type)
  {
  case sIOtype_DISCONNECT:
    Serial.printf("[IOc] Disconnected!\n");
    break;
  case sIOtype_CONNECT:
    Serial.printf("[IOc] Connected to url: %s\n", payload);

    // join default namespace (no auto join in Socket.IO V3)
    socketIO.send(sIOtype_CONNECT, "/");
    break;
  case sIOtype_EVENT:
    Serial.printf("[IOc] get event: %s\n", payload);
    break;
  case sIOtype_ACK:
    Serial.printf("[IOc] get ack: %u\n", length);
    hexdump(payload, length);
    break;
  case sIOtype_ERROR:
    Serial.printf("[IOc] get error: %u\n", length);
    hexdump(payload, length);
    break;
  case sIOtype_BINARY_EVENT:
    Serial.printf("[IOc] get binary: %u\n", length);
    hexdump(payload, length);
    break;
  case sIOtype_BINARY_ACK:
    Serial.printf("[IOc] get binary ack: %u\n", length);
    hexdump(payload, length);
    break;
  }
}

void setup()
{
  // put your setup code here, to run once:
  Serial.begin(115200);
  Serial.setDebugOutput(true);

  // Connect to wifi
  WiFi.begin("TP-LINK_75FF7C", "y123b123");

  // Wait some time to connect to wifi
  for (int i = 0; i < 10 && WiFi.status() != WL_CONNECTED; i++)
  {
    Serial.print(".");
    delay(1000);
  }

  // Check if connected to wifi
  if (WiFi.status() != WL_CONNECTED)
  {
    Serial.println("No Wifi!");
    return;
  }
  Serial.println("");
  Serial.printf("[ESP32] Connected to TP-LInk, Connecting to server.\n");

  // server address, port and URL
  socketIO.begin("192.168.1.105", 5000);

  // event handler
  socketIO.onEvent(socketIOEvent);
}

void loop()
{
  // put your main code here, to run repeatedly:
  socketIO.loop();
}
```
And my monitor shows:
[D][esp32-hal-psram.c:47] psramInit(): PSRAM enabled
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 0 - WIFI_READY
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 2 - STA_START
...[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 4 - STA_CONNECTED
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 7 - STA_GOT_IP
[D][WiFiGeneric.cpp:419] _eventCallback(): STA IP: 192.168.1.103, MASK: 255.255.255.0, GW: 192.168.1.1

[ESP32] Connected to TP-LInk, Connecting to server.
[IOc] Disconnected!
[IOc] Disconnected!
[IOc] Disconnected!
[IOc] Disconnected!
[IOc] Disconnected!
[IOc] Disconnected!
[IOc] Disconnected!
[IOc] Disconnected!
[IOc] Disconnected!
[IOc] Disconnected!
[IOc] Disconnected!
[IOc] Disconnected!
[IOc] Disconnected!
[IOc] Disconnected!
[IOc] Disconnected!
[IOc] Disconnected!

As for nodejs server code it is simple hello world one

**Comment by MigotMateusz** [comment]
I faced similar issue today.
Try changing socketIO.begin to something like this:
`socketIO.begin("192.168.1.105", 5000, "/socket.io/?EIO=4");`

**Comment by MYB-Dev** [comment]
Tanks

**Comment by MYB-Dev** [comment]
Tanks

**Comment by Links2004** [comment]
examples have been updated via 72aae526552bc05646892676b9e398a49db3a3ab

**Comment by victorsdd01** [comment]
> I faced similar issue today.
> Try changing socketIO.begin to something like this:
> `socketIO.begin("192.168.1.105", 5000, "/socket.io/?EIO=4");`

Hi, I'm new in this IOT world, I have a question about where I can find the library "WebSocketsClient.h" I need to download the repo code and rename it or what? I'll appreciate it if anybody can help me
