### ISSUE TITLE
broadcasting data as JSON messes up the string

### ISSUE THREAD

**Issue by KurdishSage-1** [Links2004/arduinoWebSockets#681]
Hey there peeps, so basically,

i have an HTML websocket client, i send the data to my esp8266 which is running a websocket server on port 81, this is the code i use inside my HTML file
`webSocket.send('{"command":"togglePins","pin":4,"state":1,"secret":547456}');`

then, i print the received text inside my esp8266, i get the string as intended
`[0] received text {"command":"togglePins","pin":4,"state":1,"secret":547456}`

now, i resend the received text to all my connected clients with this code
`webSocketSERVER.broadcastTXT(payload,length,false);`

but inside my HTML websocket client, when i receive the text back, i get it back like this
`commandtogglePinspin4state1secret547456et":547456}`
as you can see, it's totally messed up,

i tried to use this code instead
`webSocketSERVER.sendTXT(num, payload,length,false);`
but i'm still getting the same problem

i also tried to use this code
`webSocketSERVER.broadcastTXT(payload);`
but inside my html websocket i only receive 'command' instead of '{"command":"togglePins","pin":4,"state":1,"secret":547456}'

what is causing this problem?

**Comment by KurdishSage-1** [comment]
update: when i dont include double quotes inside the string, the text does not get messed up.

so my last resort will be using a different separator letter than double quotes, then replace them by double quotes when i need to change the string into json

**Comment by Links2004** [comment]
the problem comes from the fact that 
```''``` = char (once Character) which is the wrong type.
```"""```= char * (array of Character / string) which is correct.
to place a `"` inside a char * you need to write it like this:

```cpp
webSocket.send("{\"command\":\"togglePins\",\"pin\":4,\"state\":1,\"secret\":547456}");
```

but to make your live easier take a look at https://arduinojson.org/
building json by hand ist not the most convenient way to handle JSON :)

not tested but something like this:
```cpp
DynamicJsonDocument doc(1024);
doc["command"] = "togglePins";
doc["pin"] = 4;
.....

// JSON to String (serializion)      
String output;
serializeJson(doc, output);
// Send event                
webSocket.send(output);
```
