### ISSUE TITLE
Current Framework / Arduino core version does not support Webserver Hook Functions

### ISSUE THREAD

**Issue by GustafDelport** [Links2004/arduinoWebSockets#683]
getting a error when I try to connect to my local host saying that "#error Your current Framework / Arduino core version does not support Webserver Hook Functions"

**Comment by d-a-v** [comment]
You can either use another example not using webserver hook functions, 
or use the latest esp8266 arduino core (v3.0.0) which has the extension.

**Comment by Links2004** [comment]
the error you show looks like a compile error. 
not sure how to interpret "connect to my local host" in this context.

if we talking about compile errors here then your ESP8266 arduino core is a old version and needs to be updated.

https://github.com/Links2004/arduinoWebSockets/blob/a14b6b73b4f05e189ca49d6e84202c2b55db528a/src/WebSockets4WebServer.h#L72-L76
https://github.com/esp8266/Arduino/blob/f4178e58dcfe32ec1f4b7d9cfb31e3ad5559327a/libraries/ESP8266WebServer/src/ESP8266WebServer.h#L53

**Comment by GustafDelport** [comment]
Sorry I am really new to this I figured it out thank you !
