### ISSUE TITLE
Unable to build when using Arduino Core as an esp-idf component: Undefined reference to 'vtable for WiFiServer'

### ISSUE THREAD

**Issue by SelaliAdobor** [Links2004/arduinoWebSockets#688]
I'm using the latest ESP-IDF master (1d7068e4b) and latest Arduino ESP32 core (21947ebe) with the head of this repo

I'm able to build my project and reference Arduino library functions without issue, but when I include arduinoWebSockets, the linker fails out with the following error

     ld: esp-idf/external-libraries/libexternal-libraries.a(WebSocketsServer.cpp.obj):  
     (.literal._ZN16WebSocketsServerC2EtRK6StringS2_+0x4): undefined reference to `vtable for WiFiServer'/`

Manually reviewing the usages of `WiFiServer` I don't see any calls that might have been changed/removed in Arduino-core, so I'm not really sure what could be happening here

Full error with paths: 
      
       /Users/oak/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/external-libraries/libexternal-libraries.a(WebSocketsServer.cpp.obj):(.literal._ZN16WebSocketsServerC2EtRK6StringS2_+0x4): undefined reference to `vtable for WiFiServer'
     
      collect2: error: ld returned 1 exit status.

**Comment by SelaliAdobor** [comment]
This was tracked down to a circular dependency issue issue with a fix:

https://github.com/espressif/esp-idf/issues/6968
https://github.com/espressif/esp-idf/issues/6968#issuecomment-836087981

**Comment by Links2004** [comment]
Interesting,
not sure what you mean be Private library, the libb64 code is build like any other file in the arduino esp32 core.
which makes any libb64 accessible form any code.
https://github.com/espressif/arduino-esp32/blob/46d888eb68ae895aaeef41edd77362186680e512/CMakeLists.txt#L27-L28
the arduinoWebSockets uses it too :) and only falls back to its build in one for none ESP architectures (which dont have it onboard)
https://github.com/Links2004/arduinoWebSockets/blob/a14b6b73b4f05e189ca49d6e84202c2b55db528a/src/WebSockets.cpp#L31-L37

but yes linking order can be a problem, and needs to be sorted by the core devs.

**Comment by SelaliAdobor** [comment]
My understanding was that the header being under `INCLUDE_DIR` vs `PRIV...` was supposed to be a hint for ESP-IDF but maybe not?

**Comment by Links2004** [comment]
since  `cores/esp32/` is in the normal includes accessing `libb64/cencode.h` will work fine for any code.
https://github.com/espressif/arduino-esp32/blob/46d888eb68ae895aaeef41edd77362186680e512/CMakeLists.txt#L130

since the libb64 files are located under `cores/esp32/libb64/`
https://github.com/espressif/arduino-esp32/tree/46d888eb68ae895aaeef41edd77362186680e512/cores/esp32/libb64

**Comment by SelaliAdobor** [comment]
Huge thanks for the breakdown, this short comment is clearer than the ESP-IDF docs on the subject 😄 Those gave me the impression priv and include were mutually exclusive
