### ISSUE TITLE
Make local Server for WebSocketCliet

### ISSUE THREAD

**Issue by Jahongir-28** [Links2004/arduinoWebSockets#69]
Sorry for my English and I have one question. How to configure Server for WebSocketClient. The Web Socket server is works fine and I can work with NeoPixels. And Now I want to make Local server for WebSocketClient. How Client actually works?

**Comment by Links2004** [comment]
the client connects to a Websocket server for example from nodejs.
the Server is to connects with a client to it for example your web browser.

you can use any WebSocket Server you like as long its implements RFC6455.
a nodejs example can be found here:
https://github.com/Links2004/arduinoWebSockets/tree/master/tests/webSocketServer

**Comment by mkeyno** [comment]
hi dear @Links2004  , can we use the websocket server to stream the video frame in size of (60x60x3=10.6KB) in each 40ms (25fps) and then make UDP packet and push it to Ethernet connected to? (from browser to ESP and from ESP to Ethernet LAN) do we have enough timing for such task? do you any link or person use the websocket for video streaming 
tnx
