### ISSUE TITLE
Cannot set extra headers

### ISSUE THREAD

**Issue by KrzysztofMoskalik** [Links2004/arduinoWebSockets#690]
Hi, 

I cannot set extra headers using socketIO client.
Code:

```socketIO.setExtraHeaders("");```

Gives me error:

```
void WebSocketsClient::setExtraHeaders(const char*)' is inaccessible within this context
```

**Comment by Links2004** [comment]
latest master allows access to `setExtraHeaders` and as bonus `setReconnectInterval`
