### ISSUE TITLE
Can anyone pls guide me on how to send events from esp8266 client to nodejs server ?

### ISSUE THREAD

**Issue by Tusharkumar0012** [Links2004/arduinoWebSockets#694]
I am getting err of invalid payload on node js socketio server side

**Comment by Links2004** [comment]
client:
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketClient/WebSocketClient.ino

server:
https://github.com/Links2004/arduinoWebSockets/blob/master/tests/webSocketServer/index.js

**Comment by Tusharkumar0012** [comment]
sorry sir , but i am talking about socketio library . i am not able to recieve messages from esp8266 to my socketio node js server .
--------------------------------------------------esp8266 code -------------------------------------------------------------------------
#include <Arduino.h>

#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>

#include <ArduinoJson.h>

#include <WebSocketsClient.h>
#include <SocketIOclient.h>

#include <Hash.h>

ESP8266WiFiMulti WiFiMulti;
SocketIOclient socketIO;

#define USE_SERIAL Serial

void socketIOEvent(socketIOmessageType_t type, uint8_t * payload, size_t length) {
    switch(type) {
        case sIOtype_DISCONNECT:
            USE_SERIAL.printf("[IOc] Disconnected!\n");
            break;
        case sIOtype_CONNECT:
            USE_SERIAL.printf("[IOc] Connected to url: %s\n", payload);

            // join default namespace (no auto join in Socket.IO V3)
            socketIO.send(sIOtype_CONNECT, "/");
            break;
        case sIOtype_EVENT:
            USE_SERIAL.printf("[IOc] get event: %s\n", payload);
            break;
        case sIOtype_ACK:
            USE_SERIAL.printf("[IOc] get ack: %u\n", length);
            hexdump(payload, length);
            break;
        case sIOtype_ERROR:
            USE_SERIAL.printf("[IOc] get error: %u\n", length);
            hexdump(payload, length);
            break;
        case sIOtype_BINARY_EVENT:
            USE_SERIAL.printf("[IOc] get binary: %u\n", length);
            hexdump(payload, length);
            break;
        case sIOtype_BINARY_ACK:
            USE_SERIAL.printf("[IOc] get binary ack: %u\n", length);
            hexdump(payload, length);
            break;
    }
}

void setup() {
    // USE_SERIAL.begin(921600);
    USE_SERIAL.begin(115200);

    //Serial.setDebugOutput(true);
    USE_SERIAL.setDebugOutput(true);

    USE_SERIAL.println();
    USE_SERIAL.println();
    USE_SERIAL.println();

      for(uint8_t t = 4; t > 0; t--) {
          USE_SERIAL.printf("[SETUP] BOOT WAIT %d...\n", t);
          USE_SERIAL.flush();
          delay(1000);
      }

    // disable AP
    if(WiFi.getMode() & WIFI_AP) {
        WiFi.softAPdisconnect(true);
    }

    WiFiMulti.addAP("unKNOWN", "KHEMchandra2.4");

    //WiFi.disconnect();
    while(WiFiMulti.run() != WL_CONNECTED) {
        delay(100);
    }

    String ip = WiFi.localIP().toString();
    USE_SERIAL.printf("[SETUP] WiFi Connected %s\n", ip.c_str());

    // server address, port and URL
    //socketIO.begin("10.11.100.100", 8880);
    socketIO.beginSSL("192.168.29.175", 443 , "/socket.io/?EIO=4" , "818bc7329e5e336d420f441e592d527d1265bc08");
    // event handler
    socketIO.onEvent(socketIOEvent);
}

unsigned long messageTimestamp = 0;
void loop() {
    socketIO.loop();

    uint64_t now = millis();

    if(now - messageTimestamp > 2000) {
        messageTimestamp = now;

        // creat JSON message for Socket.IO (event)
        DynamicJsonDocument doc(1024);
        JsonArray array = doc.to<JsonArray>();
        
        // add evnet name
        // Hint: socket.on('event_name', ....
        array.add("toEsp");

        // add payload (parameters) for the event
        JsonObject param1 = array.createNestedObject();
        param1["now"] = "esp is ready" ; //(uint32_t) now;

        // JSON to String (serializion)
        String output;
        serializeJson(doc, output);

        // Send event        
        socketIO.sendEVENT(output);

        // Print JSON for debugging
        USE_SERIAL.println(output);
    }
}
-------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------serial monitor--------------------------------------------------------------------------
connected with unKNOWN, channel 11
02:44:08.590 -> dhcp client start...
02:44:08.637 -> ip:192.168.29.195,mask:255.255.255.0,gw:192.168.29.1
02:44:08.637 -> [SETUP] WiFi Connected 192.168.29.195
02:44:10.264 -> ["toEsp",{"now":"esp is ready"}]
02:44:10.358 -> [IOc] Connected to url: /socket.io/?EIO=4
02:44:10.442 -> [IOc] get event: ["this is node server"]
02:44:12.434 -> ["toEsp",{"now":"esp is ready"}]
02:44:14.406 -> ["toEsp",{"now":"esp is ready"}]
02:44:16.422 -> ["toEsp",{"now":"esp is ready"}]
02:44:18.430 -> ["toEsp",{"now":"esp is ready"}]
02:44:18.559 -> pm open,type:2 0
02:44:20.406 -> ["toEsp",{"now":"esp is ready"}]
02:44:22.414 -> ["toEsp",{"now":"esp is ready"}]
02:44:24.409 -> ["toEsp",{"now":"esp is ready"}]
02:44:26.411 -> ["toEsp",{"now":"esp is ready"}]
02:44:28.442 -> ["toEsp",{"now":"esp is ready"}]
02:44:30.425 -> ["toEsp",{"now":"esp is ready"}]
02:44:32.431 -> ["toEsp",{"now":"esp is ready"}]
02:44:34.409 -> ["toEsp",{"now":"esp is ready"}]
02:44:36.434 -> ["toEsp",{"now":"esp is ready"}]
02:44:46.820 -> [IOc] get event: ["this is node server"]
02:44:48.802 -> ["toEsp",{"now":"esp is ready"}]
02:44:50.793 -> ["toEsp",{"now":"esp is ready"}]
02:44:52.785 -> ["toEsp",{"now":"esp is ready"}]
02:44:54.808 -> ["toEsp",{"now":"esp is ready"}]
02:44:56.798 -> ["toEsp",{"now":"esp is ready"}]
02:44:58.774 -> ["toEsp",{"now":"esp is ready"}]
02:45:00.813 -> ["toEsp",{"now":"esp is ready"}]
02:45:02.805 -> ["toEsp",{"now":"esp is ready"}]
02:45:04.793 -> ["toEsp",{"now":"esp is ready"}]
02:45:06.788 -> ["toEsp",{"now":"esp is ready"}]
02:45:08.811 -> ["toEsp",{"now":"esp is ready"}]
02:45:10.806 -> ["toEsp",{"now":"esp is ready"}]
02:45:12.814 -> ["toEsp",{"now":"esp is ready"}]
02:45:14.815 -> ["toEsp",{"now":"esp is ready"}]
02:45:16.777 -> ["toEsp",{"now":"esp is ready"}]
02:45:18.784 -> ["toEsp",{"now":"esp is ready"}]
02:45:20.799 -> ["toEsp",{"now":"esp is ready"}]
02:45:22.819 -> ["toEsp",{"now":"esp is ready"}]
02:45:23.535 -> [IOc] get event: ["toEsp",{"D1":"3"}]                  //
02:45:23.535 -> [IOc] get event: ["toEsp",{"D1":"9"}]                   i  
02:45:23.535 -> [IOc] get event: ["toEsp",{"D1":"27"}]                 am 
02:45:23.535 -> [IOc] get event: ["toEsp",{"D1":"33"}]                 able 
02:45:23.535 -> [IOc] get event: ["toEsp",{"D1":"63"}]                 to       
02:45:23.535 -> [IOc] get event: ["toEsp",{"D1":"75"}]                 recieve
02:45:23.850 -> [IOc] get event: ["toEsp",{"D1":"81"}]                 "toEsp"
02:45:23.850 -> [IOc] get event: ["toEsp",{"D1":"100"}]                event
02:45:23.850 -> [IOc] get event: ["toEsp",{"D1":"124"}]                though 
02:45:23.893 -> [IOc] get event: ["toEsp",{"D1":"160"}]                //
02:45:23.893 -> [IOc] get event: ["toEsp",{"D1":"178"}]
02:45:23.893 -> [IOc] get event: ["toEsp",{"D1":"208"}]
02:45:23.893 -> [IOc] get event: ["toEsp",{"D1":"245"}]
02:45:23.893 -> [IOc] get event: ["toEsp",{"D1":"269"}]
02:45:23.893 -> [IOc] get event: ["toEsp",{"D1":"293"}]
02:45:23.893 -> [IOc] get event: ["toEsp",{"D1":"299"}]
02:45:23.893 -> [IOc] get event: ["toEsp",{"D1":"311"}]
02:45:23.893 -> [IOc] get event: ["toEsp",{"D1":"323"}]
02:45:24.811 -> ["toEsp",{"now":"esp is ready"}]
02:45:25.870 -> [IOc] get event: ["toEsp",{"D1":"0"}]
02:45:26.806 -> ["toEsp",{"now":"esp is ready"}]
02:45:28.823 -> ["toEsp",{"now":"esp is ready"}]
02:45:30.829 -> ["toEsp",{"now":"esp is ready"}]
02:45:32.823 -> ["toEsp",{"now":"esp is ready"}]
02:45:34.827 -> ["toEsp",{"now":"esp is ready"}]
02:45:36.788 -> ["toEsp",{"now":"esp is ready"}]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------node js socketio server-----------------------------------------------------
const path = require("path");
const express = require("express");
const socketIO = require('socket.io');
const fs = require("fs");
const https = require("https");
const { clear } = require("console");

var privateKey = fs.readFileSync(path.join(__dirname , 'cert' , 'key.pem'));
var certificate = fs.readFileSync(path.join(__dirname , 'cert' , 'cert.pem'));
var credentials = { key: privateKey , cert: certificate };
console.log(__dirname );
const HTTPS_PORT = 443;
const app = express();
const httpsServer = https.createServer(credentials , app);

let io = socketIO(httpsServer);
io.on('connection',(socket)=>
{
    console.log("A new user just connected");
    socket.emit("this is node server")
    
   socket.on('message',(message)=>
    {
        console.log(message);
      }); 

    socket.on('disconnect',()=>
    {
        console.log("user disconnected");
    });
    
    socket.on("toEspFromChrome", (data) => 
    {
        io.emit("toEsp" , data) ;
        console.log(data);
      });

     
})

//app.use(express.static("."));
app.get("/", (req, res) => res.sendFile(path.resolve(__dirname, "index.html")));
httpsServer.listen(HTTPS_PORT, () => console.log(`HTTPS server listening at ${HTTPS_PORT}`));

**Comment by Links2004** [comment]
your nodejs code is missing a handler for the `toEsp` event, the server only handles a event called `message`.

```js
socket.on('toEsp',(message)=>{
  console.log(message);
}); 
```

**Comment by Tusharkumar0012** [comment]
I tried that example sir but i am not getting any message in socket io server . Should i listen for "now" event in my server according to this example . Alsp i am not abld to understand array.add() has event names for listening on esp client . So how to send different event on server side . Anything added to array.add() is also sending it as an event name with payload to node server .
Thanks very much sir for your reply

**Comment by Tusharkumar0012** [comment]
i got it 👍 
 String o = "[\"mess\",{\"now\":\"esp is ready\"}]" ;
socketIO.sendEVENT(o);
// here i am sending to mess event and data is now : esp is ready and it is working fine .
i added this on server side .
 socket.on('mess',(message)=>
    {
        console.log(message);
      }); 
//this is how we can send custom events i think.
thanks to you again markus . you can close the issue now .
also sorry for posting in @gitZui , i just joined github yesterday so by mistake ..
