### ISSUE TITLE
Error: expected class-name before '{' token

### ISSUE THREAD

**Issue by Black2vs2** [Links2004/arduinoWebSockets#695]
Getting an error while trying to import WebSockets to my project.
Import code:
```
#include <SocketIOclient.h>
#include <WebSocketsClient.h>
#include <WiFiUdp.h>
```

Error:
```
In file included from src\main.cpp:19:
lib\arduinoWebSockets-2.3.5\src/SocketIOclient.h:38:51: error: expected class-name before '{' token
```

**Comment by Links2004** [comment]
Hi, 
how to reproduce this? 
all examples in this repo are building fine.

the linked commit, shows many space changes, what are the parts that that are really needed?

**Comment by Black2vs2** [comment]
Hi,
1) I just downloaded the arduinoWebSockets library from platformio.
2) Used the automatic "add to project" button on the arduinoWebSockets library.
3) Tried importing on main these 2 headers:
```
#include <SocketIOclient.h>
#include <WebSocketsClient.h>
```
4) On build i get the error written above.

Sorry for the commit, didn't realize the space changes.
The fix would be on line 12 (adding `#include "WebSocketsClient.h"`)
