### ISSUE TITLE
Fatal exception (28):

### ISSUE THREAD

**Issue by jandren** [Links2004/arduinoWebSockets#7]
It compiles and uploads just fine but, something goes quite wrong when running...
Any idea of what it could be?

Running W7, Arduino IDE 1.6.5 and downloaded the sources for both ESP8266/Arduino and the arduinoWebSockets today 2015-07-15 so new sources.

[SETUP] BOOT WAIT 4...
scandone
[SETUP] BOOT WAIT 3...
add 0
aid 3
pm open phy_2,type:2 0 0
cnt 

connected with TP-LINK_CB4DE8, channel 6
dhcp client start...
ip:192.168.1.100,mask:255.255.255.0,gw:192.168.1.1
[SETUP] BOOT WAIT 2...
[SETUP] BOOT WAIT 1...
Fatal exception (28):
epc1=0x40102180, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00001c20, depc=0x00000000
Fatal exception (28):
epc1=0x40102052, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00001c24, depc=0x00000000
Fatal exception (28):
epc1=0x40102052, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00001c24, depc=0x00000000
Fatal exception (28):
epc1=0x40102052, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00001c24, depc=0x00000000
Fatal exception (28):
epc1=0x40102052, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00001c24, depc=0x00000000
Fatal exception (28):
epc1=0x40102052, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00001c24, depc=0x00000000
Fatal exception (28):
epc1=0x40102052, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00001c24, depc=0x00000000
Fatal exception (28):
epc1=0x40102052, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00001c24, depc=0x00000000
Fatal exception (28):
epc1=0x40102052, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00001c24, depc=0x00000000
$epc1
 ets Jan  8 2013,rst cause:4, boot mode:(3,0)

wdt reset

**Comment by Links2004** [comment]
the address points the the basic ESP functions (0x401xxxxx) 
Fatal exception (28) means there is an access to a locked or wrong memory address (Load Prohibited)

do you run the server or client example? 
is there more output when you enable the debug functions from WebSockets:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L40

**Comment by jandren** [comment]
It's the client example file, and I don't get any more information when activating the debug. But I did once, because it actually worked once this time when starting from scratch and had to change to another ESP module because I forgot to lower the baudrate in the example to something the windows Arduino IDE manages to do, 916200 is apparently to high. Well anyway, the first time with the new board and uncommented DEBUG actually gave me an access and proper handshake to echo.websocket.org, with lots of DEBUG information so that seemed to work at least. But Im back on the same error now :(

**Comment by Links2004** [comment]
may something with you flash/upload process is wrong.
do you use the stable build from https://github.com/esp8266/Arduino or you use the latest git version?
@igrr currently working on a doc and build update and after this he will generate a new release.
see https://github.com/esp8266/Arduino/issues/558

**Comment by jandren** [comment]
Actually I used the json link for installing the esp8266 package, so then I have an old version I guess, will try to build from source instead.

**Comment by bpescaaz** [comment]
Having same issue. Have you had any luck? @jandren

**Comment by Links2004** [comment]
I have done a full test if the client example with the latest git version of ESP8266, and i cant get any exception. 
are you using the Staging version if not please try it.
http://arduino.esp8266.com/staging/package_esp8266com_index.json

**Comment by bpescaaz** [comment]
Thanks for the reply. I tried many things to get this to work.
I am using staging version. I tried it on nodemcu v1.0 and esp generic, i tried on arduino v 1.6.4 and 1.6.5. I am on windows 8.1. The node server is working and accepting socket connection it opens and closes and esp reboots.

[SETUP] BOOT WAIT 4...
[SETUP] BOOT WAIT 3...
[SETUP] BOOT WAIT 2...
[SETUP] BOOT WAIT 1...
[WSc] Connected to url: /

Exception (28):
epc1=0x4000bf64 epc2=0x00000000 epc3=0x00000000 excvaddr=0x0000000d depc=0x00000000

ctx: cont 
sp: 3ffea590 end: 3ffea960 offset: 01a0

>>>stack>>>
3ffea730:  0000000c 0000000d 00000000 3ffea870  
3ffea740:  3ffea880 402068d5 3ffea9b8 3fff4220  
3ffea750:  00000000 3fff4220 3ffea760 3fff4208 <
3ffea760:  6353575b 6567205d 65742074 203a7478  
3ffea770:  6353575b 6f43205d 63656e6e 20646574  
3ffea780:  75206f74 203a6c72 3f000a2f 3ffea7c0  
3ffea790:  00000008 00000008 3ffea7f0 40207fa4  
3ffea7a0:  401004ac 3fff4a9a 3fff4a60 000001f8  
3ffea7b0:  000001c0 3ffea870 3ffea7f0 4020805d  
3ffea7c0:  3fff4a50 40101db8 00000000 0000001c  
3ffea7d0:  40208e18 3ffea830 0000001c 3fff4768  
3ffea7e0:  401004dc 0000001c 3ffea830 40208e46  
3ffea7f0:  401004f4 00000000 3ffea830 40208e8c  
3ffea800:  401065c0 3ffea8cc 3ffea830 40208ec4  
3ffea810:  3fff16b0 4021768f 00000000 3fff50e8  
3ffea820:  402123b9 3fff50c0 3fff4768 4020443c  
3ffea830:  4020b6ee 3fff50c0 3ffe9600 3ffe9840  
3ffea840:  402039ea 3fff49b0 3fff50c0 3fff49b0  
3ffea850:  00000000 00000000 00000000 3fff422d  
3ffea860:  3ffea880 3ffea870 00000008 3ffe9940  
3ffea870:  3ffe9600 3fff4220 0000000d 3fff4220  
3ffea880:  0000000d 402020cc 00000000 4020469a  
3ffea890:  0000000d 00000030 0000000d 40202116  
3ffea8a0:  3fff4210 3ffe95e4 3ffe95f8 402048c6  
3ffea8b0:  00000000 3ffe95e4 3ffe95f8 40204828  
3ffea8c0:  00000000 00000000 3ffe9600 3ffe9840  
3ffea8d0:  00000d81 00000000 402017fe 3ffe9940  
3ffea8e0:  00000081 0000000d 402017fe 40201894  
3ffea8f0:  3ffe95f8 3ffe95f8 3ffe95e4 3ffea98c  
3ffea900:  3ffe95f8 00000000 3ffe95e4 40204f3a  
3ffea910:  40213ad7 00000000 3ffe95e4 40204fbd  
3ffea920:  3fff3d78 40202ae8 00000016 3ffea98c  
3ffea930:  3fffdc20 00000000 3ffe95e4 4020216f  
3ffea940:  3fffdc20 00000000 3ffea984 4020187a  
3ffea950:  00000000 00000000 3ffe9940 4010072c  
<<<stack<<<

 ets Jan  8 2013,rst cause:1, boot mode:(3,7)

load 0x4010f000, len 1464, room 16 
tail 8
chksum 0x7a
csum 0x7a
e

**Comment by bpescaaz** [comment]
I got it to work.

In WebSocketclient sketch:
in printf functions-  length is  spelled wrong,
in case statement WStype_TEXT:  printf args should be payload not lenght,
changed baud to 115200 to use arduino serial monitor also changed serial1 to serial,
added printf support to avr /print.h in my arduino ide.(see arduino docs)

**Comment by Links2004** [comment]
ok, that was my bad have fixed long ago in my test file but seams forget copy it bay to the examples. 
I improve the Serial usage for easier switch between Serial and Serial1.

Thanks for the feedback.
