### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by maciekfreak** [Links2004/arduinoWebSockets#70]
I have a strange issue. I'm resending all data from serial device using your websocket library. This data are strings about 10 times per second. 

I'm using nodemcu esp8266 and sometimes esp8266 freeze for about 1-2 second and then start sending again.

This is code from my loop:

`
void loop() {

    webSocket.loop();
    if (connectedClient) {
    if (Serial.available()) {
           while (Serial.available()) {
            sb=(char)Serial.read();
            if (sb == '\n') {
                webSocket.sendTXT(connectedIP, txtMsg);
                txtMsg = "";  
            } else {  
                txtMsg +=sb; 
            }
        }
        }
    }
}
`

Do you know maybe what can be responsible for these freezes?

**Comment by maciekfreak** [comment]
I tried async version and now it's looks that freeze are gone.. I will make some more tests to be sure.

**Comment by maciekfreak** [comment]
Unfortunatly lags and hanging continue. Now I think that this is somehow correlated with other wifi tasks on device. 
Computer is connected to esp8266 access point.And for example when computer looking for other wifi network from time to time, websockets lags a little bit in the same time.

Do you think that this is possible? Is any possibility to avoid such things?

**Comment by Links2004** [comment]
for serial try to use this:
https://github.com/Links2004/arduinoWebSockets/issues/61#issuecomment-198231422
sending a packed on every new line generates many overhead, whit a time based way (see link) I have get better results.
