### ISSUE TITLE
Can't connect to webSocket.begin("/", 80, "ws://abc.xyz.in/");

### ISSUE THREAD

**Issue by ChaitanyaYeole02** [Links2004/arduinoWebSockets#711]
I am trying to connect my ESP32 to my websocket server. I only have an url and port how will I be able to connect the same.
It's giving me disconnected error all the time

**Comment by Links2004** [comment]
`ws://abc.xyz.in/` =>
```cpp
webSocket.begin("abc.xyz.in", 80, "/");
```

**Comment by ChaitanyaYeole02** [comment]
I resolved it, thank you
