### ISSUE TITLE
Husarnet.h does not exist

### ISSUE THREAD

**Issue by sergesvz** [Links2004/arduinoWebSockets#726]
fatal error: Husarnet.h: No such file or directory

**Comment by Links2004** [comment]
this looks not like a problem from this lib, since no `Husarnet.h` is used in it.
https://github.com/Links2004/arduinoWebSockets/search?q=Husarnet.h

may check other libs.

**Comment by Links2004** [comment]
may related to: #478?

**Comment by sergesvz** [comment]
According to library Husarnet ESP32 by Husarnet, this library does not include any file called Husarnet.h
For ex, using 'simple-webserver.ino' file:
...
#include <Husarnet.h>
..

**Comment by sergesvz** [comment]
answer to myself: 
Husarnet need dedicated framework; see "platformio.ini"
[..
platform_packages =
    framework-arduinoespressif32 @ https://files.husarion.com/arduino/arduino-husarnet-esp32-v1.2.0.zip
..]
