### ISSUE TITLE
stream a video frame  by websocket

### ISSUE THREAD

**Issue by mkeyno** [Links2004/arduinoWebSockets#73]
hi Markus,I really appreciated to have your idea about is it possible the ESP module handle video  stream from client browser by websocket? I mean we have such function in loop
`
void loop(void)
{
server.handleClient();  
webSocket.loop();
handdle.video(frameBuffer);
}
`
has anyone test the streaming the video frame with your websocket library ?
any comment really appreciated

**Comment by msurguy** [comment]
Check out this post from the makers of Arducam, maybe it will point you to the right direction, @mkeyno! http://www.arducam.com/arducam-supports-esp8266-arduino-board-wifi-websocket-camera-demo/

**Comment by mkeyno** [comment]
thanks @msurguy , as this topic is long ago I have another question actually I intend to download the file from flash  in the way that read line by line of file and send it back to client,is websocket suitable for that?

**Comment by mkeyno** [comment]
hi @Links2004 Markus so long hearing from you , actually I've tried to download files from flash by hyperlink embedded in webpage  on flash , I change content type of files to download it  but fail yet , that's why I switched to websoket , also I've tried to build CMS webpage so update the content by websoket  link ,in absence of something like PHP & mySQL, I really appreciated to have your idea about downloading file from SPIFF or use websocket as CMS

**Comment by Links2004** [comment]
websocket can handle all kind of data including binary, so there is no problem in sending data from flash.
for really big files some changes are need, too sending it in chunks. (base work is done already  see: https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.cpp#L82 the fin parameter).
there is only a easy to use API is missing.
i also recommend using the async version then to keep the handling of multible connection smooth. 

for streaming and updating values and data live form or to the ESP ws is sure the way to go, 
since its it easy to use and much faster compared too polling via http, and need less bandwidth too.

**Comment by mkeyno** [comment]
thanks @Links2004 Markus and @msurguy , I know you too busy but can you elaborate what exactly should I do or what choose do I have to send **big file fast it as possible** ? 
let me explain my idea behind this topic
I've plan to send the frame of big image from processing on my laptop to couple of ESP node through my home wifi-modem , each ESP has couple LED strip attached to it and processing slice the image and add node IP address to each of them and transmit to those
which way is the safe and fast ?
plain TCP?
UDP?
server websocket of processing  and client websocket  on ESP node?
client websocket of processing  and server websocket  on ESP node?
as it  #define WEBSOCKETS_MAX_DATA_SIZE  (15*1024)   ,  should it less problematic to keep slice file  part below that 15Kb ? 
also I really appreciated if I have you guys  @urish , @marvinroger , @tripzero comments

**Comment by Links2004** [comment]
40ms is no problem, with a good wifi you can get around 1ms per ~1400byte
to get you a correct answer some more infos are needed. like how many data you need to send peer frame.
in a single TCP/WS packet you can get around 450 RGB LEDs (8bit per color).
for very high count of LED I Prefere UDP since you save the time for the ACK packages.
and eaven when you loss one packet no one will really see it by 25fps.
simple keep the LEDs at the same color when you miss information's. 
but when your WiFi is stable you normally not loss any.

I personally have some ESP with WS2812 running here with a websocket connection to configure stuff like Led count, overall brightness, set to static color.
and for fast data streaming (ambilight) I use UDP.

**Comment by mkeyno** [comment]
thanks Dear Markus for tip , my screen LED may have 2*3*60*60 LED and frame size would be around 64KB, but this sliced to 24 ESP module , so each module should received  about 2.7 KB chunk of data  under 40 ms ,
 so you say a dedicated wifi-router-modem can easily handle this amount of data between my computer and 24 ESP module by UDP protocol ?

**Comment by Links2004** [comment]
this will easy work.
typical WiFi can handle 54Mbit (g) or 150Mbit (n with 20 MHz channel) 
for g WiFi 64KB need ~10ms to transmit for n WiFi ~3ms.
I stream around 1MB/s to one ESP for VNC and it is working well.

yes the Websocket has no ACK itself but its using a TCP socket and TCP has ACK.
UDP is connectionless (no ACK, no transmit on loss ....) more her: http://www.diffen.com/difference/TCP_vs_UDP

**Comment by mkeyno** [comment]
very very thanks  @Links2004  Markus , I'm gonna this way ,
 also I have plan to make POV , In that POV  I should read about 300-400 line of one frame (one image) , then read line by line , display it in LED strip and wait for about ( number of lines / time of each frame =) 100 us  and do the next , I've already done it with teensy , which is read images from SD card , but I'm thinking to to stream the frame to ESP by websocket or UDP then  feed the each frame to the last process , do you thinks ESP can buffer the frames and process it in that time schedule ?

**Comment by Links2004** [comment]
may this helps to get a felling for the power of the ESP:
https://www.youtube.com/watch?v=ZCdR3YK4_iM&list=PL_uBwkglUU0qK-ZUi3iTHQhKsXv5wGSX2&index=2
all data is streamed live via VNC protocol, you can watch YouTube by this way on the ESP ;)

the SD read via SPI from the arduino libs is very slow compered to the speed you can get with network on the ESP.

**Comment by mkeyno** [comment]
wow , very amazing buddy , you refer  the VNC protocol as the old RFB protocol , do you have any sample code or direction links , I'm really interested to get into it

**Comment by Links2004** [comment]
sample code ;) https://github.com/Links2004/arduinoVNC
its a full library just like my websockets.

**Comment by mkeyno** [comment]
actually I had glance on this library before , but I don't have any idea to what VNC is and what it can do , however , its seam your library focused on display module's , is there any bare core which is reveal how to constantly send frame of data from   client to server, and then decide how to deal with the received data , in another words can you guide how to stream data to ESP module  with this protocol

**Comment by Links2004** [comment]
VNC/RFB protocol can handle video/image data, but it is not designed for generic use.
the writing to display is complete separated from the protocol  itself in my src with the VNCdisplay  class.
https://github.com/Links2004/arduinoVNC/blob/master/src/VNC.h#L141-L161
you can easy create a class to output it to a LED stripe for example.

the RFB protocol: https://github.com/Links2004/arduinoVNC/blob/master/src/VNC.cpp
display interface: https://github.com/Links2004/arduinoVNC/blob/master/src/VNC_ILI9341.cpp


the docu of RFB can be find here: https://github.com/Links2004/arduinoVNC/blob/master/docu/rfbproto%203.8.pdf
