### ISSUE TITLE
stop reconnection interval

### ISSUE THREAD

**Issue by deepak4395** [Links2004/arduinoWebSockets#732]
Hi 
I want to stop the reconnection attempts to the WebSocket server after a certain time. And I may need to start it again.
Basically, I'll disconnect from WebSocket after a certain condition and then attempt to reconnect on the user switch press.
Any help is appreciated, thanks in advance.

**Comment by Links2004** [comment]
to disconnect call:
https://github.com/Links2004/arduinoWebSockets/blob/28ed6151454fc0a3568a14abbc88b9b9aee4bba7/src/WebSocketsClient.h#L93

to control the time between reconnection attempts:
https://github.com/Links2004/arduinoWebSockets/blob/28ed6151454fc0a3568a14abbc88b9b9aee4bba7/src/WebSocketsClient.h#L100

if you dont want any reconnection attempts simply stop calling `loop()` after `disconnect()` was called.
