### ISSUE TITLE
SocketIOClient how to extract payload?

### ISSUE THREAD

**Issue by Hir02** [Links2004/arduinoWebSockets#733]
`[IOc] get event: ["select",{"label":"pen1","ration":0.6400000000000001}]`
how can I listen to an event and extract the payload?
can someone show me an example?

**Comment by Links2004** [comment]
its JSON and can be easy be decoded via the `ArduinoJson` lib.

example:

https://github.com/Links2004/arduinoWebSockets/blob/28ed6151454fc0a3568a14abbc88b9b9aee4bba7/examples/esp8266/WebSocketClientSocketIOack/WebSocketClientSocketIOack.ino#L39-L54

**Comment by Hir02** [comment]
thank you so much for the response sir/maam much appreciated, guess I was exploring the wrong file so I didn't found this
