### ISSUE TITLE
Socket IO client not connects to socketio nodejs server using https/http

### ISSUE THREAD

**Issue by bilalilyas90** [Links2004/arduinoWebSockets#734]
Hi

**This is nodejs server socketio**

const fs = require('fs');
const options = {
	key: fs.readFileSync('/etc/letsencrypt/live/domain.com/privkey.pem'),
	cert: fs.readFileSync('/etc/letsencrypt/live/domain.com/cert.pem')
};
var app = require('express')();
var http = require('https').createServer(options, app);

var io = require('socket.io')(http, {
	pingInterval: 90000,
	pingTimeout: 190000,
	transports: ['websocket'],
	allowUpgrades: false,
	upgradeTimeout: 190000,
    allowEIO3: true, // false by default,
    cors: {
        origin: "*",
        methods: ["GET","POST"],
        transports: ["websockets"]
    }
});

app.get('/', function (req, res) {
	res.send('Silence is good!');
});
io.on('connection', function (socket) {
	console.log('user is connected! ');

	socket.on('event_name', function () {
		console.log('now is fired ');
	});

	socket.on('disconnect', function () {
		console.log('user is disconnected ');
        // socket.leave("admin_room")
	});
});

http.listen(30002, function () {
	console.log('listening on *:30002');
});

**Following is esp32 code**
/*
 * WebSocketClientSocketIOack.ino
 *
 *  Created on: 20.07.2019
 *
 */

#include <Arduino.h>

#include <WiFi.h>
#include <WiFiMulti.h>
#include <WiFiClientSecure.h>

#include <ArduinoJson.h>

#include <WebSocketsClient.h>
#include <SocketIOclient.h>

WiFiMulti WiFiMulti;
SocketIOclient socketIO;

#define USE_SERIAL Serial

void socketIOEvent(socketIOmessageType_t type, uint8_t * payload, size_t length) {
    switch(type) {
        case sIOtype_DISCONNECT:
            USE_SERIAL.printf("[IOc] Disconnected!\n");
            break;
        case sIOtype_CONNECT:
            USE_SERIAL.printf("[IOc] Connected to url: %s\n", payload);

            // join default namespace (no auto join in Socket.IO V3)
            socketIO.send(sIOtype_CONNECT, "/");
            break;
        case sIOtype_EVENT:
        {
            char * sptr = NULL;
            int id = strtol((char *)payload, &sptr, 10);
            USE_SERIAL.printf("[IOc] get event: %s id: %d\n", payload, id);
            if(id) {
                payload = (uint8_t *)sptr;
            }
            DynamicJsonDocument doc(1024);
            DeserializationError error = deserializeJson(doc, payload, length);
            if(error) {
                USE_SERIAL.print(F("deserializeJson() failed: "));
                USE_SERIAL.println(error.c_str());
                return;
            }

            String eventName = doc[0];
            USE_SERIAL.printf("[IOc] event name: %s\n", eventName.c_str());

            // Message Includes a ID for a ACK (callback)
            if(id) {
                // creat JSON message for Socket.IO (ack)
                DynamicJsonDocument docOut(1024);
                JsonArray array = docOut.to<JsonArray>();

                // add payload (parameters) for the ack (callback function)
                JsonObject param1 = array.createNestedObject();
                param1["now"] = millis();

                // JSON to String (serializion)
                String output;
                output += id;
                serializeJson(docOut, output);

                // Send event
                socketIO.send(sIOtype_ACK, output);
            }
        }
            break;
        case sIOtype_ACK:
            USE_SERIAL.printf("[IOc] get ack: %u\n", length);
            break;
        case sIOtype_ERROR:
            USE_SERIAL.printf("[IOc] get error: %u\n", length);
            break;
        case sIOtype_BINARY_EVENT:
            USE_SERIAL.printf("[IOc] get binary: %u\n", length);
            break;
        case sIOtype_BINARY_ACK:
            USE_SERIAL.printf("[IOc] get binary ack: %u\n", length);
            break;
    }
}

void setup() {
    //USE_SERIAL.begin(921600);
    USE_SERIAL.begin(115200);

    //Serial.setDebugOutput(true);
    USE_SERIAL.setDebugOutput(true);

    USE_SERIAL.println();
    USE_SERIAL.println();
    USE_SERIAL.println();

      for(uint8_t t = 4; t > 0; t--) {
          USE_SERIAL.printf("[SETUP] BOOT WAIT %d...\n", t);
          USE_SERIAL.flush();
          delay(1000);
      }

    WiFiMulti.addAP("QodIT StormFiber", "wlandee88f");

    //WiFi.disconnect();
    while(WiFiMulti.run() != WL_CONNECTED) {
          USE_SERIAL.printf("wifi connecting....");
        delay(100);
    }

    String ip = WiFi.localIP().toString();
    USE_SERIAL.printf("[SETUP] WiFi Connected %s\n", ip.c_str());

    // server address, port and URL 
    //**//server address is https://securityapp.qodit.pk** 
    socketIO.beginSSL("securityapp.qodit.pk", 30002, "/socket.io/?EIO=3&transport=websocket");

    // event handler
    socketIO.onEvent(socketIOEvent);
}

unsigned long messageTimestamp = 0;
void loop() {
    socketIO.loop();

    uint64_t now = millis();

    if(now - messageTimestamp > 2000) {
        messageTimestamp = now;

        // creat JSON message for Socket.IO (event)
        DynamicJsonDocument doc(1024);
        JsonArray array = doc.to<JsonArray>();

        // add evnet name
        // Hint: socket.on('event_name', ....
        array.add("event_name");

        // add payload (parameters) for the event
        JsonObject param1 = array.createNestedObject();
        param1["now"] = (uint32_t) now;

        // JSON to String (serializion)
        String output;
        serializeJson(doc, output);

        // Send event
        socketIO.sendEVENT(output);

        // Print JSON for debugging
        USE_SERIAL.println(output);
    }
}

**Following is the error I am getting and could'nt solve it please help.  When trying to connect socketio nodejs server from web it connects successful but not i esp32**

["event_name",{"now":13794}]
[IOc] Disconnected!
[IOc] Disconnected!
[IOc] Disconnected!
["event_name",{"now":15945}]
[IOc] Disconnected!
[IOc] Disconnected!
[IOc] Disconnected!
["event_name",{"now":18096}]
[IOc] Disconnected!
[IOc] Disconnected!
[IOc] Disconnected!
["event_name",{"now":20246}]
[IOc] Disconnected!
[IOc] Disconnected!
[IOc] Disconnected!
["event_name",{"now":22398}]

**Comment by Tusharkumar0012** [comment]
Maybe its a issue on socketio version or the Library version on esp side .
I had encountered the same issue 6 months ago .

**Comment by bilalilyas90** [comment]
@Tusharkumar0012  Please ca you guide me exactly what should I do to solve this issue??

**Comment by bilalilyas90** [comment]
@Tusharkumar0012  please can you guide me?

**Comment by Tusharkumar0012** [comment]
I did that project almost 6 months ago , so I kind of forgot it . Ask the
creator of the library ( Links2004 ) . I will however post my code that I
had written both server side and esp side , that was working whenever I get
time . you mentioned HTTPS , is it working without the letsencrypt keys on
plain HTTP ?
Hope you solve it soon .

**Comment by bilalilyas90** [comment]
> I did that project almost 6 months ago , so I kind of forgot it . Ask the creator of the library ( Links2004 ) . I will however post my code that I had written both server side and esp side , that was working whenever I get time . you mentioned HTTPS , is it working without the letsencrypt keys on plain HTTP ? Hope you solve it soon .

I will try without letsencrypt keys with plain http and then let you know if it works or not ... 
and thank you in advance if you have time do upload the code so it might help us ...

**Comment by bilalilyas90** [comment]
@Tusharkumar0012  I tried with plain http and still I am unable to connect to socket io server ... it always says disconnected

**Comment by bilalilyas90** [comment]
@Links2004  Please can you help me solve this issue?

**Comment by SamuilDimitrov** [comment]
Did you manage to fix the problem and if you did, how did you do it?
