### ISSUE TITLE
sha.h didn't exist anymore with latest core  2.0.3.

### ISSUE THREAD

**Issue by Skywalkerf34** [Links2004/arduinoWebSockets#745]
d:\Users\FidL\Documents\Arduino\libraries\arduinoWebSockets\src\WebSockets.cpp:42:10: fatal error: hwcrypto/sha.h: No such file or directory
 #include <hwcrypto/sha.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.

**Comment by Links2004** [comment]
fix merged, release of new Version will follow soon
