### ISSUE TITLE
Server receives JSON Object instead of String

### ISSUE THREAD

**Issue by NiklasProbst** [Links2004/arduinoWebSockets#755]
Hello,
I searched all day long but couldn't find a detailed description of the following commands:
.send()
.sendTXT()
.sendBIN()
.sendEVENT()

First I want to know what do those commands do and when to use which?

Second I want to send a JSON String to my NodeJS Socket, however I get a JSON Object not the String causing my Server to crash.

`if(now - messageTimestamp > 2000) {
        messageTimestamp = now;

        // creat JSON message for Socket.IO (event)
        DynamicJsonDocument doc(1024);
        JsonArray array = doc.to<JsonArray>();

        // add evnet name
        // Hint: socket.on('event_name', ....
        array.add("message");

        // add payload (parameters) for the event
        JsonObject param1 = array.createNestedObject();
        param1["now"] = (uint32_t) now;

        // JSON to String (serializion)
        String output;
        serializeJson(doc, output);

        // Send event
        socketIO.send(output); 

        // Print JSON for debugging
        USE_SERIAL.println(output);
    }`

The above code sends a Json object to the server however I need a JSON String.

Thank you very much in advance!

**Comment by Links2004** [comment]
is you server code using plan websocket or socket.IO?

**Comment by NiklasProbst** [comment]
Here is my Server Code:
`import { Socket } from "./node_modules/socket.io/dist/socket";
import * as _http from 'http';
import * as _io from 'socket.io';

/*const http = require("http").createServer();
const io = require("socket.io")(http, {
    cors: { origin: "*" },
});*/

const http = _http.createServer();
const io = new _io.Server(http, {
    cors: {origin: '*'},
});


interface Data {
    temp?: number,
    isHeating?: boolean,
}

var data: Data = {
    temp: -1,
    isHeating: false
};


io.on("connection", (socket: Socket) => {                               //wird aufgerufen, wenn sich ein Client mit dem Server verbindet
    console.log(`New client connection with ID ${socket.id}`);

    socket.emit('message', JSON.stringify(data));

    socket.on("message", (message: string) => {
        console.log(message);
        console.dir(message, { depth: null });
        data = {...data, ...JSON.parse(message)};
        console.log(`${socket.id} sent ${message}`);                   
        io.emit('message', JSON.stringify(data));                            
    });
});

http.listen(3000, () => console.log('listening on http://localhost:3000'));    //Server hört auf den Port (hier 3000)`

**Comment by Links2004** [comment]
there is no need to do a JSON.stringify or JSON.parse with socket.IO,
since socket.IO will take care of that for you.

**Comment by NiklasProbst** [comment]
Can I somehow send a String? Because all my other Clients (e.g Android Studio App) send Json Strings.

**Comment by Links2004** [comment]
you can, but it may is easier to simply do a check on the server side.

````js
if(typeof message == 'String') {
 data = {...data, ...JSON.parse(message)};
 } else {
  data = {...data, ...message};
 }
```

**Comment by NiklasProbst** [comment]
Thank you so much Links. Have a nice day. Greetings from Austria
