### ISSUE TITLE
SocketIO with https using server's CA

### ISSUE THREAD

**Issue by zekageri** [Links2004/arduinoWebSockets#756]
### The socketIO works with insecure http server which i'm initialising like this:

```C
void serverCommSys::init() {
    Serial.printf("Connecting to HsH server on URL %s...\n",hsh_fileSystem.config.serverBaseURL);
    socketIO.begin(hsh_fileSystem.config.serverBaseIP, 80, "/socket.io/?EIO=4","HsH");
    socketIO.onEvent(socketIOEvent);
    firstConnectionHappened = true;
}
```

However my server uses HTTPS with it's own CA.
How can i connect to this server using my server's ca with SocketIO?

**If i try to connect like this:**

```C
void serverCommSys::initWithSSL() {
    Serial.printf("Connecting to HsH server on URL %s...\n",hsh_fileSystem.config.serverBaseURL);
    socketIO.beginSSL(hsh_fileSystem.config.serverBaseIP, 443, "/socket.io/?EIO=4","HsH");
    socketIO.onEvent(socketIOEvent);
    firstConnectionHappened = true;
}
```

_It's just wont work._

**If i try to use this function:**

```C
void serverCommSys::initWithSSL() {
    
    char ca[10000];
    hsh_fileSystem.readFile(SERVER_CA_PATH,ca);
    
    Serial.printf("Connecting to HsH server on URL %s...\n",hsh_fileSystem.config.serverBaseURL);
    socketIO.beginSslWithCA(hsh_fileSystem.config.serverBaseIP, 443, "/socket.io/?EIO=4",ca,"HsH");
    socketIO.onEvent(socketIOEvent);
    firstConnectionHappened = true;
}
```

**I get compile errors such as:**

```
src/utilities/HsHServerComm.cpp: In member function 'void serverCommSys::initWithSSL()':
src/utilities/HsHServerComm.cpp:27:98: error: 'void WebSocketsClient::beginSslWithCA(const char*, uint16_t, const char*, const char*, const char*)' is inaccessible within this context
     socketIO.beginSslWithCA(hsh_fileSystem.config.serverBaseIP, 443, "/socket.io/?EIO=4",ca,"HsH");

                   ^
In file included from src/utilities/HsHServerComm.h:14,
                 from src/utilities/HsHServerComm.cpp:1:
lib/arduinoWebSockets/src/WebSocketsClient.h:55:10: note: declared here        
     void beginSslWithCA(const char * host, uint16_t port, const char * url = "/", const char * CA_cert = NULL, const char * protocol = "arduino");
          ^~~~~~~~~~~~~~
src/utilities/HsHServerComm.cpp:27:98: error: 'WebSocketsClient' is not an accessible base of 'SocketIOclient'
     socketIO.beginSslWithCA(hsh_fileSystem.config.serverBaseIP, 443, "/socket.io/?EIO=4",ca,"HsH");
```

**Comment by Links2004** [comment]
```beginSSLWithCA``` is the way to go here.

https://github.com/Links2004/arduinoWebSockets/blob/master/src/SocketIOclient.h#L57-L60

you most likely need to cast your `ca` `char *` to `const char *`

**Comment by zekageri** [comment]
just to test this, with a quick dirty cast i compiled with this line:

`socketIO.beginSslWithCA(hsh_fileSystem.config.serverBaseIP, 443, "/socket.io/?EIO=4", String(ca).c_str(), "HsH");`

and i get the same error.

`error: 'void WebSocketsClient::beginSslWithCA(const char*, uint16_t, const char*, const char*, const char*)' is inaccessible within this context`

**Comment by zekageri** [comment]
**It suddenly started working with this line:**

`socketIO.beginSSL(hsh_fileSystem.config.serverBaseIP, 443, "/socket.io/?EIO=4","HsH");`

Without CA, without Fingerprint, without authentication. 
The server rejects every http request and upgrades everything to https.

How is this possible?

**Comment by zekageri** [comment]
My server has this config:

```JS
var https  = require('https').createServer( credentials, app );
const io = new Server(https ,{secure: true} );
io.on("connection", (socket) => {
    console.log("HsH socket connected");
});
```

And a webpage served by the server is also https, so it can not initiate a socket connection trought http because it would be "Mixed content" so it is https on server client side too. The esp can not connect without SSL to the server too.

So i'm confused now A.F

**Comment by zekageri** [comment]
` error: 'class SocketIOclient' has no member named 'beginSSLWithCA'; did you mean 'beginSslWithCA'?`

**Comment by Links2004** [comment]
is you lib and ESP core uptodate, the error hints at a old version.

**Comment by zekageri** [comment]
Lib is latest master. I just downloaded again.
Framework is: **- framework-arduinoespressif32 @ 3.20003.220613 (2.0.3)**

**Comment by zekageri** [comment]
The interesting thing is that if i initiate a connection with `socketIO.beginSSL(hsh_fileSystem.config.serverBaseIP, 443, "/socket.io/?EIO=4","HsH");` It can connect to a https server without problem, data exchange working fine but my HTTPS get requests are stopped working on other tasks. They are returning `http code -1`

**Comment by zekageri** [comment]
Any toughts on this @Links2004?

**Comment by zekageri** [comment]
If i `#define SSL_BARESSL` it would allow me to use `socketIO.beginSSLWithCA` but the baressl requires `#include <ArduinoBearSSL.h>` which i dont want. Is it absolutely necessary?

**Comment by zekageri** [comment]
Okay so i moved  this line in the `SocketIOclient.h` -> `void beginSSLWithCA(const char * host, uint16_t port, const char * url = "/socket.io/?EIO=3", const char * CA_cert = NULL, const char * protocol = "arduino");` after the  `HAS_SSL` define, before `#ifndef SSL_AXTLS` like this:

```C
#ifdef HAS_SSL
    void beginSSL(const char * host, uint16_t port, const char * url = "/socket.io/?EIO=3", const char * protocol = "arduino");
    void beginSSL(String host, uint16_t port, String url = "/socket.io/?EIO=3", String protocol = "arduino");
    void beginSSLWithCA(const char * host, uint16_t port, const char * url = "/socket.io/?EIO=3", const char * CA_cert = NULL, const char * protocol = "arduino");
#ifndef SSL_AXTLS
    void beginSSLWithCA(const char * host, uint16_t port, const char * url = "/socket.io/?EIO=3", const char * CA_cert = NULL, const char * protocol = "arduino");
    void beginSSLWithCA(const char * host, uint16_t port, const char * url = "/socket.io/?EIO=3", BearSSL::X509List * CA_cert = NULL, const char * protocol = "arduino");
    void setSSLClientCertKey(const char * clientCert = NULL, const char * clientPrivateKey = NULL);
    void setSSLClientCertKey(BearSSL::X509List * clientCert = NULL, BearSSL::PrivateKey * clientPrivateKey = NULL);
#endif
```

**And in the SocketIOclient.cpp i placed the function before SSL_BARESSL define. like this:**

```C
#if defined(HAS_SSL)
void SocketIOclient::beginSSL(const char * host, uint16_t port, const char * url, const char * protocol) {
    WebSocketsClient::beginSocketIOSSL(host, port, url, protocol);
    WebSocketsClient::enableHeartbeat(60 * 1000, 90 * 1000, 5);
    initClient();
}

void SocketIOclient::beginSSL(String host, uint16_t port, String url, String protocol) {
    WebSocketsClient::beginSocketIOSSL(host, port, url, protocol);
    WebSocketsClient::enableHeartbeat(60 * 1000, 90 * 1000, 5);
    initClient();
}
void SocketIOclient::beginSSLWithCA(const char * host, uint16_t port, const char * url, const char * CA_cert, const char * protocol) {
    WebSocketsClient::beginSocketIOSSLWithCA(host, port, url, CA_cert, protocol);
    WebSocketsClient::enableHeartbeat(60 * 1000, 90 * 1000, 5);
    initClient();
}
#if defined(SSL_BARESSL)
void SocketIOclient::beginSSLWithCA(const char * host, uint16_t port, const char * url, const char * CA_cert, const char * protocol) {
    WebSocketsClient::beginSocketIOSSLWithCA(host, port, url, CA_cert, protocol);
    WebSocketsClient::enableHeartbeat(60 * 1000, 90 * 1000, 5);
    initClient();
}

void SocketIOclient::beginSSLWithCA(const char * host, uint16_t port, const char * url, BearSSL::X509List * CA_cert, const char * protocol) {
    WebSocketsClient::beginSocketIOSSLWithCA(host, port, url, CA_cert, protocol);
    WebSocketsClient::enableHeartbeat(60 * 1000, 90 * 1000, 5);
    initClient();
}

void SocketIOclient::setSSLClientCertKey(const char * clientCert, const char * clientPrivateKey) {
    WebSocketsClient::setSSLClientCertKey(clientCert, clientPrivateKey);
}

void SocketIOclient::setSSLClientCertKey(BearSSL::X509List * clientCert, BearSSL::PrivateKey * clientPrivateKey) {
    WebSocketsClient::setSSLClientCertKey(clientCert, clientPrivateKey);
}
```

Now i can use `socketIO.beginSSLWithCA(hsh_fileSystem.config.serverBaseIP, 443, "/socket.io/?EIO=4", (const char*) ca, "HsH");` but the HTTP requests are still down when socket is connected.

**Comment by Links2004** [comment]
the axTLS can only handle one active TLS / SSL connection.
not sure if its the same for BARE SSL too.

its possible that parsing the CA as string is working with axTLS to (what you done with moving the define),
so feel free to create a PR.


side node:
the ESP8266 uses BARE SSL now (before axTLS)
the ESP32 only supports axTLS

**Comment by zekageri** [comment]
I have implemented this way:

**SocketIOclient.h:**

`void disconnect();`

**SocketIOclient.cpp:**

```C
void SocketIOclient::disconnect() {
    WebSocketsClient::disconnect();
}
```

I'm disconnecting it right before my HTTPS request by calling this disconnect:

```C
socketIO.disconnect();
HTTPClient http;
http.begin( fileCheckURL, ca );
```

It is successfully disconnecting, and performs my HTTPS request, but after that, the **SocketIO can not reconnect.**

Serial after HTTPS request.
```
IO - Disconnected!
IO - Disconnected!
IO - Disconnected!
IO - Disconnected!
IO - Disconnected!
IO - Disconnected!
IO - Disconnected!
IO - Disconnected!
IO - Disconnected!
IO - Disconnected!
IO - Disconnected!
IO - Disconnected!
IO - Disconnected!
IO - Disconnected!
IO - Disconnected!
IO - Disconnected!
IO - Disconnected!
IO - Disconnected!
```

I'm calling `http.end();` after every request so the resource should have been released.

**Comment by zekageri** [comment]
### Here is a more detailed log

`IO - Connected to url: /socket.io/?EIO=4` --> Connecting successfully.

**Begin of the https request, first closing the socket**

```
IO - Disconnected!
Loop locked
[1200097][D][HTTPClient.cpp:303] beginInternal(): protocol: https, host: hitecmyhome 
[1200099][D][HTTPClient.cpp:598] sendRequest(): request type: 'GET' redirCount: 0

[1200854][D][HTTPClient.cpp:1156] connect():  connected to hitecmyhome:443
[1200884][D][HTTPClient.cpp:1307] handleHeaderResponse(): code: 200
[1200885][D][HTTPClient.cpp:1310] handleHeaderResponse(): size: 1046
[1200886][D][HTTPClient.cpp:628] sendRequest(): sendRequest code=200    

[HTTP] GET... code: 200
[pSystem] Old file doc deserialized successfully
[File] No new files to download

[1202060][D][HTTPClient.cpp:393] disconnect(): tcp keep open for reuse 

Loop unlocked
[1205022][E][ssl_client.cpp:37] _handle_error(): [start_ssl_client():185]: (-10112) X509 - Format not recognized as DER or PEM
[1205022][E][WiFiClientSecure.cpp:135] connect(): start_ssl_client: -10112
IO - Disconnected!
[1210037][E][ssl_client.cpp:37] _handle_error(): [start_ssl_client():185]: (-10112) X509 - Format not recognized as DER or PEM
[1210038][E][WiFiClientSecure.cpp:135] connect(): start_ssl_client: -10112
IO - Disconnected!
[1215051][E][ssl_client.cpp:37] _handle_error(): [start_ssl_client():185]: (-10112) X509 - Format not recognized as DER or PEM
[1215052][E][WiFiClientSecure.cpp:135] connect(): start_ssl_client: -10112
IO - Disconnected!
[1220066][E][ssl_client.cpp:37] _handle_error(): [start_ssl_client():185]: (-10112) X509 - Format not recognized as DER or PEM
[1220067][E][WiFiClientSecure.cpp:135] connect(): start_ssl_client: -10112
IO - Disconnected!
[1225080][E][ssl_client.cpp:37] _handle_error(): [start_ssl_client():185]: (-10112) X509 - Format not recognized as DER or PEM
[1225081][E][WiFiClientSecure.cpp:135] connect(): start_ssl_client: -101
```

**HTTP log says that it will keep the tcp open for reuse, but ssl_client says that the format is not recognized, but it uses the same CA as before.**

**Comment by Links2004** [comment]
Its possible that the the HTTP client has messed with the CA stored inside the axTLS, so may try calling `beginSSLWithCA` again to set it.

it the ESP32 HTTPClient still is based on the ESP8266 HTTPClient 
I wrote back in the days then disabling the reuse is possible too.
and `end` will not kill the connection if I remember right if `reuse` is aktive.
but this info is ~4-5 years old ;)

**Comment by zekageri** [comment]
God, the SSL is really broken everywhere in the ESP32.

It indeed messed with the CA.

I did the following:

```C
void serverCommSys::disconnect(){
    socketIO.disconnect();
    connected = false;
    loopLock();
}

void serverCommSys::loopLock(){
    loopLocked = true;
    #if DEBUG_SOCKET
        Serial.println("Loop locked");
    #endif
}

void serverCommSys::loopUnlock(){
    initWithSSL();
    loopLocked = false;
    #if DEBUG_SOCKET
        Serial.println("Loop unlocked");
    #endif
}
```

Calling `disconnect()` before every `HTTPS` call.
It will disconnect the socket client and set the loop to locked state.

After the `HTTPS` request, it will call `loopUnlock()` which will init an SSL connection again, and enabling the loop again if there is a disconnect.

So now, it seems to me that everything is working.

I have 3 kind of `HTTPS` calls in my program right now, every single one of them has to call these functions.

**Comment by zekageri** [comment]
But this is a messy workaround.

First of all i had to copy the `beginSSLWithCA(const char * host, uint16_t port, const char * url, const char * CA_cert, const char * protocol)` function under `#if defined(HAS_SSL)` define at `SocketIOclient.cpp` to be able to call it.

After i had to implement a `disconnect()` functionality to the socketIO client.

After all that i had to disconnect the socket client before every `HTTPS` call ( since there can be only one TLS client ),
and reinitiate the SSL connection again manually.

This is messy but it seems to work for now.

**Comment by Links2004** [comment]
the `beginSSLWithCA` and `disconnect` change are welcome as a PR ;) 

it may makes sense to implement a 
```cpp
    void enableLoop(void);
    void disableLoop(void);
```
as a advanced feature in the lib, since I think you are not the only one with that problem.

on the TLS side there is nothing we can do in this lib.

**Comment by zekageri** [comment]
I never did a PR but i will try it.

Yeah, i know that the TLS should be refactored by Espressif or the Arduino folks...

I will close this issue and really thank you for your help.
I apprecite every single kindness coming from you.
