### ISSUE TITLE
arduino websockets to upgrade http connections to ws

### ISSUE THREAD

**Issue by aguaviva** [Links2004/arduinoWebSockets#76]
Should this be done here or in the webserver? Thanks for the excellent job :)

**Comment by Links2004** [comment]
the arduinoWebSockets has its own http server to handle the WebSockets Update requests. 
I have some planes to allow the integration in too [ESPAsyncWebServer](https://github.com/me-no-dev/ESPAsyncWebServer), but currently my free time is very limited.

**Comment by aguaviva** [comment]
Thanks. I was asking for this because I'd be great to have the webserver and the websockets both use the port 80.. This is really convenient for using the websockets behind a firewall. Could you at least have your library to use an open socket from the webserver? That should be it right? Then the rest of the code would go in the AsyncWebServer

**Comment by Links2004** [comment]
there is now easy integration of the Websocket in to a webserver yet.
the only way right now is to override the handleNonWebsocketConnection handle to act as normal http server.
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsServer.h#L120
