### ISSUE TITLE
core_esp8266_features.h:132:38: error: expected ',' or ';' before 'esp_is_8285'

### ISSUE THREAD

**Issue by arlaor** [Links2004/arduinoWebSockets#782]
Hi @Links2004 
thank you for this library.
i'm used arduino ide 1.8.19 and esp8266 boards 3.1.0-dev
I am getting the following error when working with your library. Is there any solution for this problem?

In file included from C:\Users\Marthi-K\Documents\Arduino\libraries\arduinoWebSockets\src\libb64\cencode.c:9:
C:\Users\Marthi-K\Documents\Arduino\hardware\esp8266com\esp8266\cores\esp8266/core_esp8266_features.h:132:38: error: expected ',' or ';' before 'esp_is_8285'
  132 | bool __attribute__((const, nothrow)) esp_is_8285();
      |                                      ^~~~~~~~~~~
In file included from C:\Users\Marthi-K\Documents\Arduino\libraries\arduinoWebSockets\src\libb64\cdecode.c:9:
C:\Users\Marthi-K\Documents\Arduino\hardware\esp8266com\esp8266\cores\esp8266/core_esp8266_features.h:132:38: error: expected ',' or ';' before 'esp_is_8285'
  132 | bool __attribute__((const, nothrow)) esp_is_8285();
      |                                      ^~~~~~~~~~~
Usando librería ESP8266WiFi con versión 1.0 en la carpeta: C:\Users\Marthi-K\Documents\Arduino\hardware\esp8266com\esp8266\libraries\ESP8266WiFi 
Usando librería arduinoWebSockets con versión 2.3.7 en la carpeta: C:\Users\Marthi-K\Documents\Arduino\libraries\arduinoWebSockets 
Usando librería Hash con versión 1.0 en la carpeta: C:\Users\Marthi-K\Documents\Arduino\hardware\esp8266com\esp8266\libraries\Hash 
exit status 1
Error compilando para la tarjeta Generic ESP8266 Module.

**Comment by avoev** [comment]
Hello @arlaor , this appears to be a problem with the ESP8266 Community Version 3.1.0
I had the same issue, but downgrading it to https://github.com/esp8266/Arduino/releases/tag/3.0.2 fixed it.
All the best.

**Comment by mcspr** [comment]
That's esp8266 Core issue, not this lib
See https://github.com/esp8266/Arduino/issues/8794 and https://github.com/esp8266/Arduino/pull/8795, should be with Cores 3.1.1+ (when it is released)

**Comment by arlaor** [comment]
> https://github.com/esp8266/Arduino/blob/master/cores/esp8266/core_esp8266_features.h
> 
> Copiei esse código e colei no arquivo core_esp8266_features.h e deu certo

Is correct. This work. Thanks
