### ISSUE TITLE
Weak performance when connecting With SSL using ESP8266

### ISSUE THREAD

**Issue by hhyari** [Links2004/arduinoWebSockets#784]
Im using this begin command on ESP8266 to connect to socket io connection.

`socketIO.beginSSL(constants.socketHost, 443, "/socket.io/?EIO=4");
`

There is a very noticeable difference in speed when sending and receiving messages comparing to connecting without SSL connection.

It's worth mentioning that the server is secured by cloudflare.

 Is there something wrong? or is that a normal behavior?

**Comment by thek0d3r** [comment]
It might not be the actual code itself, but the usage of Cloudflare. You said you connected to it without SSL. Did you use the local address or the public one?

**Comment by hhyari** [comment]
> It might not be the actual code itself, but the usage of Cloudflare. You said you connected to it without SSL. Did you use the local address or the public one?

@thek0d3r I used the public

**Comment by thek0d3r** [comment]
> > It might not be the actual code itself, but the usage of Cloudflare. You said you connected to it without SSL. Did you use the local address or the public one?
> 
> @thek0d3r I used the public

In that case it might be because of Cloudflare. As far as I know, it adds a security check to the request if you forward the request through their proxy. Try to set the request to be DNS only and check if the latency gets lower.

**Comment by hhyari** [comment]
@thek0d3r This strange behavior is no longer happening, probably it was a cloudflare issue.
