### ISSUE TITLE
Empty sketch will not compile

### ISSUE THREAD

**Issue by Jkillelea** [Links2004/arduinoWebSockets#79]
A black sketch, with only the WebSockets library headers (`WebSocketsClient.h, WebSocketsServer.h, WebSockets.h`) does not compile.

```
Arduino: 1.6.5 (Linux), Board: "Generic ESP8266 Module, 80 MHz, 40MHz, DIO, 115200, 1M (512K SPIFFS), ck, Serial, HTTPServer"

In file included from /home/user/Arduino/sketchbook/libraries/WebSockets/src/WebSocketsClient.h:29:0,
                 from WebSockets_esp8266.ino:1:
/home/user/Arduino/sketchbook/libraries/WebSockets/src/WebSockets.h:90:25: fatal error: ESP8266WiFi.h: No such file or directory
 #include <ESP8266WiFi.h>
                         ^
```

Including `ESP8266WiFi.h` manually causes another compile error, since `Hash.h` was not included.
Including `Hash.h` also does not fix the problem, since errors are now thrown about the actual code inside.

**Comment by Jkillelea** [comment]
The sketch in question:

`#include <WebSocketsClient.h>
#include <WebSocketsServer.h>
#include <WebSockets.h>


void setup() {
}

void loop() {
}`

**Comment by Links2004** [comment]
yes this normal.
the Arduino IDE can not detect the dependencies to other libs.


you need for example at minimum:
```
#include <ESP8266WiFi.h>
#include <Hash.h>
#include <WebSocketsClient.h>

void setup() {
}

void loop() {
}
```

```ESP8266WiFi``` and ```Hash ```are part of the ESP arduino Port.
