### ISSUE TITLE
ESP32 Secure WebSocket Server over SSL (wss)

### ISSUE THREAD

**Issue by meakashrao** [Links2004/arduinoWebSockets#796]
I am looking for a secure WebSocket Server implementation over SSL for ESP32 using Arduino IDE, so far I haven't been able to find any implementation regarding the same. Please help to get me started with the same.

If there is any Library for the same or how can I use this library to implement the same, i'd be happy to hear any suggestions regarding the same.

**Comment by justbendev** [comment]
Ping me if you find any :sweat_smile:

**Comment by bananacity** [comment]
did you find anything?
