### ISSUE TITLE
Header names are case sensitive.

### ISSUE THREAD

**Issue by creationix** [Links2004/arduinoWebSockets#8]
After two days of debugging to try and figure out why my luvit websocket client couldn't connect, I discovered that my header names had `Websocket` while browsers had `WebSocket`.  A proper websocket server should do a case insensitive check.

It's up to you if you think it's worth the extra code and performance cost to do all header keys case insensitive.  In this case I just changed my client to better match what browsers send so I'm not blocked by this.

https://github.com/luvit/lit/commit/4dacac1add7d325abae17e3579d49ae416053b38

**Comment by Links2004** [comment]
the rfc6455 says:
```
The request MUST include a header field with the name |Sec-WebSocket-Version|.  The value of this header field MUST be 13.
```
(https://tools.ietf.org/html/rfc6455#page-18)

for cases where case insensitive is allowed they write it down like this fore example:
```
 If the response lacks an |Upgrade| header field or the |Upgrade| header field contains a value that is not an ASCII case-insensitive match for the value "websocket", the client MUST _Fail the WebSocket Connection_.
```
(https://tools.ietf.org/html/rfc6455#page-19)

so i think the only valid way is "Sec-WebSocket-Version" like all browser do it,
i prefer to implement the rfc6455 as exact as possible :)
if you have some other source of information please give me a link.

**Comment by creationix** [comment]
On [page 4](https://tools.ietf.org/html/rfc6455#page-4), it says:

> The format and parsing of headers is as defined in [RFC2616].

And then in [RFC2616 secion 4.2](https://tools.ietf.org/html/rfc2616#section-4.2) it says:

> Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.

**Comment by Links2004** [comment]
have missed this one, will do some changes on weekend.
