### ISSUE TITLE
datas from seismic portal

### ISSUE THREAD

**Issue by eqcq** [Links2004/arduinoWebSockets#80]
Hi and thanks for all you've done.
I'm trying to retrieve realtime datas from the seismic portal with my huzzah 8266 using your websocket library. with javascript I have no problems, but in Arduino I can't connect to the data using websocket

Here the link for the data
http://www.seismicportal.eu/realtime.html

I've you any ideas about the way to achieve this ? Thanks a lot.

**Comment by Links2004** [comment]
set the debug port in the IDE and enable debug for websockets here:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L30
the Serial infos will help to solve the problem.

**Comment by eqcq** [comment]
ok thanks for the answer I've enabled debug and upload this code on my esp8266 :
`/*
 * WebSocketClient.ino
 *
 *  Created on: 24.05.2015
 *
 */

#include <Arduino.h>

#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>

#include <WebSocketsClient.h>

#include <Hash.h>

ESP8266WiFiMulti WiFiMulti;
WebSocketsClient webSocket;


#define USE_SERIAL Serial1

void webSocketEvent(WStype_t type, uint8_t * payload, size_t lenght) {


    switch(type) {
        case WStype_DISCONNECTED:
            USE_SERIAL.printf("[WSc] Disconnected!\n");
            break;
        case WStype_CONNECTED:
            {
                USE_SERIAL.printf("[WSc] Connected to url: %s\n",  payload);
        
          // send message to server when Connected
        webSocket.sendTXT("Connected");
            }
            break;
        case WStype_TEXT:
            USE_SERIAL.printf("[WSc] get text: %s\n", payload);

      // send message to server
      // webSocket.sendTXT("message here");
            break;
        case WStype_BIN:
            USE_SERIAL.printf("[WSc] get binary lenght: %u\n", lenght);
            hexdump(payload, lenght);

            // send data to server
            // webSocket.sendBIN(payload, lenght);
            break;
    }

}

void setup() {
    // USE_SERIAL.begin(921600);
    USE_SERIAL.begin(115200);

    //Serial.setDebugOutput(true);
    USE_SERIAL.setDebugOutput(true);

    USE_SERIAL.println();
    USE_SERIAL.println();
    USE_SERIAL.println();

      for(uint8_t t = 4; t > 0; t--) {
          USE_SERIAL.printf("[SETUP] BOOT WAIT %d...\n", t);
          USE_SERIAL.flush();
          delay(1000);
      }

    WiFiMulti.addAP("ssid", "pass");  // in my code there's the good ssid and pass of course

    //WiFi.disconnect();
    while(WiFiMulti.run() != WL_CONNECTED) {
        delay(100);
    }

    webSocket.begin("www.seismicportal.eu/standing_order", 80);
    //webSocket.setAuthorization("user", "Password"); // HTTP Basic Authorization
    webSocket.onEvent(webSocketEvent);

}

void loop() {
    webSocket.loop();
}`

I launch the serial monitor and nothing happened

**Comment by eqcq** [comment]
Ok my mistake now in the serial monitor I've got this :

[SETUP] BOOT WAIT 4...
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 1
cnt 

connected with EQCQhome, channel 1
dhcp client start...
[SETUP] BOOT WAIT 3...
ip:10.0.1.13,mask:255.255.255.0,gw:10.0.1.1
[SETUP] BOOT WAIT 2...
[SETUP] BOOT WAIT 1...
[WS-Client] asyncConnect...
[WS-Client] connection to www.seismicportal.eu/standing_order/:80 Faild
pm open,type:2 0

`#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>
#include <WebSocketsClient.h>
#include <Hash.h>

ESP8266WiFiMulti WiFiMulti;
WebSocketsClient webSocket;
#define USE_SERIAL Serial
void webSocketEvent(WStype_t type, uint8_t * payload, size_t lenght) {
  switch(type) {
        case WStype_DISCONNECTED:
            USE_SERIAL.printf("[WSc] Disconnected!\n");
            break;
        case WStype_CONNECTED:
            {
                USE_SERIAL.printf("[WSc] Connected to url: %s\n",  payload);
        
          // send message to server when Connected
        webSocket.sendTXT("Connected");
            }
            break;
        case WStype_TEXT:
            USE_SERIAL.printf("[WSc] get text: %s\n", payload);
   // send message to server
  // webSocket.sendTXT("message here");
            break;
        case WStype_BIN:
            USE_SERIAL.printf("[WSc] get binary lenght: %u\n", lenght);
            hexdump(payload, lenght);
            // send data to server
            // webSocket.sendBIN(payload, lenght);
            break;
    }
}
void setup() {
    // USE_SERIAL.begin(921600);
    USE_SERIAL.begin(115200);
    //Serial.setDebugOutput(true);
    USE_SERIAL.setDebugOutput(true);
    USE_SERIAL.println();
    USE_SERIAL.println();
    USE_SERIAL.println();
      for(uint8_t t = 4; t > 0; t--) {
          USE_SERIAL.printf("[SETUP] BOOT WAIT %d...\n", t);
          USE_SERIAL.flush();
          delay(1000);
      }
    WiFiMulti.addAP("EQCQhome", "leroidesmouches");
    //WiFi.disconnect();
    while(WiFiMulti.run() != WL_CONNECTED) {
        delay(100);
    }
    webSocket.begin("www.seismicportal.eu/standing_order/", 80);
    //webSocket.setAuthorization("user", "Password"); // HTTP Basic Authorization
    webSocket.onEvent(webSocketEvent);
}
void loop() {
  webSocket.loop();
}`

**Comment by Links2004** [comment]
the first parameter is the hostname.
```cpp
webSocket.begin("seismicportal.eu", 80, "/standing_order/");
```
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.h#L43

**Comment by eqcq** [comment]
thanks a lot everything is ok now 👍 
and congrats for this essential library 💯

**Comment by eqcq** [comment]
A last question.
How to convert the payload result in a string (in order to parse the json result) ?
thanks
