### ISSUE TITLE
Connect 2 ESP8266 through WebSocket

### ISSUE THREAD

**Issue by crisap94** [Links2004/arduinoWebSockets#81]
Hi Markus, Nice library

I've been reading for a while trying to get the way to communicate 2 ESP8266, I want to get some data from 1 and send it to another, but through a conventional http request is too slow, i can see that the ESP can be a WebSocketServer, and a WebSocketClient too, due to the name of the Libraries.

I will appreciate like some assistance from you, i have tried the libs with no luck.

**Comment by Links2004** [comment]
normally the client example shut be able to connect to the server example.
do you get any error messages, may activating Debug helps to find the problem.
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L30

**Comment by crisap94** [comment]
![image](https://cloud.githubusercontent.com/assets/9030289/15658033/396cbd2a-267d-11e6-994a-78ad637678de.png)
Debug is activated. but
This is what i get when i upload the client and the server, i actually don't know what's going on with it.

**Comment by Links2004** [comment]
there are no debug message to see.
try to add:
```cpp
Serial.setDebugOutput(true);
```
in the ```setup```

**Comment by crisap94** [comment]
I could get it, And i apologise for my stupid error, the websocket's ip which i was trying to connect was wrong, now i'm using one ESP as a AP, it starts the websocket server at the gateway, on the port 81 (or another), and the other ESP as STA connecting to the AP, and works like a charm. Thank you so much for this library.

**Comment by Links2004** [comment]
you are welcome.
