### ISSUE TITLE
nginx ws proxying

### ISSUE THREAD

**Issue by jlippa** [Links2004/arduinoWebSockets#83]
Not really an issue - more of a question. Does anyone know if it's possible to use nginx as a websocket proxy with this library? I'd be interested to see the actual nginx config if anyone has it working.

Ideally I'd like to use nginx as an upfront SSL websocket proxy for my project that's using this library running on an ESP8266 12F. I've played around with a few different configs based on the docs here https://www.nginx.com/blog/websocket-nginx/ and here http://nginx.org/en/docs/http/websocket.html but nothing works yet.

Thanks,
Joe

**Comment by jlippa** [comment]
It is possible! Working nginx SSL caching proxy config is attached. 

After much playing and debugging I noticed a couple of things:

1. At first I was unable to get serial debugging working as is by simply uncommenting DEBUG_WEBSOCKETS here https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L30. For some unknown reason os_printf isn't working for me on my setup with an ESP8266 so I've swapped os_printf for a Serial.printf call to get serial debugging working.

1. Once I had serial debugging working, I was able to see the problem that was preventing my original nginx config working and the problem that I had is related to what I believe is a bug in this library here: https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsServer.cpp#L593

This line is performing a case sensitive match against the Connection header Upgrade value (note the upper case U character) and strictly speaking this is wrong because the spec says "A |Connection| header field that includes the token "Upgrade", treated as an ASCII **case-insensitive** value." (please see https://tools.ietf.org/html/rfc6455#section-4.2.1).

I've fixed this "bug" locally but the config that I've attached here works around this problem by specifying: proxy_set_header Connection   "Upgrade"; matching the existing current case sensitive implementation.

[esp8266.links2004arduinoWebsockets.ssl.reverse.proxy.conf.txt](https://github.com/Links2004/arduinoWebSockets/files/298912/esp8266.links2004arduinoWebsockets.ssl.reverse.proxy.conf.txt)

**Comment by jlippa** [comment]
ps happy to make a pull request if you agree this is a bug that needs fixing :)

**Comment by Links2004** [comment]
to goal is to implement RFC6455 ;) is a bug that needs fixing.
when you fix it keep in mind "Connection" can contain additional content.
one option is:
```cpp
if(headerValue.toLowerCase().indexOf("upgrade") >= 0) {
```
not pretty but it does its job.

**Comment by jlippa** [comment]
New pull request is created with a comment thanks.
I'm not really sure where you'd want that nginx config file adding so I'll let you add that to the appropriate location - I do think it might be of value to future users.
