### ISSUE TITLE
Cant detect disconnection

### ISSUE THREAD

**Issue by cobogt** [Links2004/arduinoWebSockets#84]
Im connecting the ESP8266 to a websocket server using NodeJS and it works fine like 5 minutes but then i cant send anything to the server and the server cant send me anything. The problem is that i never get a call to the WStype_DISCONNECTED event.

**Comment by Links2004** [comment]
please enable debug and post the output here.

for debug to work you need to enable the debug options of the ESP to,
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md#usage
simple set the Serial port you want to user and activate debug here:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L30
