### ISSUE TITLE
WebSocketsClient.cpp begin() error

### ISSUE THREAD

**Issue by Jepsens1** [Links2004/arduinoWebSockets#853]
`#include <SPI.h>`
`#include <WiFi101.h>`
`#include <WebSocketsClient.h>`
`#include "arduino_secrets.h"`
`char ssid[] = SECRET_SSID; `
`char pass[] = SECRET_PASS;`
`WiFiClient client;`
`WebSocketsClient webSocket;`

`void setup() {`
 ` Serial.begin(9600);`

  `// Connect to Wi-Fi`
  `while (status != WL_CONNECTED) {`
    `Serial.print("Attempting to connect to SSID: ");`
    `Serial.println(ssid);`
    `status = WiFi.begin(ssid, pass);`
    `delay(5000);  // wait 5 seconds for connection`
  `}`
  `Serial.println("Connected to wifi");`
  `webSocket.begin("192.168.0.14", 81,"/");`
  `webSocket.onEvent(webSocketEvent);`
`}`

when trying to compile i get this error

`\src\WebSocketsClient.cpp: In member function 'void WebSocketsClient::begin(arduino::IPAddress, uint16_t, const char*,` `const char*)':`
`\src\WebSocketsClient.cpp:98:23: error: 'class arduino::IPAddress' has no member named 'toString'; did you mean 'fromString'?`
     `return begin(host.toString().c_str(), port, url, protocol);`
                       `^~~~~~~~`
                       `fromString`
`\src\WebSocketsClient.cpp:98:62: error: return-statement with a value, in function returning 'void' [-fpermissive]`
     `return begin(host.toString().c_str(), port, url, protocol);`
                                                              ^

`exit status 1`

`Compilation error: exit status 1`

**Comment by TheTinyBang** [comment]
Hi Jepsens1,

did you find a solution to this, as I am also running into the same issue
