### ISSUE TITLE
WebSocket with AT commands (GSM model: Quectel EC25) 

### ISSUE THREAD

**Issue by feyzanoz** [Links2004/arduinoWebSockets#857]
I need to use WebSocket for MicroOCPP application. I am using a Quectel EC25 model modem and ESP32 S3 WROOM -1.

**Comment by SwapB5632** [comment]
Hello all 
I'm doing the same. But some how don't able to manage to route the WebSocket request from WIFI client with GSM client. kindly help if anyone having the solution. 

Waiting for the respace.

**Comment by Links2004** [comment]
See: https://github.com/Links2004/arduinoWebSockets/issues/197
