### ISSUE TITLE
Websocket with IRremote

### ISSUE THREAD

**Issue by arlaor** [Links2004/arduinoWebSockets#86]
Hi
I need your help with 2 issues with websockets in esp8266 nodemcu V1.
1.
I am using a remote control to turn on and off a relay.
I'm the same relay switching on and off via a web page with Checkbox Switch in my ESP8266 V1 websocket nodemcu.
How I can do to make the turn on or off the relay with the remote control, the switch will automatically update checkbox?
If the relay is turned on with the remote control, the switch automatically change checkbox checked on the server.
If the relay is turned off with the remote control, the switch automatically changes checkbox not checked on the server.
2.
How do I print on a server with websockets, temperature and humidity of a DHT11 module?

**Comment by arlaor** [comment]
Hi @wvdv2002 @Links2004 Do you know anything about this to fix it?

**Comment by wvdv2002** [comment]
Sorry, this is more in the web development department, which I have less knowledge off. I guess you can start 2 websockets in both directions and push updates over that connection? Or is a websocket already bidirectional in both diretions for puhs messages?

**Comment by Links2004** [comment]
yes a websocket  connection is bidirectional.
simple call 
```cpp
webSocket.sendTXT("relay:ON");
```
or
```cpp
webSocket.sendTXT("relay:OFF");
```
on the arduino and you will get a message in the browser you get the message with:
```js
connection.onmessage = function (e) {
	console.log('ESP sends: ', e.data);
};
```
https://github.com/Links2004/arduinoWebSockets/blob/master/tests/webSocket.html#L22-L23

**Comment by arlaor** [comment]
Hi @wvdv2002 @Links2004
Sorry, do not know how to relate the code you indicate me in the sketch that I have modified

The variables that change the pin state from 0 to 1 or 1 to 0 are
estadoD1
estadoD2
estadoD3
estadoD4
estadoD5
the part of the sketch that manages the IrRemote, these variables are related between the lines 480-548
the part of the sketch that manages the website server, these variables are interrelated lines 409-475

lines that update the status of the web page for the actual state of the switch is displayed when they are modified by the website and not through IrRemote this between the lines 122-196.


This is my current code

[Websockets IRremote.ino](https://gist.github.com/arlaor/d2824afb08e090045055c70fe42a2994)

when I try to add the code that you send me some errors are generated in the arduino IDE that do not allow upload the sketch to my board.
 therefore I imagine that besides lines

webSocket.sendTXT ( "relay: ON");
or

webSocket.sendTXT ( "relay: OFF");
on the arduino and you will get a message in the browser you get the message with:

connection.onmessage = function (e) {
    console.log ( 'ESP SENDS', e.data);
};

I should create some definitions of functions or something to take the code that you send me?

I am unfortunately very lost on this issue and not as sending information to the websockets of changes in state of the pins that are modified or void functions that are outside the script of the website server.

**Comment by Links2004** [comment]
you already have all you need in you code only need some copy and paste.

you have:
```cpp
   if (LEDStatus) {
          webSocket.sendTXT(num, LEDON, strlen(LEDON));
        }  else {
          webSocket.sendTXT(num, LEDOFF, strlen(LEDOFF));
        }
```
to send the status on the connect event

for sending the update on change of the status you only need to add
```cpp
   if (LEDon) {
          webSocket.sendTXT(LEDON, strlen(LEDON));
        }  else {
          webSocket.sendTXT(LEDOFF, strlen(LEDOFF));
        }
```
to your ```writeLED``` function.
with this you send the message to all connected clients.

**Comment by arlaor** [comment]
This is the message in arduino IDE

exit status 1
call of overloaded 'sendTXT(const char [12], size_t)' is ambiguous

 for 

> if (LEDon) {
          webSocket.sendTXT(LEDON, strlen(LEDON));
        }  else {
          webSocket.sendTXT(LEDOFF, strlen(LEDOFF));
        

> }

The lines of code you send me the place between 409-475 lines of code are thus:

static void writeLED(bool LEDon)
{
  LEDStatus = LEDon;
  if (LEDon) {
       webSocket.sendTXT(LEDON, strlen(LEDON));
    digitalWrite(D1, 1);
    estadoD1=1;
    Serial.print(digitalRead(D1));
  }
  else {
       webSocket.sendTXT(LEDOFF, strlen(LEDOFF));
    digitalWrite(D1, 0);
    estadoD1=0;
    Serial.print(digitalRead(D1));
  }
}

but it does not work
not allow me to load the code

**Comment by arlaor** [comment]
[](url)

**Comment by arlaor** [comment]
@Links2004 
What or what are the total of lines that must be copied to the order of upgrade work?
And where in the sketch should be placed?

**Comment by arlaor** [comment]
Hi @wvdv2002 
Do you know where I place the code that tells me @Links2004 ?  What should add other lines to work ?.
I have tried to do but the Arduino IDE generates errors discussed above me and not let me compile the sketch
Not sure how do websockets to know how to take a message sent from a specific function.

**Comment by arlaor** [comment]
thanks
