### ISSUE TITLE
cookie header value

### ISSUE THREAD

**Issue by jjssoftware** [Links2004/arduinoWebSockets#88]
Here's a thought for discussion - do you think there's any general use-case mileage in the WebSocketsServer handleHeader function and it's supporting code handling and supporting the Cookie header? 

I know this isn't a websocket specific thing but if present, this header is passed at the time where the client attempts to negotiate upgrade from http to websockets. I've implemented this change locally because in my case I use this in the server to determine if a websocket connection is allowed based on the cookie value passed by the client in the WebSocketServerEvent WStype_CONNECTED socketEvent (my cookie is a sessionId authentication type cookie).

My thinking is that if this was generally supported, it opens up the potential for custom authentication schemes similar to the one I've implemented.

**Comment by jlippa** [comment]
If that made no sense whatsoever please feel free to take a look at the commit in my fork here: https://github.com/jlippa/arduinoWebSockets/commit/550e607a4e54e1ac500b44a62ef19de951b6830f

This change gives me the ability to allow / disallow a client websocket connect request within the WebSocketServerEvent with code that looks something like this: 

    switch(socketEventType) {
        case WStype_CONNECTED:
			{
				if(!isAuthenticated(websocketserver->_clients[socketClientIdx].cookieHeaderValue)) {
					//immediate disconnect
					websocketserver->disconnect(socketClientIdx);
				}
			}
			break;
        default:
        	break;
    }

**Comment by Links2004** [comment]
the basic Idea is good, but I think this need some better abstraction.
and I think the ```_clients``` move in the ifdef will break the non ESP support in the server. 

my idea to this is to add a generic "not managed" header received callback,
which then return a value to indelicate if the connection should be accepted or not.
if one header callback return not OK (false) the connection will never come to the Upgrade state.

**Comment by jlippa** [comment]
Yes, now that I look closer I see you're right - there's a bug in my fork for non ESP users.

The better abstracted approach sounds interesting. If I understand correctly and to expand a little, what you're suggesting is the introduction of a new delegate e.g. bool onHeader(WebSocketServerHttpHeaderEvent headerData); If assigned, this would be called for each non websocket specific http header passed at client handshake negotiation time and if any of these headers passed to that onHeader handler result in a false value being returned, the handshake / websocket connect request would be denied.

If that's along the right lines that works for me and I'd be happy to take a stab at the implementation for this.

**Comment by Links2004** [comment]
yes that is the idea.
feel free to implement it, I will merge it then.
I am short on time at the moment anyway.

**Comment by jlippa** [comment]
thanks new pull request added. I've included a new example in examples/WebSocketServer/WebSocketServerHttpHeaderValidation.ino that demonstrates this feature so hopefully people will be able to understand how this hangs together

**Comment by Links2004** [comment]
looking good,
I add one comment to the PR, where I am not sure it it will work.

**Comment by jlippa** [comment]
thanks for that you did spot an error there - should be fine now
