### ISSUE TITLE
WebSocket disconnects on large payload WStype_TEXT

### ISSUE THREAD

**Issue by blackcoffeexbt** [Links2004/arduinoWebSockets#880]
Similar to this issue https://github.com/Links2004/arduinoWebSockets/issues/114

Platform: ESP32-S3
Running the example sketch https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp32/WebSocketClient/WebSocketClient.ino

I'm finding that when a payload exceeds ~16kb, the websocket connection is disconnected. I've tested with a different lib ([Gil Mai](https://github.com/gilmaimon/ArduinoWebsockets/blob/master/examples/Minimal-Esp32-Client/Minimal-Esp32-Client.ino) and found that this issue is specific to this lib.

Do you have an idea of what the cause / work around could be?

Thanks :)

**Comment by Links2004** [comment]
this is the defined limit, you can increase it, but its there for a reason ;)

https://github.com/Links2004/arduinoWebSockets/blob/93707d455fff3c667aedd92b485276101f5e6eba/src/WebSockets.h#L66

if you send a loot of big frames like this you can easily run out of RAM / heap.

for sending big chunks of data its better to use the fragmentation.
any typical TCP/IP network and the ESP network stack can not handle 16k frames (mtu) any way.

which as a result mean that you dont lose anything if you do the fragmentation on the "date input" side.

**Comment by blackcoffeexbt** [comment]
Thanks for the reply. By fragmentation, do you mean splitting the payload into multiple messages on the sender side or something else? Unfortunately, I'm working with a protocol spec that doesn't include this ability and some messages can be very large. I'll bump the max data size and do some testing. 

Thanks again and thanks for the work on this lib :)

**Comment by Links2004** [comment]
If the max size change works for you then its fine.
the websocket protokoll has support for fragmentation but not all servers support it.
as a result its currently not exposed in the lib.

whats needed for using the WS fragmentation is `sendFrame` calles with 

https://github.com/Links2004/arduinoWebSockets/blob/93707d455fff3c667aedd92b485276101f5e6eba/src/WebSockets.h#L255-L258

e.g. 

- WStype_FRAGMENT_TEXT_START
- WStype_FRAGMENT (repeate as needed)
- WStype_FRAGMENT_FIN

**Comment by blackcoffeexbt** [comment]
This is great. Thanks for the help :)
