### ISSUE TITLE
Support for arduino rev4 wifi

### ISSUE THREAD

**Issue by dmtzs** [Links2004/arduinoWebSockets#891]
Interested in this library to be used for an arduino rev4 wifi to connect to websockets. Is there a timeline to make this library available for arduino rev 4 wifi?

**Comment by Links2004** [comment]
I dont have a Arduino UNO R4 WiFi, so I can not test it,
but the lib will for sure run on the ESP32-S3 on it.
no Idea about the RA4M1 part.

**Comment by dmtzs** [comment]
So which example you recommend me to use? In thee examples is using old wifi.h, which should be now wifis3.h (I already changed that) but don't understand which is the correct library to install for wifimulti.h

**Comment by dmtzs** [comment]
As I don't signs of real support o will close the issue as there's no intention to support arduino 4 wifi
