### ISSUE TITLE
esp32 Arduino v3.0.4 changed NetworkClientSecur::etCACertBundle arguments

### ISSUE THREAD

**Issue by totalretribution** [Links2004/arduinoWebSockets#896]
Hi,
The latest version of arduino esp32 v3.0.4 has changed the function  ```void setCACertBundle(const uint8_t *bundle);``` to ```void setCACertBundle(const uint8_t *bundle, size_t size);```.

This breaks Websockets with the following error
```/WebSocketsClient.cpp:250:45: error: no matching function for call to 'NetworkClientSecure::setCACertBundle(const uint8_t*&)'```

Thanks

**Comment by Coyotexi** [comment]
the same problem is also present in wrbsocketserver

**Comment by Links2004** [comment]
setCACertBundle is not used in the websocketserver code.
and the build test pass: https://github.com/Links2004/arduinoWebSockets/actions/runs/10234531631/job/28314167005

are you at the master branch?
the setCACertBundle change is not released yet.

**Comment by Coyotexi** [comment]
in Arduino IDE 2.3.2 only 2.5.1 is available. I manually installed 2.5.2, now eps32 3.04 also works
