### ISSUE TITLE
WSS support for client

### ISSUE THREAD

**Issue by fhernand** [Links2004/arduinoWebSockets#9]
Is it possible to connect via wss to a server from a arduinoWebSockets client?

**Comment by Links2004** [comment]
WSS is not possible until we get SSL support on the ESP

**Comment by bnh129** [comment]
It looks like SSL client support is now available in esp8266/Arduino, are there any plans to support it with arduinoWebSockets?

**Comment by Links2004** [comment]
client support is possible, server support not.
getting the client to use SSL/TLS shut be easy.

change ```WiFiClient```  to ```WiFiClientSecure```  
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L79

may implement a fingerprint check like.
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/examples/HTTPSRequest/HTTPSRequest.ino#L51-L55

**Comment by Links2004** [comment]
SSL is now supported.
https://github.com/Links2004/arduinoWebSockets/blob/master/examples/WebSocketClientSSL/WebSocketClientSSL.ino
