### ISSUE TITLE
socketio.begin on web address instead of ip number? connecting ESP32 to online server via socketio

### ISSUE THREAD

**Issue by omarcostahamido** [Links2004/arduinoWebSockets#918]
I am trying to connect to a socketio server (version ^4.7.5) living on a cloud server i have, which has a domain on it.
But I've noticed that when I replace `socketIO.begin("192.168.1.1", 3000, "/socket.io/?EIO=4");` with `socketIO.begin("https://mydomain.com", 80, "/socket.io/?EIO=4");` it wont connect. I even tried it locally by spinning a local nodejs server and using `socketIO.begin("http://192.168.1.3", 3000, "/socket.io/?EIO=4");` but it won't connect. I feel like I am missing something very basic here, so I appreciate your help very much! What would you do to connect an ESP32 using socketio to an external server on the web?
🙏

**Comment by omarcostahamido** [comment]
just to add a comment to say that i don't think socketio version would be the problem since it works when i connect with `socketIO.begin("192.168.1.1", 3000, "/socket.io/?EIO=4");` to a machine running this latest version.

**Comment by Links2004** [comment]
the IP can be a domain/host to, you only do need to not add the protocol.
```cpp
socketIO.begin("mydomain.com", 3000, "/socket.io/?EIO=4");
```

for SSL
```cpp
socketIO.beginSSL("mydomain.com", 3000, "/socket.io/?EIO=4");
```

you can take a look here, for all the diffrent way of checking the cert (if needed).
https://github.com/Links2004/arduinoWebSockets/blob/ca8026e550ba8f165e5295e1597e56055caa6db2/src/SocketIOclient.h#L53-L62

**Comment by omarcostahamido** [comment]
I was about to write here that I am at a lost. but then it hit me...
`socketIO.beginSSL("mydomain.com", 443, "/socket.io/?EIO=4");`
of course, https is served on port `443`! _dOH!_
Thank you so much for your patience... it works beautifully.
Sometimes all you need is to take it reeally slow :)
