### ISSUE TITLE
Xtensa error in Arduino 1.6.9

### ISSUE THREAD

**Issue by DhanvinderSingh** [Links2004/arduinoWebSockets#92]
We are trying to build this project and having difficulty setting up the IDE. we are working in Arduino and with Wifi chip  ESP8266.

The error we're getting is: exec: "/bin/xtensa-lx106-elf-g++": file does not exist

What is this file and where should it be?

Edit:

Here is the verbose log.

C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware "C:\Program Files (x86)\Arduino\hardware" -tools "C:\Program Files (x86)\Arduino\tools-builder" -tools "C:\Program Files (x86)\Arduino\hardware\tools\avr" -built-in-libraries "C:\Program Files (x86)\Arduino\libraries" -libraries "C:\Users\nabbot\Documents\Arduino\libraries" -fqbn=Arduino:avr:generic:CpuFrequency=80,FlashFreq=40,FlashMode=dio,UploadSpeed=115200,FlashSize=512K64,ResetMethod=ck,Debug=Disabled,DebugLevel=None____ -ide-version=10609 -build-path "C:\Users\nabbot\AppData\Local\Temp\buildbdc8da3f94e115e2149e9b25d6db80e1.tmp" -warnings=none -prefs=build.warn_data_percentage=75 -verbose "C:\DHTServer\DHTServer.ino"

C:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware "C:\Program Files (x86)\Arduino\hardware" -tools "C:\Program Files (x86)\Arduino\tools-builder" -tools "C:\Program Files (x86)\Arduino\hardware\tools\avr" -built-in-libraries "C:\Program Files (x86)\Arduino\libraries" -libraries "C:\Users\nabbot\Documents\Arduino\libraries" -fqbn=Arduino:avr:generic:CpuFrequency=80,FlashFreq=40,FlashMode=dio,UploadSpeed=115200,FlashSize=512K64,ResetMethod=ck,Debug=Disabled,DebugLevel=None____ -ide-version=10609 -build-path "C:\Users\nabbot\AppData\Local\Temp\buildbdc8da3f94e115e2149e9b25d6db80e1.tmp" -warnings=none -prefs=build.warn_data_percentage=75 -verbose "C:\DHTServer\DHTServer.ino"

"/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\Program Files (x86)\Arduino\hardware\Arduino\avr/tools/sdk/include" "-IC:\Program Files (x86)\Arduino\hardware\Arduino\avr/tools/sdk/lwip/include" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11  -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=80000000L    -DARDUINO=10609 -DARDUINO_ESP8266_ESP01 -DARDUINO_ARCH_AVR  -DESP8266 "-IC:\Program Files (x86)\Arduino\hardware\Arduino\avr\cores\esp8266" "-IC:\Program Files (x86)\Arduino\hardware\Arduino\avr\variants\generic" "C:\Users\nabbot\AppData\Local\Temp\buildbdc8da3f94e115e2149e9b25d6db80e1.tmp\sketch\DHTServer.ino.cpp" -o "nul"

"/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\Program Files (x86)\Arduino\hardware\Arduino\avr/tools/sdk/include" "-IC:\Program Files (x86)\Arduino\hardware\Arduino\avr/tools/sdk/lwip/include" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11  -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=80000000L    -DARDUINO=10609 -DARDUINO_ESP8266_ESP01 -DARDUINO_ARCH_AVR  -DESP8266 "-IC:\Program Files (x86)\Arduino\hardware\Arduino\avr\cores\esp8266" "-IC:\Program Files (x86)\Arduino\hardware\Arduino\avr\variants\generic" "C:\Users\nabbot\AppData\Local\Temp\buildbdc8da3f94e115e2149e9b25d6db80e1.tmp\sketch\DHTServer.ino.cpp" -o "nul"

"/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\Program Files (x86)\Arduino\hardware\Arduino\avr/tools/sdk/include" "-IC:\Program Files (x86)\Arduino\hardware\Arduino\avr/tools/sdk/lwip/include" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11  -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=80000000L    -DARDUINO=10609 -DARDUINO_ESP8266_ESP01 -DARDUINO_ARCH_AVR  -DESP8266 "-IC:\Program Files (x86)\Arduino\hardware\Arduino\avr\cores\esp8266" "-IC:\Program Files (x86)\Arduino\hardware\Arduino\avr\variants\generic" "C:\Users\nabbot\AppData\Local\Temp\buildbdc8da3f94e115e2149e9b25d6db80e1.tmp\sketch\DHTServer.ino.cpp" -o "C:\Users\nabbot\AppData\Local\Temp\buildbdc8da3f94e115e2149e9b25d6db80e1.tmp\preproc\ctags_target_for_gcc_minus_e.cpp"

exec: "/bin/xtensa-lx106-elf-g++": file does not exist
Error compiling for board Generic ESP8266 Module.

please assist us. Thank you.

**Comment by DhanvinderSingh** [comment]
exec: "/bin/xtensa-lx106-elf-g++": file does not exist
Error compiling for board Generic ESP8266 Module.

**Comment by Links2004** [comment]
it looks like a strange mix of windows, linux, AVR and ESP8266 commands.
there is something very wrong.

I recommend to do a clean install of the Arduino IDE + ESP8266 core again.
https://github.com/esp8266/Arduino#installing-with-boards-manager
for the clean reinstall you need to delete the Arduino dir in AppData and the Program Files one   "C:\Program Files (x86)\Arduino"

if this still not helps, you can report this to the 
ESP8266 arduino port. (https://github.com/esp8266/Arduino) or
the Arduino IDE itself (https://github.com/arduino/Arduino),
since this is Problem of the IDE.

**Comment by DhanvinderSingh** [comment]
hello this is the problem i am having now when i put in the link provided below in preferences
http://arduino.esp8266.com/stable/package_esp8266com_index.json


![capture](https://cloud.githubusercontent.com/assets/19804128/15909638/2fd2554e-2d95-11e6-9ce3-ae1b20f2fdad.PNG)

**Comment by Links2004** [comment]
the ESP8266 core has noting to do with the Adafruit.
do the same happen without the link?

**Comment by DhanvinderSingh** [comment]
how can i add esptool in tools>programmer because i am missing that option. i need that option to run the board. 
![image](https://cloud.githubusercontent.com/assets/19804128/16016497/5439b7ce-3169-11e6-99eb-7760cf7f8812.png)

**Comment by Links2004** [comment]
there is no ESP programmer.
Please referee to https://github.com/esp8266/Arduino for more Infos.

there are many getting stated howtos for the ESP8266 with arduino too, some examples:

http://www.arduinesp.com/getting-started
https://learn.adafruit.com/adafruit-huzzah-esp8266-breakout/using-arduino-ide
http://www.seeedstudio.com/blog/2014/09/11/getting-started-with-esp8266/

and many more, this repo is for my arduinoWebSockets library, 
if you have problems with the library you can ask here, 
but for the basics for the ESP please use https://github.com/esp8266/Arduino since the core is develop there.

**Comment by DhanvinderSingh** [comment]
Thank You, I got the ESP8266 to work.

**Comment by Sheep666** [comment]
Hello,I also got this problem.
xtensa-lx106-elf/bin/xtensa-lx106-elf-g++": file does not exist
However,I can find this file in the directory.
So can you share the experience with me about this issue！

**Comment by vsobolyev** [comment]
Just got this problem. Try to do what the wiki says:
cd esp8266/tools
python get.py
