### ISSUE TITLE
WSS/SSL support for ESP32 -- README.md update

### ISSUE THREAD

**Issue by akdeb** [Links2004/arduinoWebSockets#926]
Hi @Links2004 
This lib has been working like a charm for WS but not for WSS for us. We are sending and receiving bidirectional audio to and from our python server but our server doesn't capture audio when using beginSSL with the correct CA.

The README says that this is only supported for:

> wss / SSL
> supported for:
> wss client on the ESP8266
> wss / SSL is not natively supported in WebSocketsServer however it is possible to achieve secure websockets by running the ?device behind an SSL proxy. See [Nginx](https://github.com/Links2004/arduinoWebSockets/blob/master/examples/Nginx/esp8266.ssl.reverse.proxy.conf) for a sample Nginx server configuration file to enable this.

Is WSS/SSL currently being supported on ESP32?

**Comment by Links2004** [comment]
yes WSS / SSL is supported on the ESP32 (in client mode)
keep in minde that the encription needs additional CPU power on the ESP not sure how good this mixes with audio data.

**Comment by kakopappa** [comment]
If it works for ws but not for wss it’s likely you are running out of memory. Have you tried enabling verbose logging ?

**Comment by akdeb** [comment]
Makes sense put up a PR here with the update https://github.com/Links2004/arduinoWebSockets/pull/927 @Links2004

**Comment by akdeb** [comment]
@kakopappa I currently have this setup in my platformio.ini. Would you add anything else to enable verbose logging? 

```
monitor_filters =
  esp32_exception_decoder
  time
build_flags = 
    -D CORE_DEBUG_LEVEL=0
    ; -D BOARD_HAS_PSRAM=1`
board_build.partitions = partition.csv
```

**Comment by kakopappa** [comment]
Hi,

Not a PIO user, so did a quick search and found this.


build_flags = -DCORE_DEBUG_LEVEL=5

**Comment by Links2004** [comment]
setting `DEBUG_ESP_PORT=Serial` will print the debug messages for the lib to the set Serial port

**Comment by akdeb** [comment]
Awesome thank you both! Debugging now and will close this issue.
