### ISSUE TITLE
updating of information in multiple clients with Websockets

### ISSUE THREAD

**Issue by arlaor** [Links2004/arduinoWebSockets#94]
Hi.
I have had problems trying to update the information sent from a void outside the script developed within the HTML code of various switch on / off.
The question is this. when I run a switch on / off directly from the page, to enable or disable a pin in my ESP8266 V1, this is updated on all clients that are connected to the server. everything is normal.
But when I sent the order from outside the website, from another void, only updates the switch on the website of the last device that was connected to the server, and the other devices do not update the information on the page.

What should I do to make the new switch status is updated in real time on all devices connected to the server?
I clarify that this happens when I change the state of the switch from outside the script VOID containing the websockets.

**Comment by arlaor** [comment]
Hi @Links2004 This is my [code](https://goo.gl/LwZVEf)
I ask please your collaboration.

**Comment by Links2004** [comment]
you use ``` webSocket.sendTXT(socketNumber, LEDON, strlen(LEDON));``` in your ```writeLED``` functions.
the function is to send to one client to send to all clients remove the ```socketNumber``` from the call
``` webSocket.sendTXT(LEDON, strlen(LEDON));``` then it will send to all connected clients.

**Comment by arlaor** [comment]
socketNumber use has been the only way to prevent the error in arduino IDE.

`exit status 1
call of overloaded 'sendTXT(const char [12], size_t)' is ambiguous`

since apparently I must define certain parameters before sending the message.
`webSocket.sendTXT(LEDON, strlen(LEDON))`
How I can send the message you are commenting without getting this error?
`exit status 1
call of overloaded 'sendTXT(const char [12], size_t)' is ambiguous`
Arduino IDE does not allow me to compile

**Comment by Links2004** [comment]
use ```broadcastTXT.sendTXT(LEDON);```, I had looked to the wrong file.
note: the lib can detect the length itself no need for the ```strlen(LEDON)```

**Comment by arlaor** [comment]
ok. Thanks
